force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/CRM_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Approval_Status__c</fullName>
    <label>CRM Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/Contracts_Detail__c.object-meta.xml
<CustomObject>
    <label>Contracts Detail</label>
    <nameField>
        <displayFormat>CD-{YYMM}-{000000}</displayFormat>
        <label>Contracts Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts_Detail__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <label>Contracts</label>
    <referenceTo>Contracts__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Code</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SubmitContractControllerTest.cls
@isTest
private class SubmitContractControllerTest {
    static testMethod void testMethod1() {
        Contracts__c con = new Contracts__c();
        insert con;
        
        Product__c p = new Product__c();
        p.Name = '12341234';
        p.External_Id__c = '12341234';
        insert p;
        
        Contracts_Detail__c conDetail=new Contracts_Detail__c();
        conDetail.Contracts__c=con.Id;
        conDetail.Product__c=p.Id;
        insert conDetail;
        
        SubmitContractController.submitContract('');
        SubmitContractController.submitContract(con.Id);
        con.CRM_Approval_Status__c='Approved';
        update con;
        SubmitContractController.submitContract(con.Id);
    }
}