force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/CRM_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Approval_Status__c</fullName>
    <label>CRM Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/Contracts_Detail__c.object-meta.xml
<CustomObject>
    <label>Contracts Detail</label>
    <nameField>
        <displayFormat>CD-{YYMM}-{000000}</displayFormat>
        <label>Contracts Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts_Detail__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <label>Contracts</label>
    <referenceTo>Contracts__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContractsTriggerHandlerTest.cls
@IsTest
private  class ContractsTriggerHandlerTest {
	static testMethod void testMock(){
		Contracts__c con=new Contracts__c();
		insert con;
        Contracts_Detail__c conDetail=new Contracts_Detail__c();
        conDetail.Contracts__c=con.Id;
        insert conDetail;

		Contracts__c con1=new Contracts__c();
        con1.CRM_Approval_Status__c='Draft';
		insert con1;
        con1.CRM_Approval_Status__c='Approved';
		update con1;
	}
    
}