force-app/main/default/objects/Campaign/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/MKT_Approval__c.field-meta.xml
<CustomField>
    <fullName>MKT_Approval__c</fullName>
    <label>MKT Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>TEXT(MONTH(Datevalue(CreatedDate)) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Monthly_Budget__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Budget</label>
    <referenceTo>Monthly_Budget__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(CreatedDate) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Offline_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Offline_Campaign</fullName>
    <active>true</active>
    <label>Offline Campaign</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Online_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Online_Campaign</fullName>
    <active>true</active>
    <label>Online Campaign</label>
</RecordType>

force-app/main/default/objects/Campaign_Budget__c/Campaign_Budget__c.object-meta.xml
<CustomObject>
    <label>Campaign Budget</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Budget</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Budget__c/fields/Budgeted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/ExteralId__c.field-meta.xml
<CustomField>
    <fullName>ExteralId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>销售组织+年份</inlineHelpText>
    <label>ExteralId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Budget__c/fields/Campaign_Budget__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Budget__c</fullName>
    <label>Campaign Budget</label>
    <referenceTo>Campaign_Budget__c</referenceTo>
    <relationshipLabel>Monthly Budget</relationshipLabel>
    <relationshipName>Monthly_Budget_Parent</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/ExteralId__c.field-meta.xml
<CustomField>
    <fullName>ExteralId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>年份+销售+月份</inlineHelpText>
    <label>ExteralId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Budget_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 05-28-2025
 * @last modified by  : Gerry 
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-28-2025   Gerry   Initial Version
**/
@isTest
public with sharing class CampaignTriggerHandlerTest {
    static testMethod void testMethod1() {
        
        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'bisfnewuser@testorg.com';
        u.Alias = 'newUser';
        u.Email='bisfnewuser@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.Sales_Org__c='3010';
        u.Delivery_Plant__c='3010';
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;
        
        Campaign_Budget__c camBud = new Campaign_Budget__c();
        camBud.Sales_Org__c='3010';
        camBud.Plant__c='3010';
        camBud.Year__c=String.valueOf(date.today().Year());
        camBud.Budgeted_Amount__c=10000;
        //camBud.ExteralId__c='testuser_2025_1';
        insert camBud;

        Monthly_Budget__c mb=new Monthly_Budget__c();
        mb.Campaign_Budget__c=camBud.Id;
        mb.Budgeted_Amount__c=1000;
        mb.Month__c=String.valueOf(date.today().Month());
        mb.Sales_Rep__c=u.Id;
        insert mb;

        Campaign cam = new Campaign();
        cam.Date__c=date.today();
        cam.OwnerId=u.Id;
        cam.Name='test';
        cam.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Offline_Campaign').getRecordTypeId();
        insert cam;
        
        Campaign cam1 = new Campaign();
        cam1.Date__c=date.today();
        cam1.OwnerId=u.Id;
        cam1.Name='test';
        cam1.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Online_Campaign').getRecordTypeId();
        insert cam1;
        
        cam.Approval_Status__c = 'Approved';
        update cam;
        cam1.Approval_Status__c = 'Approved';
        update cam1;
        cam1.MKT_Approval__c = 'Approving';
        update cam1;
    }
}