force-app/main/default/objects/Campaign/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Customer_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Search/Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.MDG_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns (Ship To)</relationshipLabel>
    <relationshipName>Campaigns_Ship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <label>Campaign Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaing Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Product__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Product</relationshipLabel>
    <relationshipName>Campaign_Product_Child</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Campaign__r.Approval_Status__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Business_Model__c</fullName>
    <label>Business Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deliver_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Business_Model1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Free Order</relationshipLabel>
    <relationshipName>Free_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.MDG_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order (Ship To)</relationshipLabel>
    <relationshipName>Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Model_C.recordType-meta.xml
<RecordType>
    <fullName>Model_C</fullName>
    <active>true</active>
    <label>Model C</label>
</RecordType>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Campaign_Product__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Product</label>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Free Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Distr_Channel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribution Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Model1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C0</fullName>
        <label>Model C</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>Model B</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>Model C+</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>Model A</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>Model A+</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>Model B+</label>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateFreeOrderController.cls
/**
 * @description       : 创建free Order控制类
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 04-16-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   03-02-2026   Gerry   Initial Version
**/
public without sharing class CreateFreeOrderController {

    @AuraEnabled
    public static Output createFreeOrder(String recordId) {
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        Savepoint sp = Database.setSavepoint();
        try {
            Campaign ca = [SELECT OwnerId,Ship_To__c,Approval_Status__c,Id,Sales_Org__c,Delivery_Plant__c,Customer_Lookup__c,Distribution_Channel__c FROM Campaign WHERE Id =:recordId];
            if (ca.Approval_Status__c != 'Approved') {
                out.isSucess = false;
                out.errorMsg = 'The campaign is not approved.';
                return out;
            }
            Order__c order = new Order__c();
            order.Sales_Org__c = ca.Sales_Org__c;
            order.Deliver_Plant__c = ca.Delivery_Plant__c;
            order.Business_Model__c = 'C0';
            order.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Model_C').getRecordTypeId();
            order.Campaign__c = recordId;
            order.Status__c = 'Draft';
            order.Order_type__c = 'ZFD';
            order.Customer__c = ca.Customer_Lookup__c;
            order.Currency__c = 'USD';
            order.Distr_Channel__c = ca.Distribution_Channel__c;
            order.Ship_To__c = ca.Ship_To__c;
            order.OwnerId = ca.OwnerId;
            order.Terms_Of_Payment__c = 'AR01';
            Database.insert(order);
            out.newRecordId = order.Id;
            List<Order_Item__c> oiList = new List<Order_Item__c>();
            Integer itemNum = 10;
            for (Campaign_Product__c cp : [
                                            SELECT 
                                                Id,Product_Name__c,Quantity__c,Product_Name__r.Product__r.Name,Product_Name__r.Name,Product_Unit_Lookup__c,
                                                Delivery_Date__c,Unit__c
                                            FROM 
                                                Campaign_Product__c 
                                            WHERE Campaign__c = :recordId
                                            AND Product_Name__r.Product__r.Name != null
                                            AND Product_Name__r.Name != null
            ]) {
                Order_Item__c oi = new Order_Item__c();
                oi.Order__c = order.Id;
                oi.Commodity__c = cp.Product_Name__c;
                oi.Campaign_Product__c = cp.Id;
                oi.IsCreate__c = TRUE;
                oi.Quantity__c = cp.Quantity__c;
                oi.Material_Number__c = cp.Product_Name__r.Product__r.Name;
                oi.Product_Type__c = 'Free Product';
                oi.Product_Name_Text__c = cp.Product_Name__r.Name;
                oi.SAP_Item_Num__c = String.valueOf(itemNum);
                oi.Material_Description__c = cp.Product_Name__r.Name;
                oi.Price__c = 0;
                oi.Sales_Unit__c = cp.Product_Unit_Lookup__c;
                oi.Sales_Unit_Text__c = cp.Unit__c;
                oi.Delivery_Date__c = cp.Delivery_Date__c;
                itemNum += 10;
                oiList.add(oi);
            }
            if (oiList.size()>0) {
                Database.insert(oiList);
            }
            order.Status__c = 'Approved';
            update order;//触发sap同步
        } catch (Exception e) {
            System.debug('error:'+e.getMessage()+';Line:'+e.getLineNumber());
            Database.rollback(sp); 
            out.isSucess = false; 
            out.errorMsg = e.getMessage();
        }
        return out;
        
    }
    public class Output{
        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public String returnUrl {get;set;}

        @AuraEnabled
        public String newRecordId {get;set;}
    }
}