force-app/main/default/objects/Campaign/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>TEXT(MONTH(Datevalue(CreatedDate)) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Monthly_Budget__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Budget</label>
    <referenceTo>Monthly_Budget__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(CreatedDate) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Offline_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Offline_Campaign</fullName>
    <active>true</active>
    <label>Offline Campaign</label>
</RecordType>

force-app/main/default/objects/Campaign_Budget__c/Campaign_Budget__c.object-meta.xml
<CustomObject>
    <label>Campaign Budget</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Budget</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Budget__c/fields/Budgeted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/ExteralId__c.field-meta.xml
<CustomField>
    <fullName>ExteralId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>销售组织+年份</inlineHelpText>
    <label>ExteralId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DataImportTemplate__c/DataImportTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DataImportTemplate</label>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/ImportDataFieldConf__c.object-meta.xml
<CustomObject>
    <label>Import Data Field Configuration</label>
    <nameField>
        <label>Import Data Field Configuration Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/fields/Obj_Name__c.field-meta.xml
<CustomField>
    <fullName>Obj_Name__c</fullName>
    <label>Obj Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Budget__c/fields/Campaign_Budget__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Budget__c</fullName>
    <label>Campaign Budget</label>
    <referenceTo>Campaign_Budget__c</referenceTo>
    <relationshipLabel>Monthly Budget</relationshipLabel>
    <relationshipName>Monthly_Budget_Parent</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/ExteralId__c.field-meta.xml
<CustomField>
    <fullName>ExteralId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>年份+销售+月份</inlineHelpText>
    <label>ExteralId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Budget_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/Participants_List__c.object-meta.xml
<CustomObject>
    <label>Participants List</label>
    <nameField>
        <label>Participants  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants List</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participants_List__c/fields/Sales_rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_rep__c</fullName>
    <label>Sales rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchImportParticipantsListTest.cls
@isTest
public with sharing class BatchImportParticipantsListTest {
    static testMethod void testMethod1() {
        ContentVersion contentVersion = new ContentVersion(
                    Title = 'Penguins',
                    PathOnClient = 'Penguins.jpg',
                    VersionData = Blob.valueOf('Test Content'),
                    IsMajorVersion = true
            );
        insert contentVersion;
        ContentVersion c = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];
        ContentDistribution cdl = new ContentDistribution();
        cdl.ContentVersionId = contentVersion.Id;
        cdl.Name = 'PublicShare';
        cdl.PreferencesAllowViewInBrowser = true;
        cdl.PreferencesLinkLatestVersion = true;
        cdl.PreferencesNotifyOnVisit = false;
        cdl.PreferencesPasswordRequired = false;
        cdl.PreferencesAllowOriginalDownload = true;
        cdl.PreferencesNotifyRndtnComplete = false;
        insert cdl;

        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'bisfnewuser@testorg.com';
        u.Alias = 'newUser';
        u.Email='bisfnewuser@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Sales_Org__c='3010';
        u.Delivery_Plant__c='3010';
        insert u;

        Campaign_Budget__c camBud = new Campaign_Budget__c();
        camBud.Sales_Org__c='3010';
        camBud.Plant__c='3010';
        camBud.Year__c=String.valueOf(date.today().Year());
        camBud.Budgeted_Amount__c=10000;
        //camBud.ExteralId__c='testuser_2025_1';
        insert camBud;

        Monthly_Budget__c mb=new Monthly_Budget__c();
        mb.Campaign_Budget__c=camBud.Id;
        mb.Budgeted_Amount__c=1000;
        mb.Month__c=String.valueOf(date.today().Month());
        mb.Sales_Rep__c=u.Id;
        insert mb;

        Campaign cam = new Campaign();
        cam.Date__c=date.today();
        cam.OwnerId=u.Id;
        cam.Name='test';
        cam.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Offline_Campaign').getRecordTypeId();
        insert cam;


        DataImportTemplate__c dit1 = new DataImportTemplate__c();
        dit1.Name = 'Participants_List_MX';
        dit1.FileId__c = c.Id;
        insert dit1;
        
        ImportDataFieldConf__c dataConf=new ImportDataFieldConf__c();
        dataConf.RecordType__c='3010;5070';
        dataConf.Obj_Name__c='Participants_List__c';
        insert dataConf;


        BatchImportParticipantsListController.getInitData(cam.Id);
    }

    static testMethod void testMethod2() {

        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'bisfnewuser@testorg.com';
        u.Alias = 'newUser';
        u.Email='bisfnewuser@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Sales_Org__c='3010';
        u.Delivery_Plant__c='3010';
        insert u;

        Campaign_Budget__c camBud = new Campaign_Budget__c();
        camBud.Sales_Org__c='3010';
        camBud.Plant__c='3010';
        camBud.Year__c=String.valueOf(date.today().Year());
        camBud.Budgeted_Amount__c=10000;
        //camBud.ExteralId__c='testuser_2025_1';
        insert camBud;

        Monthly_Budget__c mb=new Monthly_Budget__c();
        mb.Campaign_Budget__c=camBud.Id;
        mb.Budgeted_Amount__c=1000;
        mb.Month__c=String.valueOf(date.today().Month());
        mb.Sales_Rep__c=u.Id;
        insert mb;

        Campaign cam = new Campaign();
        cam.Date__c=date.today();
        cam.OwnerId=u.Id;
        cam.Name='test';
        cam.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Offline_Campaign').getRecordTypeId();
        insert cam;

        String json ='[{"Name":"testname","Position__c":"test"}]';
        Map<String,String> strMap = new Map<String,String>();
        strMap.put('Name','Name');
        strMap.put('Position__c','Position');
       
        List<String> mustFillValueFields = new List<String>();
        BatchImportParticipantsListController.saveData(json,strMap,mustFillValueFields,cam.Id);
        mustFillValueFields.add('Sales_rep__c');
        BatchImportParticipantsListController.saveData(json,strMap,mustFillValueFields,cam.Id);
    }
}