force-app/main/default/objects/Campaign/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HERBICIDES</fullName>
            </value>
            <value>
                <fullName>INSECTICIDES</fullName>
            </value>
            <value>
                <fullName>FUNGICIDES</fullName>
            </value>
            <value>
                <fullName>BIOLOGICAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DataImportTemplate__c/DataImportTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DataImportTemplate</label>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/ImportDataFieldConf__c.object-meta.xml
<CustomObject>
    <label>Import Data Field Configuration</label>
    <nameField>
        <label>Import Data Field Configuration Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportDataFieldConf__c/fields/IF_Need__c.field-meta.xml
<CustomField>
    <fullName>IF_Need__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IF Need</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ImportDataFieldConf__c/fields/Obj_Name__c.field-meta.xml
<CustomField>
    <fullName>Obj_Name__c</fullName>
    <label>Obj Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/Participants_List__c.object-meta.xml
<CustomObject>
    <label>Participants List</label>
    <nameField>
        <label>Participants  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants List</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participants_List__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Participants List</relationshipLabel>
    <relationshipName>Participants_List_Campaign</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLIENTE A</fullName>
                <label>CUSTOMER A</label>
            </value>
            <value>
                <fullName>CLIENTE B</fullName>
                <label>CUSTOMER B</label>
            </value>
            <value>
                <fullName>CLIENTE C</fullName>
                <label>CUSTOMER C</label>
            </value>
            <value>
                <fullName>MEGA FARMER</fullName>
            </value>
            <value>
                <fullName>FARMER</fullName>
            </value>
            <value>
                <fullName>CLIENTE Estratégico</fullName>
                <label>Strategy customer</label>
            </value>
            <value>
                <fullName>CLIENTE Convencional</fullName>
                <label>Conventional customer</label>
            </value>
            <value>
                <fullName>CLIENTE Transaccional</fullName>
                <label>Transactional customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <label>Crop</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maíz</fullName>
                <label>Corn</label>
            </value>
            <value>
                <fullName>Soja</fullName>
                <label>Soybean</label>
            </value>
            <value>
                <fullName>Trigo</fullName>
                <label>Wheat</label>
            </value>
            <value>
                <fullName>Sorgo</fullName>
                <label>Sorghum</label>
            </value>
            <value>
                <fullName>Girasol</fullName>
                <label>Sunflower</label>
            </value>
            <value>
                <fullName>Cebada</fullName>
                <label>Barley</label>
            </value>
            <value>
                <fullName>Maní</fullName>
                <label>Peanut</label>
            </value>
            <value>
                <fullName>Caña de Azúcar</fullName>
                <label>Sugarcane</label>
            </value>
            <value>
                <fullName>Tabaco</fullName>
                <label>Tobacco</label>
            </value>
            <value>
                <fullName>Poroto</fullName>
                <label>Bean</label>
            </value>
            <value>
                <fullName>Algodón</fullName>
                <label>Cotton</label>
            </value>
            <value>
                <fullName>Cítricos</fullName>
                <label>Citrus</label>
            </value>
            <value>
                <fullName>Limon</fullName>
                <label>Lemon</label>
            </value>
            <value>
                <fullName>Arroz</fullName>
                <label>Rice</label>
            </value>
            <value>
                <fullName>Papa</fullName>
                <label>Potato</label>
            </value>
            <value>
                <fullName>Cebolla</fullName>
                <label>Onion</label>
            </value>
            <value>
                <fullName>Hortalizas</fullName>
                <label>Vegetables</label>
            </value>
            <value>
                <fullName>Alfalfa</fullName>
            </value>
            <value>
                <fullName>Aguacate</fullName>
                <label>Avocado</label>
            </value>
            <value>
                <fullName>Tomate y Chile</fullName>
                <label>Tomatoe &amp; pepper</label>
            </value>
            <value>
                <fullName>Frutillas</fullName>
                <label>Berries</label>
            </value>
            <value>
                <fullName>Agave</fullName>
            </value>
            <value>
                <fullName>Piña</fullName>
                <label>Pineapple</label>
            </value>
            <value>
                <fullName>Brasicas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Hectares_of_Field__c.field-meta.xml
<CustomField>
    <fullName>Hectares_of_Field__c</fullName>
    <label>Hectares of Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Preferred_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Product_Name__c</fullName>
    <label>Preferred Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HERBICIDAS</fullName>
                <label>HERBICIDES</label>
            </value>
            <value>
                <fullName>INSECTICIDAS</fullName>
                <label>INSECTICIDES</label>
            </value>
            <value>
                <fullName>FUNGICIDAS</fullName>
                <label>FUNGICIDES</label>
            </value>
            <value>
                <fullName>BIOLOGICOS</fullName>
                <label>BIOLOGICAL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOA</fullName>
            </value>
            <value>
                <fullName>NEA</fullName>
            </value>
            <value>
                <fullName>CORDOBA</fullName>
            </value>
            <value>
                <fullName>LITORAL</fullName>
            </value>
            <value>
                <fullName>BS AS</fullName>
            </value>
            <value>
                <fullName>LA PAMPA</fullName>
            </value>
            <value>
                <fullName>CUYO</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
            <value>
                <fullName>Occidente Norte</fullName>
            </value>
            <value>
                <fullName>Occidente Sur</fullName>
            </value>
            <value>
                <fullName>Michichoacán</fullName>
            </value>
            <value>
                <fullName>Bajío</fullName>
            </value>
            <value>
                <fullName>Pacifico</fullName>
            </value>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Centro</fullName>
            </value>
            <value>
                <fullName>Altiplano</fullName>
            </value>
            <value>
                <fullName>Golfo Norte</fullName>
            </value>
            <value>
                <fullName>Golfo Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Sales_rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_rep__c</fullName>
    <label>Sales rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participants_List__c/fields/Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Social_Media__c</fullName>
    <label>Social Media</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sitio web</fullName>
            </value>
            <value>
                <fullName>Linkedin</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Tik Tok</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/Quote_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Detail</label>
    <nameField>
        <displayFormat>QD-{000000}</displayFormat>
        <label>Quote Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Detail__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchImportParticipantsListController.cls
public without sharing class BatchImportParticipantsListController {
    //初始化数据
    @AuraEnabled
    public static InitData getInitData(String id){
        InitData init = new InitData();
        
        Campaign cam=[SELECT Id,Sales_Org__c FROM Campaign WHERE Id =: id];
        //检验导入用户是否是同一sales org
        List<User> impoUserList = [SELECT Id,Sales_Org__c,Delivery_Plant__c FROM User WHERE Id=:System.UserInfo.getUserId()];
        init.userFlag = '0';
        if (cam.Sales_Org__c != impoUserList[0].Sales_Org__c ) {
            init.userFlag = '1';
        }
        //获取模板链接
        List<ContentDistribution> salesLink;
        //获取 数据导入字段配置 对象中配置的字段
        List<ImportDataFieldConf__c> fieldConfs;
        
        
        DataImportTemplate__c fileidSalesOrg ;
        if(cam.Sales_Org__c=='3010' || cam.Sales_Org__c=='3020'){
            fileidSalesOrg= DataImportTemplate__c.getValues('Participants_List_MX');
        }
        if(cam.Sales_Org__c=='5070' || cam.Sales_Org__c=='5130'){
            fileidSalesOrg= DataImportTemplate__c.getValues('Participants_List_AR');
        }
       
        String salesOrgValue = fileidSalesOrg.FileId__c;
        salesLink = [SELECT Id, ContentDownloadUrl, DistributionPublicUrl
                                                          FROM ContentDistribution 
                                                          WHERE ContentDocumentId =: salesOrgValue  LIMIT 1];
        fieldConfs = [SELECT Id, Obj_Name__c, Field_Label_Name__c,RecordType__c  ,
                                                    Field_Api_Name__c,Data_Type__c, If_Need__c 
                                                    FROM ImportDataFieldConf__c 
                                                    WHERE Obj_Name__c = 'Participants_List__c' ];
                
        if (!Test.isRunningTest()) {
            init.salesDownloadLink = salesLink[0].ContentDownloadUrl;
        }
        
        System.debug('fieldConfs===》'+fieldConfs);
        // 字段Label和API对应关系
        Map<String,String> excelHeaderMap = new Map<String, String>();
        // API和字段Label对应关系 
        Map<String,String> excelHeaderKeyToLabelMap = new Map<String, String>();
        Set<String> mustFillValueFields = new Set<String>(); // 在配置表中勾选了必填的字段API

        for(ImportDataFieldConf__c curConf : fieldConfs){
            excelHeaderMap.put(curConf.Field_Label_Name__c, curConf.Field_Api_Name__c);
            excelHeaderKeyToLabelMap.put(curConf.Field_Api_Name__c, curConf.Field_Label_Name__c);
            List<String> recordTypeList = new List<String>();
            if (String.isNotBlank(curConf.RecordType__c)) {
                    String objectRecordType = curConf.RecordType__c;
                    recordTypeList = objectRecordType.split(';');
            }
            //设置必填字段
            if (curConf.IF_Need__c && (String.isBlank(curConf.RecordType__c) || (String.isNotBlank(curConf.RecordType__c) && recordTypeList.contains(cam.Sales_Org__c)))) {
                    mustFillValueFields.add(curConf.Field_Api_Name__c);
                }
        }   
        init.excelHeaderMap = excelHeaderMap;
        init.excelHeaderKeyToLabelMap = excelHeaderKeyToLabelMap;    
        init.mustFillValueFields = mustFillValueFields;
        System.debug('查看必填字段==》'+mustFillValueFields);
        return init;
    }

    //构造验证失败得返回值
    public static Integer ValiriFailed(List<ValiriFailedSalesTarget> valiriFailedSalesTargets, Participants_List__c salesTar, String failedReason, Map<String, ValiriFailedSalesTarget> inveRepo_inveRepoValiriFail, String execlRowNum){
       
        if(inveRepo_inveRepoValiriFail.containsKey(execlRowNum)){
            ValiriFailedSalesTarget valiriFailed = inveRepo_inveRepoValiriFail.get(execlRowNum);
            valiriFailed.FailedReason = valiriFailed.FailedReason + '; ' + failedReason;
        }else{
            ValiriFailedSalesTarget valiriFailed = new ValiriFailedSalesTarget();
            valiriFailed.Name = String.valueOf(salesTar.Name);
            valiriFailed.FailedReason = failedReason;
            valiriFailed.execlNum = execlRowNum;
            valiriFailedSalesTargets.add(valiriFailed);
            inveRepo_inveRepoValiriFail.put(execlRowNum, valiriFailed);
          
        }
        return 1;
    }

    //保存数据至Salesforce
    @AuraEnabled
    public static InsertSalesTargetResult saveData( String TargetJson,Map<String,String> excelHeaderKeyToLabelMap, List<String> mustFillValueFields,String camId) {
        /*if(!Test.isRunningTest()){
            TargetJson = '[' + TargetJson.substring(TargetJson.indexOf(',{')+1); // 去掉execl表头
        }*/

        String targetSubStr = '},'; 
        Integer count = 0; 
        Integer index = TargetJson.indexOf(targetSubStr); 
        while(index != -1) { 
            count++; index = TargetJson.indexOf(targetSubStr, index + 1); 
        } 
        System.debug('子字符串 "' + targetSubStr + '" 出现的次数: ' + count);
        System.debug('TargetJson===>'+TargetJson);
        Decimal maxRow;
        if (!Test.isRunningTest()) {
            DataImportTemplate__c fileidMaxRow = DataImportTemplate__c.getValues('MaxRow');
            String maxRowValue = fileidMaxRow.FileId__c;
            maxRow = Decimal.valueOf(maxRowValue);
        }else{
            maxRow = 100;
        }

        //超出最大导入数量  
        if(count > maxRow){
            InsertSalesTargetResult insertResult = new InsertSalesTargetResult();
            insertResult.lResult = 'tooManyRecord';
            // insertResult.valiriFailedSalesTarget = valiriFailedSalesTargets;
            insertResult.successValiAmount = 0;
            insertResult.failedValiAmount = 0;
            insertResult.successInsertAmount = 0;
            insertResult.excelMaxRow = maxRow;
            return insertResult;     
        }

        List<ValiriFailedSalesTarget> valiriFailedSalesTargets = new List<ValiriFailedSalesTarget>(); // 存储验证失败的
        Map<String, ValiriFailedSalesTarget> inveRepo_inveRepoValiriFail = new Map<String, ValiriFailedSalesTarget>(); 
        
        System.debug('验证失败的前台返回数据===》'+mustFillValueFields+'    Size()===>'+mustFillValueFields.size());   //size = 49
        

        // Integer  num = 0;
        List<Object> testList = (List<Object>)JSON.deserializeUntyped(TargetJson);
        System.debug('testList==>'+testList);
       
        if(testList.size()>0){
            for(Object testItem : testList){
                Map<String, Object> sales = (Map<String, Object>) testItem;
            }
        }

        Campaign campaign=[SELECT Id FROM Campaign WHERE Id =: camId];

       
        List<Participants_List__c> insertsList = new List<Participants_List__c>();  
        Integer rowNum = 4;
        Set<String> keySet = new Set<String>();
        Set<String>  vertifyDupilcateData= new Set<String>();
        for(Object testObj : testList) {
            Integer flag = 0;
            Map<String, Object> testMap = (Map<String, Object>)testObj;
            // String testJson = JSON.serialize(testObj);
            Participants_List__c parList = new Participants_List__c();
            parList.Campaign__c=camId;
            //camMember.ContactId='003D5000013N7KwIAK';
            try{
                System.debug('begin: '+ rowNum);
                for(String curField : mustFillValueFields){
                    if(!testMap.containsKey(curField) || String.isBlank(String.valueOf(testMap.get(curField))) ){
                        ValiriFailed(valiriFailedSalesTargets, 
                                parList, '\"' + 
                                    excelHeaderKeyToLabelMap.get(curField) + '\"' + System.label.Sales_Forcast_Imp_Required, 
                                    inveRepo_inveRepoValiriFail,String.valueOf(rowNum));
                    }
                }

                /*if(testMap.get('Name')!=null)
                {
                    if(vertifyDupilcateData.contains(String.valueOf(testMap.get('Name'))))
                    {
                        flag = ValiriFailed(valiriFailedSalesTargets, parList, 'Exist Same  Participant Name '+String.valueOf(testMap.get('Name')), inveRepo_inveRepoValiriFail, String.valueOf(rowNum));   
                    }
                    else
                    {
                        vertifyDupilcateData.add(String.valueOf(testMap.get('Name')));
                    }
                }*/
                parList.Name=String.valueOf(testMap.get('Name'));
                parList.Email__c=String.valueOf(testMap.get('Email__c')) ;
                parList.Phone__c=String.valueOf(testMap.get('Phone__c'));
                parList.Company_Name__c=String.valueOf(testMap.get('Company_Name__c'));
                parList.Company_Type__c=String.valueOf(testMap.get('Company_Type__c'));
                parList.Position__c=String.valueOf(testMap.get('Position__c'));
                parList.Crop__c=String.valueOf(testMap.get('Crop__c'));
                parList.Product_Line__c=String.valueOf(testMap.get('Product_Line__c'));
                parList.Preferred_Product_Name__c=String.valueOf(testMap.get('Preferred_Product_Name__c'));
                parList.Sales_rep__c=String.valueOf(testMap.get('Sales_rep__c'));
                parList.Hectares_of_Field__c=String.valueOf(testMap.get('Hectares_of_Field__c'));
                parList.Region__c=String.valueOf(testMap.get('Region__c'));
                parList.Social_Media__c=String.valueOf(testMap.get('Social_Media__c'));
                insertsList.add(parList);


            }catch(Exception e) {
                flag = ValiriFailed(valiriFailedSalesTargets, parList,System.Label.Sales_Forcast_Imp_System_Exception + e.getMessage() + '[' + e.getLineNumber() + ']' , inveRepo_inveRepoValiriFail, String.valueOf(rowNum));   
            }

            System.debug(rowNum);
            System.debug(testMap);
            System.debug(valiriFailedSalesTargets);
            rowNum = rowNum + 1;
        } 
        
        
        
        //回滚
        System.savepoint sp = Database.setSavepoint();
        try {
            InsertSalesTargetResult insertResult = new InsertSalesTargetResult();
            System.debug('valiriFailedSalesTargets==>'+valiriFailedSalesTargets);
            //存在验证失败的数据
            if(valiriFailedSalesTargets.size() > 0){
                insertResult.valiriFailedSalesTarget = valiriFailedSalesTargets;   //存在验证失败的数据
                System.debug('存在验证失败的数据： insertResult.valiriFailedSalesTarget===>'+ insertResult.valiriFailedSalesTarget+'  size() '+insertResult.valiriFailedSalesTarget.size());
                insertResult.lResult = 'Failed';
                if(testList.size()>0){
                    insertResult.successValiAmount = testList.size() - valiriFailedSalesTargets.size();
                }else {
                    insertResult.successValiAmount = 0 ;
                }
                
                insertResult.failedValiAmount = valiriFailedSalesTargets.size();
                insertResult.successInsertAmount = 0;
            }else{
                System.debug('insertsList==>'+insertsList);
                //插入数据
                insert insertsList;
                //Database.upsert(insertsList,Quote_Detail__c.fields.External_Id__c);
                //Database.upsert(insertsList);
                System.debug('insertsList.size()==>'+insertsList.size());
                insertResult.lResult = 'Success';
                insertResult.successValiAmount = insertsList.size();
                insertResult.failedValiAmount = 0;
                insertResult.successInsertAmount = insertsList.size();    
            }
            return insertResult;   

        } catch (Exception e) {
            System.debug('LineNumber:' + e.getLineNumber() + 'Message:' + e.getMessage());
            Database.rollback(sp);
            InsertSalesTargetResult insertResult = new InsertSalesTargetResult();
            insertResult.lResult = 'Error';
            insertResult.successValiAmount = 0;
            insertResult.failedValiAmount = 0;
            insertResult.successInsertAmount = 0;
            insertResult.excelMaxRow = maxRow;
            insertResult.errMsg = 'LineNumber:' + e.getLineNumber() + 'Message:' + e.getMessage();
            return insertResult; 
        }
    }

    //初始化数据
    public class InitData {
        //销售目标模板下载链接
        @AuraEnabled public String salesDownloadLink{get; set;}
        //字段Label和API对应关系
        @AuraEnabled public Map<String, String> excelHeaderMap{get; set;}
        //API和字段Label对应关系
        @AuraEnabled public Map<String, String> excelHeaderKeyToLabelMap{get; set;}
        //必填字段
        @AuraEnabled public Set<String> mustFillValueFields{get;set;}
        //检验user是否能导入这个销售预测
        @AuraEnabled public String userFlag{get; set;}
        
    } 
    // 验证失败的数据
    public class ValiriFailedSalesTarget {
        @AuraEnabled public String execlNum{get; set;}  // Execl行数
        @AuraEnabled public String Name{get; set;}     //  销售目标名称
        @AuraEnabled public String FailedReason{get; set;}  // 失败原因
    }
    // 执行插入数据的返回值
    public class InsertSalesTargetResult {
        @AuraEnabled public List<ValiriFailedSalesTarget> valiriFailedSalesTarget;
        @AuraEnabled public String lResult{get; set;}
        @AuraEnabled public String errMsg{get; set;}
        @AuraEnabled public Decimal excelMaxRow{get; set;}
        @AuraEnabled public Integer successValiAmount{get; set;}
        @AuraEnabled public Integer failedValiAmount{get; set;}
        @AuraEnabled public Integer successInsertAmount{get; set;}
    }

}