force-app/main/default/objects/Campaign/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <label>Campaign Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaing Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Product__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Product</relationshipLabel>
    <relationshipName>Campaign_Product_Child</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipLabel>Campaign Product</relationshipLabel>
    <relationshipName>Campaign_Product_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Campaign__r.Approval_Status__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Product__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Is_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Default_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Unit__c</fullName>
    <label>Default Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Unit</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Shelves</fullName>
                <default>true</default>
                <label>On Shelves</label>
            </value>
            <value>
                <fullName>Off Shelves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Conversion_Coefficient__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Coefficient__c</fullName>
    <inlineHelpText>1 [Product Sales Unit] = [Conversion Coefficient] [Basic Metering Unit]</inlineHelpText>
    <label>Conversion Coefficient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Unit</relationshipLabel>
    <relationshipName>Product_Unit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Unit__c</fullName>
    <label>Product Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddCampaignProductControllerTest.cls
/**************************************************************************************************
 * Name: AddCampaignProductControllerTest
 * Object: Campaign_Product__c
 * Purpose: Test class for AddCampaignProductController
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Agentforce        2026-04-15         Created             
***************************************************************************************************/
@isTest
private class AddCampaignProductControllerTest {
    
    @testSetup
    static void setup() {
        // Create test Campaign
        Campaign testCampaign = new Campaign(
            Name = 'Test Campaign',
            Sales_Org__c = '5130',
            IsActive = true
        );
        insert testCampaign;
        
        // Create test Product
        Product__c testProduct = new Product__c(
            Name = 'TEST001'
        );
        insert testProduct;
        
        // Create test Product Sales Info
        Product_Sales_Info__c testProductSalesInfo = new Product_Sales_Info__c(
            Product__c = testProduct.Id,
            Sales_Organization__c = '5130',
            Status__c = 'On Shelves',
            Default_Sales_Unit__c = 'KG'
        );
        insert testProductSalesInfo;
        
        // Create test Product Name
        Product_Name__c testProductName = new Product_Name__c(
            Name = 'Test Product Name',
            Product__c = testProduct.Id,
            Product_Sales_Info__c = testProductSalesInfo.Id,
            Is_Delete__c = false
        );
        insert testProductName;
        
        // Create test Product Unit
        Product_Unit__c testProductUnit = new Product_Unit__c(
            Product__c = testProduct.Id,
            Product_Sales_Unit__c = 'KG',
            Conversion_Coefficient__c = 1
        );
        insert testProductUnit;
    }
    
    @isTest
    static void testInitData() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.initData(testCampaign.Id);
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        System.assertNotEquals(null, result.productNameList, 'Product list should not be null');
        System.assertEquals(1, result.productNameList.size(), 'Should return one product');
    }
    
    @isTest
    static void testInitDataWithExistingProducts() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        Product_Name__c testProductName = [SELECT Id FROM Product_Name__c LIMIT 1];
        
        // Create existing campaign product
        Campaign_Product__c existingProduct = new Campaign_Product__c(
            Campaign__c = testCampaign.Id,
            Product_Name__c = testProductName.Id,
            Quantity__c = 5,
            Unit__c = 'KG',
            Delivery_Date__c = Date.today()
        );
        insert existingProduct;
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.initData(testCampaign.Id);
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        System.assertEquals(1, result.campaignProductList.size(), 'Should return one existing product');
    }
    
    @isTest
    static void testSearchDataMe() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.searchDataMe(testCampaign.Id, 'Test');
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        System.assertEquals(1, result.productNameList.size(), 'Should return one product');
    }
    
    @isTest
    static void testSearchDataMeEmpty() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.searchDataMe(testCampaign.Id, '');
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        System.assertEquals(1, result.productNameList.size(), 'Should return one product');
    }
    
    @isTest
    static void testSaveData() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        Product_Name__c testProductName = [SELECT Id FROM Product_Name__c LIMIT 1];
        
        // Create campaign product data
        AddCampaignProductController.CampaignProduct cp = new AddCampaignProductController.CampaignProduct();
        cp.indexNum = '10';
        cp.campaignProductData = new Campaign_Product__c(
            Campaign__c = testCampaign.Id,
            Product_Name__c = testProductName.Id,
            Quantity__c = 10,
            Unit__c = 'KG',
            Delivery_Date__c = Date.today()
        );
        cp.opList = new List<AddCampaignProductController.Option>();
        
        List<AddCampaignProductController.CampaignProduct> campaignProductList = new List<AddCampaignProductController.CampaignProduct>{cp};
        List<String> deleteList = new List<String>();
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.saveData(campaignProductList, deleteList);
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        
        List<Campaign_Product__c> savedProducts = [
            SELECT Id, Quantity__c, Unit__c 
            FROM Campaign_Product__c 
            WHERE Campaign__c = :testCampaign.Id
        ];
        System.assertEquals(1, savedProducts.size(), 'Should create one campaign product');
        System.assertEquals(10, savedProducts[0].Quantity__c, 'Quantity should match');
        System.assertEquals('KG', savedProducts[0].Unit__c, 'Unit should match');
    }
    
    @isTest
    static void testSaveDataWithDelete() {
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        Product_Name__c testProductName = [SELECT Id FROM Product_Name__c LIMIT 1];
        
        // Create existing campaign product
        Campaign_Product__c existingProduct = new Campaign_Product__c(
            Campaign__c = testCampaign.Id,
            Product_Name__c = testProductName.Id,
            Quantity__c = 5,
            Unit__c = 'KG',
            Delivery_Date__c = Date.today()
        );
        insert existingProduct;
        
        List<AddCampaignProductController.CampaignProduct> campaignProductList = new List<AddCampaignProductController.CampaignProduct>();
        List<String> deleteList = new List<String>{existingProduct.Id};
        
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.saveData(campaignProductList, deleteList);
        Test.stopTest();
        
        System.assertEquals(true, result.isSucess, 'Should be successful');
        
        List<Campaign_Product__c> remainingProducts = [
            SELECT Id 
            FROM Campaign_Product__c 
            WHERE Campaign__c = :testCampaign.Id
        ];
        System.assertEquals(0, remainingProducts.size(), 'Product should be deleted');
    }
    
    @isTest
    static void testErrorHandling() {
        Test.startTest();
        AddCampaignProductController.Output result = AddCampaignProductController.initData(null);
        Test.stopTest();
        
        System.assertEquals(false, result.isSucess, 'Should fail');
        System.assertNotEquals(null, result.errorMsg, 'Error message should be present');
    }
}