force-app/main/default/objects/Customer_Update__c/Customer_Update__c.object-meta.xml
<CustomObject>
    <label>Customer Update</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Customer Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Updates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Update__c/fields/Approve_Status__c.field-meta.xml
<CustomField>
    <fullName>Approve_Status__c</fullName>
    <label>Approve Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Updates</relationshipLabel>
    <relationshipName>Customer_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/New_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Name__c</fullName>
    <label>New Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/Owner_Plant__c.field-meta.xml
<CustomField>
    <fullName>Owner_Plant__c</fullName>
    <formula>Owner:User.Deliver_Plant_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance__mdt/Finance__mdt.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <pluralLabel>Finances</pluralLabel>
</CustomObject>

force-app/main/default/objects/Finance__mdt/fields/Delivery_Pant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Pant__c</fullName>
    <label>Delivery Pant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3011</fullName>
                <default>true</default>
                <label>3011</label>
            </value>
            <value>
                <fullName>3010</fullName>
            </value>
            <value>
                <fullName>3020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finance__mdt/fields/Finance__c.field-meta.xml
<CustomField>
    <fullName>Finance__c</fullName>
    <label>Finance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerUpdateTriggerHandler.cls
/**
 * @description       : 客户
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 12-10-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   12-09-2025   Gerry   Initial Version
**/
public without sharing class CustomerUpdateTriggerHandler implements Triggers.Handler{
    public void handle(){
        if (Trigger.isAfter && Trigger.isUpdate) {
            Map<Id,Customer_Update__c> oldMap = (Map<Id,Customer_Update__c>)Trigger.oldMap;
            List<Account> accUpdateList = new List<Account>();
            for (Customer_Update__c cu : (List<Customer_Update__c>)Trigger.new) {
                if (cu.Approve_Status__c == 'Approved' && cu.Approve_Status__c <> oldMap.get(cu.Id).Approve_Status__c) {
                    Account acc = new Account();
                    acc.Id = cu.Customer__c;

                    if (String.isNotBlank(cu.New_Customer_Name__c) && String.isNotEmpty(cu.New_Customer_Name__c)) {
                        acc.Name = cu.New_Customer_Name__c;
                    }
                    accUpdateList.add(acc);
                }
            }

            if (accUpdateList.size()>0) {
                Utility.isPassTriggerLogic = TRUE;//跳过校验逻辑
                Database.update(accUpdateList);
            }
        }

        if (Trigger.isbefore && Trigger.isInsert) {
            List<Account> accUpdateList = new List<Account>();
            Set<String> OwnerId = new Set<String>();
            Map<String,String> financeMap = new Map<String,String>();
            for(Finance__mdt fin : [SELECT Delivery_Pant__c,Finance__c FROM Finance__mdt]){
                financeMap.put(fin.Delivery_Pant__c, fin.Finance__c);
            }
            for (Customer_Update__c cu : (List<Customer_Update__c>)Trigger.new) {
                cu.Finance_User__c = financeMap.get(cu.Owner_Plant__c);
            }
        }
    }
}