force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <label>Campaign Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaing Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Campaign__r.Approval_Status__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignProductTriggerHandler.cls
public without sharing class CampaignProductTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isbefore && Trigger.isinsert)
        {
            for(Campaign_Product__c campaignProduct :(List<Campaign_Product__c>)Trigger.new)
            { 
                if(campaignProduct.Status__c=='Approved'){
                    //campaignProduct.addError('Campaign Approved Not Insert Campaign Product');
                    campaignProduct.addError(System.Label.CampaignProductInsertError);}
            }
        }
        if (Trigger.isbefore && Trigger.isupdate)
        {
            for(Campaign_Product__c campaignProduct :(List<Campaign_Product__c>)Trigger.new)
            {
                if(campaignProduct.Status__c=='Approved'){
                    //campaignProduct.addError('Campaign Approved Not Update Campaign Product');
                    campaignProduct.addError(System.Label.CampaignProductUpdateError);}
            }
        }
}
}