force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Actual_Credit_limit__c.field-meta.xml
<CustomField>
    <fullName>Actual_Credit_limit__c</fullName>
    <label>Customer Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Credit_Segment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Segment__c</fullName>
    <label>Credit Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credit_Segement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Remaining_Credit__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Credit__c</fullName>
    <label>SAP Available Credit Limit (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Rules__c.field-meta.xml
<CustomField>
    <fullName>Rules__c</fullName>
    <label>Rules</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rules</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Valid_Until__c</fullName>
    <label>Customer Credit Line Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Check_Rule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OV2</fullName>
        <label>OV2	Subsidiary Company With Overdue Open Items 0 Days</label>
    </customValue>
    <customValue>
        <fullName>OV1</fullName>
        <label>OV1	Subsidiary Company With Overdue Open Items 30 Days</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>01 Default -All Checks Active (Stat. Credit Limit)</label>
    </customValue>
    <customValue>
        <fullName>OV3</fullName>
        <label>OV3	Subsidiary Company With Overdue Open Items 15 Days</label>
    </customValue>
    <customValue>
        <fullName>OV4</fullName>
        <label>OV4 Credit Limit + Overdue Payment + 60 days</label>
    </customValue>
    <customValue>
        <fullName>OV</fullName>
        <isActive>false</isActive>
        <label>OV default-overseas subsidiary company</label>
    </customValue>
    <description>检查规则</description>
    <masterLabel>Check Rule</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Credit_Segement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z000</fullName>
        <default>true</default>
        <label>Z000 Overseas General Credit segment</label>
    </customValue>
    <description>信用段</description>
    <masterLabel>Credit Segement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Normal Check</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 Middle Risk</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B High Risk</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Medium Risk</label>
    </customValue>
    <description>风险等级</description>
    <masterLabel>Risk Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rules.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>STANDARD</fullName>
        <default>true</default>
        <label>STANDARD</label>
    </customValue>
    <masterLabel>Rules</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerCreditTriggerHandler.cls
public without sharing class CustomerCreditTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate)) {
            Map<Id,Customer_Credit_Info__c> oldMap = (Map<Id,Customer_Credit_Info__c>)Trigger.oldMap;
            for (Customer_Credit_Info__c csi : (List<Customer_Credit_Info__c>)Trigger.new) {
                if (Trigger.isUpdate && csi.Remaining_Credit__c!=oldMap.get(csi.Id).Remaining_Credit__c) {
                    continue;
                }
                if (System.isBatch() || System.isFuture()) {
                    continue;
                }
                if (Trigger.isUpdate) {
                    if (
                        oldMap.get(csi.Id).Actual_Credit_limit__c!=csi.Actual_Credit_limit__c ||
                        oldMap.get(csi.Id).Check_Rule__c!=csi.Check_Rule__c ||
                        oldMap.get(csi.Id).Credit_Segment__c!=csi.Credit_Segment__c ||
                        oldMap.get(csi.Id).Risk_Class__c!=csi.Risk_Class__c ||
                        oldMap.get(csi.Id).Rules__c!=csi.Rules__c ||
                        oldMap.get(csi.Id).Valid_Until__c!=csi.Valid_Until__c 
                    ) {
                        if (!Test.isRunningTest()) {
                            CustomerlimitSyncToSAP.submitToSAPFutrue(csi.Id);
                        }
                    }
                }else{
                    if (!Test.isRunningTest()) {
                            CustomerlimitSyncToSAP.submitToSAPFutrue(csi.Id);
                        }
                }
            }
        }
    }
}