force-app/main/default/objects/Contract_Processing_Product__c/Contract_Processing_Product__c.object-meta.xml
<CustomObject>
    <label>Tolling Product List</label>
    <nameField>
        <label>Tolling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tolling Product List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/FOB_Price__c.field-meta.xml
<CustomField>
    <fullName>FOB_Price__c</fullName>
    <label>FOB Bulking Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Is_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&apos;USD&apos;</defaultValue>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Exchange__c.field-meta.xml
<CustomField>
    <fullName>Exchange__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Retrograde__c.field-meta.xml
<CustomField>
    <fullName>Is_Retrograde__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is based on market price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/Quote_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Detail</label>
    <nameField>
        <displayFormat>QD-{000000}</displayFormat>
        <label>Quote Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Detail__c/fields/BU_Profit_Rate__c.field-meta.xml
<CustomField>
    <fullName>BU_Profit_Rate__c</fullName>
    <label>BU Margin Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/CIF_90_Days__c.field-meta.xml
<CustomField>
    <fullName>CIF_90_Days__c</fullName>
    <label>Quote Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/CIF_90_Days_Without_Margin__c.field-meta.xml
<CustomField>
    <fullName>CIF_90_Days_Without_Margin__c</fullName>
    <label>Quote Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/CIF_Price_Include_Commission__c.field-meta.xml
<CustomField>
    <fullName>CIF_Price_Include_Commission__c</fullName>
    <label>CIF Price Include Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Clearance_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Cost_Percentage__c</fullName>
    <label>Customs Clearance %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission Per Unit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Commission_Percent__c.field-meta.xml
<CustomField>
    <fullName>Commission_Percent__c</fullName>
    <label>Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Contract_Processing_Product__c.field-meta.xml
<CustomField>
    <fullName>Contract_Processing_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tolling Product</label>
    <referenceTo>Contract_Processing_Product__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Contract_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Delivery Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/FOB_Price__c.field-meta.xml
<CustomField>
    <fullName>FOB_Price__c</fullName>
    <label>FOB Bulking Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Is_Hand_Add__c.field-meta.xml
<CustomField>
    <fullName>Is_Hand_Add__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Add Manually</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <label>Item Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Order_Qnty__c.field-meta.xml
<CustomField>
    <fullName>Order_Qnty__c</fullName>
    <label>Order Qnty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Packing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Packing_Cost__c</fullName>
    <label>Packing Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>Packing_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packing Size</label>
    <referenceTo>Package_Data__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Packing_Size</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Pallet__c.field-meta.xml
<CustomField>
    <fullName>Pallet__c</fullName>
    <label>Pallet Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Term Cost Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product English Name</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Price_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Process_Cost__c.field-meta.xml
<CustomField>
    <fullName>Process_Cost__c</fullName>
    <label>Tolling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Child</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Quote_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product_Name__c</fullName>
    <label>Quote Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddQuoteDetailController.cls
/**************************************************************************************************
 * Name: AddQuoteDetailController
 * Object: 
 * Purpose: 添加报价产品控制类
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Noel             2024-10-14         Created             
***************************************************************************************************/
public without sharing class AddQuoteDetailController {
    @AuraEnabled
    public static Output initData(String quoteRecordId) {
        try {
            system.debug('quoteRecordId:'+quoteRecordId);
            Quote__c quote = [SELECT Name,Id,Quotation_Type__c,Exchange__c,Is_Retrograde__c,Payment_Term_Cost_Rate__c,Incoterms__c,Sales_Org__c  FROM Quote__c WHERE Id=:quoteRecordId];
            Output out = new Output();
            out.isSucess = true;
            out.quoteDetailList = new List<QuoteDetail>();
            if ((quote.Incoterms__c == 'DAP' || quote.Incoterms__c == 'DDP') && quote.Sales_Org__c == '3010') {
                out.isMXDAPORDDP = true;
            }else{
                out.isMXDAPORDDP = false;
            }
            if(quote.Quotation_Type__c=='HQ_Purchase' )
            {
                out.isHQSubClient=true;
            }
            else
            {
                out.isHQSubClient=false;
            }
            out.exchangeRate=quote.Exchange__c;
            if(quote.Is_Retrograde__c)
            {
                out.isRetrograde=false;
            }
            else
            {
                out.isRetrograde=true;
            }
            
            out.paymentTermCostRate=quote.Payment_Term_Cost_Rate__c;
            
            List<Quote_Detail__c> quoteDetailList = [
                                    SELECT 
                                        Id, Price_List__c,Is_Hand_Add__c,Inland_Cost_Including_Insurance__c,Clearance_Cost_Percentage__c,Packing_Size__c,Commission_Percent__c,Quote__c,FOB_Price__c,Order_Qnty__c,Packing_Cost__c,Pallet__c,Freight_Cost__c,Payment_Terms__c,CIF_90_Days__c,CIF_90_Days_Without_Margin__c,Cost__c,Contract_Processing_Product__c,Process_Cost__c,Commission__c,Item_Cost__c,Item_Price__c,BU_Profit_Rate__c,Delivery_Time__c,CIF_Price_Include_Commission__c,Quote_Product_Name__c,Unit__c
                                    FROM 
                                        Quote_Detail__c 
                                    WHERE Quote__c	 =: quoteRecordId];

            Integer index = 0;
            List<String> productNameList=new List<String>();
            for (Quote_Detail__c quoteDetail : quoteDetailList) {
                QuoteDetail qd = new QuoteDetail();
                qd.quoteDetailData = quoteDetail;
                qd.index=index;
                out.quoteDetailList.add(qd);
                index++;
                if(quoteDetail.Price_List__c != null)
                {
                    productNameList.add(quoteDetail.Price_List__c);
                    qd.isNotEdit=true;
                }else{
                    qd.isNotEdit=false;
                }
                if(quoteDetail.Contract_Processing_Product__c != null)
                {
                    productNameList.add(quoteDetail.Contract_Processing_Product__c);
                }
            }

            out.productNameList=productNameList;
            SearchProduct search = searchDataMe('',out.isHQSubClient);
            out.priceListList = search.priceListList;
            out.errorMsg = '';
            system.debug('out:'+out);
            return out;
        } catch (Exception e) {
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = e.getMessage()+';'+e.getLineNumber();
            return out;
        }
        
    
    }

    @AuraEnabled
    public static SearchProduct searchDataMe(String searchData,boolean isHQSubClient) {
        try {
            System.debug('isHQSubClient===>'+isHQSubClient);
            SearchProduct searchPro = new SearchProduct();
            searchPro.isSucess = true;
            searchPro.priceListList=new List<PriceList>();
            String query;
            if(isHQSubClient)
            {
                query = 'SELECT Id,Name,FOB_Price__c,Currency__c,Unit__c FROM Price_List__c WHERE Is_Delete__c=false';
                if (String.isNotBlank(searchData)) 
                {
                    query += ' AND (Name=:searchData OR Name LIKE \'%' + searchData + '%\')';
                }
            }
            else
            {
                query = 'SELECT Id,Name FROM Contract_Processing_Product__c';
                if (String.isNotBlank(searchData)) 
                {
                    query += ' WHERE Name=:searchData OR Name LIKE \'%' + searchData + '%\'';
                }
            }
            query +=' limit 100';
            Integer index=1;
            if(isHQSubClient)
            {
                List<Price_List__c> priceList = Database.query(query);
                System.debug('priceList===>'+priceList.size());
                for (Price_List__c priList : priceList) 
                {
            	    PriceList PL = new PriceList();
                    PL.priceListData=priList; 
                    PL.index=index;
                    index++;
                    searchPro.priceListList.add(PL);
                }  
            }
            else
            {
                List<Contract_Processing_Product__c> productList = Database.query(query);
                System.debug('productList===>'+productList.size());
                for (Contract_Processing_Product__c product : productList) 
                {
                    PriceList PL = new PriceList();
                    PL.productData=product; 
                    PL.index=index;
                    index++;
                    searchPro.priceListList.add(PL);
                }
            }
            System.debug('searchPro====>'+searchPro);
            searchPro.errorMsg = '';
            return searchPro;
        } catch (Exception e) {
            SearchProduct searchPro = new SearchProduct();
            searchPro.isSucess = false;
            searchPro.errorMsg = e.getMessage()+';'+e.getLineNumber();
            System.debug('out====>'+searchPro);
            return searchPro;
        }
    }

    @AuraEnabled
    public static Output saveData(
        List<QuoteDetail> quoteDetailList,
        List<String> deleteList
    ) {
        try {
            Output out = new Output();
            out.isSucess = true;
            if (deleteList.size()>0) {
                Database.delete(deleteList);
            }
            System.debug('quoteDetailList:'+quoteDetailList);
            if (quoteDetailList.size()>0) 
            {
                List<Quote_Detail__c> upsertQuoteDetailList = new List<Quote_Detail__c>();
                String orderId;
                for (QuoteDetail  qd: quoteDetailList) 
                {
                	Quote_Detail__c quoteDetail=new Quote_Detail__c();
                	quoteDetail=qd.quoteDetailData;
                    quoteDetail.Id=qd.quoteDetailData.Id;
                    /*if(quoteDetail.Price_List__c != null)
                    {
                        quoteDetail.External_Id__c=quoteDetail.Quote__c+'_'+quoteDetail.Price_List__c;
                    }
                    if(quoteDetail.Quote_Product_Name__c != null)
                    {
                        quoteDetail.External_Id__c=quoteDetail.Quote__c+'_'+quoteDetail.Quote_Product_Name__c;
                    }
                    if(quoteDetail.Contract_Processing_Product__c != null)
                    {
                        quoteDetail.External_Id__c=quoteDetail.Quote__c+'_'+quoteDetail.Contract_Processing_Product__c;
                    }*/
                	upsertQuoteDetailList.add(quoteDetail);
                }
                Database.upsert(upsertQuoteDetailList);
                //Database.upsert(upsertQuoteDetailList,Quote_Detail__c.fields.External_Id__c);
            }
            
            out.errorMsg = '';
            return out;
        } catch (Exception e) {
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = e.getMessage()+';Line:'+e.getLineNumber();
            return out;
        }
        
    
    }

    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public Boolean isHQSubClient {get;set;}

        @AuraEnabled
        public Boolean isRetrograde {get;set;}

        @AuraEnabled
        public Decimal exchangeRate {get;set;}

        @AuraEnabled
        public Decimal paymentTermCostRate {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public List<QuoteDetail> quoteDetailList {get;set;}

        @AuraEnabled
        public List<PriceList> priceListList {get;set;}

        @AuraEnabled
        public List<String> productNameList {get;set;}

        @AuraEnabled
        public Boolean isMXDAPORDDP {get;set;}

    }


     public class QuoteDetail {

        @AuraEnabled
        public Quote_Detail__c quoteDetailData {get;set;}

        @AuraEnabled
        public Boolean isNotEdit {get;set;}

         @AuraEnabled
        public Integer index {get;set;}
    
    }

     public class SearchProduct{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public List<PriceList> priceListList {get;set;}
 
    }
    public class PriceList {

        @AuraEnabled
        public Price_List__c priceListData {get;set;}

        @AuraEnabled
        public Contract_Processing_Product__c productData {get;set;}

        @AuraEnabled
        public Integer index {get;set;}
    
    }
}