force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Billing_Item_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Item_Num__c</fullName>
    <label>SAP Invoice Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Num__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Base_Amount__c</fullName>
    <label>Collection Amount (Local Currency)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Base_Currency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Base_Currency__c</fullName>
    <label>Local Currency of Collection Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Collection Amount (Transaction Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Transaction Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Drawer__c.field-meta.xml
<CustomField>
    <fullName>Drawer__c</fullName>
    <label>Drawer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Item</relationshipLabel>
    <relationshipName>Invoice_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Quantity__c</fullName>
    <label>Invoice Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>Invoice Amount with Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>Invoice Amount without Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Tax__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Reference_Order__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order__c</fullName>
    <label>Reference Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Accounting_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Document_Number__c</fullName>
    <label>Accounting Document Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Collection_Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Base_Amount__c</fullName>
    <label>Collection Amount (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Collection_Transaction_Currency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Currency__c</fullName>
    <label>Transaction Currency of Collection Amoun</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Time__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Time__c</fullName>
    <label>Invoice Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>SAP Total Amount</label>
    <summarizedField>Billing__c.SAP_Total_Amount__c</summarizedField>
    <summaryForeignKey>Billing__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>SAP Total Net</label>
    <summarizedField>Billing__c.SAP_Total_Net__c</summarizedField>
    <summaryForeignKey>Billing__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Transaction_Currency__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Currency__c</fullName>
    <label>Transaction Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code2__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code2__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number 2</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Order Item Collection Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/External_Id2__c.field-meta.xml
<CustomField>
    <fullName>External_Id2__c</fullName>
    <label>External Id2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/FECHA_DE_VENCIMIENTO__c.field-meta.xml
<CustomField>
    <fullName>FECHA_DE_VENCIMIENTO__c</fullName>
    <label>FECHA DE VENCIMIENTO</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>SAP Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>SAP Total Amount(w/ tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Tax__c</fullName>
    <label>SAP Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Billing document blocked for forwarding to FI</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B Journal entry not created (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Journal entry has been created</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D Billing document is not relevant for accounting</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>E Billing document canceled</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>F Journal entry not created (pricing error)</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G Journal entry not created (export data missing)</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>H Posted via invoice list</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>I Posted via invoice list (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>K Journal entry not created (no authorization)</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L Billing doc. blocked for transfer to manager (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M Analyst Approval refused (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>N No Journal entry due to fund management (only IS-PS)</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPBillingWebService.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 04-02-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   04-02-2026   Gerry   Initial Version
**/
@RestResource(urlMapping='/SAPBillingWebService')
global without sharing class SAPBillingWebService {
    global class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqBillingInfo> resultinfo;
    }
    
    global class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
    }
    
    global class ReqBillingInfo{
        public String VBELN;//销售发票号
        public String FKART;//开票类型
        public String RFBSK;//开票状态
        public String BELNR;//会计凭证号
        public String ERDAT;//开票日期
        public String ERZET;//开票时间
        public String ERNAM;//开票人
        public String WAERK;//币种
        public String WRBTR;//回款交易币金额
        public String WAERK1;//回款交易币币种
        public String DMBTR;//回款本位币金额
        public String RFCCUR;//回款本位币币种
        public String SFAKN; //冲销发票号
        public String docnum; //点票号
        public String NETDT;//到期日期
        public List<BillingRow> ITEMS;
    }
    
    
    global class BillingRow{
        public String POSNR;//销售发票行号
        public Decimal FKIMG;//发票数量
        public Decimal AMOUNT;//含税合计
        public Decimal NETWR;//净值合计
        public Decimal MWSBP;//税额合计
        public Decimal AMOUNT_CONV;
        public Decimal NETWR_CONV;
        public Decimal MWSBP_CONV;
        public String AUBEL;//参考订单号
        public String AUPOS;//参考订单行号
        public String VGBEL;//参考交货单
        public String VGPOS;//参考交货单行号
        public String MATNR;//物料编码
        public String ARKTX; //物料描述
        
    }
    
    /**
     * SAP开票信息同步接口
     * @param bodyStrJson bodyStrJson
     *
     * @return ResponseBody
     */
    @HttpPost
    global static SAPOrderWebService.ResponseBody doPost() {
        String respTime = String.valueOf(Datetime.now());
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String bodyStrJson = req.requestBody.toString();
        
        List<String> dataIdList = new List<String>();
        List<SAPOrderWebService.ReturnData> returnDataList = new List<SAPOrderWebService.ReturnData>();
        
        Boolean isSuccess = true;
        Boolean isPartSuccess = true;
        Savepoint sp = Database.setSavepoint();
        
        String errorMsg;
        try {
            System.debug('bodyStrJson1==' + bodyStrJson);
            RequestBody reqBody = (RequestBody) JSON.deserialize(bodyStrJson, RequestBody.class);
            SAPOrderWebService.Output out = feedbackOrderInfo(reqBody.resultinfo);
            isSuccess = out.isSuccess;
            isPartSuccess = out.isPartSuccess;
            errorMsg = out.error;
            returnDataList = out.ReturnDataList;
        } catch (Exception e) {
            Database.rollback(sp);
            errorMsg = InterfaceUtility.getProperErrorMessage(e.getMessage()) + '[' + e.getLineNumber() + ']';
            isSuccess = false;
        }
        SAPOrderWebService.ResponseBody response = SAPOrderWebService.returnData(respTime, isSuccess, errorMsg, returnDataList);
        InterfaceUtility.insertInterfaceLog('SAPBillingWebService', 'SAP', 'CRM',
        '/services/apexrest/receiveDataFromExternal/  requestCode:SAP003', bodyStrJson, isSuccess, isPartSuccess,
        JSON.serialize(response), errorMsg, 'POST', dataIdList, 'Upsert', 'SAP同步发票至CRM'
            );
        
        return response;
    }
    
    public static SAPOrderWebService.Output feedbackOrderInfo(List<ReqBillingInfo> resultinfo) {
        List<Billing__c> billList = new List<Billing__c>();
        List<Invoice__c> invoiceList = new List<Invoice__c>();
        Map<Integer,Billing__c> billListMap = new Map<Integer,Billing__c>();
        Map<Integer,List<Billing__c>> billListMapColl = new Map<Integer,List<Billing__c>>();
        Map<Integer,Billing__c> billListMapFina = new Map<Integer,Billing__c>();
        Map<Integer,Invoice__c> invoiceListMap = new Map<Integer,Invoice__c>();
        Boolean isPartSuccess = false;
        Set<String> orderItemSet = new Set<String>();
        Set<String> deliverySet = new Set<String>();
        Set<String> orderSet = new Set<String>();
        Set<String> billExSet = new Set<String>();
        for(ReqBillingInfo rbi : resultinfo){
            for (BillingRow br : rbi.ITEMS) {
                orderItemSet.add(br.AUBEL+'_'+br.AUPOS);
                deliverySet.add(br.VGBEL+'_'+br.VGPOS);
                orderSet.add(br.AUBEL);
                billExSet.add(rbi.VBELN+br.POSNR);
            }
        }
        //已经被取消的单子
        Map<String,Billing__c> billMap = new Map<String,Billing__c>();
        for (Billing__c bill : [SELECT Id,External_Id__c FROM Billing__c WHERE External_Id__c IN:billExSet AND Billing_Status__c='E']) {
            billMap.put(bill.External_Id__c,bill);
        }
        List<Order_Item__c> oiList = [SELECT Id,External_Id__c,External_Id2__c 
                                        FROM Order_Item__c 
                                        WHERE External_Id__c IN: orderItemSet OR External_Id2__c IN: orderItemSet];
        Map<String,String> oiMap = new Map<String,String>();
        if (oiList.size()>0) {
            for(Order_Item__c o : oiList){
                oiMap.put(o.External_Id__c,o.Id);
                if (o.External_Id2__c!=null) {
                    oiMap.put(o.External_Id2__c,o.Id);
                }
            }
        }
        
        Map<String,Order__c> orMap = new Map<String,Order__c>();
        for (Order__c order : [SELECT Owner.IsActive,OwnerId,Id,SAP_Order_Code__c,SAP_Order_Code2__c,Sales_Org__c FROM Order__c WHERE SAP_Order_Code__c IN:orderSet OR SAP_Order_Code2__c IN:orderSet]) {
            orMap.put(order.SAP_Order_Code__c, order);
            if (order.SAP_Order_Code2__c!=null) {
                orMap.put(order.SAP_Order_Code2__c, order);
            }
        }
        
        List<Delivery_Note__c> dnList = [SELECT Id,External_Id__c 
                                        FROM Delivery_Note__c 
                                        WHERE External_Id__c IN: deliverySet];
        Map<String,String> dnMap = new Map<String,String>();
        if (oiList.size()>0) {
            for(Delivery_Note__c dn : dnList){
                dnMap.put(dn.External_Id__c,dn.Id);
            }
        }
        
        Set<String> cancelBillSet = new Set<String>();
        
        for(ReqBillingInfo rbi : resultinfo){
            cancelBillSet.add(rbi.SFAKN);
        }
        
        SAPOrderWebService.Output out = new SAPOrderWebService.Output();
        out.ReturnDataList = new List<SAPOrderWebService.ReturnData>();
        SAPOrderWebService.ReturnData returnDataMsgTmp;
        
        Map<String,String> cancelBillMap = new Map<String,String>();
        List<Billing__c> reverseBillList = [SELECT Id,Billing_Num__c FROM Billing__c WHERE Billing_Num__c IN: cancelBillSet];
        for(Billing__c bi : reverseBillList){
            cancelBillMap.put(bi.Billing_Num__c,bi.Id);
        }
        Integer billIndex = 0;
        Integer invoiceIndex = 0;
        for(ReqBillingInfo rbi : resultinfo){
            List<Billing__c> billListTmp = new List<Billing__c>();
            Boolean flag = false;
            String AUBEL;
            for (BillingRow br : rbi.ITEMS) {
                AUBEL = br.AUBEL;
                Billing__c bill = new Billing__c();
                //头部分
                bill.Billing_Num__c = rbi.VBELN;
                bill.Billing_Type__c = rbi.FKART;
                if (billMap.get(rbi.VBELN+br.POSNR)!=null) {//如果是已经取消的发票则
                    bill.Billing_Status__c = 'E';
                    flag = true;
                }else{
                    bill.Billing_Status__c = rbi.RFBSK;
                }
                //到期日期
                bill.FECHA_DE_VENCIMIENTO__c = Date.valueOf(rbi.NETDT);
                
                bill.Accounting_Document_Number__c = rbi.BELNR;
                bill.Invoice_Date__c = Date.valueOf(rbi.ERDAT);
                bill.Invoice_Time__c = rbi.ERZET;
                bill.Drawer__c = rbi.ERNAM;
                bill.Currency__c = rbi.WAERK;
                if (String.isNotBlank(rbi.WRBTR)) {
                    bill.Collection_Transaction_Amount__c = Decimal.valueOf(rbi.WRBTR);
                }else{
                    bill.Collection_Transaction_Amount__c = null;
                }
                
                bill.Collection_Transaction_Currency__c  = rbi.WAERK1;
                bill.Collection_Base_Amount__c = rbi.DMBTR;
                bill.Collection_Base_Currency__c = rbi.RFCCUR;
                //ITEMS部分
                bill.Billing_Item_Num__c = br.POSNR;
                bill.Invoice_Quantity__c = br.FKIMG;
                bill.SAP_Total_Amount__c = br.AMOUNT;
                bill.SAP_Total_Tax__c = br.MWSBP;
                bill.SAP_Total_Net__c = br.NETWR;
                bill.Reference_Order__c = br.AUBEL;
                bill.Reference_Order_Item__c = br.AUPOS;
                bill.Reference_Delivery_Num__c = br.VGBEL;
                bill.Reference_Delivery_Item_Num__c = br.VGPOS;
                bill.Delivery_Note__c = dnMap.get(br.VGBEL+'_'+br.VGPOS);
                bill.Order_Item__c = oiMap.get(br.AUBEL+'_'+br.AUPOS);
                if (orMap.containsKey(br.AUBEL)) {
                    bill.Order__c = orMap.get(br.AUBEL).Id;
                }else{
                    returnDataMsgTmp = new SAPOrderWebService.ReturnData();
                    returnDataMsgTmp.vbeln = rbi.VBELN;
                    returnDataMsgTmp.posnr = br.POSNR;
                    returnDataMsgTmp.msgty = 'E';
                    returnDataMsgTmp.msgtx = br.AUBEL+'不存在！';
                    out.ReturnDataList.add(returnDataMsgTmp);
                    isPartSuccess = true;
                    continue;
                }
                
                bill.External_Id__c = rbi.VBELN+br.POSNR;
                bill.Material_Code__c = br.MATNR;//物料编码
                bill.Description__c = br.ARKTX; //物料描述
                // bill.OwnerId = orMap.get(br.AUBEL).OwnerId;
                bill.SAP_Total_Amount_USD__c = br.AMOUNT_CONV;
                bill.SAP_Total_Net_UDS__c = br.NETWR_CONV;
                bill.SAP_Total_Tax_USD__c = br.MWSBP_CONV;
                if (String.isNotBlank(rbi.SFAKN)) {
                    // Billing__c billRela = new Billing__c();
                    // billRela.External_Id__c = rbi.SFAKN+br.POSNR;
                    bill.Reverse_Billing__c = cancelBillMap.get(rbi.SFAKN);
                    bill.Reverse_Invoice_Number__c = rbi.SFAKN;
                    bill.Billing_Status__c = 'E';
                    flag = true;
                }
                Invoice__c inv = new Invoice__c();
                inv.External_Id__c = rbi.VBELN;
                bill.Invoice__r = inv;
                billList.add(bill);
                billListTmp.add(bill);
                billListMap.put(billIndex,bill);
                billIndex++;
            }
            if (!orMap.containsKey(AUBEL)) {
                continue;
            }
            Invoice__c inv = new Invoice__c();
            inv.Order__c = orMap.get(AUBEL).Id;
            inv.Sales_Org__c = orMap.get(AUBEL).Sales_Org__c;	//2024/11.05 增加sales org赋值
            if(orMap.get(AUBEL).Owner.IsActive) {
                inv.OwnerId = orMap.get(AUBEL).OwnerId;
            }
            
            inv.External_Id__c = rbi.VBELN;
            inv.Name = rbi.VBELN;
            inv.Ticket_Number__c =  rbi.docnum;
            inv.Invoice_Type__c = rbi.FKART;
            inv.Invoice_Status__c = rbi.RFBSK;
            if (flag) {
                inv.Invoice_Status__c = 'E';
            }
            inv.Accounting_Document_Number__c = rbi.BELNR;
            inv.Invoice_Date__c = Date.valueOf(rbi.ERDAT);
            inv.Invoice_Time__c = rbi.ERZET;
            inv.Drawer__c = rbi.ERNAM;
            inv.Transaction_Currency__c = rbi.WAERK;
            if (String.isNotBlank(rbi.WRBTR)) {
                inv.Collection_Transaction_Amount__c = Decimal.valueOf(rbi.WRBTR);
            }else{
                inv.Collection_Transaction_Amount__c = null;
            }
            
            inv.Collection_Transaction_Currency__c  = rbi.WAERK1;
            if (String.isNotBlank(rbi.DMBTR)) {
                inv.Collection_Base_Amount__c = Decimal.valueOf(rbi.DMBTR);
            }
            
            inv.Collection_Base_Currency__c = rbi.RFCCUR;
            invoiceList.add(inv);
            invoiceListMap.put(invoiceIndex,inv);
            billListMapColl.put(invoiceIndex,billListTmp);
            invoiceIndex++;
        }
        
        
        // if (invoiceList.size() >0) {
            //     Database.upsert(invoiceList,Invoice__c.fields.External_Id__c, true);
        // }
        String errorStr = '';
        String code = '';
        Integer index = 0;
        Integer resultIndex = 0;
        SAPOrderWebService.ReturnData returnDataMsg;
        if (invoiceListMap.size() > 0) {
            resultIndex = 0;
            List<Database.UpsertResult> resultListHead = Database.upsert(invoiceListMap.values(),Invoice__c.fields.External_Id__c, false);
            for(Integer i=0;i<resultListHead.size();i++) {
                Database.UpsertResult resultHead = resultListHead[resultIndex];
                if(!resultHead.isSuccess()) {
                    errorStr = '';
                    for(Database.Error errorStrItem : resultHead.getErrors()) {
                        errorStr = errorStr + errorStrItem.getMessage();
                    }
                    for (Billing__c billTmp : billListMapColl.get(resultIndex)) {
                        returnDataMsg = new SAPOrderWebService.ReturnData();
                        returnDataMsg.vbeln = billTmp.Billing_Num__c;
                        returnDataMsg.posnr = billTmp.Billing_Item_Num__c;
                        returnDataMsg.msgty = 'E';
                        returnDataMsg.msgtx = errorStr;
                        out.ReturnDataList.add(returnDataMsg);
                    }
                    billListMapColl.remove(resultIndex);
                    isPartSuccess = true;
                }
                resultIndex++;
            }
        }
        
        // if (billList.size() > 0) {
            //     Database.upsert(billList,Billing__c.fields.External_Id__c, true);
        // }
        Integer billTmpFinaIndex = 0;
        if (billListMapColl.size() > 0) {
            for(Integer key : billListMapColl.keySet()) {
                List<Billing__c> billingTmp = billListMapColl.get(key);
                for (Billing__c billTmp : billingTmp) {
                    billListMapFina.put(billTmpFinaIndex,billTmp);
                    billTmpFinaIndex++;
                }
            }
            // for (List<Billing__c> billingTmp : billListMapColl) {
                //     for (Billing__c billTmp : billingTmp) {
                    //         billListMapFina.put(billTmpFinaIndex,billTmp);
                    //         billTmpFinaIndex++;
                //     }
            // }
        }
        Integer resultDetailIndex = 0;
        if (billListMapFina.size() > 0) {
            List<Database.UpsertResult> resultListItem = Database.upsert(billListMapFina.values(),Billing__c.fields.External_Id__c, false);
            resultDetailIndex = 0;
            for(Integer i=0;i<resultListItem.size();i++) {
                Database.UpsertResult resultItem = resultListItem[resultDetailIndex];
                errorStr = '';
                code = '';
                index = 0;
                if(!resultItem.isSuccess()) {
                    for(Database.Error errorStrItem : resultItem.getErrors()) {
                        errorStr = errorStr + errorStrItem.getMessage();
                    }
                    // code = billListMapFina.get(resultDetailIndex).External_Id__c;
                    // index = code.indexOf('_');
                    returnDataMsg = new SAPOrderWebService.ReturnData();
                    returnDataMsg.vbeln = billListMapFina.get(resultDetailIndex).Billing_Num__c;
                    returnDataMsg.posnr = billListMapFina.get(resultDetailIndex).Billing_Item_Num__c;
                    returnDataMsg.msgty = 'E';
                    returnDataMsg.msgtx = errorStr;
                    out.ReturnDataList.add(returnDataMsg);
                    isPartSuccess = true;
                } else {
                    // code = billListMapFina.get(resultDetailIndex).External_Id__c;
                    // index = code.indexOf('_');
                    returnDataMsg = new SAPOrderWebService.ReturnData();
                    returnDataMsg.vbeln = billListMapFina.get(resultDetailIndex).Billing_Num__c;
                    returnDataMsg.posnr = billListMapFina.get(resultDetailIndex).Billing_Item_Num__c;
                    returnDataMsg.msgty = 'S';
                    returnDataMsg.msgtx = 'The data is successfully written!';
                    out.ReturnDataList.add(returnDataMsg);
                }
                resultDetailIndex++;
            }
        }
        out.isSuccess = true;
        out.isPartSuccess = isPartSuccess;
        
        if (cancelBillSet.size()>0) {
            List<Billing__c> cancelBillList = [SELECT Id,Billing_Num__c,Invoice__c FROM Billing__c WHERE Billing_Num__c IN: cancelBillSet];
            List<Billing__c> upCancelBillList = new List<Billing__c>();
            Map<String,Invoice__c> inMap = new Map<String,Invoice__c>();
            Map<String,String> relationMap = new Map<String,String>();
            for(Billing__c bi : cancelBillList){
                relationMap.put(bi.Billing_Num__c,bi.Id);
                Billing__c upBill = new Billing__c();
                upBill.Id = bi.Id;
                upBill.Billing_Status__c = 'E';
                upCancelBillList.add(upBill);
                if (!inMap.containsKey(bi.Invoice__c)) {
                    Invoice__c inv = new Invoice__c();
                    inv.Id = bi.Invoice__c;
                    inv.Invoice_Status__c = 'E';
                    inMap.put(bi.Invoice__c,inv);
                }
            }
            if (inMap.size()>0) {
                update inMap.values();
            }
            if (upCancelBillList.size()>0) {
                update upCancelBillList;
            }
            List<Billing__c> billNeedUpdate = new List<Billing__c>();
            for(Billing__c bill : billList) {
                if(bill.Reverse_Invoice_Number__c!=null && bill.Reverse_Billing__c==null) {
                    bill.Reverse_Billing__c = relationMap.get(bill.Reverse_Invoice_Number__c);
                    billNeedUpdate.add(bill);
                }
            }
            if(billNeedUpdate.size()>0) {
                update billNeedUpdate;
            }
        }
        
        return out;
        
    }
}