force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Billing_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Num__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Collection Amount (Transaction Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Item</relationshipLabel>
    <relationshipName>Invoice_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>Invoice Amount with Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>Invoice Amount without Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Net_UDS__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net_UDS__c</fullName>
    <label>SAP Total Net (convert)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>SAP Total Amount</label>
    <summarizedField>Billing__c.SAP_Total_Amount__c</summarizedField>
    <summaryForeignKey>Billing__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>SAP Total Net</label>
    <summarizedField>Billing__c.SAP_Total_Net__c</summarizedField>
    <summaryForeignKey>Billing__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Order Item Collection Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>SAP Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>SAP Total Amount(w/ tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Billing document blocked for forwarding to FI</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B Journal entry not created (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Journal entry has been created</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D Billing document is not relevant for accounting</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>E Billing document canceled</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>F Journal entry not created (pricing error)</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G Journal entry not created (export data missing)</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>H Posted via invoice list</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>I Posted via invoice list (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>K Journal entry not created (no authorization)</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L Billing doc. blocked for transfer to manager (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M Analyst Approval refused (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>N No Journal entry due to fund management (only IS-PS)</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceItemTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 05-28-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-28-2025   Gerry   Initial Version
**/
@isTest
private class InvoiceItemTriggerHandlerTest {


    @IsTest
    static void testHandle() {
        Invoice__c inv = new Invoice__c();
        inv.External_Id__c = '1';
        Insert inv;
        Billing__c bill = new Billing__c();
        // bill.Order_Item__c = orI1.Id;
        bill.Billing_Status__c = 'C';
        bill.Billing_Num__c = '1234';
        // bill.Order__c = order1.Id;
        bill.Invoice_Date__c = Date.valueOf('2024-01-02');
        bill.SAP_Total_Net__c = 10;
        bill.SAP_Total_Net_UDS__c = 10;
        bill.SAP_Total_Amount__c = 0;
        bill.Collection_Transaction_Amount__c = 0;
        // bill.OwnerId = u.Id;
        bill.Invoice__c = inv.Id;
        Insert bill;
    }
}