force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Billing_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Num__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Collection Amount (Transaction Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Quantity__c</fullName>
    <label>Invoice Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Delivery Quantity(Order Unit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Bill_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Bill_Quantity__c</fullName>
    <label>Order Item Invoiced Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Order Item Collection Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Order Item Delivered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Billing document blocked for forwarding to FI</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B Journal entry not created (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Journal entry has been created</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D Billing document is not relevant for accounting</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>E Billing document canceled</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>F Journal entry not created (pricing error)</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G Journal entry not created (export data missing)</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>H Posted via invoice list</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>I Posted via invoice list (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>K Journal entry not created (no authorization)</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L Billing doc. blocked for transfer to manager (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M Analyst Approval refused (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>N No Journal entry due to fund management (only IS-PS)</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesOrderDataBatch.cls
/**************************************************************************************************
 * Name: SubmitOrderController
 * Object: 
 * Purpose: 销售数据batch
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-20         Created             
***************************************************************************************************/
global without sharing class SalesOrderDataBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    public String query;
    public String filedStr;
    public String type;
    public Date closeDate;
    global Boolean flag;
    global String errorMsg;
    global Datetime startTime;
    global SalesOrderDataBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT Id,Delivery_Quantity__c,Collection_Transaction_Amount__c FROM Order_Item__c WHERE Order__r.Status__c=\'Approved\'';
    }

    global void execute(SchedulableContext sc) {
        SalesOrderDataBatch svo = new SalesOrderDataBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order_Item__c> orderList) {
        try {
            Set<String> orderIdSet = new Set<String>();
            for (Order_Item__c ord : orderList) {
                orderIdSet.add(ord.Id);
            }
            Map<Id,Order_Item__c> updateOrderItemMap = new Map<Id,Order_Item__c>();
            Map<Id,Order_Item__c> updateOrderItemInvoiceMap = new Map<Id,Order_Item__c>();
            for (AggregateResult agg : [SELECT Order_Item__c oi,SUM(Delivery_Quantity__c) dq FROM Delivery_Note__c WHERE Order_Item__c IN:orderIdSet AND (Delivery_Post_Status__c='C' OR Delivery_Post_Status__c='B') group by Order_Item__c ]){
                Order_Item__c oi = new Order_Item__c();
                oi.Id = (String)agg.get('oi');
                oi.Delivery_Quantity__c = (Decimal)agg.get('dq');
                
                updateOrderItemMap.put(oi.Id, oi);
            }
            for (AggregateResult agg : [SELECT Order_Item__c oi,SUM(Invoice_Quantity__c) quNum FROM Billing__c WHERE Order_Item__c IN:orderIdSet AND Billing_Status__c='C' group by Order_Item__c ]){
                // if (updateOrderItemMap.get((String)agg.get('oi'))!=null) {
                //     updateOrderItemMap.get((String)agg.get('oi')).Bill_Quantity__c = (Decimal)agg.get('quNum');
                // }else{
                    Order_Item__c oi = new Order_Item__c();
                    oi.Id = (String)agg.get('oi');
                    // oi.Collection_Transaction_Amount__c = (Decimal)agg.get('sta');
                    oi.Bill_Quantity__c = (Decimal)agg.get('quNum');
                    updateOrderItemInvoiceMap.put(oi.Id, oi);
                // }
                
            }

            Map<Id,Order_Item__c> updateOrderItemTransactionMap = new Map<Id,Order_Item__c>();
            Set<String> billIdSet = new Set<String>();
            for (Billing__c bi : [SELECT Id,Collection_Transaction_Amount__c,Billing_Num__c,Order__c,Order_Item__c FROM Billing__c WHERE Order_Item__c IN:orderIdSet AND Billing_Status__c='C']) {
                if (billIdSet.contains(bi.Billing_Num__c)) {
                    continue;
                }
                if (!updateOrderItemTransactionMap.containskey(bi.Order_Item__c)) {
                    Order_Item__c oi = new Order_Item__c();
                    oi.Id = bi.Order_Item__c;
                    oi.Collection_Transaction_Amount__c = bi.Collection_Transaction_Amount__c;
                    updateOrderItemTransactionMap.put(oi.Id, oi);
                }else{
                    if (updateOrderItemTransactionMap.get(bi.Order_Item__c).Collection_Transaction_Amount__c==null) {
                        updateOrderItemTransactionMap.get(bi.Order_Item__c).Collection_Transaction_Amount__c = 0;
                    }
                    updateOrderItemTransactionMap.get(bi.Order_Item__c).Collection_Transaction_Amount__c += bi.Collection_Transaction_Amount__c==null?0:bi.Collection_Transaction_Amount__c;
                }
                billIdSet.add(bi.Billing_Num__c);
            }
            for(Order_Item__c ord : orderList) {
                if(updateOrderItemMap.get(ord.Id)!=null) {
                    ord.Delivery_Quantity__c = updateOrderItemMap.get(ord.Id).Delivery_Quantity__c;
                }else{
                    ord.Delivery_Quantity__c = 0;
                }
                if(updateOrderItemInvoiceMap.get(ord.Id)!=null) {
                    ord.Bill_Quantity__c = updateOrderItemInvoiceMap.get(ord.Id).Bill_Quantity__c;
                }else{
                    ord.Bill_Quantity__c = 0;
                }
                if(updateOrderItemTransactionMap.get(ord.Id)!=null) {
                    ord.Collection_Transaction_Amount__c = updateOrderItemTransactionMap.get(ord.Id).Collection_Transaction_Amount__c;
                }else{
                    ord.Collection_Transaction_Amount__c = 0;
                }
               
            }
            Utility.IgnoreAction(true,false,'SalesOrderDataBatch'); 
            Update orderList;
            Utility.IgnoreAction(false,false,'SalesOrderDataBatch'); 
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        SalesOrderInvoiceBatch soib = new SalesOrderInvoiceBatch();
        Database.executeBatch(soib,100);
        Utility.setBatchInfo('SalesOrderDataBatch', this.flag, this.startTime, this.errorMsg);
    }
}