force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Invoice_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date_Month__c</fullName>
    <formula>TEXT(MONTH(Invoice_Date__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Month_Data__c.field-meta.xml
<CustomField>
    <fullName>Month_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Data</label>
    <referenceTo>Month_Data__c</referenceTo>
    <relationshipLabel>Invoice Item</relationshipLabel>
    <relationshipName>Invoice_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Month_Data__c/Month_Data__c.object-meta.xml
<CustomObject>
    <label>Month Data</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceItemTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 05-26-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-26-2025   Gerry   Initial Version
**/
public without sharing class InvoiceItemTriggerHandler implements Triggers.Handler {
    public void handle() {
        //赋值月份主数据
        if(Trigger.isbefore && (Trigger.isupdate || Trigger.isInsert)) {
            Map<String,String> monthIdMap = new Map<String,String>();
            for (Month_Data__c md : [SELECT Id,Name FROM Month_Data__c]) {
                monthIdMap.put(md.Name, md.ID);
            }
            for (Billing__c bi : (List<Billing__c>)Trigger.new) {
                bi.Month_Data__c = monthIdMap.get(bi.Invoice_Date_Month__c);
            }
        }
    }
}