force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Billing_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Num__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Collection_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collection_Transaction_Amount__c</fullName>
    <label>Collection Amount (Transaction Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Amount__c</fullName>
    <label>Invoice Amount with Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/SAP_Total_Net__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Net__c</fullName>
    <label>Invoice Amount without Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Amount_of_refund__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_refund__c</fullName>
    <label>Collection Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <label>Invoice Amount with Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice_Amount_Net__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount_Net__c</fullName>
    <label>Invoice Amount without Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Billing document blocked for forwarding to FI</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B Journal entry not created (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Journal entry has been created</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D Billing document is not relevant for accounting</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>E Billing document canceled</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>F Journal entry not created (pricing error)</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G Journal entry not created (export data missing)</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>H Posted via invoice list</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>I Posted via invoice list (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>K Journal entry not created (no authorization)</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L Billing doc. blocked for transfer to manager (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M Analyst Approval refused (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>N No Journal entry due to fund management (only IS-PS)</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesOrderInvoiceBatch.cls
/**************************************************************************************************
 * Name: SalesOrderInvoiceBatch
 * Object: 
 * Purpose: 销售发票数据
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-20         Created             
***************************  ************************************************************************/
global without sharing class SalesOrderInvoiceBatch implements Database.Batchable<sObject>,Database.Stateful {
    public String query;
    public String filedStr;
    public String type;
    public Date closeDate;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;
    global SalesOrderInvoiceBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT Id,Amount_of_refund__c,Invoice_Amount__c,Invoice_Amount_Net__c FROM Order__c WHERE Status__c=\'Approved\'';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order__c> orderList) {
        try {
            Set<String> orderIdSet = new Set<String>();
            for (Order__c ord : orderList) {
                orderIdSet.add(ord.Id);
            }
            Map<String,Order__c> orMap = new Map<String,Order__c>();
            for (AggregateResult agg : [SELECT Order__c oi,SUM(SAP_Total_Amount__c) sta,SUM(SAP_Total_Net__c) staNet FROM Billing__c WHERE Order__c IN:orderIdSet AND Billing_Status__c='C' group by Order__c]){
                Order__c orData = new Order__c();
                orData.Id = (String)agg.get('oi');
                orData.Invoice_Amount__c = (Decimal)agg.get('sta');
                orData.Invoice_Amount_Net__c = (Decimal)agg.get('staNet');
                orData.Amount_of_refund__c = 0;
                orMap.put(orData.Id, orData);
            }

            Map<String,Order__c> orAmountMap = new Map<String,Order__c>();
            Set<String> billIdSet = new Set<String>();
            for (Billing__c bi : [SELECT Id,Collection_Transaction_Amount__c,Billing_Num__c,Order__c FROM Billing__c WHERE Order__c IN:orderIdSet AND Billing_Status__c='C']) {
                if (billIdSet.contains(bi.Billing_Num__c)) {
                    continue;
                }
                if (bi.Collection_Transaction_Amount__c!=null) {
                    if(orAmountMap.containsKey(bi.order__c)) {
                        orAmountMap.get(bi.order__c).Amount_of_refund__c += bi.Collection_Transaction_Amount__c;
                    }else{
                        Order__c orData = new Order__c();
                        orData.Amount_of_refund__c = bi.Collection_Transaction_Amount__c;
                        orAmountMap.put(bi.order__c,orData);
                    }
                    
                    billIdSet.add(bi.Billing_Num__c);
                    // orAmountMap.put(bi.order__c,orData);
                }
            }
            for (Order__c orData : orderList) {
                if(orMap.get(orData.Id)!=null) {
                    orData.Invoice_Amount__c = orMap.get(orData.Id).Invoice_Amount__c;
                    orData.Invoice_Amount_Net__c = orMap.get(orData.Id).Invoice_Amount_Net__c;
                }else{
                    orData.Invoice_Amount__c = 0;
                    orData.Invoice_Amount_Net__c = 0;
                }
                if(orAmountMap.get(orData.Id)!=null) {
                    orData.Amount_of_refund__c = orAmountMap.get(orData.Id).Amount_of_refund__c;
                }else{
                    orData.Amount_of_refund__c = 0;
                }
                
            }
            Utility.IgnoreAction(true,false,'SalesOrderInvoiceBatch'); 
            Database.update(orderList);   
            Utility.IgnoreAction(false,false,'SalesOrderInvoiceBatch'); 
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('SalesOrderInvoiceBatch', this.flag, this.startTime, this.errorMsg);
        SalesFillUpOrderBatch svo = new SalesFillUpOrderBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
    }
}