force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book__c/fields/No_Price_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>No_Price_Item_Count__c</fullName>
    <label>No Price Item Count</label>
    <summaryFilterItems>
        <field>Price_Book_Item__c.Price__c</field>
        <operation>equals</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Price_Book_Item__c.Price_Book__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>PBI-{000000}</displayFormat>
        <label>Price Book Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Item__c/fields/Is_Changing__c.field-meta.xml
<CustomField>
    <fullName>Is_Changing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Changing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Item</relationshipLabel>
    <relationshipName>Price_Book_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PriceBookChangeTriggerHandler.cls
/**
 * @description       : 价格手册trigger
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 06-10-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-09-2025   Gerry   Initial Version
**/
public without sharing class PriceBookChangeTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isAfter && (Trigger.isUpdate)) {
            List<Price_Book_Item__c> pbiList = new List<Price_Book_Item__c>();
            Map<Id,Price_Book__c> oldMap = (Map<Id,Price_Book__c>)Trigger.oldMap;
            Set<String> pbIdSet = new Set<String>();
            for (Price_Book__c pbd : (List<Price_Book__c>)Trigger.New) {
                if(pbd.Status__c == 'Approved' && oldMap.get(pbd.Id).Status__c != pbd.Status__c) {
                    pbIdSet.add(pbd.Id);
                }
            }

            for(Price_Book_Item__c pbi : [SELECT Id,Is_Changing__c FROM Price_Book_Item__c WHERE Price_Book__c IN:pbIdSet AND Is_Changing__c=true]) {
                pbi.Is_Changing__c = false;
                pbiList.add(pbi);
            }
            if(pbiList.size()>0) {
                Database.Update(pbiList);
            }
        }

        if (Trigger.isBefore && (Trigger.isUpdate)) {
            List<Price_Book_Item__c> pbiList = new List<Price_Book_Item__c>();
            Map<Id,Price_Book__c> oldMap = (Map<Id,Price_Book__c>)Trigger.oldMap;
            Set<String> pbIdSet = new Set<String>();
            for (Price_Book__c pbd : (List<Price_Book__c>)Trigger.New) {
                if(pbd.Status__c == 'Approving' && oldMap.get(pbd.Id).Status__c != pbd.Status__c && pbd.No_Price_Item_Count__c != 0) {
                    //Some price book item does not have price,can't submit
                    pbd.addError(System.Label.PriceBookNoPrice);
                }
            }
        }

    }
}