force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>PBI-{000000}</displayFormat>
        <label>Price Book Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Item__c/fields/Is_Changing__c.field-meta.xml
<CustomField>
    <fullName>Is_Changing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Changing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Item</relationshipLabel>
    <relationshipName>Price_Book_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PriceBookTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 11-14-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-10-2025   Gerry   Initial Version
**/
public class PriceBookTriggerHandler implements Triggers.Handler{
	public void handle() {
        if(Trigger.isBefore && (Trigger.isUpdate || Trigger.isInsert)) {
            Map<Id,Price_Book_Item__c> oldMap = (Map<Id,Price_Book_Item__c>)Trigger.oldMap;
            for(Price_Book_Item__c pbd : (List<Price_Book_Item__c>)Trigger.New) {
                if(Trigger.isUpdate) {
                    if(oldMap.get(pbd.Id).Is_Changing__c != pbd.Is_Changing__c || oldMap.get(pbd.Id).Status__c != pbd.Status__c) {
                        continue;
                    }
                }
                
                pbd.Is_Changing__c = true;
                if(System.Test.isRunningTest()){
                    pbd.Is_Changing__c = false;
                }
            }
        }
        if (Trigger.isAfter && (Trigger.isUpdate || Trigger.isInsert)) {
            Map<String,Price_Book__c> pbMap = new Map<String,Price_Book__c>();
            Map<Id,Price_Book_Item__c> oldMap = (Map<Id,Price_Book_Item__c>)Trigger.oldMap;
            for (Price_Book_Item__c pbd : (List<Price_Book_Item__c>)Trigger.New) {
                if(Trigger.isInsert) {
                    Price_Book__c updatePbd = new Price_Book__c();
                    updatePbd.Id = pbd.Price_Book__c;
                    updatePbd.Status__c = 'Draft';
                    pbMap.put(pbd.Price_Book__c,updatePbd);
                }
                
                if(Trigger.isUpdate && pbd.Is_Changing__c) {
                    Price_Book__c updatePbd = new Price_Book__c();
                    updatePbd.Id = pbd.Price_Book__c;
                    updatePbd.Status__c = 'Draft';
                    pbMap.put(pbd.Price_Book__c,updatePbd);
                }
            }
            if(pbMap.size()>0) {
                Database.Update(pbMap.values());
            }
        }
    }
}