force-app/main/default/objects/Account/fields/Accounts_Email__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Email__c</fullName>
    <label>Accounts Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACN_No__c.field-meta.xml
<CustomField>
    <fullName>ACN_No__c</fullName>
    <formula>RIGHT(Tax_Number__c, LEN(Tax_Number__c) - 2)</formula>
    <label>ACN No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Country)</relationshipLabel>
    <relationshipName>Accounts_Country</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Importer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Date_Business_Started__c.field-meta.xml
<CustomField>
    <fullName>Date_Business_Started__c</fullName>
    <label>Date Business Started</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <label>House Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operating_Address__c.field-meta.xml
<CustomField>
    <fullName>Operating_Address__c</fullName>
    <label>Operating Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province_State__c.field-meta.xml
<CustomField>
    <fullName>Province_State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province/State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Province/State)</relationshipLabel>
    <relationshipName>Accounts_Province</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Legal Person Telephone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Province_Master_Data__c/Country_Province_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Country/Province Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Province_Master_Data__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Country/Province Master Data</relationshipLabel>
    <relationshipName>Country_Province_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Province_Master_Data__c/recordTypes/Country.recordType-meta.xml
<RecordType>
    <fullName>Country</fullName>
    <active>true</active>
    <label>Country</label>
</RecordType>

force-app/main/default/objects/Country_Province_Master_Data__c/recordTypes/Province.recordType-meta.xml
<RecordType>
    <fullName>Province</fullName>
    <active>true</active>
    <label>Province</label>
</RecordType>

force-app/main/default/objects/Trading_Reference__c/Trading_Reference__c.object-meta.xml
<CustomObject>
    <label>Trading Reference</label>
    <nameField>
        <label>Trading Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trading Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trading_Reference__c/fields/Accounts_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Email_Address__c</fullName>
    <label>Accounts Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trading_Reference__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trading Reference</relationshipLabel>
    <relationshipName>Trading_Reference</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trading_Reference__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createCustomerPDF.cls
/**
 * @description       : 
 * @author            : Niko
 * @group             : 
 * @last modified on  : 03-02-2026
 * @last modified by  : Niko
**/
public with sharing class createCustomerPDF {
    // Supplier Information
    public String supplierAddress { get; set; }
    public String supplierPostalAddress { get; set; }
    public String supplierPhone { get; set; }
    public String supplierEmail { get; set; }
    public String facsimile { get; set; }
    public String website { get; set; }

    // Applicant Info
    public Account customer;
    public String companyName { get; set; }
    public String tradeName { get; set; }
    public String abn { get; set; }
    public String acn { get; set; }
    public String phoneNum { get; set; }
    public String orderEmail { get; set; }
    public String postalAddr { get; set; }
    public String oprAddr { get; set; }
    public String customerType { get; set; }
    public String startDate { get; set; }

    // Financial Information
    public Decimal creditRequired { get; set; }
    
    // Representatives
    public List<Contact> representatives { get; set; }
    public String req1Name { get; set; }
    public String req2Name { get; set; }
    public String req3Name { get; set; }
    public String req1Address { get; set; }
    public String req2Address { get; set; }
    public String req3Address { get; set; }
    public String req1Position { get; set; }
    public String req2Position { get; set; }
    public String req3Position { get; set; }
    public String req1Email { get; set; }
    public String req2Email { get; set; }
    public String req3Email { get; set; }
    public String req1Phone { get; set; }
    public String req2Phone { get; set; }
    public String req3Phone { get; set; }

    // bank info
    public String branch { get; set; }
    public String bsb { get; set; }

    //trading reference
    public List<Trading_Reference__c> tradingRef { get; set; }
 
    // Constructor
    public createCustomerPDF() {
        initializeSupplierInfo();
        setApplicantInfo();
        setRepresentative();
        setBankInfo();
        setTradeRef();
    }

    private void initializeSupplierInfo() {
        // Set default supplier information
        supplierAddress = '5.08 12 Century Circuit, Norwest NSW 2153';
        supplierPostalAddress = 'PO Box 6506, Norwest NSW 2153';
        supplierPhone = '+61 2 8123 0170';
        supplierEmail = 'admin@rainbowagro.com.au';
        facsimile = '+61 2 8123 0171';
        website = 'www.rainbowagro.com/au/';
    }

    public void setApplicantInfo() {
        customer = [
            SELECT
                Name, Tax_Number__c,ACN_No__c,Phone,Accounts_Email__c,House_Number__c,
                Street__c,District__c,City__c,Province_State__c,Country__c,Postal_Code__c,
                Operating_Address__c,Customer_Type__c,Date_Business_Started__c
            FROM
                Account
            WHERE
                Id = :ApexPages.currentPage().getParameters().get('id')
        ];
        companyName = customer.Name == null ? '' : customer.Name;
        abn = customer.Tax_Number__c == null ? '' : customer.Tax_Number__c;
        acn = customer.ACN_No__c == null ? '' : customer.ACN_No__c;
        phoneNum = customer.Phone == null ? '' : customer.Phone;
        orderEmail = customer.Accounts_Email__c == null ? '' : customer.Accounts_Email__c;
        postalAddr = combinePostalAddress();
        oprAddr = customer.Operating_Address__c == null ? '' : customer.Operating_Address__c;
        customerType = customer.Customer_Type__c == null ? '' : customer.Customer_Type__c;
        startDate = customer.Date_Business_Started__c == null ? '' : customer.Date_Business_Started__c.format();
    }

    public String combinePostalAddress() {
        String province = '';
        String country = '';
        if (customer.Province_State__c != null && customer.Country__c != null) {
            Country_Province_Master_Data__c p = [ SELECT Name FROM Country_Province_Master_Data__c WHERE Id = :customer.Province_State__c LIMIT 1];
            Country_Province_Master_Data__c c = [ SELECT Name FROM Country_Province_Master_Data__c WHERE Id = :customer.Country__c LIMIT 1];
            province = p.Name;
            country = c.Name;
        }
        if (customer.House_Number__c != null && customer.Street__c != null && customer.District__c != null && customer.City__c != null && customer.Postal_Code__c != null) {
            return customer.House_Number__c + ' ' + customer.Street__c + ', ' + customer.District__c + ', ' + customer.City__c + ', ' + province + ' ' + country + ', ' + customer.Postal_Code__c;
        }
        return '';
    }

    public void setRepresentative() {
        representatives = [
            SELECT
                Name,Address__c,Position__c,Email,Phone
            FROM
                Contact
            WHERE
                AccountId = :ApexPages.currentPage().getParameters().get('id') LIMIT 3
        ];
        if (representatives.size() > 0) {
            req1Name = representatives.get(0).Name;
            req1Address = representatives.get(0).Address__c;
            req1Position = representatives.get(0).Position__c;
            req1Email = representatives.get(0).Email;
            req1Phone = representatives.get(0).Phone;
        }
        if (representatives.size() > 1) {
            req2Name = representatives.get(1).Name;
            req2Address = representatives.get(1).Address__c;
            req2Position = representatives.get(1).Position__c;
            req2Email = representatives.get(1).Email;
            req2Phone = representatives.get(1).Phone;
        }
        if (representatives.size() > 2) {
            req3Name = representatives.get(2).Name;
            req3Address = representatives.get(2).Address__c;
            req3Position = representatives.get(2).Position__c;
            req3Email = representatives.get(2).Email;
            req3Phone = representatives.get(2).Phone;
        }
    }

    public void setBankInfo() {
        customer = [
            SELECT
                Bank_Name__c,Branch__c,BSB__c,Account_Number__c
            FROM
                Account
            WHERE
                Id = :ApexPages.currentPage().getParameters().get('id')
        ];
        branch = customer.Bank_Name__c==null ? '' : customer.Bank_Name__c + '/' + customer.Branch__c==null ? '' : customer.Branch__c;
        bsb = customer.BSB__c==null ? '' : customer.BSB__c + '/' + customer.Account_Number__c==null ? '' : customer.Account_Number__c;
    }

    public void setTradeRef() {
        tradingRef = [
            SELECT
                Name,Accounts_Email_Address__c,State__c,Telephone__c
            FROM
                Trading_Reference__c
            WHERE
                Customer__c = :customer.id
        ];
    }
}