force-app/main/default/objects/Account/fields/Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Business_Model__c</fullName>
    <label>Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Model1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group_Customer</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tax_Number_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Number_Category__c</fullName>
    <label>Customer Tax Number Category</label>
    <summaryForeignKey>Customer_Tax_Number_Category__c.Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Business_Model__c</fullName>
    <label>Business Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Business_Model1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Cust_Pric_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Cust_Pric_Procedure__c</fullName>
    <label>Customer Price Procedure</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>MX Procedure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <defaultValue>$User.Division_Text__c</defaultValue>
    <description>产品组</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Inco_Location1__c.field-meta.xml
<CustomField>
    <fullName>Inco_Location1__c</fullName>
    <label>Inco.Location1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Incoterms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Is_Freeze__c.field-meta.xml
<CustomField>
    <fullName>Is_Freeze__c</fullName>
    <label>Is Freeze</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/isSync__c.field-meta.xml
<CustomField>
    <fullName>isSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <label>Price Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 Bulk Buyer</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 Occasional Buyer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Reconciliation_Account__c.field-meta.xml
<CustomField>
    <fullName>Reconciliation_Account__c</fullName>
    <label>Reconciliation Account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Reconciliation_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_District__c.field-meta.xml
<CustomField>
    <fullName>Sales_District__c</fullName>
    <defaultValue>$User.Sales_District_Text__c</defaultValue>
    <label>Sales District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sales_Group__c</fullName>
    <defaultValue>$User.Sales_Group_Text__c</defaultValue>
    <label>Sales Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <defaultValue>$User.Sales_Office_Text__c</defaultValue>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_Office</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions__c</fullName>
    <label>Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Terms_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_Of_Payment__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <formula>Tax_Category_Master_Data__r.Country_District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country/District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Category Master Data</label>
    <referenceTo>Tax_Category_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <formula>Tax_Category_Master_Data__r.Tax_Category_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Category Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Number_Category__c/Customer_Tax_Number_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Number Category</label>
    <nameField>
        <displayFormat>CTNC-{000000}</displayFormat>
        <label>Customer Tax Number Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Number_Category__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Tax Number Category</relationshipLabel>
    <relationshipName>Customer_Tax_Number_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Number_Category__c/fields/Tax_Number_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Number Master Data</label>
    <referenceTo>Tax_Number_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Number Category</relationshipLabel>
    <relationshipName>Customer_Tax_Number_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/Tax_Category_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Tax Category Master Data</label>
    <nameField>
        <label>Tax Category Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <label>Country/District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <label>Tax Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Business_Model1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C0</fullName>
        <label>Model C</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>Model B</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>Model C+</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>Model A</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>Model A+</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>Model B+</label>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group_Customer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z001</fullName>
        <default>true</default>
        <label>Z001 Company Customer</label>
    </customValue>
    <customValue>
        <fullName>Z002</fullName>
        <label>Z002 Person Customer</label>
    </customValue>
    <customValue>
        <fullName>Z000</fullName>
        <label>Z000 Rainbow GROUP</label>
    </customValue>
    <masterLabel>Customer Group(Customer)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 General Division</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <description>产品组</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP Carriage and insurance paid to</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAF</fullName>
        <label>DAF Delivered at frontier</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP Delivered at place</label>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
        <label>DAT Delivered at terminal</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DDU</fullName>
        <label>DDU Delivered Duty Unpaid</label>
    </customValue>
    <customValue>
        <fullName>DEQ</fullName>
        <label>DEQ Delivered ex quay (duty paid)</label>
    </customValue>
    <customValue>
        <fullName>DES</fullName>
        <label>DES Delivered ex ship</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS Free Alongside Ship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FH</fullName>
        <label>FH Free house</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB Free on board</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UN Not Free</label>
    </customValue>
    <description>国际贸易条款</description>
    <masterLabel>Incoterms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Reconciliation_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1122020100</fullName>
        <label>1122020100 Accounts Receivable - None-Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122020200</fullName>
        <label>1122020200 Accounts Receivable - None-Related parties-Foreign</label>
    </customValue>
    <customValue>
        <fullName>1122020000</fullName>
        <label>1122020000 AR: Accounts Receivable - None-Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010000</fullName>
        <label>1122010000 AR: Accounts Receivable - Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010100</fullName>
        <label>1122010100 Accounts Receivable - Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122000000</fullName>
        <label>1122000000 Cuentas a Cobrar</label>
    </customValue>
    <masterLabel>Reconciliation Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AG1</fullName>
        <label>AG1 AgroT Sales group 1</label>
    </customValue>
    <customValue>
        <fullName>Z01</fullName>
        <label>Z01 南美1商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>Z02 南美2商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z03</fullName>
        <label>Z03 北美商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z04</fullName>
        <label>Z04 中美商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z05</fullName>
        <label>Z05 巴西商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z06</fullName>
        <label>Z06 非洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z07</fullName>
        <label>Z07 澳洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z08</fullName>
        <label>Z08 亚洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z09</fullName>
        <label>Z09 CIS商务小组</label>
    </customValue>
    <description>销售组</description>
    <masterLabel>Sales Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Office.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGR1</fullName>
        <label>AGR1 Agroterrum office</label>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
        <label>Commercial Department 1</label>
    </customValue>
    <customValue>
        <fullName>Z002</fullName>
        <label>Commercial Department 2</label>
    </customValue>
    <description>销售办公室</description>
    <masterLabel>Sales Office</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Shipping_Conditions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>01 Standard</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Pick up</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03 RB Gualeguaychu</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04 RB Buenos Aires</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05 SLA en Alsina</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06 SLA en Zárate</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>07 Agroterrum Gualeguay</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>08 Daser en Victoria</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>09 Deylar en San Franci</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Tokbritz en Chaco</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11 Agrosym en Salta</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 AGSOF S.A.</label>
    </customValue>
    <masterLabel>Shipping Conditions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerSalesInfoSyncToSAP.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 02-13-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   07-01-2025   Gerry   Initial Version
**/
public without sharing class CustomerSalesInfoSyncToSAP {

    

    @Future(callout=true)
    public static void submitToSAPFutrue(String Id,String type){
        submitToSAP(Id,type);
    }

    @AuraEnabled
    public static ReturnResult submitToSAP(String Id,String type){
        String END_POINT;
        if (type=='I') {
            END_POINT = 'CustomerSalesInfoNEW';
        }
        if(type=='U') {
            END_POINT = 'CustomerSalesInfoUpdate';
        }
        ReturnResult returnResult = new ReturnResult();
        returnResult.isSuccess = true;

        Boolean isSuccess = true;
        String requestBody = '';
        String responseBodyStr = '';
        String errorMessage = '';
        List<Customer_Sales_Info__c> accList;
        try{
            RequestBody request = new RequestBody();
            request.esbinfo = new ReqESInfo();
            request.esbinfo.attr1 = 'SFCRM';
            request.esbinfo.attr2 = 'SAP';
            List<ReqCustomerSalesInfo> resultinfoList = new List<ReqCustomerSalesInfo>();
            //获取客户销售信息
            accList=[SELECT Id,Name,Customer__r.MDG_Customer_Code__c,
                        Sales_Org__c,Distr_Channel__c,Customer__c,
                        Division__c,Sales_District__c,Sales_Office__c,
                        Sales_Group__c,Currency__c,Price_Group__c,Cust_Pric_Procedure__c,
                        Delivering_Plant__c,Shipping_Conditions__c,Terms_Of_Payment__c,
                        Acct_Assmt_Grp_Cust__c,Incoterms__c,Inco_Location1__c,Payment_method__c 
                        ,Business_model__c,Customer__r.Customer_Group__c,Reconciliation_Account__c,OwnerId   ,Is_Freeze__c,isSync__c
                    FROM 
                        Customer_Sales_Info__c 
                    WHERE Id =:Id];
            String customerId = accList[0].Customer__c;
            //获取客户税收类别
            List<Customer_Tax_Category__c> cusTaxList=[SELECT Id,Country_District__c,
                                        Tax_Category__c,Tax_Category_Name__c,Tax_Category_Master_Data__r.Name,Tax_Category_Master_Data__r.Country_Code__c 
                                        FROM Customer_Tax_Category__c 
                                        WHERE Sales_View__c =: Id];

            // //获取客户财务视图
            // List<Customer_Financial_Info__c> cusFicList=[SELECT Id,Customer__r.MDG_Customer_Code__c,
            //                             Company_Code__c,Reconciliation_Account__c  
            //                             FROM Customer_Financial_Info__c 
            //                             WHERE Customer__c =: customerId];
            
            //获取客户税号类别
            List<Customer_Tax_Number_Category__c> cusTaxNumList=[SELECT Id,Customer__r.MDG_Customer_Code__c,
                                        Tax_Number_Master_Data__r.Code__c,Long_Tax_Number__c   
                                        FROM Customer_Tax_Number_Category__c 
                                        WHERE Customer__c =: customerId];
            
            ReqCustomerSalesInfo rcsi = new ReqCustomerSalesInfo();
            rcsi.partner = accList[0].Customer__r.MDG_Customer_Code__c;
            rcsi.ktokk = accList[0].Customer__r.Customer_Group__c;
            rcsi.flucu01 = new List<salesInfo>();
            salesInfo si = new salesInfo();
            si.kunnr = accList[0].Customer__r.MDG_Customer_Code__c;
            si.vkorg = accList[0].Sales_Org__c;
            si.vtweg = accList[0].Distr_Channel__c;
            si.spart = accList[0].Division__c;
            si.bzirk = accList[0].Sales_District__c;
            // si.kdgrp = accList[0].Customer__r.Customer_Group__c;
            si.kdgrp = '';
            si.kvgr1 = accList[0].Payment_method__c;
            si.kvgr3 = accList[0].Business_model__c;
            si.vkbur = accList[0].Sales_Office__c;
            si.vkgrp = accList[0].Sales_Group__c;
            si.waers = accList[0].Currency__c;
            si.konda = accList[0].Price_Group__c;
            si.kalks = accList[0].Cust_Pric_Procedure__c;
            si.vwerk = accList[0].Delivering_Plant__c;
            si.vsbed = accList[0].Shipping_Conditions__c;
            si.zterm = accList[0].Terms_Of_Payment__c;
            si.ktgrd = accList[0].Acct_Assmt_Grp_Cust__c;
            si.inco1 = accList[0].Incoterms__c;
            si.inco2_L = accList[0].Inco_Location1__c;
            if(accList[0].Is_Freeze__c=='00') {
                si.AUFSD = '';
            }else{
                si.AUFSD = accList[0].Is_Freeze__c;
            }
            
            si.TAXKDS = new List<TaxRow>();
            
            //客户税收类别赋值
            if (
                !accList[0].isSync__c ||
                accList[0].Sales_Org__c=='3010' ||
                accList[0].Sales_Org__c=='3020' ||
                accList[0].Sales_Org__c=='2100'
            ) {
                List<TaxRow> taxList = new List<TaxRow>();
                for(Customer_Tax_Category__c ctc : cusTaxList){
                    TaxRow tr = new TaxRow();
                    tr.aland = ctc.Tax_Category_Master_Data__r.Country_Code__c;
                    tr.taxkd = ctc.Tax_Category__c;
                    tr.taxkd = tr.taxkd.substring(0,tr.taxkd.indexof('-'));
                    tr.tatyp = ctc.Tax_Category_Master_Data__r.Name;
                    taxList.add(tr);
                }
                si.TAXKDS = taxList;
            }
            
            rcsi.flucu01.add(si);
            rcsi.flucu00 = new List<FinancialRow>();
            //客户财务信息赋值
            List<FinancialRow> ficList = new List<FinancialRow>();
            // for(Customer_Financial_Info__c cfi : cusFicList){
            FinancialRow fr = new FinancialRow();
            fr.kunnr = accList[0].Customer__r.MDG_Customer_Code__c;
            fr.bukrs = accList[0].Sales_Org__c;
            fr.akont = accList[0].Reconciliation_Account__c;
            ficList.add(fr);
            // }
            rcsi.flucu00 = ficList;

            rcsi.taxnums = new List<TaxNumberRow>();
            //客户税号类别赋值
            List<TaxNumberRow> tnrList = new List<TaxNumberRow>();
            for(Customer_Tax_Number_Category__c ctnc : cusTaxNumList){
                TaxNumberRow tnr = new TaxNumberRow();
                tnr.partner = ctnc.Customer__r.MDG_Customer_Code__c;
                tnr.taxtype = ctnc.Tax_Number_Master_Data__r.Code__c;
                tnr.taxnumxl = ctnc.Long_Tax_Number__c;
                tnrList.add(tnr);
            }
            rcsi.taxnums = tnrList;

            resultinfoList.add(rcsi);
            request.resultinfo = resultinfoList;
            requestBody = JSON.serialize(request);
            requestBody = requestBody.replaceAll('null', '\"\"');
            System.debug('requestBody++'+requestBody);
            System.debug('requestBody++'+requestBody);
            HttpResponse responseBody = InterfaceUtility.send_SAP_POST_Service(requestBody, END_POINT);
            System.debug('responseBody++'+responseBody);
            responseBodyStr = responseBody.getBody();
            System.debug('responseBodyStr===' + responseBodyStr);
            isSuccess = responseBody.getStatusCode() == 200 ? true : false;
            if (isSuccess) {
                ResponseBody syncReturnData = (ResponseBody) JSON.deserialize(responseBodyStr, ResponseBody.class);
                System.debug('responseData===' + syncReturnData);
                if ( syncReturnData.esbinfo != null ) {
                    returnResult.message = syncReturnData.esbinfo.returnmsg;
                    Customer_Sales_Info__c upcsi = new Customer_Sales_Info__c();
                    upcsi.Id = Id;
                    if (syncReturnData.esbinfo.returnstatus == 'S') {
                        upcsi.Sync_Status__c = 'Synchronized';
                        upcsi.Sync_Failure_Reasons__c = '';
                        upcsi.isSync__c = true;
                    }
                    if(syncReturnData.esbinfo.returnstatus == 'E'){
                        upcsi.Sync_Status__c = 'Synchronization Failure';
                        upcsi.Sync_Failure_Reasons__c = syncReturnData.resultinfo[0].msgtx;
                        isSuccess = false;
                        errorMessage = syncReturnData.esbinfo.returnmsg;
                        returnResult.isSuccess = false;
                        returnResult.message = syncReturnData.esbinfo.returnmsg;
                        Utility.notificationUser(accList[0].OwnerId,Id);
                    }
                    update upcsi;
                }else{
                    returnResult.isSuccess = false;
                    returnResult.message = responseBodyStr;
                    isSuccess = false;
                    errorMessage = responseBodyStr;
                    Customer_Sales_Info__c upcsi = new Customer_Sales_Info__c();
                    upcsi.Id = Id;
                    upcsi.Sync_Status__c = 'Synchronization Failure';
                    upcsi.Sync_Failure_Reasons__c = 'null';
                    update upcsi;
                    Utility.notificationUser(accList[0].OwnerId,Id);
                }
                
            } else {
                returnResult.isSuccess = false;
                returnResult.message = responseBodyStr;
                isSuccess = false;
                errorMessage = responseBodyStr;
                Customer_Sales_Info__c upcsi = new Customer_Sales_Info__c();
                upcsi.Id = Id;
                upcsi.Sync_Status__c = 'Synchronization Failure';
                upcsi.Sync_Failure_Reasons__c = ''+responseBody.getStatusCode();
                update upcsi;
                Utility.notificationUser(accList[0].OwnerId,Id);
            }

        }
        catch (Exception e) {
            if (accList.size()>0) {
                Utility.notificationUser(accList[0].OwnerId,Id);
            }
            Customer_Sales_Info__c upcsi = new Customer_Sales_Info__c();
            upcsi.Id = Id;
            upcsi.Sync_Status__c = 'Synchronization Failure';
            upcsi.Sync_Failure_Reasons__c = e.getMessage()+e.getLineNumber();
            update upcsi;
            System.debug('错误信息'+e.getMessage()+e.getLineNumber());
            returnResult.isSuccess = false;
            returnResult.message = e.getMessage()+e.getLineNumber();
            isSuccess = false;
            errorMessage = e.getMessage()+e.getLineNumber();
        }
        InterfaceUtility.insertInterfaceLog('CustomerSalesInfoSyncToSAP', 'CRM',
                    'SAP', END_POINT, requestBody, isSuccess, false,
                    responseBodyStr, errorMessage, 'POST', new List<String>{Id},
                    '客户销售视图同步SAP', 'CRM同步客户销售视图至SAP');
        return returnResult;
    }

    public class ReturnResult {
        @InvocableVariable(Label='是否成功' Description='是否成功')
        public Boolean isSuccess;
        @InvocableVariable(Label='返回信息结果' Description='返回信息结果')
        public String message;
    }

    public class ResponseBody {
      public RespESInfo esbinfo;
      public List<RespCustomerInfo> resultinfo;
    }

    public class RespESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
        public String responsetime;//返回时间
        public String returnstatus;//接口状态
        public String returncode;//接口状态码
        public String returnmsg;//接口消息
        public String attr1;//预留字段
        public String attr2;//预留字段
        public String attr3;//预留字段
    }

    public class RespCustomerInfo{
        public String msgty;//处理状态
        public String msgtx;//错误信息
    }

    public class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqCustomerSalesInfo> resultinfo;

    }

    public class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
        public String attr1;//发送方
        public String attr2;//接受方

    }
    public class ReqCustomerSalesInfo {
        public String ktokk;
        public String partner;
        public List<FinancialRow> flucu00;
        public List<TaxNumberRow> taxnums;
        public List<salesInfo> flucu01;
    }
    public class salesInfo{
        public String kunnr;//客户编码
        public String vkorg;//销售组织
        public String vtweg;//分销渠道
        public String spart;//产品组
        public String bzirk;//销售地区
        public String kdgrp;//客户组
        public String kvgr1;//客户组1
        public String kvgr3;//客户组3
        public String vkbur;//销售部门
        public String vkgrp;//销售组
        public String waers;//币种
        public String konda;//价格组
        public String kalks;//Cust.Price.过程
        public String vwerk;//交货工厂
        public String vsbed;//装运条件
        public String zterm;//付款条件
        public String ktgrd;//客户科目分配组
        public String inco1;//国际贸易条款
        public String inco2_L;//国贸条款位置 1
        public String AUFSD;//冻结
        public List<TaxRow> TAXKDS;//税收类别
    }

    public class TaxRow{
        public String aland;//国家代码
        public String tatyp;//税分类
        public String taxkd;//税收类别编码
    }

    public class FinancialRow{
        public String kunnr;//客户编码
        public String bukrs;//公司代码
        public String akont;//统驭科目
    }

    public class TaxNumberRow{
        public String partner;//客户编码
        public String taxtype;//税号类别
        public String taxnumxl;//长税号
    }
}