force-app/main/default/objects/Account/fields/Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Business_Model__c</fullName>
    <label>Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Model1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group_Customer</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Business_Model__c</fullName>
    <label>Business Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Business_Model1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Cust_Pric_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Cust_Pric_Procedure__c</fullName>
    <label>Customer Price Procedure</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>MX Procedure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <defaultValue>$User.Division_Text__c</defaultValue>
    <description>产品组</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Inco_Location1__c.field-meta.xml
<CustomField>
    <fullName>Inco_Location1__c</fullName>
    <label>Inco.Location1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Incoterms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <label>Price Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 Bulk Buyer</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 Occasional Buyer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Reconciliation_Account__c.field-meta.xml
<CustomField>
    <fullName>Reconciliation_Account__c</fullName>
    <label>Reconciliation Account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Reconciliation_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_District__c.field-meta.xml
<CustomField>
    <fullName>Sales_District__c</fullName>
    <defaultValue>$User.Sales_District_Text__c</defaultValue>
    <label>Sales District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sales_Group__c</fullName>
    <defaultValue>$User.Sales_Group_Text__c</defaultValue>
    <label>Sales Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <defaultValue>$User.Sales_Office_Text__c</defaultValue>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sales_Office</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions__c</fullName>
    <label>Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Terms_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_Of_Payment__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <formula>Tax_Category_Master_Data__r.Country_District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country/District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Category Master Data</label>
    <referenceTo>Tax_Category_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <formula>Tax_Category_Master_Data__r.Tax_Category_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Category Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Type__c</fullName>
    <label>Tax Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Number_Category__c/Customer_Tax_Number_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Number Category</label>
    <nameField>
        <displayFormat>CTNC-{000000}</displayFormat>
        <label>Customer Tax Number Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Number_Category__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Tax Number Category</relationshipLabel>
    <relationshipName>Customer_Tax_Number_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/Tax_Category_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Tax Category Master Data</label>
    <nameField>
        <label>Tax Category Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <label>Country/District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <label>Tax Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Business_Model1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C0</fullName>
        <label>Model C</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>Model B</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>Model C+</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>Model A</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>Model A+</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>Model B+</label>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group_Customer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z001</fullName>
        <default>true</default>
        <label>Z001 Company Customer</label>
    </customValue>
    <customValue>
        <fullName>Z002</fullName>
        <label>Z002 Person Customer</label>
    </customValue>
    <customValue>
        <fullName>Z000</fullName>
        <label>Z000 Rainbow GROUP</label>
    </customValue>
    <masterLabel>Customer Group(Customer)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 General Division</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <description>产品组</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP Carriage and insurance paid to</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAF</fullName>
        <label>DAF Delivered at frontier</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP Delivered at place</label>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
        <label>DAT Delivered at terminal</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DDU</fullName>
        <label>DDU Delivered Duty Unpaid</label>
    </customValue>
    <customValue>
        <fullName>DEQ</fullName>
        <label>DEQ Delivered ex quay (duty paid)</label>
    </customValue>
    <customValue>
        <fullName>DES</fullName>
        <label>DES Delivered ex ship</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS Free Alongside Ship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FH</fullName>
        <label>FH Free house</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB Free on board</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UN Not Free</label>
    </customValue>
    <description>国际贸易条款</description>
    <masterLabel>Incoterms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Reconciliation_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1122020100</fullName>
        <label>1122020100 Accounts Receivable - None-Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122020200</fullName>
        <label>1122020200 Accounts Receivable - None-Related parties-Foreign</label>
    </customValue>
    <customValue>
        <fullName>1122020000</fullName>
        <label>1122020000 AR: Accounts Receivable - None-Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010000</fullName>
        <label>1122010000 AR: Accounts Receivable - Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010100</fullName>
        <label>1122010100 Accounts Receivable - Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122000000</fullName>
        <label>1122000000 Cuentas a Cobrar</label>
    </customValue>
    <masterLabel>Reconciliation Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AG1</fullName>
        <label>AG1 AgroT Sales group 1</label>
    </customValue>
    <customValue>
        <fullName>Z01</fullName>
        <label>Z01 南美1商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>Z02 南美2商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z03</fullName>
        <label>Z03 北美商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z04</fullName>
        <label>Z04 中美商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z05</fullName>
        <label>Z05 巴西商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z06</fullName>
        <label>Z06 非洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z07</fullName>
        <label>Z07 澳洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z08</fullName>
        <label>Z08 亚洲商务小组</label>
    </customValue>
    <customValue>
        <fullName>Z09</fullName>
        <label>Z09 CIS商务小组</label>
    </customValue>
    <description>销售组</description>
    <masterLabel>Sales Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Office.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGR1</fullName>
        <label>AGR1 Agroterrum office</label>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
        <label>Commercial Department 1</label>
    </customValue>
    <customValue>
        <fullName>Z002</fullName>
        <label>Commercial Department 2</label>
    </customValue>
    <description>销售办公室</description>
    <masterLabel>Sales Office</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Shipping_Conditions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>01 Standard</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Pick up</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03 RB Gualeguaychu</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04 RB Buenos Aires</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05 SLA en Alsina</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06 SLA en Zárate</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>07 Agroterrum Gualeguay</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>08 Daser en Victoria</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>09 Deylar en San Franci</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Tokbritz en Chaco</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11 Agrosym en Salta</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 AGSOF S.A.</label>
    </customValue>
    <masterLabel>Shipping Conditions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>J1AU</fullName>
        <label>J1AU IVA Ventas</label>
    </customValue>
    <customValue>
        <fullName>J1A1</fullName>
        <label>J1A1 Perc. IIBB CABA</label>
    </customValue>
    <customValue>
        <fullName>J1A2</fullName>
        <label>J1A2 Perc. IIBB ARBA</label>
    </customValue>
    <customValue>
        <fullName>J1A3</fullName>
        <label>J1A3 Perc. IIBB EntreRios</label>
    </customValue>
    <customValue>
        <fullName>J1A4</fullName>
        <label>J1A4 Perc. IIBB Santa Fe</label>
    </customValue>
    <customValue>
        <fullName>J1A5</fullName>
        <label>J1A5 Perc. IIBB Córdoba</label>
    </customValue>
    <customValue>
        <fullName>J1A6</fullName>
        <label>J1A6 Perc. IIBB Salta</label>
    </customValue>
    <customValue>
        <fullName>J1A7</fullName>
        <label>J1A7 Perc. IIBB Tucumán</label>
    </customValue>
    <customValue>
        <fullName>J1A8</fullName>
        <label>J1A8 Perc. IIBB Otras</label>
    </customValue>
    <customValue>
        <fullName>MWST</fullName>
        <label>MWST IVA repercutido</label>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
        <label>MX01 I.E.P.S. (MEXICO)</label>
    </customValue>
    <masterLabel>Tax Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerSalesInfoSyncToSAPTest.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 07-31-2025
 * @last modified by  : Gerry 
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   07-31-2025   Gerry   Initial Version
**/
@isTest
private class CustomerSalesInfoSyncToSAPTest {
    static testMethod void testMethod1() {
        Account a = new Account();
        a.Name = 'Test';
        a.Group_Name__c = 'test';
        a.MDG_Customer_Code__c = '1111';
        a.Customer_Group__c = 'Z001';
        insert a;
        Customer_Sales_Info__c csi = new Customer_Sales_Info__c();
        csi.Sales_Org__c = '5130';
        csi.Distr_Channel__c = '00';
        csi.Division__c = '10';
        csi.Delivering_Plant__c = '5130';
        csi.Sales_District__c = 'ZAR00';
        // csi.Sales_Office__c = 'AGR1';
        // csi.Sales_Group__c = 'AG1';
        csi.Currency__c = 'USD';
        csi.Price_Group__c = '02';
        csi.Cust_Pric_Procedure__c = '01';
        csi.Delivering_Plant__c = '5130';
        csi.Shipping_Conditions__c = '01';
        csi.Terms_Of_Payment__c = 'AR01';
        csi.Acct_Assmt_Grp_Cust__c = '01';
        // csi.Inco_Location1__c = '11';
        // csi.Payment_method__c = 'Z1';
        csi.Business_Model__c = 'C0';
        csi.Reconciliation_Account__c = '1122020000';
        csi.Sales_View_Status__c = 'Approved';
        csi.Customer__c = a.Id;
        csi.Incoterms__c = '';
        insert csi;
        Tax_Category_Master_Data__c tcmd = new Tax_Category_Master_Data__c();
        tcmd.Country_Code__c = '11';
        tcmd.Country_District__c = '11';
        tcmd.Name = '11';
        tcmd.Tax_Category_Name__c = '11';
        insert tcmd;
        Customer_Tax_Category__c ctc = new Customer_Tax_Category__c();
        ctc.Tax_Category_Type__c = 'J1AU';
        ctc.Tax_Category__c = '1-Responsable IVA';
        ctc.Tax_Category_Master_Data__c = tcmd.Id;
        ctc.Sales_View__c = csi.Id;
        insert ctc;
        Tax_Number_Master_Data__c tnmd = new Tax_Number_Master_Data__c();
        tnmd.Code__c = '11';
        tnmd.Name = '11';
        insert tnmd;
        Customer_Tax_Number_Category__c ctnc = new Customer_Tax_Number_Category__c();
        ctnc.Customer__c = a.Id;
        ctnc.Long_Tax_Number__c = '11';
        ctnc.Tax_Number_Master_Data__c = tnmd.Id;
        insert ctnc;
        CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'I');
    }

    static testMethod void testMethod2() {
        Account a = new Account();
        a.Name = 'Test';
        a.Group_Name__c = 'test';
        a.MDG_Customer_Code__c = '1111';
        a.Customer_Group__c = 'Z001';
        insert a;
        Customer_Sales_Info__c csi = new Customer_Sales_Info__c();
        csi.Sales_Org__c = '5130';
        csi.Distr_Channel__c = '00';
        csi.Division__c = '10';
        csi.Delivering_Plant__c = '5130';
        csi.Sales_District__c = 'ZAR00';
        // csi.Sales_Office__c = 'AGR1';
        // csi.Sales_Group__c = 'AG1';
        csi.Currency__c = 'USD';
        csi.Price_Group__c = '02';
        csi.Cust_Pric_Procedure__c = '01';
        csi.Delivering_Plant__c = '5130';
        csi.Shipping_Conditions__c = '01';
        csi.Terms_Of_Payment__c = 'AR01';
        csi.Acct_Assmt_Grp_Cust__c = '01';
        // csi.Inco_Location1__c = '11';
        // csi.Payment_method__c = 'Z1';
        csi.Business_Model__c = 'C0';
        csi.Reconciliation_Account__c = '1122020000';
        csi.Sales_View_Status__c = 'Approved';
        csi.Customer__c = a.Id;
        csi.Incoterms__c = '';
        insert csi;
        Tax_Category_Master_Data__c tcmd = new Tax_Category_Master_Data__c();
        tcmd.Country_Code__c = '11';
        tcmd.Country_District__c = '11';
        tcmd.Name = '11';
        tcmd.Tax_Category_Name__c = '11';
        insert tcmd;
        Customer_Tax_Category__c ctc = new Customer_Tax_Category__c();
        ctc.Tax_Category_Type__c = 'J1AU';
        ctc.Tax_Category__c = '1-Responsable IVA';
        ctc.Tax_Category_Master_Data__c = tcmd.Id;
        ctc.Sales_View__c = csi.Id;
        insert ctc;
        Tax_Number_Master_Data__c tnmd = new Tax_Number_Master_Data__c();
        tnmd.Code__c = '11';
        tnmd.Name = '11';
        insert tnmd;
        Customer_Tax_Number_Category__c ctnc = new Customer_Tax_Number_Category__c();
        ctnc.Customer__c = a.Id;
        ctnc.Long_Tax_Number__c = '11';
        ctnc.Tax_Number_Master_Data__c = tnmd.Id;
        insert ctnc;
        Test.setMock(HttpCalloutMock.class, new TestHttpMock.CustomerInfoSyncToSap());
        test.startTest();
        CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'I');
        test.stopTest();
        
    }
}