force-app/main/default/objects/Account/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Credit_Segment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Segment__c</fullName>
    <label>Credit Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credit_Segement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Local_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Local_Credit_Limit__c</fullName>
    <label>Local Credit Limit1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Rules__c.field-meta.xml
<CustomField>
    <fullName>Rules__c</fullName>
    <label>Rules</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rules</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sinosure_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sinosure_Credit_Limit__c</fullName>
    <label>Sinosure Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/Customer_Quota_Change__c.object-meta.xml
<CustomObject>
    <label>Credit Limit Application</label>
    <nameField>
        <displayFormat>CLA-{000000}</displayFormat>
        <label>Customer Credit Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Credit_Segment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Segment__c</fullName>
    <label>Credit Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credit_Segement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Quota_Change</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Local_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Local_Credit_Limit__c</fullName>
    <label>Local Credit line1(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Post_Application_Credit__c.field-meta.xml
<CustomField>
    <fullName>Post_Application_Credit__c</fullName>
    <label>Applied Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Rules__c.field-meta.xml
<CustomField>
    <fullName>Rules__c</fullName>
    <label>Rules</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rules</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Sinosure_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sinosure_Credit_Limit__c</fullName>
    <label>Sinosure Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Quota_Change__c/fields/Valid_After_Change_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_After_Change_To__c</fullName>
    <description>变更后有效期至</description>
    <label>Customer Credit Line Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Check_Rule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OV2</fullName>
        <label>OV2	Subsidiary Company With Overdue Open Items 0 Days</label>
    </customValue>
    <customValue>
        <fullName>OV1</fullName>
        <label>OV1	Subsidiary Company With Overdue Open Items 30 Days</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>01 Default -All Checks Active (Stat. Credit Limit)</label>
    </customValue>
    <customValue>
        <fullName>OV3</fullName>
        <label>OV3	Subsidiary Company With Overdue Open Items 15 Days</label>
    </customValue>
    <customValue>
        <fullName>OV4</fullName>
        <label>OV4 Credit Limit + Overdue Payment + 60 days</label>
    </customValue>
    <customValue>
        <fullName>OV</fullName>
        <isActive>false</isActive>
        <label>OV default-overseas subsidiary company</label>
    </customValue>
    <description>检查规则</description>
    <masterLabel>Check Rule</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Credit_Segement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z000</fullName>
        <default>true</default>
        <label>Z000 Overseas General Credit segment</label>
    </customValue>
    <description>信用段</description>
    <masterLabel>Credit Segement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Normal Check</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 Middle Risk</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B High Risk</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Medium Risk</label>
    </customValue>
    <description>风险等级</description>
    <masterLabel>Risk Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rules.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>STANDARD</fullName>
        <default>true</default>
        <label>STANDARD</label>
    </customValue>
    <masterLabel>Rules</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerQuotaChangeTriggerHandlerTest.cls
@IsTest
private class CustomerQuotaChangeTriggerHandlerTest {
    static testMethod void testMock(){
        Account a = new Account();
        a.Name = 'Test';
        a.Group_Name__c = 'test';
        a.Customer_Approval_Status__c = 'Approved';
        a.Sync_Status__c = 'Synchronized';
        Insert a;
        
        Customer_Sales_Info__c csi = new Customer_Sales_Info__c();
        csi.Sales_Org__c = '3020';
        csi.Distr_Channel__c = '10';
        csi.Sales_View_Status__c = 'Approved';
        csi.Sync_Status__c='Synchronized';
        csi.Customer__c = a.Id;
        insert csi;
        
        Customer_Credit_Info__c cci = new Customer_Credit_Info__c();
        cci.Customer__c = a.Id;
        cci.ExternalId__c = a.Id;
        insert cci;
        
        Customer_Quota_Change__c cqc = new Customer_Quota_Change__c();
        cqc.Customer__c = a.Id;
        cqc.Post_Application_Credit__c = 1;
        cqc.Valid_After_Change_To__c = System.today();
        cqc.Rules__c = 'STANDARD';
        cqc.Risk_Class__c = 'A';
        cqc.Check_Rule__c = 'OV1';
        cqc.Credit_Segment__c = 'Z000';
        cqc.Sinosure_Credit_Limit__c = 1;
        cqc.Local_Credit_Limit__c = 1;
        Insert cqc;
        cqc.Approval_Status__c = 'Approved';
        update cqc;
    }
}