force-app/main/default/objects/Account/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company_Account.recordType-meta.xml
<RecordType>
    <fullName>Company_Account</fullName>
    <active>true</active>
    <label>Company Account</label>
</RecordType>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Actual_Credit_limit__c.field-meta.xml
<CustomField>
    <fullName>Actual_Credit_limit__c</fullName>
    <label>Customer Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Credit_Segment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Segment__c</fullName>
    <label>Credit Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credit_Segement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Local_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Local_Credit_Limit__c</fullName>
    <label>Local Credit Limit1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Remaining_Credit__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Credit__c</fullName>
    <label>SAP Available Credit Limit (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Rules__c.field-meta.xml
<CustomField>
    <fullName>Rules__c</fullName>
    <label>Rules</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rules</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sinosure_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sinosure_Credit_Limit__c</fullName>
    <label>Sinosure Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Valid_Until__c</fullName>
    <label>Customer Credit Line Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <formula>Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MDG Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not synchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization error</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Model_C.recordType-meta.xml
<RecordType>
    <fullName>Model_C</fullName>
    <active>true</active>
    <label>Model C</label>
</RecordType>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Check_Rule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OV2</fullName>
        <label>OV2	Subsidiary Company With Overdue Open Items 0 Days</label>
    </customValue>
    <customValue>
        <fullName>OV1</fullName>
        <label>OV1	Subsidiary Company With Overdue Open Items 30 Days</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>01 Default -All Checks Active (Stat. Credit Limit)</label>
    </customValue>
    <customValue>
        <fullName>OV3</fullName>
        <label>OV3	Subsidiary Company With Overdue Open Items 15 Days</label>
    </customValue>
    <customValue>
        <fullName>OV4</fullName>
        <label>OV4 Credit Limit + Overdue Payment + 60 days</label>
    </customValue>
    <customValue>
        <fullName>OV</fullName>
        <isActive>false</isActive>
        <label>OV default-overseas subsidiary company</label>
    </customValue>
    <description>检查规则</description>
    <masterLabel>Check Rule</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Credit_Segement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z000</fullName>
        <default>true</default>
        <label>Z000 Overseas General Credit segment</label>
    </customValue>
    <description>信用段</description>
    <masterLabel>Credit Segement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Normal Check</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 Middle Risk</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B High Risk</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Medium Risk</label>
    </customValue>
    <description>风险等级</description>
    <masterLabel>Risk Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rules.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>STANDARD</fullName>
        <default>true</default>
        <label>STANDARD</label>
    </customValue>
    <masterLabel>Rules</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloseOrderBatchTest.cls
/**
 * @description       : Test class for CloseOrderBatch
 * @author            : Agentforce
 * @group             : 
 * @last modified on  : 04-22-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   04-13-2026   Agentforce   Initial Version
**/
@isTest
public class CloseOrderBatchTest {
    
    /**
     * @description Create test data for Account, Customer_Credit_Info, Customer_Sales_Info, Order, and Order_Item
     */
    @TestSetup
    static void setupTestData() {
        // Create Account
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.Group_Name__c = 'Test Group';
        testAccount.MDG_Customer_Code__c = '12345';
        testAccount.Customer_Approval_Status__c = 'Approved';
        testAccount.Sync_Status__c = 'synchronized';
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Company_Account').getRecordTypeId();
        insert testAccount;
        
        // Create Customer Credit Info
        Customer_Credit_Info__c creditInfo = new Customer_Credit_Info__c();
        creditInfo.Customer__c = testAccount.Id;
        creditInfo.Rules__c = 'STANDARD';
        creditInfo.Risk_Class__c = 'A';
        creditInfo.Check_Rule__c = 'OV1';
        creditInfo.Credit_Segment__c = 'Z000';
        creditInfo.Valid_Until__c = Date.today().addDays(30);
        creditInfo.Sinosure_Credit_Limit__c = 100000;
        creditInfo.Local_Credit_Limit__c = 100000;
        creditInfo.Actual_Credit_limit__c = 100000;
        creditInfo.Sync_Status__c = 'Synchronized';
        creditInfo.Remaining_Credit__c = 100000;
        creditInfo.ExternalId__c = 'TEST12345';
        insert creditInfo;
        
        // Create Customer Sales Info
        Customer_Sales_Info__c salesInfo = new Customer_Sales_Info__c();
        salesInfo.Sales_Org__c = '5070';
        salesInfo.Distr_Channel__c = '00';
        salesInfo.Sales_View_Status__c = 'Approved';
        salesInfo.Sync_Status__c = 'Synchronized';
        salesInfo.Customer__c = testAccount.Id;
        salesInfo.Acct_Assmt_Grp_Cust__c = '01';
        salesInfo.Payment_method__c = 'YPF';
        insert salesInfo;
        
        // Create Orders with different order types
        List<Order__c> orders = new List<Order__c>();
        
        // Order with type ZARE (Argentina)
        Order__c order1 = new Order__c();
        order1.Customer__c = testAccount.Id;
        order1.Sales_Org__c = '5070';
        order1.Distr_Channel__c = '00';
        order1.Customer_Sales_Info__c = salesInfo.Id;
        order1.Currency__c = 'USD';
        order1.Deliver_Plant__c = '5070';
        order1.Business_Model__c = 'C0';
        order1.Order_type__c = 'ZARE';
        order1.Order_Reason__c = '101';
        order1.Status__c = 'Approved';
        order1.Sync_Status__c = 'Synchronized';
        order1.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Model_C').getRecordTypeId();
        order1.Cust_Reference__c = 'REF001';
        order1.Stock_Aging_Limit__c = '60';
        order1.SAP_Order__c = true;
        orders.add(order1);
        
        // Order with type ZMX3 (Mexico)
        Order__c order2 = new Order__c();
        order2.Customer__c = testAccount.Id;
        order2.Sales_Org__c = '3010';
        order2.Distr_Channel__c = '10';
        order2.Customer_Sales_Info__c = salesInfo.Id;
        order2.Currency__c = 'USD';
        order2.Deliver_Plant__c = '3010';
        order2.Business_Model__c = 'B0';
        order2.Order_type__c = 'ZMX3';
        order2.Order_Reason__c = 'MX1';
        order2.Status__c = 'Approved';
        order2.Sync_Status__c = 'Synchronized';
        order2.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Model_C').getRecordTypeId();
        order2.Cust_Reference__c = 'REF002';
        order2.Stock_Aging_Limit__c = '60';
        order2.SAP_Order__c = true;
        orders.add(order2);
        
        // Order with type ZARB
        Order__c order3 = new Order__c();
        order3.Customer__c = testAccount.Id;
        order3.Sales_Org__c = '5070';
        order3.Distr_Channel__c = '00';
        order3.Customer_Sales_Info__c = salesInfo.Id;
        order3.Currency__c = 'USD';
        order3.Deliver_Plant__c = '5070';
        order3.Business_Model__c = 'C0';
        order3.Order_type__c = 'ZARB';
        order3.Order_Reason__c = '101';
        order3.Status__c = 'Approved';
        order3.Sync_Status__c = 'Synchronized';
        order3.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Model_C').getRecordTypeId();
        order3.Cust_Reference__c = 'REF003';
        order3.Stock_Aging_Limit__c = '60';
        order3.SAP_Order__c = true;
        orders.add(order3);
        
        // Standard order type - use 5070 which is simpler
        Order__c order4 = new Order__c();
        order4.Customer__c = testAccount.Id;
        order4.Sales_Org__c = '5070';
        order4.Distr_Channel__c = '00';
        order4.Customer_Sales_Info__c = salesInfo.Id;
        order4.Currency__c = 'USD';
        order4.Deliver_Plant__c = '5070';
        order4.Business_Model__c = 'C0';
        order4.Order_type__c = 'ZARA';
        order4.Order_Reason__c = 'Z11';
        order4.Status__c = 'Approved';
        order4.Sync_Status__c = 'Synchronized';
        order4.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Model_C').getRecordTypeId();
        order4.Cust_Reference__c = 'REF004';
        order4.Stock_Aging_Limit__c = '60';
        order4.SAP_Order__c = true;
        orders.add(order4);
        
        insert orders;
        
        // Create Order Items
        List<Order_Item__c> orderItems = new List<Order_Item__c>();
        
        // Order Item for ZARE order (should fail without Delivery_Note)
        Order_Item__c item1 = new Order_Item__c();
        item1.Order__c = orders[0].Id;
        item1.isClosed__c = false;
        item1.IsCreate__c = true;
        orderItems.add(item1);
        
        // Order Item for ZMX3 order with reference
        Order_Item__c item2 = new Order_Item__c();
        item2.Order__c = orders[1].Id;
        item2.isClosed__c = false;
        item2.IsCreate__c = true;
        orderItems.add(item2);
        
        // Order Item for ZARB order
        Order_Item__c item3 = new Order_Item__c();
        item3.Order__c = orders[2].Id;
        item3.isClosed__c = false;
        item3.IsCreate__c = true;
        orderItems.add(item3);
        
        // Order Item for standard order
        Order_Item__c item4 = new Order_Item__c();
        item4.Order__c = orders[3].Id;
        item4.isClosed__c = false;
        item4.IsCreate__c = true;
        orderItems.add(item4);
        
        insert orderItems;
    }
    
    /**
     * @description Test successful batch execution with single order item
     */
    @isTest
    static void testBatchExecutionSuccess() {
        // Get test order item
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c 
                                    WHERE Order__r.Order_type__c = 'ZARA' LIMIT 1];
        
        Test.startTest();
        // Execute batch with single order item number
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        Database.executeBatch(batch, 10);
        Test.stopTest();
        
        // Verify batch was initialized correctly
        System.assertNotEquals(null, batch.query, 'Query should be initialized');
        System.assertEquals(true, batch.flag, 'Flag should be initialized as true');
        System.assertNotEquals(null, batch.startTime, 'Start time should be set');
        System.assertEquals(1, batch.orderItemNumberList.size(), 'Should have one order item in list');
    }
    
    /**
     * @description Test batch execution with multiple order items
     */
    @isTest
    static void testBatchExecutionMultipleItems() {
        // Get multiple test order items
        List<Order_Item__c> orderItems = [SELECT Id, Name FROM Order_Item__c 
                                          WHERE Order__r.Order_type__c IN ('ZARA', 'ZARB') 
                                          LIMIT 2];
        
        String orderItemNumbers = orderItems[0].Name + ',' + orderItems[1].Name;
        
        Test.startTest();
        // Execute batch with multiple order item numbers
        CloseOrderBatch batch = new CloseOrderBatch(orderItemNumbers);
        Database.executeBatch(batch, 10);
        Test.stopTest();
        
        // Verify batch handles multiple items
        System.assertEquals(2, batch.orderItemNumberList.size(), 'Should have two order items in list');
        System.assertEquals(orderItems[0].Name, batch.orderItemNumberList[0], 'First item should match');
        System.assertEquals(orderItems[1].Name, batch.orderItemNumberList[1], 'Second item should match');
    }
    
    /**
     * @description Test batch execution with ZARE order type without Delivery Note (should fail)
     */
    @isTest
    static void testBatchExecutionZAREWithoutDeliveryNote() {
        // Get ZARE order item (without Delivery_Note)
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c 
                                    WHERE Order__r.Order_type__c = 'ZARE' LIMIT 1];
        
        Test.startTest();
        // Execute batch
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        Database.executeBatch(batch, 10);
        Test.stopTest();
        
        // Verify the order item was not closed due to validation
        Order_Item__c updatedItem = [SELECT Id, isClosed__c FROM Order_Item__c WHERE Id = :orderItem.Id];
        System.assertEquals(false, updatedItem.isClosed__c, 'Order item should not be closed without Delivery Note');
    }
    
    /**
     * @description Test batch execution with Mexico order type (ZMX3) with reference
     */
    @isTest
    static void testBatchExecutionZMX3WithReference() {
        // Get ZMX3 order item
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c 
                                    WHERE Order__r.Order_type__c = 'ZMX3' LIMIT 1];
        
        Test.startTest();
        // Execute batch
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        Database.executeBatch(batch, 10);
        Test.stopTest();
        
        // Verify batch processed the item
        System.assertEquals(1, batch.orderItemNumberList.size(), 'Should have one order item');
    }
    
    /**
     * @description Test QueryLocator start method
     */
    @isTest
    static void testStartMethod() {
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c LIMIT 1];
        
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        
        Test.startTest();
        Database.BatchableContext bc = null;
        Database.QueryLocator ql = batch.start(bc);
        Test.stopTest();
        
        // Verify QueryLocator is returned
        System.assertNotEquals(null, ql, 'QueryLocator should not be null');
    }
    
    /**
     * @description Test execute method with Test.isRunningTest() condition
     */
    @isTest
    static void testExecuteMethod() {
        Order_Item__c orderItem = [SELECT Id, Name, Order__c FROM Order_Item__c 
                                    WHERE Order__r.Order_type__c = 'ZARA' LIMIT 1];
        
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        
        Test.startTest();
        Database.BatchableContext bc = null;
        List<Order_Item__c> orderList = [SELECT Id FROM Order_Item__c WHERE Id = :orderItem.Id];
        batch.execute(bc, orderList);
        Test.stopTest();
        
        // Verify execute method completes without error
        // The actual closing logic calls CloseOrderController.closeOrder() which may have its own validation
        System.assertNotEquals(null, orderList, 'Order list should not be null');
        System.assertEquals(1, orderList.size(), 'Should have one order item');
    }
    
    /**
     * @description Test finish method
     */
    @isTest
    static void testFinishMethod() {
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c LIMIT 1];
        
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        
        Test.startTest();
        Database.BatchableContext bc = null;
        batch.finish(bc);
        Test.stopTest();
        
        // Finish method is empty, just verify it executes without error
        System.assert(true, 'Finish method should execute without error');
    }
    
    /**
     * @description Test batch with invalid order item number
     */
    @isTest
    static void testBatchWithInvalidOrderItemNumber() {
        Test.startTest();
        // Execute batch with non-existent order item number
        CloseOrderBatch batch = new CloseOrderBatch('INVALID-123456');
        Database.executeBatch(batch, 10);
        Test.stopTest();
        
        // Verify batch completes without errors (empty result set)
        System.assertEquals(1, batch.orderItemNumberList.size(), 'Should have one item in list');
        System.assertEquals('INVALID-123456', batch.orderItemNumberList[0], 'Should contain invalid number');
    }
    
    /**
     * @description Test batch state management
     */
    @isTest
    static void testBatchStateManagement() {
        Order_Item__c orderItem = [SELECT Id, Name FROM Order_Item__c LIMIT 1];
        
        CloseOrderBatch batch = new CloseOrderBatch(orderItem.Name);
        
        // Verify initial state
        System.assertEquals(true, batch.flag, 'Initial flag should be true');
        System.assertEquals(null, batch.errorMsg, 'Initial error message should be null');
        
        // Manually set flag to false
        batch.flag = false;
        batch.errorMsg = 'Test Error';
        
        System.assertEquals(false, batch.flag, 'Flag should be updated');
        System.assertEquals('Test Error', batch.errorMsg, 'Error message should be set');
    }
    
    /**
     * @description Test batch with comma-separated multiple order numbers including spaces
     */
    @isTest
    static void testBatchWithMultipleOrderNumbersWithSpaces() {
        List<Order_Item__c> orderItems = [SELECT Id, Name FROM Order_Item__c LIMIT 2];
        
        String orderItemNumbers = orderItems[0].Name + ', ' + orderItems[1].Name;
        
        Test.startTest();
        CloseOrderBatch batch = new CloseOrderBatch(orderItemNumbers);
        Database.executeBatch(batch, 10);
        Test.stopTest();


        
        // Verify split handles spaces correctly
        System.assertEquals(2, batch.orderItemNumberList.size(), 'Should have two items');
    }
     @isTest
    static void testBatchWithMultipleOrderNumbersWithSpaces1() {
        
        Test.startTest();
        CloseOrderBatch batch = new CloseOrderBatch('SELECT Id, Name FROM Order_Item__c',1);
        Database.executeBatch(batch, 10);
        Test.stopTest();
    }
    /**
     * @description Test batch constructor initialization
     */
    @isTest
    static void testBatchConstructorInitialization() {
        String testOrderNumber = 'TEST-123,TEST-456,TEST-789';
        
        CloseOrderBatch batch = new CloseOrderBatch(testOrderNumber);
        
        // Verify all properties are initialized
        System.assertNotEquals(null, batch.startTime, 'Start time should be initialized');
        System.assertEquals(3, batch.orderItemNumberList.size(), 'Should split into 3 items');
        System.assertEquals(true, batch.flag, 'Flag should be true');
        System.assertNotEquals(null, batch.query, 'Query should be initialized');
        System.assert(batch.query.contains('SELECT Id FROM Order_Item__c'), 'Query should select from Order_Item__c');
        System.assert(batch.query.contains('WHERE Name IN:orderItemNumberList'), 'Query should filter by name');
    }
}