force-app/main/default/objects/Account/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Actual_Credit_limit__c.field-meta.xml
<CustomField>
    <fullName>Actual_Credit_limit__c</fullName>
    <label>Customer Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Check_Rule__c.field-meta.xml
<CustomField>
    <fullName>Check_Rule__c</fullName>
    <label>Check Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Rule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Credit_Segment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Segment__c</fullName>
    <label>Credit Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credit_Segement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Local_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Local_Credit_Limit__c</fullName>
    <label>Local Credit Limit1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Remaining_Credit__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Credit__c</fullName>
    <label>SAP Available Credit Limit (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Rules__c.field-meta.xml
<CustomField>
    <fullName>Rules__c</fullName>
    <label>Rules</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rules</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sinosure_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sinosure_Credit_Limit__c</fullName>
    <label>Sinosure Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Valid_Until__c</fullName>
    <label>Customer Credit Line Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Check_Rule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OV2</fullName>
        <label>OV2	Subsidiary Company With Overdue Open Items 0 Days</label>
    </customValue>
    <customValue>
        <fullName>OV1</fullName>
        <label>OV1	Subsidiary Company With Overdue Open Items 30 Days</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>01 Default -All Checks Active (Stat. Credit Limit)</label>
    </customValue>
    <customValue>
        <fullName>OV3</fullName>
        <label>OV3	Subsidiary Company With Overdue Open Items 15 Days</label>
    </customValue>
    <customValue>
        <fullName>OV4</fullName>
        <label>OV4 Credit Limit + Overdue Payment + 60 days</label>
    </customValue>
    <customValue>
        <fullName>OV</fullName>
        <isActive>false</isActive>
        <label>OV default-overseas subsidiary company</label>
    </customValue>
    <description>检查规则</description>
    <masterLabel>Check Rule</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Credit_Segement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z000</fullName>
        <default>true</default>
        <label>Z000 Overseas General Credit segment</label>
    </customValue>
    <description>信用段</description>
    <masterLabel>Credit Segement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Normal Check</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 Middle Risk</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B High Risk</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Medium Risk</label>
    </customValue>
    <description>风险等级</description>
    <masterLabel>Risk Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rules.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>STANDARD</fullName>
        <default>true</default>
        <label>STANDARD</label>
    </customValue>
    <masterLabel>Rules</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetCustomerlimitFROMSAP.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 10-23-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-25-2025   Gerry   Initial Version
**/
public without sharing class GetCustomerlimitFROMSAP {//客户使用额度查询

    public static final String END_POINT = 'getLimit';

    @AuraEnabled

    public static RespCustomerInfo submitToSAP(List<String> customerCodeList,String WAERS,String BUKRS){
        List<String> recordIdList = new List<String>();
        System.debug('WAERS'+WAERS);
        ResponseBody syncReturnData = null;
        ReturnResult returnResult = new ReturnResult();

        returnResult.isSuccess = true;

        Boolean isSuccess = true;

        String requestBody = '';

        String responseBodyStr = '';

        String errorMessage = '';

        try{

            RequestBody request = new RequestBody();

            request.esbinfo = new ReqESInfo();
            request.esbinfo.requesttime = String.valueOf(Datetime.now());
            request.esbinfo.instid = 'GSD004';
            List<ReqCustomerInfo> resultinfoList = new List<ReqCustomerInfo>();

            //获取客户

            List<Customer_Credit_Info__c> accList = [ SELECT Id,Name,

                                                        Rules__C,

                                                        Risk_Class__C,

                                                        Check_Rule__C,

                                                        Credit_Segment__C,

                                                        Valid_Until__C,

                                                        Customer__C,

                                                        Sinosure_Credit_Limit__C,

                                                        Local_Credit_Limit__C,

                                                        Actual_Credit_limit__C,

                                                        Sync_Status__C,

                                                        Remaining_Credit__C,
                                                        Customer__r.MDG_Customer_Code__c

                                                    FROM 
                                                        Customer_Credit_Info__c

                                                    WHERE 
                                                        Customer__r.MDG_Customer_Code__c IN:customerCodeList
                                                    ];

        Map<String,String> cciMap = new Map<String,String>();
        for (Customer_Credit_Info__c cci : accList) {
            recordIdList.add(cci.Id);
            ReqCustomerInfo rci = new ReqCustomerInfo();
            cciMap.put(cci.Customer__r.MDG_Customer_Code__c, cci.Id);
            rci.partner = cci.Customer__r.MDG_Customer_Code__c;
            rci.creditSegment = accList[0].credit_Segment__c;
            if (String.isNotBlank(WAERS)) {
                System.debug('进入销售逻辑');
                rci.WAERS = WAERS;
            }
            if (String.isNotBlank(BUKRS)) {
                rci.BUKRS = BUKRS;
            }
            resultinfoList.add(rci);
        }
        



        

        request.resultinfo = resultinfoList;

        requestBody = JSON.serialize(request);



        System.debug('requestBody++'+requestBody);

        HttpResponse responseBody = InterfaceUtility.send_SAP_POST_Service(requestBody, END_POINT);

        System.debug('responseBody++'+responseBody);

        responseBodyStr = responseBody.getBody();

        System.debug('responseBodyStr===' + responseBodyStr);



        isSuccess = responseBody.getStatusCode() == 200 ? true : false;



            if (isSuccess) {

                syncReturnData = (ResponseBody) JSON.deserialize(responseBodyStr, ResponseBody.class);

                System.debug('responseData===' + syncReturnData);

                if ( syncReturnData.esbinfo != null ) {

                    returnResult.message = syncReturnData.esbinfo.returnmsg;

                    

                    if (syncReturnData.esbinfo.returnstatus == 'S') {

                        List<Customer_Credit_Info__c> updateList = new List<Customer_Credit_Info__c>();
                        for (RespCustomerInfo rci : syncReturnData.resultinfo) {
                            Customer_Credit_Info__c upAcc = new Customer_Credit_Info__c();
                            upAcc.Id = cciMap.get(rci.partner);
                            upAcc.Remaining_Credit__C = rci.amount;
                            if (String.isNotBlank(rci.zsfyq)) {
                                upAcc.Overdue__c = true;
                            }else{
                                upAcc.Overdue__c = false;
                            }
                            updateList.add(upAcc);
                        }
                        update updateList;
                    }

                    if(syncReturnData.esbinfo.returnstatus == 'E'){
                        isSuccess = false;
                        errorMessage = syncReturnData.esbinfo.returnmsg;
                        returnResult.isSuccess = false;
                        returnResult.message = syncReturnData.esbinfo.returnmsg;
                    }

                    if(syncReturnData.esbinfo.returnstatus == 'W'){
                        isSuccess = false;
                        errorMessage = syncReturnData.esbinfo.returnmsg;
                        returnResult.isSuccess = false;
                        returnResult.message = syncReturnData.esbinfo.returnmsg;
                    }

                }else{

                    returnResult.isSuccess = false;
                    returnResult.message = responseBodyStr;
                    isSuccess = false;
                    errorMessage = responseBodyStr;

                }


            } else {
                returnResult.isSuccess = false;
                returnResult.message = responseBodyStr;
                isSuccess = false;
                errorMessage = responseBodyStr;

            }
        }

        catch (Exception e) {

            System.debug('错误信息'+e.getMessage()+'行数：'+e.getLineNumber());

            returnResult.isSuccess = false;

            returnResult.message = e.getMessage()+e.getLineNumber();

            isSuccess = false;

            errorMessage = e.getMessage()+e.getLineNumber();

        }

        InterfaceUtility.insertInterfaceLog('GetCustomerlimitFROMSAP', 'CRM',

                    'SAP', END_POINT, requestBody, isSuccess, false,

                    responseBodyStr, errorMessage, 'POST', recordIdList,

                    '客户额度信息查询', 'CRM查询SAP信用额度余额');

        // if (isSuccess) {
            // return null;
            if (syncReturnData!=null && syncReturnData.resultinfo!=null) {
                if (syncReturnData.resultinfo.size()>0) {
                    // syncReturnData.resultinfo[0].zovdmtr = '5000';
                    return syncReturnData.resultinfo[0];
                }else{
                    RespCustomerInfo r = new RespCustomerInfo();
                    r.msgty = 'E';
                    r.msgtx = 'No result';
                    return r;
                }
            }else{
                RespCustomerInfo r = new RespCustomerInfo();
                r.msgty = 'E';
                r.msgtx = 'No result';
                return r;
            }
            
            
        // }else{
        //     return null;
        // }
        

    }



    public class ReturnResult {

        @InvocableVariable(Label='是否成功' Description='是否成功')

        public Boolean isSuccess;

        @InvocableVariable(Label='返回信息结果' Description='返回信息结果')

        public String message;

    }



    public class ResponseBody {

      public RespESInfo esbinfo;

      public List<RespCustomerInfo> resultinfo;

    }



    public class RespESInfo{

        public String instid;//接口编号

        public String requesttime;//请求时间

        public String responsetime;//返回时间

        public String returnstatus;//接口状态

        public String returncode;//接口状态码

        public String returnmsg;//接口消息

        public String attr1;//预留字段

        public String attr2;//预留字段

        public String attr3;//预留字段

    }



    public class RespCustomerInfo{  //响应信息 resultinfo



        public String partner;  //业务伙伴编码

        public Decimal amount;   //剩余额度

        public String WAERS; //币种

        public String zsfyq;//是否逾期

        public String exch_rate;//汇率

        public String ZOVDAYS;//最大逾期天数

        public String zovdmtr;//逾期金额

        public String msgty;

        public String msgtx;
    }



    public class RequestBody {

        public ReqESInfo esbinfo;

        public List<ReqCustomerInfo> resultinfo;

        public String iex01;//预留字段1

        public String iex02;//预留字段2

        public String iex03;//预留字段3

        public String iex04;//预留字段4

        public String iex05;//预留字段5

        public String iex06;//预留字段6

    }



    public class ReqESInfo{

        public String instid;//接口编号

        public String requesttime;//请求时间

        public String attr1;//预留字段

        public String attr2;//预留字段

        public String attr3;//预留字段

    }



    public class ReqCustomerInfo{

        public String partner;//客户编码

        public String creditSegment;//信用段

        public String WAERS;//币种

        public String BUKRS;//销售组织

        public String iex01;//预留字段1

        public String iex02;//预留字段2

        public String iex03;//预留字段3

        public String iex04;//预留字段4

        public String iex05;//预留字段5

        public String iex06;//预留字段6

    }

}