force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Country)</relationshipLabel>
    <relationshipName>Accounts_Country</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Add_Operation_Date__c.field-meta.xml
<CustomField>
    <fullName>Add_Operation_Date__c</fullName>
    <label>Latest Performance Shared Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Create_Plant__c.field-meta.xml
<CustomField>
    <fullName>Create_Plant__c</fullName>
    <formula>TEXT(CreatedBy.Delivery_Plant__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Create Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Customer_Owner_Plant__c.field-meta.xml
<CustomField>
    <fullName>Customer_Owner_Plant__c</fullName>
    <formula>Text(Customer__r.Owner.Delivery_Plant__c)</formula>
    <label>Customer Owner Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Is_Ruuning__c.field-meta.xml
<CustomField>
    <fullName>Is_Ruuning__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Ruuning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep_Country__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Country__c</fullName>
    <formula>Sales_Rep__r.Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep_Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Delivery_Plant__c</fullName>
    <formula>TEXT(Sales_Rep__r.Delivery_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Shared_Performance__c.field-meta.xml
<CustomField>
    <fullName>Shared_Performance__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Shared Performance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/Sales_Forcast__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast Detail</label>
    <nameField>
        <displayFormat>SFD-{000000}</displayFormat>
        <label>Sales Forcast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forcast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Forcast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <formula>TEXT(Sales_Forecast_Summary__r.Delivery_Plant__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Forecast_Local_Curreny__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Forecast_Local_Curreny__c</fullName>
    <label>Monthly Forecast (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Forecast_USD__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Forecast_USD__c</fullName>
    <label>Monthly Forecast (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Price_Local__c.field-meta.xml
<CustomField>
    <fullName>Price_Local__c</fullName>
    <label>Price (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Price_USD__c.field-meta.xml
<CustomField>
    <fullName>Price_USD__c</fullName>
    <label>Price (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Monthly_Forecast_Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Monthly_Forecast_Local_Currency__c</fullName>
    <label>Rolling Forecast (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Monthly_Forecast_USD__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Monthly_Forecast_USD__c</fullName>
    <label>Rolling Monthly Forecast (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Price_Local__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Price_Local__c</fullName>
    <label>Rolling Price(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Price_USD__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Price_USD__c</fullName>
    <label>Rolling Price(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Volumn_Local__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Volumn_Local__c</fullName>
    <label>Rolling Volumn(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Rolling_Volumn_USD__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Volumn_USD__c</fullName>
    <label>Rolling Volumn(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Volumn_Local__c.field-meta.xml
<CustomField>
    <fullName>Volumn_Local__c</fullName>
    <label>Volumn (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>User Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTeamTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 12-12-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-27-2025   Gerry   Initial Version
**/
public without sharing class AccountTeamTriggerHandler  implements Triggers.Handler{
    public static void handle() {
        if (Trigger.isbefore && Trigger.isUpdate) {
            User u = [SELECT Id,Profile.Name,Delivery_Plant__c,Country__c FROM User WHERE Id=:System.UserInfo.getUserId()];
            // 判断当前用户是否在某个权限集下
            List<PermissionSetAssignment> psaList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSet.Name = 'Country_Admin'];
            Boolean hasPermissionSet = !psaList.isEmpty();
            Map<Id,Account_Team__c> oldMap = (Map<Id,Account_Team__c>)Trigger.oldMap;
            // List<String> userList = System.Label.Customer_Team_User.split(';');
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                if (at.Is_Ruuning__c && !System.Test.isRunningTest()) {
                    //at.adderror('Cannot edit in shared processing');
                    at.adderror(System.Label.AccTeamEditError);
                }
                if (
                    u.Profile.Name != 'System Administrator' && 
                    at.Sales_Rep_Delivery_Plant__c != 
                    at.Customer_Owner_Plant__c && 
                    !System.Test.isRunningTest() &&
                    !hasPermissionSet
                ) {
                    //at.adderror('Cannot edit across factories data');
                    at.adderror(System.Label.AccTeamEditPlantError);
                }
                if (hasPermissionSet && at.Sales_Rep_Country__c != u.Country__c) {
                    at.adderror(System.Label.AccTeamEditPlantError);
                }
                if (at.Is_Ruuning__c == oldMap.get(at.Id).Is_Ruuning__c) {
                    at.Is_Ruuning__c = true;
                }
                if (at.Shared_Performance__c != oldMap.get(at.Id).Shared_Performance__c && at.Shared_Performance__c) {
                    at.Add_Operation_Date__c = System.today();
                }
            }
        }
        if (Trigger.isbefore && Trigger.isInsert) {
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                at.Add_Operation_Date__c = System.today();
            }
        }

        if (Trigger.isafter && Trigger.isUpdate ) {
            //调用数据共享
            Map<Id,Account_Team__c> oldMap = (Map<Id,Account_Team__c>)Trigger.oldMap;
          
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                if (!System.isBatch() && !System.isFuture() && !System.Test.isRunningTest()) {
                    Database.executeBatch(new ShareAccountDataBatch(at.Id,at.Customer__c,1), 100);
                }
                
            }
        }

        //自动生成销售预测 start
        if (Trigger.isafter && (Trigger.isUpdate || Trigger.isInsert )) {
            Map<Id,Account_Team__c> oldMap = (Map<Id,Account_Team__c>)Trigger.oldMap;

            Map<String,String> userMap = new Map<String,String>();
            Set<String> accSet = new Set<String>();
            Set<String> userSet = new Set<String>();
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                
                
                if(
                    (Trigger.isUpdate && oldMap.get(at.Id).Shared_Performance__c != at.Shared_Performance__c && at.Shared_Performance__c) ||
                    (Trigger.isinsert && at.Shared_Performance__c)
                ) {
                    accSet.add(at.Customer__c);
                    userSet.add(at.CreatedById );
                    userMap.put(at.CreatedById ,at.Sales_Rep__c);
                }

                
            }
            Map<String,List<Sales_Forcast__c>> salesForcastMap = new Map<String,List<Sales_Forcast__c>>();
            List<Schema.FieldSetMember> fieldSetMembers = SObjectType.Sales_Forcast__c.FieldSets.QueryField.getFields();
            // 拼接需要复制得字段
            String orderQuery = 'SELECT ';
            String field = '';
            Date day = System.today();
            String year = String.valueOf(day.Year());
            for (Schema.FieldSetMember f : fieldSetMembers) {
                if (String.isNotBlank(field)) {
                    field += ','+f.getFieldPath();
                }else{
                    field += f.getFieldPath();
                }
                
            }
            orderQuery = orderQuery+field+' FROM Sales_Forcast__c WHERE Customer__c IN:accSet AND OwnerId IN:userSet AND Year__c=:year';
            List<Sales_Forcast__c> sfList = Database.query(orderQuery);
            
            Map<String,List<Sales_Forcast__c>> sfMap = new Map<String,List<Sales_Forcast__c>>();
            for(Sales_Forcast__c sf : sfList) {
                if(sfMap.containsKey(sf.Customer__c+'_'+sf.OwnerId)) {
                    sfMap.get(sf.Customer__c+'_'+sf.OwnerId).add(sf);
                }else{
                    sfMap.put(sf.Customer__c+'_'+sf.OwnerId,new List<Sales_Forcast__c>{sf});
                }
                
            }
            Map<String,Sales_Forcast__c> insertList = new Map<String,Sales_Forcast__c>();
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                //自动生成销售预测 start
                IF (
                    (Trigger.isUpdate && oldMap.get(at.Id).Shared_Performance__c != at.Shared_Performance__c && at.Shared_Performance__c) ||
                    (Trigger.isinsert && at.Shared_Performance__c)
                ){  
                    if(sfMap.get(at.Customer__c+'_'+at.CreatedById )!=null && at.Sales_Rep_Delivery_Plant__c==at.Create_Plant__c) {
                        for(Sales_Forcast__c sf : sfMap.get(at.Customer__c+'_'+at.CreatedById )) {
                            Sales_Forcast__c cloneSf = sf.clone();
                            cloneSf.Price_USD__c = 0;
                            cloneSf.Monthly_Forecast_USD__c = 0;
                            cloneSf.Monthly_Forecast_Local_Curreny__c = 0;
                            cloneSf.Volumn_Local__c = 0;
                            cloneSf.Price_Local__c = 0;
                            cloneSf.Rolling_Monthly_Forecast_USD__c = 0;
                            cloneSf.Rolling_Price_USD__c = 0;
                            cloneSf.Rolling_Volumn_USD__c = 0;
                            cloneSf.Rolling_Monthly_Forecast_Local_Currency__c = 0;
                            cloneSf.Rolling_Volumn_Local__c = 0;
                            cloneSf.Rolling_Price_Local__c = 0;
                            cloneSf.OwnerId = at.Sales_Rep__c;
                            cloneSf.External_Id__c = cloneSf.Year__c+cloneSf.Month__c+cloneSf.Product_Name__c+
                                                cloneSf.Customer__c+
                                                cloneSf.OwnerId;
                            insertList.put(cloneSf.External_Id__c,cloneSf);
                        }
                    }
                    
                }
            }
            Set<String> externalSet = new Set<String>();
            for(Sales_Forcast__c sf : [SELECT Id,External_Id__c FROM Sales_Forcast__c WHERE External_Id__c IN:insertList.keySet()]) {
                externalSet.add(sf.External_Id__c);
            }

            List<Sales_Forcast__c> iList = new List<Sales_Forcast__c>();
            for(Sales_Forcast__c sf : insertList.values()) {
                if(externalSet.contains(sf.External_Id__c)) {
                    continue;
                }
                iList.add(sf);
            }
            Insert iList;
            //自动生成销售预测 end
        }

        if (Trigger.isbefore && Trigger.isdelete) {
            User u = [SELECT Id,Profile.Name,Delivery_Plant__c,Country__c FROM User WHERE Id=:System.UserInfo.getUserId()];
            // 判断当前用户是否在某个权限集下
            List<PermissionSetAssignment> psaList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSet.Name = 'Country_Admin'];
            Boolean hasPermissionSet = !psaList.isEmpty();
            Set<String> accSet = new Set<String>();
            // List<String> userList = System.Label.Customer_Team_User.split(';');
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.old) {
                accSet.add(at.Customer__c);
            }
            Map<String,String> accMap = new Map<String,String>();
            for (Account acc : [SELECT Id,OwnerId FROM Account WHERE Id IN:accSet]) {
                accMap.put(acc.Id, acc.OwnerId);
            }
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.old) {
                if (at.Is_Ruuning__c && !System.Test.isRunningTest()) {
                    //at.adderror('Cannot edit/delete in shared processing');
                    at.adderror(System.Label.AccTeamEditDelError);
                }
                if (at.Sales_Rep__c == accMap.get(at.Customer__c) && !System.Test.isRunningTest()) {
                    //at.adderror('Cannot delete account owner\'s data');
                    at.adderror(System.Label.AccTeamDelError);
                }
                if (
                    u.Profile.Name != 'System Administrator' && 
                    at.Sales_Rep_Delivery_Plant__c != at.Customer_Owner_Plant__c && 
                    !System.Test.isRunningTest() &&
                    !hasPermissionSet
                ) {
                    //at.adderror('Cannot delete across factories data');
                    at.adderror(System.Label.AccTeamDelPlantError);
                }

                if (hasPermissionSet && at.Sales_Rep_Country__c != u.Country__c) {
                    at.adderror(System.Label.AccTeamDelPlantError);
                }
            }
        }
        if (Trigger.isafter && Trigger.isdelete) {
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.old) {
                if (!System.isBatch() && !System.isFuture() &&  !System.Test.isRunningTest()) {
                    Database.executeBatch(new DeleteShareBatch(at.Customer__c,at.Sales_Rep__c,1), 100);
                }
            }
            
        }
        if (Trigger.isbefore && Trigger.isinsert) {
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                at.External_Id__c = at.Customer__c+'_'+at.Sales_Rep__c;
            }}
        if (Trigger.isafter && Trigger.isinsert) {
            User u = [SELECT Id,Profile.Name,Delivery_Plant__c,Country__c FROM User WHERE Id=:System.UserInfo.getUserId()];
            Set<String> accSet = new Set<String>();
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                accSet.add(at.Customer__c);
            }
            Map<String,String> accMap = new Map<String,String>();
            for (Account acc : [SELECT Id,OwnerId FROM Account WHERE Id IN:accSet]) {
                accMap.put(acc.Id, acc.OwnerId);
            }
            // 判断当前用户是否在某个权限集下
            List<PermissionSetAssignment> psaList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSet.Name = 'Country_Admin'];
            Boolean hasPermissionSet = !psaList.isEmpty();
            // List<String> userList = System.Label.Customer_Team_User.split(';');
            for (Account_Team__c at : (List<Account_Team__c>)Trigger.new) {
                if (
                    u.Profile.Name != 'System Administrator' && 
                    u.Id != accMap.get(at.Customer__c) && 
                    at.Sales_Rep__c != accMap.get(at.Customer__c) && 
                    !System.Test.isRunningTest() &&
                    !hasPermissionSet
                ) {
                    //at.adderror('Customer Owner Can Insert account Team data');
                    at.adderror(System.Label.AccTeamOwnerInsertError);
                }
                system.debug('at.Sales_Rep_Delivery_Plant__c:'+at.Sales_Rep_Delivery_Plant__c);
                system.debug('u.Delivery_Plant__c:'+ u.Delivery_Plant__c);
                System.debug('hasPermissionSet'+hasPermissionSet);   
                if (
                    u.Profile.Name != 'System Administrator' && 
                    at.Sales_Rep_Delivery_Plant__c != u.Delivery_Plant__c && 
                    !System.Test.isRunningTest() &&
                    !hasPermissionSet
                ) {
                    //at.adderror('Only Can Insert Same Deliver Sale Rep account Team data');
                    System.debug('进入校验逻辑1');
                    at.adderror(System.Label.AccTeamInsertSameDeliveryError);
                }
                System.debug('at.Sales_Rep_Country__c'+at.Sales_Rep_Country__c);
                System.debug('u.Country__c'+u.Country__c);

                if (hasPermissionSet && at.Sales_Rep_Country__c != u.Country__c) {
                    System.debug('进入校验逻辑2');
                    at.adderror(System.Label.AccTeamInsertSameDeliveryError);
                }
                if (!System.isBatch() && !System.isFuture() && !System.Test.isRunningTest()) {
                    Database.executeBatch(new ShareAccountDataBatch(at.Id,at.Customer__c,1), 100);
                }
            }
        }
    }
}