force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Country)</relationshipLabel>
    <relationshipName>Accounts_Country</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_YPF__c.field-meta.xml
<CustomField>
    <fullName>Is_YPF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is YPF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Sales Info</relationshipLabel>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Country_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_Text__c</fullName>
    <formula>Country__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/isSync__c.field-meta.xml
<CustomField>
    <fullName>isSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Reconciliation_Account__c.field-meta.xml
<CustomField>
    <fullName>Reconciliation_Account__c</fullName>
    <label>Reconciliation Account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Reconciliation_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Category Master Data</label>
    <referenceTo>Tax_Category_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Type__c</fullName>
    <label>Tax Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/Tax_Category_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Tax Category Master Data</label>
    <nameField>
        <label>Tax Category Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Reconciliation_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1122020100</fullName>
        <label>1122020100 Accounts Receivable - None-Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122020200</fullName>
        <label>1122020200 Accounts Receivable - None-Related parties-Foreign</label>
    </customValue>
    <customValue>
        <fullName>1122020000</fullName>
        <label>1122020000 AR: Accounts Receivable - None-Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010000</fullName>
        <label>1122010000 AR: Accounts Receivable - Related parties</label>
    </customValue>
    <customValue>
        <fullName>1122010100</fullName>
        <label>1122010100 Accounts Receivable - Related parties-local</label>
    </customValue>
    <customValue>
        <fullName>1122000000</fullName>
        <label>1122000000 Cuentas a Cobrar</label>
    </customValue>
    <masterLabel>Reconciliation Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>J1AU</fullName>
        <label>J1AU IVA Ventas</label>
    </customValue>
    <customValue>
        <fullName>J1A1</fullName>
        <label>J1A1 Perc. IIBB CABA</label>
    </customValue>
    <customValue>
        <fullName>J1A2</fullName>
        <label>J1A2 Perc. IIBB ARBA</label>
    </customValue>
    <customValue>
        <fullName>J1A3</fullName>
        <label>J1A3 Perc. IIBB EntreRios</label>
    </customValue>
    <customValue>
        <fullName>J1A4</fullName>
        <label>J1A4 Perc. IIBB Santa Fe</label>
    </customValue>
    <customValue>
        <fullName>J1A5</fullName>
        <label>J1A5 Perc. IIBB Córdoba</label>
    </customValue>
    <customValue>
        <fullName>J1A6</fullName>
        <label>J1A6 Perc. IIBB Salta</label>
    </customValue>
    <customValue>
        <fullName>J1A7</fullName>
        <label>J1A7 Perc. IIBB Tucumán</label>
    </customValue>
    <customValue>
        <fullName>J1A8</fullName>
        <label>J1A8 Perc. IIBB Otras</label>
    </customValue>
    <customValue>
        <fullName>MWST</fullName>
        <label>MWST IVA repercutido</label>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
        <label>MX01 I.E.P.S. (MEXICO)</label>
    </customValue>
    <masterLabel>Tax Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerSalesInfoTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 11-11-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-16-2025   Gerry   Initial Version
**/
public without sharing class CustomerSalesInfoTriggerHandler  implements Triggers.Handler{
    public void handle() {
        if (Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate)) {
            Map<Id,Customer_Sales_Info__c> oldMap = (Map<Id,Customer_Sales_Info__c>)Trigger.oldMap;
            Set<String> countrySet = new Set<String>();
            Set<String> csiSet = new Set<String>();
            Set<String> customerSet = new Set<String>();//客户Id
            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                countrySet.add(csi.Country_Code_Text__c);
                customerSet.add(csi.Customer__c);
                if (Trigger.isUpdate && csi.Country__c!=oldMap.get(csi.Id).Country__c) {
                    csiSet.add(csi.Id);
                }
            }
            List<Customer_Tax_Category__c> ccDeleteList = [SELECT Id FROM Customer_Tax_Category__c WHERE Sales_View__c IN:csiSet];
            if (ccDeleteList.size()>0) {
                Database.delete(ccDeleteList);
            }
            Map<String,List<Tax_Category_Master_Data__c>> tcmdMap = new Map<String,List<Tax_Category_Master_Data__c>>();
            for (Tax_Category_Master_Data__c tcmd : [SELECT Id,Country_Code__c,Name FROM Tax_Category_Master_Data__c WHERE Country_Code__c IN:countrySet]) {
                if (tcmdMap.containsKey(tcmd.Country_Code__c)) {
                    tcmdMap.get(tcmd.Country_Code__c).add(tcmd);
                }else{
                    tcmdMap.put(tcmd.Country_Code__c, new List<Tax_Category_Master_Data__c>{tcmd});
                }
            }
            List<Customer_Tax_Category__c> insertList = new List<Customer_Tax_Category__c>();
            
            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                if (tcmdMap.get(csi.Country_Code_Text__c)!=null && (Trigger.isInsert || (Trigger.isUpdate && csi.Country__c!=oldMap.get(csi.Id).Country__c))) {
                    for (Tax_Category_Master_Data__c tcm : tcmdMap.get(csi.Country_Code_Text__c)) {
                        Customer_Tax_Category__c ctc = new Customer_Tax_Category__c();
                        ctc.Sales_View__c = csi.Id;
                        ctc.Tax_Category_Master_Data__c = tcm.Id;
                        ctc.Tax_Category_Type__c = tcm.Name;
                        insertList.add(ctc);
                    }
                }
            }
            Database.Insert(insertList);

            //判断该客户是否为ypf客户---start
            List<Account> accList = new List<Account>();
            for (Account acc : [SELECT Id,Is_YPF__c,(SELECT Id FROM Account_Sales_Info__r WHERE Payment_method__c='YPF' limit 1) FROM Account WHERE Id IN:customerSet]) {
                if (acc.Account_Sales_Info__r.size()>0) {
                    acc.Is_YPF__c = true;
                }else{
                    acc.Is_YPF__c = false;
                }
                accList.add(acc);
            }
            Utility.IgnoreAction(true,false,'CustomerSalesInfoTriggerHandler'); 
            Database.Update(accList);
            Utility.IgnoreAction(false,false,'CustomerSalesInfoTriggerHandler');
            //判断该客户是否为ypf客户---end

        }

        if (Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate)) {
            Set<String> customerSet = new Set<String>();
            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                if (
                    (csi.Delivering_Plant__c == '3010' || csi.Delivering_Plant__c == '3011' || csi.Delivering_Plant__c == '3020') &&
                    csi.Acct_Assmt_Grp_Cust__c == '01'
                ) {
                    csi.Reconciliation_Account__c = '1122010100';
                }

                if (
                    (csi.Delivering_Plant__c == '3010' || csi.Delivering_Plant__c == '3011' || csi.Delivering_Plant__c == '3020') &&
                    csi.Acct_Assmt_Grp_Cust__c == '02'
                ) {
                    csi.Reconciliation_Account__c = '1122020100';
                }

                if (
                    (csi.Delivering_Plant__c == '5070' || csi.Delivering_Plant__c == '5130') &&
                    csi.Acct_Assmt_Grp_Cust__c == '01'
                ) {
                    csi.Reconciliation_Account__c = '1122010000';
                }

                if (
                    (csi.Delivering_Plant__c == '5070' || csi.Delivering_Plant__c == '5130') &&
                    csi.Acct_Assmt_Grp_Cust__c == '02'
                ) {
                    csi.Reconciliation_Account__c = '1122020000';
                }

                customerSet.add(csi.Customer__c);
                csi.External_ID__c = csi.Customer__c+'_'+csi.Sales_Org__c+'_'+csi.Distr_Channel__c;
            }

            Map<String,Account> accMap = new Map<String,Account>();
            for (Account acc : [SELECT Id,Customer_Approval_Status__c,MDG_Customer_Code__c FROM Account WHERE Id IN:customerSet]) {
                accMap.put(acc.Id, acc);
            }

            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                if(accMap.get(csi.Customer__c).Customer_Approval_Status__c!='Draft' && accMap.get(csi.Customer__c).Customer_Approval_Status__c!='Approved') {
                    csi.addError(System.Label.SalesInfoCannotSave);
                }

                // if (accMap.get(csi.Customer__c).Customer_Approval_Status__c=='Approved' && accMap.get(csi.Customer__c).MDG_Customer_Code__c == null) {
                //     csi.addError(System.Label.SalesInfoCannotSave);
                // }
            }
        }

        if (Trigger.isAfter && Trigger.isUpdate) {
            Map<Id,Customer_Sales_Info__c> oldMap = (Map<Id,Customer_Sales_Info__c>)Trigger.oldMap;
            Set<String> accIdSet = new Set<String>();
            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                accIdSet.add(csi.Customer__c);
            }
            Map<Id,Account> accMap = new Map<Id,Account>([SELECT Id,MDG_Customer_Code__c FROM Account WHERE Id IN:accIdSet]);
            for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.New) {
                
                Set<String> uSet = new Set<String>();
                uSet.add(csi.OwnerId);
                if(oldMap.get(csi.Id).Sales_View_Status__c!=csi.Sales_View_Status__c && csi.Sales_View_Status__c=='Approved') {
                    if(accMap.get(csi.Customer__c)!=null && accMap.get(csi.Customer__c).MDG_Customer_Code__c!=null) {
                        if (!csi.isSync__c) {
                            CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'I');
                        }else{
                            CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'U');
                        }
                    }else{
                        Datetime d = Datetime.now();
                        String minute = d.minute() + 1 + '';
                        String sch =  d.second() +  ' ' +   minute +    ' ' +   d.hour() +   ' ' +   d.day() +  ' ' +  d.month() +  ' ? ' + d.year();
                        SyncAccountSalesInfoSchedule schup = new SyncAccountSalesInfoSchedule(
                            csi.Id
                        );
                        System.schedule(
                        '定时一分钟后SyncAccountSalesInfo' + Datetime.now().getTime(),
                        sch,
                        schup
                        );
                    }
                }

                if(oldMap.get(csi.Id).Sales_View_Status__c==csi.Sales_View_Status__c && csi.Sales_View_Status__c=='Approved' && !System.isBatch() && !System.isFuture() && csi.Sync_Status__c==oldMap.get(csi.Id).Sync_Status__c) {
                    if (!csi.isSync__c) {
                        CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'I');
                    }else{
                        CustomerSalesInfoSyncToSAP.submitToSAPFutrue(csi.Id,'U');
                    }
                }

                //审批结果通知
                if(csi.Sales_View_Status__c == 'Approved' && csi.Sales_View_Status__c!=oldMap.get(csi.Id).Sales_View_Status__c) {
                    Utility.notificationUserTitle(uSet,csi.Id,System.Label.Sales_Approved_Title,System.Label.Sales_Approved_Title+csi.Name);
                }

                if(csi.Sales_View_Status__c == 'Rejected' && csi.Sales_View_Status__c!=oldMap.get(csi.Id).Sales_View_Status__c) {
                    Utility.notificationUserTitle(uSet,csi.Id,System.Label.Sales_Rejected_Title,System.Label.Sales_Rejected_Title+csi.Name);
                }
            }
           
        }

        // 共享数据到客户小组
        if (Trigger.isAfter && Trigger.isinsert ) {
            for (Customer_Sales_Info__c order : (List<Customer_Sales_Info__c>)Trigger.new) {
                ShareDataToAccountTeam.shareData('Customer_Sales_Info__c', order.Id, order.Customer__c, 'Customer_Sales_Info__c',order.OwnerId);
            }
        }
        // 共享数据到客户小组
        if (Trigger.isbefore && Trigger.isUpdate ) {
             Map<Id,Customer_Sales_Info__c> oldMap = (Map<Id,Customer_Sales_Info__c>)Trigger.oldMap;
             for (Customer_Sales_Info__c csi : (List<Customer_Sales_Info__c>)Trigger.new) {
                if(oldMap.get(csi.Id).Delivering_Plant__c !=csi.Delivering_Plant__c) {
                    system.debug('变更工厂');
                Database.executeBatch(new ChangeShareDataToAccountTeamBatch('Customer_Sales_Info__c', csi.Id, csi.Customer__c, 'Customer_Sales_Info__c',csi.OwnerId,oldMap.get(csi.Id).Delivering_Plant__c,'Customer_Sales_Info__share'));
                }}
        }
    }
}