force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Country)</relationshipLabel>
    <relationshipName>Accounts_Country</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/Customer_Update__c.object-meta.xml
<CustomObject>
    <label>Customer Update</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Customer Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Updates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Update__c/fields/Approve_Status__c.field-meta.xml
<CustomField>
    <fullName>Approve_Status__c</fullName>
    <label>Approve Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Updates</relationshipLabel>
    <relationshipName>Customer_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/Finance_Start_Approve__c.field-meta.xml
<CustomField>
    <fullName>Finance_Start_Approve__c</fullName>
    <label>Finance Start Approve</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Customer_Update__c/fields/New_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Name__c</fullName>
    <label>New Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificationFinanceCustomerUpdateTest.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 12-16-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   12-16-2025   Gerry   Initial Version
**/
@isTest
private class NotificationFinanceCustomerUpdateTest {
    static testMethod void testMock1(){
        Account a = new Account(
            Name = 'Tax Clean',
            Group_Name__c = 'Test Group',
            Tax_Number__c = '12-34-56',
            Country__c = null, // avoid after-insert country-specific branches not under test
            Customer_Approval_Status__c = 'Draft',
            Sync_Status__c = 'Synchronized'
        );
        insert a;
        Customer_Update__c cu = new Customer_Update__c();
        cu.New_Customer_Name__c = '1';
        cu.Customer__c = a.Id;
        cu.Approve_Status__c = 'Approving';
        cu.Finance_Start_Approve__c = System.now().addDays(-2);
        insert cu;
        NotificationFinanceCustomerUpdateBatch svo = new NotificationFinanceCustomerUpdateBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 5);
    }
}