force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customers (Country)</relationshipLabel>
    <relationshipName>Accounts_Country</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/CRM_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Approval_Status__c</fullName>
    <label>CRM Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HQ Contracts (Customer)</relationshipLabel>
    <relationshipName>HQ_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Export_Country__c.field-meta.xml
<CustomField>
    <fullName>Export_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Export Country</label>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Final_Customer__c.field-meta.xml
<CustomField>
    <fullName>Final_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts_Final_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Payment_Term_Cost_Rate__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Cost_Rate__c</fullName>
    <label>Payment Term Cost Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Province_Master_Data__c/Country_Province_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Country/Province Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Province_Master_Data__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Country/Province Master Data</relationshipLabel>
    <relationshipName>Country_Province_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Province_Master_Data__c/recordTypes/Country.recordType-meta.xml
<RecordType>
    <fullName>Country</fullName>
    <active>true</active>
    <label>Country</label>
</RecordType>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_Province_Master_Data__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_Province_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Sales Info</relationshipLabel>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Is_Freeze__c.field-meta.xml
<CustomField>
    <fullName>Is_Freeze__c</fullName>
    <label>Is Freeze</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Rate__c/Payment_Rate__c.object-meta.xml
<CustomObject>
    <label>Payment Rate</label>
    <nameField>
        <label>Payment Term Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Rate</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Rate__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Rate__c/fields/Payment_Term_Cost_Rate__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Cost_Rate__c</fullName>
    <label>Payment Term Cost Rate(Customer)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Rate__c/fields/Payment_Term_Cost_Rate_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Cost_Rate_Subsidiary__c</fullName>
    <label>Payment Term Cost Rate(Subsidiary)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quote_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>User Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not synchronized</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronization error</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronized</fullName>
    </customValue>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractsTriggerHandler.cls
/**
 * @description       : 合同trigger
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 01-14-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-13-2025   Gerry   Initial Version
**/
public without sharing class ContractsTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isBefore &&  Trigger.isinsert)
        {
            for (Contracts__c con : (List<Contracts__c>)Trigger.new) 
            {
                if(con.Quote__c==null)
                {
                    if(con.Sales_Org__c=='3010'){/*con.Final_Customer_Payment_Terms__c=system.label.MXContractPaymentTerms;*/}
                    if(con.Sales_Org__c=='5070'){con.Final_Customer_Payment_Terms__c=system.label.ARContractPaymentTerms;}
                }
            }
            //校验客户冻结
            // Set<String> accSet = new Set<String>();
            // Set<String> salesOrgSet = new Set<String>();
            // Set<String> accSalesOrgSet = new Set<String>();
            // for (Contracts__c con : (List<Contracts__c>)Trigger.new) {
            //     accSet.add(con.Final_Customer__c);
            //     salesOrgSet.add(con.Sales_Org__c);
            // }
            // for(Customer_Sales_Info__c csi :[SELECT Id,Customer__c,Sales_Org__c FROM Customer_Sales_Info__c WHERE Customer__c IN:accSet AND Sales_Org__c IN:salesOrgSet AND Is_Freeze__c='01'])
            // {
            //     accSalesOrgSet.add(csi.Customer__c+'_'+csi.Sales_Org__c);
            // }
            // System.debug('accSalesOrgSet=>'+accSalesOrgSet);
            // for (Contracts__c con : (List<Contracts__c>)Trigger.new) {
            //     if (accSalesOrgSet != null && accSalesOrgSet.contains(con.Final_Customer__c+'_'+con.Sales_Org__c)) {
            //         con.addError(System.Label.AccFreezeError);
            //     }
            // }
        }
        if(Trigger.isBefore && Trigger.isupdate) {
            Map<Id,Contracts__c> oldMap = (Map<Id,Contracts__c>)Trigger.oldMap;
            User u = [SELECT Id,Profile.Name,Delivery_Plant__c FROM User WHERE Id=:System.UserInfo.getUserId()];
            Profile pro = [SELECT Id FROM Profile WHERE Name='Interface Profile' limit 1];
            for (Contracts__c con : (List<Contracts__c>)Trigger.new) 
            {
                
                if(con.Sync_Status__c=='Synchronized' &&  u.Profile.Name != 'System Administrator' &&  oldMap.get(con.Id).Sync_Status__c==con.Sync_Status__c && system.UserInfo.getProfileId()!=pro.Id) {
                    //con.addError('This contract synced to BPM,can not change');
                    con.addError(System.Label.ContractChangeSyncStatusError);
                }
            }
        }
        if (Trigger.isBefore && (Trigger.isupdate || Trigger.isinsert)) {
            //List<Profile> adminPro = [SELECT Id FROM Profile WHERE Id=:UserInfo.getProfileId() AND  (Name='Interface Profile' OR Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema') limit 1];
            System.debug('进入逻辑');
            Set<String> paymentTermSet = new Set<String>();
            List<Contracts__c> conList = (List<Contracts__c>)Trigger.new;
            for (Contracts__c con : conList) 
            {
                
                if(con.Final_Customer_Payment_Terms__c != null)
                {
                    paymentTermSet.add(con.Final_Customer_Payment_Terms__c);
                }
            }
            System.debug('paymentTermSet'+paymentTermSet);
            Map<String,Payment_Rate__c> paymentRateMap = new Map<String,Payment_Rate__c>();
            for(Payment_Rate__c payRate:[SELECT Id,Name,Payment_Term_Cost_Rate__c,Payment_Term_Cost_Rate_Subsidiary__c  FROM Payment_Rate__c WHERE Name IN:paymentTermSet])
            {
                paymentRateMap.put(payRate.Name,payRate);
            }
            for (Contracts__c con : (List<Contracts__c>)Trigger.new) 
            {
                //if(quote.Sync_Status__c=='Not synchronized')
                //{       
                    if (paymentRateMap.get(con.Final_Customer_Payment_Terms__c) == null) 
                    {
                        //con.addError('Contracts Payment_Term Not Map Payment_Rate__c Data');
                        con.Payment_Term_Cost_Rate__c =1;
                    }
                    else 
                    {
                        con.Payment_Term_Cost_Rate__c = paymentRateMap.get(con.Final_Customer_Payment_Terms__c).Payment_Term_Cost_Rate__c;
                    }
                //}
            }

        }
        if (Trigger.isAfter && Trigger.isinsert) {
            // 共享数据到客户小组
            for (Contracts__c con : (List<Contracts__c>)Trigger.new) {
                ShareDataToAccountTeam.shareData('Contracts__c', con.Id, con.Final_Customer__c, 'Contract__c',con.OwnerId);
            }
        }
        if (Trigger.isAfter && Trigger.isupdate)
        {
            Map<Id,Contracts__c> oldMap = (Map<Id,Contracts__c>)Trigger.oldMap;
            for (Contracts__c con : (List<Contracts__c>)Trigger.new)
            {
                if(oldMap.get(con.Id).CRM_Approval_Status__c != con.CRM_Approval_Status__c && con.CRM_Approval_Status__c=='Approved') {
                   //  DraftContractSyncToBPM.ReturnResult rr = DraftContractSyncToBPM.submitToBPMFu(con.Id);
                   DraftContractSyncToBPM.submitToBPMFu(con.Id);
                   //同步BPM后发送邮件
                //    String body = '<div>'+System.Label.ContractSyncBPMBody+'</div>';
                //    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                //    body = body.replaceAll('【合同编号】', con.Name);
                //    Integer index = String.valueOf(URL.getOrgDomainUrl()).indexof('=')+1;
                //    System.debug('28');
                //    String recordURL = String.valueOf(URL.getOrgDomainUrl()).subString(index);
                //    System.debug('30');
                //    //body = body.replaceAll('【链接】',recordURL.replace(']','')+'/'+con.Id);
                //    email.setHtmlBody(body);
                //    email.setSubject(System.Label.Contract_Sync_BPM+con.Name);
                //    List<String> emailList = new List<String>();
                //    if(con.Sales_Org__c=='3010'){ 
                //     for(String userEmail:System.Label.MXContractSyncNoticeEmail.split(';'))
                //     {if(userEmail != null){emailList.add(userEmail);}
                //     }}
                //    if(con.Sales_Org__c=='5070'){
                //     for(String userEmail:System.Label.ARContractSyncNoticeEmail.split(';'))
                //     {if(userEmail != null){emailList.add(userEmail);}
                //     }}
                //    email.setToAddresses(emailList);
                //    OrgWideEmailAddress[] owea = [select Id,DisplayName from OrgWideEmailAddress];
                //    if (owea.size() > 0 ) {
                //    email.setOrgWideEmailAddressId(owea.get(0).Id);
                // // email.setSenderDisplayName(owea.get(0).DisplayName);
                //   }
                //    email.setUseSignature(false);
                //    email.setBccSender(false);
                //    if(!Test.isRunningTest())Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
                //    System.debug('105');   
                }
                if(oldMap.get(con.Id).Delivery_Plant__c !=con.Delivery_Plant__c) {
                    Database.executeBatch(new ChangeShareDataToAccountTeamBatch('Contracts__c', con.Id, con.Final_Customer__c, 'Contract__c',con.OwnerId,oldMap.get(con.Id).Delivery_Plant__c,'Contracts__share'));
                }
            }
        }
        if (Trigger.isBefore && (Trigger.isInsert || Trigger.isupdate))
        {
            Map<String,Id> codeCountryMap=new Map<String,Id>();
            for(Country_Province_Master_Data__c cpmd:[SELECT Id,Code__c FROM Country_Province_Master_Data__c WHERE RecordType.DeveloperName='Country'])
            {
                codeCountryMap.put(cpmd.Code__c,cpmd.Id);
            }
            system.debug('codeCountryMap=>'+codeCountryMap);
            List<User> userList = [SELECT Id,Country__c FROM User WHERE Id=:System.UserInfo.getUserId()];
            if(userList.size()>0)
            {
                for (Contracts__c con : (List<Contracts__c>)Trigger.new)
                {
                    con.Export_Country__c=codeCountryMap.get(userList[0].Country__c);
                }
            }
            Set<String> mdgCodeSet=new Set<String>();
            string mdgCode;
            for (Contracts__c con : (List<Contracts__c>)Trigger.new)
            {
                if(con.Delivery_Plant__c != null){mdgCode='000000'+con.Delivery_Plant__c;mdgCodeSet.add(mdgCode);}
            }
            System.debug('mdgCodeSet==>'+mdgCodeSet);
            Map<String,Id> codeAccMap=new Map<String,Id>();
            for(Account acc:[SELECT Id,MDG_Customer_Code__c FROM Account WHERE MDG_Customer_Code__c IN:mdgCodeSet])
            {
                codeAccMap.put(acc.MDG_Customer_Code__c,acc.Id);
            }
            System.debug('codeAccMap==>'+codeAccMap);
            for (Contracts__c con : (List<Contracts__c>)Trigger.new)
            {
                if(con.Quote__c == null && con.Delivery_Plant__c != null && codeAccMap.get('000000'+con.Delivery_Plant__c) != null){con.Customer__c=codeAccMap.get(mdgCode);con.Final_Customer__c=con.Customer__c;}
            }
        }
        

    }
}