force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG__c.field-meta.xml
<CustomField>
    <fullName>MDG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MDG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Info__c/Bank_Info__c.object-meta.xml
<CustomObject>
    <label>Bank Info</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Bank Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Info__c/fields/Bank_Key__c.field-meta.xml
<CustomField>
    <fullName>Bank_Key__c</fullName>
    <label>Bank Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Info__c/fields/C_R__c.field-meta.xml
<CustomField>
    <fullName>C_R__c</fullName>
    <label>C/R</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>33</fullName>
                <isActive>false</isActive>
                <label>33</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Info</relationshipLabel>
    <relationshipName>Bank_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Info__c/fields/Valid_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_End_Date__c</fullName>
    <description>有效期结束日期</description>
    <label>Valid End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Info__c/fields/Valid_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_Start_Date__c</fullName>
    <description>有效期开始日期</description>
    <label>Valid Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BankInfoTriggerHandlerTest.cls
@IsTest  
private class BankInfoTriggerHandlerTest {  
    static testMethod void testMock(){
            Account a = new Account();
         
            a.Name = '001D600001n4hjPIAQ';
            a.Group_Name__c = '001D600001n4hjPIAQ';
            a.Customer_Approval_Status__c = 'Approved';
            a.Sync_Status__c = 'Synchronized';
            a.MDG__c = false;
            insert a;

            Bank_Info__c bank1 = new Bank_Info__c();
            //bank1.name= 'BI-000008';
            bank1.Customer__c = a.Id;
            bank1.BANK_KEY__c = '015';
            bank1.Valid_Start_Date__c = Date.valueOf('2024-06-01');
            bank1.Valid_End_Date__c = Date.valueOf('2024-07-01');
            bank1.C_R__c = 'MX';
            insert bank1;

            //bank1.BANK_KEY__c = '016';
            //update bank1;
            //BankInfoTriggerHandler.handle();
        }
}