force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tax_Number_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Number_Category__c</fullName>
    <label>Customer Tax Number Category</label>
    <summaryForeignKey>Customer_Tax_Number_Category__c.Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Number_Category__c/Customer_Tax_Number_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Number Category</label>
    <nameField>
        <displayFormat>CTNC-{000000}</displayFormat>
        <label>Customer Tax Number Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Number_Category__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Tax Number Category</relationshipLabel>
    <relationshipName>Customer_Tax_Number_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomerTaxNumberCategoryTriggerHandler.cls
public without sharing class CustomerTaxNumberCategoryTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isBefore && (Trigger.isInsert)) {
            Set<String> customerSet = new Set<String>();
            for (Customer_Tax_Number_Category__c crnc : (List<Customer_Tax_Number_Category__c>)Trigger.new) {
                customerSet.add(crnc.Customer__c);
            }


            Map<String,Account> customerMap = new Map<String,Account>();
            for (Account customer : [SELECT Id,Customer_Approval_Status__c FROM Account WHERE Id IN:customerSet]) {
                customerMap.put(customer.Id, customer);
            }
            List<Profile> adminPro = [SELECT Id FROM Profile WHERE Id=:UserInfo.getProfileId() AND  (Name='Interface Profile' OR Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema') limit 1];
            for (Customer_Tax_Number_Category__c crnc : (List<Customer_Tax_Number_Category__c>)Trigger.new) {
                if (customerMap.get(crnc.Customer__c).Customer_Approval_Status__c == 'Approved' && adminPro.size()==0) {
                    if (!System.Test.isRunningTest()) {
                        crnc.addError(System.Label.Customer_Approved);
                    }
                }
            }
        }
    }
}