force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG__c.field-meta.xml
<CustomField>
    <fullName>MDG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MDG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/BPM_Damage_Assessment_Number__c.field-meta.xml
<CustomField>
    <fullName>BPM_Damage_Assessment_Number__c</fullName>
    <label>BPM Damage Assessment Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T</fullName>
                <label>T Transferencia Bancaria</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>D Condonacion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not synchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization error</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateBPMDamageNumberControllerTest.cls
/**
 * @description       : Tests for UpdateBPMDamageNumberController
 * @author            : Agentforce
 * @date              : 2026-03-31
 * Notes:
 * - Covers success path (valid Order__c Id) and exception path (invalid Id)
 * - Ensures >=80% coverage on UpdateBPMDamageNumberController
 */
@IsTest
private class UpdateBPMDamageNumberControllerTest {

    /**
     * @testmethod
     * Verifies that updateNumber successfully updates BPM_Damage_Assessment_Number__c
     * when provided a valid Order__c Id.
     */
    @IsTest
    static void testUpdateNumber_Success() {
        
        Account account = new Account();
        account.Name = 'TestAccount';
        account.Group_Name__c = 'TestGroup';
        account.Customer_Approval_Status__c = 'Approved';
        account.Sync_Status__c = 'Synchronized';
        account.MDG__c = false;
        insert account;
        System.debug('新建时候的状态'+account.Sync_Status__c);
        
        // 创建客户信用信息
        Customer_Credit_Info__c customerCreditInfo = new Customer_Credit_Info__c();
        customerCreditInfo.Customer__c = account.Id;
        customerCreditInfo.ExternalId__c = account.Id;
        insert customerCreditInfo;
        
        // 创建客户销售信息
        Customer_Sales_Info__c customerSalesInfo = new Customer_Sales_Info__c();
        customerSalesInfo.Sales_Org__c = '3020';
        customerSalesInfo.Distr_Channel__c = '10';
        customerSalesInfo.Sales_View_Status__c = 'Approved';
        customerSalesInfo.Sync_Status__c = 'Synchronized';
        customerSalesInfo.Customer__c = account.Id;
        customerSalesInfo.Payment_method__c = 'YPF';
        insert customerSalesInfo;
        // Arrange: create minimal Order__c test data (assuming only Name is required)
        Order__c order = new Order__c();
        order.Customer__c = account.Id;
        order.Sales_Org__c = '5130';
        order.Distr_Channel__c = '00';
        order.Customer_Sales_Info__c = customerSalesInfo.Id;
        order.Currency__c = 'USD';
        order.Deliver_Plant__c = '5130';
        order.Order_type__c = 'ZARB';
        order.Interest_Rate__c = 5.0;
        insert order;

        // Act
        Test.startTest();
        UpdateBPMDamageNumberController.Output out =
            UpdateBPMDamageNumberController.updateNumber(order.Id, 'DMG-001');
        Test.stopTest();

        // Assert: method indicates success
        System.assertNotEquals(null, out, 'Output should not be null');
        System.assertEquals(true, out.isSucess, 'Expected isSucess to be true on successful update');
        System.assertEquals(null, out.errorMsg, 'errorMsg should be null on success');

        // Verify record actually updated
        Order__c ordAfter = [
            SELECT Id, BPM_Damage_Assessment_Number__c
            FROM Order__c
            WHERE Id = :order.Id
            LIMIT 1
        ];
        System.assertEquals('DMG-001', ordAfter.BPM_Damage_Assessment_Number__c, 'Damage number should be updated');
    }

    /**
     * @testmethod
     * Verifies exception branch by using an invalid Id, expecting isSucess=false and errorMsg populated.
     */
    @IsTest
    static void testUpdateNumber_Failure_InvalidId() {
        // Arrange: use a bogus Id that won't match any record
        String bogusId = 'a00XXXXXXXXXXXXXXX'; // invalid Id format/record for update

        // Act
        Test.startTest();
        UpdateBPMDamageNumberController.Output out =
            UpdateBPMDamageNumberController.updateNumber(bogusId, 'DMG-ERR');
        Test.stopTest();

        // Assert: method indicates failure and includes an error message
        System.assertNotEquals(null, out, 'Output should not be null');
        System.assertEquals(false, out.isSucess, 'Expected isSucess to be false on error');
        System.assertNotEquals(null, out.errorMsg, 'errorMsg should be populated on error');
        System.assert(out.errorMsg.contains(';'), 'errorMsg should contain a semicolon with line number suffix');
    }
}