force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Details__c/Collection_Details__c.object-meta.xml
<CustomObject>
    <label>Collection Details</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Collection Details Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SAPCollectionWebServiceTest.cls
@isTest
private class SAPCollectionWebServiceTest {
    static testMethod void testMethod1() {
        // 创建账户
        Account a = new Account();
        a.Name = 'Test111';
        a.Group_Name__c = 'test111';  
        a.MDG_Customer_Code__c = '123';
        a.Customer_Approval_Status__c = 'Approved';
        a.Sync_Status__c = 'Synchronized';
        Insert a;



        // 创建并填充请求体
        List<SAPCollectionWebService.ReqOrderInfo> rbList = new List<SAPCollectionWebService.ReqOrderInfo>();
        SAPCollectionWebService.ReqOrderInfo rb = new SAPCollectionWebService.ReqOrderInfo();
        rb.KUNNR = '123'; // 客户编码
        rb.BUKRS = '5130'; // 公司代码
        rb.GJAHR = '2023'; // 会计年度
        rb.BELNR = '123456'; // 会计凭证
        rb.BUZEI = '10'; // 凭证行号
        rb.H_BLART = 'AA'; // 凭证类型
        rb.H_WAERS = 'EUR'; // 凭证货币
        rb.RFCCUR = 'EUR'; // 本位币
        rb.KURSF = '1.0'; // 汇率
        rb.H_BUDAT = '2024-06-07'; // 过账日期
        rb.SHKZG = 'H'; // 借贷方
        rb.WRBTR = '1000'; // 凭证货币金额
        rb.DMBTR = '1000'; // 本位币金额
        rb.PRCTR = 'P123'; // 利润中心
        rb.HKONT = '1000'; // 会计科目
        rbList.add(rb);


        SAPCollectionWebService.ReqESInfo esbInfo = new SAPCollectionWebService.ReqESInfo();
        esbInfo.instid = '123456';
        esbInfo.requesttime = DateTime.now().format('yyyyMMddHHmmss'); // 请求时间

        SAPCollectionWebService.RequestBody requestBody = new SAPCollectionWebService.RequestBody();
        requestBody.esbinfo = esbInfo;
        requestBody.resultinfo = rbList;

        String requestContent = JSON.serialize(requestBody);

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/SAPCollectionWebService';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(requestContent);
        RestContext.request = request;
        Test.startTest();
        SAPCollectionWebService.doPost();
        Test.stopTest();

        List<Collection_Details__c> collectionDetails = [SELECT External_Id__c FROM Collection_Details__c WHERE External_Id__c = '5130202312345610'];//
        //System.assertEquals(1, collectionDetails.size(), 'error');
        if (collectionDetails.isEmpty()) {
            System.debug('No records found with External_Id__c = 5130202312345610');
        } else {
            System.debug('Found records: ' + collectionDetails);
        }
    }
}