force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <defaultValue>$User.Distr_Channel_Text__c</defaultValue>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <formula>Tax_Category_Master_Data__r.Country_District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country/District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Category Master Data</label>
    <referenceTo>Tax_Category_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <formula>Tax_Category_Master_Data__r.Tax_Category_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Category Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Type__c</fullName>
    <label>Tax Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/Tax_Category_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Tax Category Master Data</label>
    <nameField>
        <label>Tax Category Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Country_District__c.field-meta.xml
<CustomField>
    <fullName>Country_District__c</fullName>
    <label>Country/District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/fields/Tax_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Name__c</fullName>
    <label>Tax Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>J1AU</fullName>
        <label>J1AU IVA Ventas</label>
    </customValue>
    <customValue>
        <fullName>J1A1</fullName>
        <label>J1A1 Perc. IIBB CABA</label>
    </customValue>
    <customValue>
        <fullName>J1A2</fullName>
        <label>J1A2 Perc. IIBB ARBA</label>
    </customValue>
    <customValue>
        <fullName>J1A3</fullName>
        <label>J1A3 Perc. IIBB EntreRios</label>
    </customValue>
    <customValue>
        <fullName>J1A4</fullName>
        <label>J1A4 Perc. IIBB Santa Fe</label>
    </customValue>
    <customValue>
        <fullName>J1A5</fullName>
        <label>J1A5 Perc. IIBB Córdoba</label>
    </customValue>
    <customValue>
        <fullName>J1A6</fullName>
        <label>J1A6 Perc. IIBB Salta</label>
    </customValue>
    <customValue>
        <fullName>J1A7</fullName>
        <label>J1A7 Perc. IIBB Tucumán</label>
    </customValue>
    <customValue>
        <fullName>J1A8</fullName>
        <label>J1A8 Perc. IIBB Otras</label>
    </customValue>
    <customValue>
        <fullName>MWST</fullName>
        <label>MWST IVA repercutido</label>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
        <label>MX01 I.E.P.S. (MEXICO)</label>
    </customValue>
    <masterLabel>Tax Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeCustomerSalesInfoLWCControllerTest.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 07-31-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   07-31-2025   Gerry   Initial Version
**/
@isTest
private class ChangeCustomerSalesInfoLWCControllerTest {
    static testMethod void testMethod1() {
        Account a = new Account();
        a.Name = 'Test';
        a.Group_Name__c = 'test';
        a.Customer_Approval_Status__c = 'Approved';
        a.Sync_Status__c = 'Synchronized';
        a.MDG_Customer_Code__c = '1234';
        Insert a;
        Customer_Credit_Info__c cci = new Customer_Credit_Info__c();
        cci.Customer__c = a.Id;
        cci.ExternalId__c = a.Id;
        insert cci;
        Customer_Sales_Info__c csi = new Customer_Sales_Info__c();
        csi.Sales_Org__c = '3010';
        csi.Delivering_Plant__c = '3010';
        csi.Distr_Channel__c = '10';
        csi.Sales_View_Status__c = 'Approved';
        csi.Customer__c = a.Id;
        csi.Acct_Assmt_Grp_Cust__c='02';
        insert csi;
        Tax_Category_Master_Data__c tcmd = new Tax_Category_Master_Data__c();
        tcmd.Country_Code__c = '11';
        tcmd.Country_District__c = '11';
        tcmd.Name = '11';
        tcmd.Tax_Category_Name__c = '11';
        insert tcmd;
        Customer_Tax_Category__c ctc = new Customer_Tax_Category__c();
        ctc.Tax_Category_Type__c = 'J1AU';
        ctc.Tax_Category__c = '1-Responsable IVA';
        ctc.Tax_Category_Master_Data__c = tcmd.Id;
        ctc.Sales_View__c = csi.Id;
        insert ctc;
        ChangeCustomerSalesInfoLWCController.changeData(csi.Id);
    }
}