force-app/main/default/objects/Account/fields/Customer_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SynchronizedMDG</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG__c.field-meta.xml
<CustomField>
    <fullName>MDG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MDG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Account_Share__c.field-meta.xml
<CustomField>
    <fullName>Account_Share__c</fullName>
    <label>Account/Contact Share</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeleteShare__c/DeleteShare__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DeleteShare</label>
</CustomObject>

force-app/main/default/objects/DeleteShare__c/fields/SQL__c.field-meta.xml
<CustomField>
    <fullName>SQL__c</fullName>
    <label>SQL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShareDataQuery__c/ShareDataQuery__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ShareDataQuery</label>
</CustomObject>

force-app/main/default/objects/ShareDataQuery__c/fields/Sql__c.field-meta.xml
<CustomField>
    <fullName>Sql__c</fullName>
    <label>Sql</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Share.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Share</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShareAccountDataBatchtest.cls
@IsTest 
public with sharing class ShareAccountDataBatchtest {
    static testMethod void testMock(){
        Account acc = new Account();
        acc.Name = 'test acc';
        acc.Group_Name__c = '001D600001n4hjPIAQ';
        acc.Customer_Approval_Status__c = 'Approved';
        acc.Sync_Status__c = 'Synchronized';
        acc.MDG__c = false;
        insert acc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'testuserbisfc@testorg.com';
        u.Alias = 'newUser';
        u.Email='testuserbisfc@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;
        Account_Team__c at = new Account_Team__c();
        at.Customer__c = acc.Id;
        at.Sales_Rep__c = u.Id;
        insert at;
        at.Account_Share__c = 'read';
        update at;
        DeleteShare__c sd = new DeleteShare__c();
        sd.Name = 'Account';
        sd.Index__c  =1;
        sd.Sql__c = 'SELECT Id FROM AccountShare WHERE AccountId=:recordId AND UserOrGroupId=:userId AND Account.OwnerId !=:userId';
        insert sd;
        delete at;
    }

    static testMethod void testMock1(){
        Account acc = new Account();
        acc.Name = 'test acc';
        acc.Group_Name__c = '001D600001n4hjPIAQ';
        acc.Customer_Approval_Status__c = 'Approved';
        acc.Sync_Status__c = 'Synchronized';
        acc.MDG__c = false;
        insert acc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'testuserbisfc@testorg.com';
        u.Alias = 'newUser';
        u.Email='testuserbisfc@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;
        Account_Team__c at = new Account_Team__c();
        at.Customer__c = acc.Id;
        at.Sales_Rep__c = u.Id;
        insert at;
        ShareDataQuery__c sdq = new ShareDataQuery__c();
        sdq.Name = '1';
        sdq.Sql__c = 'SELECT Id,OwnerId FROM Account WHERE Id=:recordId';
        sdq.Object__c = 'Account';
        sdq.Field__c = 'Account_Share__c';
        sdq.Index__c = 1;
        insert sdq;
        Database.executeBatch(new ShareAccountDataBatch(at.Id,at.Customer__c,1), 100);
    }

    static testMethod void testMock2(){
        Account acc = new Account();
        acc.Name = 'test acc';
        acc.Group_Name__c = '001D600001n4hjPIAQ';
        acc.Customer_Approval_Status__c = 'Approved';
        acc.Sync_Status__c = 'Synchronized';
        acc.MDG__c = false;
        insert acc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'testuserbisfc@testorg.com';
        u.Alias = 'newUser';
        u.Email='testuserbisfc@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;
        Account_Team__c at = new Account_Team__c();
        at.Customer__c = acc.Id;
        at.Sales_Rep__c = u.Id;
        insert at;
        ShareDataQuery__c sdq = new ShareDataQuery__c();
        sdq.Name = '1';
        sdq.Sql__c = 'SELECT Id,OwnerId FROM Account WHERE Id=:recordId';
        sdq.Object__c = 'Account';
        sdq.Field__c = 'Account_Share__c';
        sdq.Index__c = 1;
        insert sdq;
        // Database.executeBatch(new ShareAccountDataBatch(at.Id,at.Customer__c,1), 100);
        AccountShare as1 = new AccountShare();
        as1.AccountId = acc.Id;
        as1.AccountAccessLevel = 'read';
        as1.OpportunityAccessLevel = 'None';
        as1.UserOrGroupId = u.Id;
        as1.RowCause = 'Manual';
        insert as1;
        Test.startTest();
        DeleteShare__c sd = new DeleteShare__c();
        sd.Name = 'Account';
        sd.Index__c  =1;
        sd.Sql__c = 'SELECT Id FROM AccountShare WHERE AccountId=:recordId AND UserOrGroupId=:userId AND Account.OwnerId !=:userId';
        insert sd;
        delete at;
        Test.stopTest();
    }
}