force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Legal Person Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Shipping_Address__c/Customer_Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Shipping Address</label>
    <nameField>
        <displayFormat>CSA-{000000}</displayFormat>
        <label>Customer Shipping Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Shipping_Address__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Shipping Addresses</relationshipLabel>
    <relationshipName>Customer_Shipping_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Shipping_Address__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <description>详细地址</description>
    <label>Detailed Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>CASESAFEID( Order__r.Customer__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Note_Item_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Item_Num__c</fullName>
    <label>SAP Delivery Note Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Note_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Num__c</fullName>
    <label>SAP Delivery Note Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Delivery Quantity(Order Unit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Is_Note__c.field-meta.xml
<CustomField>
    <fullName>Is_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Already Sent Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>Customer_Shipping_Address__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Customer_Shipping_Address__c.Status__c</field>
            <operation>equals</operation>
            <value>Enable</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Shipping_Address__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Receiver Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Order Item Delivered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Depend_On_Item__c.field-meta.xml
<CustomField>
    <fullName>Depend_On_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fill up Consignment Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Issue Consignment)</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit_Text__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit_Text__c</fullName>
    <label>Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendEmailDeliveryOrder.cls
/**************************************************************************************************
 * Name: SendEmailOrder
 * Object: 
 * Purpose: 发送发货单邮件功能类
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-08-14         Created             
***************************************************************************************************/
public without sharing class SendEmailDeliveryOrder {
    public static void sendEmail(List<Delivery_Note__c> dnList) {
        // List<Delivery_Note__c> dnList = [SELECT Order__r.Name,Order__r.Email__c,Delivery_Quantity__c,Id,Order__r.Customer__r.Name,Order__r.Customer_Shipping_Address__r.Direction__c,Delivery_Note_Num__c,Delivery_Note_Item_Num__c,Order_Item__r.Commodity__r.Name,Order_Item__r.Sales_Unit_Text__c,Order_Item__r.Material_Number__c FROM Delivery_Note__c WHERE Order__c =:orderId AND Is_Note__c=false AND (Delivery_Post_Status__c='C' OR Delivery_Post_Status__c='B')];
        if (dnList[0].Order__r.Email__c == null) {
            return;
        }
        Map<String,List<Delivery_Note__c>> dnMap = new Map<String,List<Delivery_Note__c>>();
        for (Delivery_Note__c dn : dnList) { 
            if (dnMap.containskey(dn.Delivery_Note_Num__c)) {
                dnMap.get(dn.Delivery_Note_Num__c).add(dn);
            }else{
                dnMap.put(dn.Delivery_Note_Num__c,new List<Delivery_Note__c>{dn});
            }
        }
        System.debug('dnMap'+dnMap);
        List<String> emailList = new List<String>();
        emailList.addall(dnList[0].Order__r.Email__c.split(';'));
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress];
        if (owea.size() > 0 ) {
             email.setOrgWideEmailAddressId(owea.get(0).Id);
        }
        email.setToAddresses(emailList);//set mail getter
        email.setSubject('['+dnList[0].Order__r.Name+']Delivery Note'); //set subject
        String body = 'Hola,<br/>';
        body += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The following Porducts are on the way sending to you.<br/>';
        body += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;EMPRESA:&nbsp;&nbsp;'+dnList[0].Order__r.Customer__r.Name+'<br/>';
        body += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DIRECCION:&nbsp;&nbsp;'+dnList[0].Order__r.Customer_Shipping_Address__r.Direction__c+'<br/>';
        body += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DELIVERY ORDER:&nbsp;&nbsp;';
        String num = '';
        for (String key : dnMap.keySet()) {
            if (String.isNotBlank(num)) {
                num += ','+key;
            }else{
                num += key;
            }
        }
        System.debug('num'+num);
        body += num+'<br/><br/>';
        
        for (String key : dnMap.keySet()) {
            body += key+':<br/>';
            body += '<table  Class="typeface " width="100%" style="border-right: 1px solid #000000; border-bottom: 1px solid #000000;">';
            body += '<tr style="text-align: center;">';
                        body += '<th width="5%">No.</th>';
                        body += '<th width="20%">MATERIAL</th>';
                        body += '<th width="20%">DESCRIPCIÓN DE PRODUCTO</th>';
                        body += '<th width="10%">CANTIDAD</th>';
                        body += '<th width="10%">UNIDAD</th>';
            body += '</tr>';
            for (Delivery_Note__c dn : dnMap.get(key)) {
                System.debug('进入逻辑');
                body += '<tr>';
                body += '<td width="5%" align="center">'+dn.Delivery_Note_Item_Num__c+'</td>';
                if (!System.Test.isRunningTest()) {
                    body += '<td width="20%" align="center">'+dn.Order_Item__r.Material_Number__c.subString(6)+'</td>';
                }
                body += '<td width="20%" align="center">'+dn.Order_Item__r.Commodity__r.Name+'</td>';
                body += '<td width="10%" align="center">'+dn.Delivery_Quantity__c+'</td>';
                body += '<td width="10%" align="center">'+dn.Order_Item__r.Sales_Unit_Text__c+'</td>';
                body += '</tr>';
            }
            body += '</table><br/><br/>';
        }
            
        
        System.debug('body'+body);
        email.setHtmlBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                email
        });
        for (Delivery_Note__c dn : dnList) {
            dn.Is_Note__c = true;
        }
        Database.update(dnList);
    }
}