force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Legal Person Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sales_View_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_View_Status__c</fullName>
    <label>Sales View Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SyncFailed</fullName>
                <isActive>false</isActive>
                <label>SyncFailed</label>
            </value>
            <value>
                <fullName>SynchronizedSAP</fullName>
                <isActive>false</isActive>
                <label>SynchronizedSAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>CASESAFEID( Order__r.Customer__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Estimated_invoicing_date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_invoicing_date__c</fullName>
    <formula>Delivery_Post_Date__c + VALUE(TEXT(Order__r.Stock_Aging_Limit__c)) +2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated invoicing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Remain_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remain_Quantity__c</fullName>
    <formula>Delivery_Quantity__c  -  Issue_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remain Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Receiver Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Depend_On_Item__c.field-meta.xml
<CustomField>
    <fullName>Depend_On_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fill up Consignment Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Issue Consignment)</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Remain_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remain_Quantity__c</fullName>
    <formula>IF(ISBLANK( Issue_Quantity__c ),Delivery_Quantity__c,Delivery_Quantity__c - Issue_Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Order Item Delivered Quantity - ZARB Used Quantity</inlineHelpText>
    <label>ZARB Remain Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailInventoryBatch.cls
/**
 * @description       : 发送寄售库存至客户邮箱:展示客户+产品+产品名+ 寄售数量+预计开票日
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 09-12-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   09-12-2025   Gerry   Initial Version
**/
global without sharing class EmailInventoryBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    public String query;
    
    global Boolean flag;
    global String errorMsg;
    global Datetime startTime;
    global EmailInventoryBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT Id,Customer__r.Email__c FROM Customer_Sales_Info__c WHERE Sales_Org__c=\'5130\' AND Sales_View_Status__c=\'Approved\'';
    }

    global void execute(SchedulableContext sc) {
        EmailInventoryBatch svo = new EmailInventoryBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 5);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Customer_Sales_Info__c> csiList) {
        try {
            //销售视图Id
            Set<String> csiIdList = new Set<String>();

            for (Customer_Sales_Info__c csi : csiList) {
                csiIdList.add(csi.Id);
            }

            //客户+产品+产品名+预计开票日------>寄售数量
            Map<String,Decimal> remainMap = new Map<String,Decimal>();

            //客户ID
            Set<String> accIdList = new Set<String>();
            for (AggregateResult agg1 : [
                                        SELECT 
                                            SUM(Remain_Quantity__c) remain,
                                            Order__r.Customer__c acc,
                                            Order_Item__r.Commodity__r.Name productName,
                                            Order_Item__r.Commodity__r.Product_Sales_Info__r.Product__r.Name productCode,
                                            Estimated_invoicing_date__c eidate
                                        FROM 
                                            Delivery_Note__c
                                        WHERE 
                                            Order__r.Customer_Sales_Info__c IN:csiIdList AND 
                                            Delivery_Post_Status__c ='C' AND 
                                            Order__r.Order_type__c = 'ZARB' AND  
                                            Order__r.Sales_Org__c = '5130' AND 
                                            // Auto_Issue_Consignment__c=false AND
                                            Remain_Quantity__c >0 AND
                                            Estimated_invoicing_date__c !=null
                                            Group by Order__r.Customer__c,Order_Item__r.Commodity__r.Name,Order_Item__r.Commodity__r.Product_Sales_Info__r.Product__r.Name,Estimated_invoicing_date__c
                                            order by Estimated_invoicing_date__c

            ]) {
                remainMap.put((String)agg1.get('acc')+'_'+(String)agg1.get('productCode')+'_'+(String)agg1.get('productName')+'_'+String.valueOf(agg1.get('eidate')), (Decimal)agg1.get('remain'));
                accIdList.add((String)agg1.get('acc'));
            }

            Map<String,Account> accMap = new Map<String,Account>();
            for (Account acc : [SELECT Id,Email__c,Name FROM Account WHERE Id IN:accIdList]) {
                accMap.put(acc.Id,acc);
            }
            List<String> thHeadList = new List<String> {System.Label.CustomerName,System.Label.ProductCode,System.Label.ProductName,System.Label.RemainQuantity,System.Label.EstimatedInvoicingDate};
            if(remainMap.size()>0){

                //客户---->所有产品剩余数量
                Map<String,Utility.Table> currTableMap = new Map<String,Utility.Table>();

                
                for(String key : remainMap.keySet()){
                    List<String> keyList = key.split('_');
                    // 构建邮件表格的tr td内容
                    Utility.TableTr tableTr = new Utility.TableTr();
                    tableTr.tdMap.put(System.Label.CustomerName,new Utility.TableTd(accMap.get(keyList[0]).Name));
                    tableTr.tdMap.put(System.Label.ProductCode,new Utility.TableTd(keyList[1]));
                    tableTr.tdMap.put(System.Label.ProductName,new Utility.TableTd(keyList[2]));
                    tableTr.tdMap.put(System.Label.RemainQuantity,new Utility.TableTd(String.valueOf(remainMap.get(key))));
                    tableTr.tdMap.put(System.Label.EstimatedInvoicingDate,new Utility.TableTd(keyList[3]));
                    if (currTableMap.containsKey(keyList[0])) {
                        currTableMap.get(keyList[0]).tbody.trs.add(tableTr);
                    }else{
                       
                        Utility.Table currTable = BatchSendEmailToOrder.getDefaultTable(thHeadList);
                        currTable.tbody.trs.add(tableTr);
                        currTableMap.put(keyList[0],currTable);
                    }
                    
                }
                List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
                if (currTableMap.size()>0) {

                    //汇总客户对应的产品信息到一个邮件中
                    for (String key : currTableMap.keySet()) {
                        List<String> emailList = new List<String>();
                        emailList.add(accMap.get(key).Email__c);
                        String body = Utility.getEmailTableHTML(currTableMap.get(key), thHeadList);
                        Messaging.SingleEmailMessage email = Utility.getSingleEmailMessage(System.Label.CQN,emailList, body,null,null);
                        emails.add(email);
                    }
                }

                if (emails.size()>0) {
                    Messaging.sendEmail(emails);
                }
            }
            
            
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('EmailInventoryBatch', this.flag, this.startTime, this.errorMsg);
    }
}