force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Legal Person Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Auto_Issue_Consignment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Issue_Consignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Issue Consignment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>CASESAFEID( Order__r.Customer__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Days_after_delivery__c.field-meta.xml
<CustomField>
    <fullName>Days_after_delivery__c</fullName>
    <formula>TODAY() -  Delivery_Post_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days After Delivery</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT( Order__r.Order_type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Remain_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remain_Quantity__c</fullName>
    <formula>Delivery_Quantity__c  -  Issue_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remain Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Stock_Aging_Countdown__c.field-meta.xml
<CustomField>
    <fullName>Stock_Aging_Countdown__c</fullName>
    <formula>IF(
ISBLANK( Delivery_Post_Date__c ),
NULL,
IF(
TODAY() - (Delivery_Post_Date__c + 2) &lt;= 0  &amp;&amp; ISPICKVAL(Delivery_Post_Status__c  , &apos;C&apos;) ,
  VALUE( TEXT(Order__r.Stock_Aging_Limit__c) ) ,
VALUE( TEXT(Order__r.Stock_Aging_Limit__c) )- (TODAY() - (Delivery_Post_Date__c + 2))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Order&apos;s Stock Aging Limit - (TODAY - (Delivery Post Date + 2))</inlineHelpText>
    <label>Stock Aging Countdown(days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Auto_Issue_Consignment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Issue_Consignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Issue Consignment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Receiver Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Stock_Aging_Limit__c.field-meta.xml
<CustomField>
    <fullName>Stock_Aging_Limit__c</fullName>
    <label>Stock Aging Limit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Model_C.recordType-meta.xml
<RecordType>
    <fullName>Model_C</fullName>
    <active>true</active>
    <label>Model C</label>
</RecordType>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Auto_Issue_Consignment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Issue_Consignment__c</fullName>
    <formula>Order__r.Auto_Issue_Consignment__c</formula>
    <label>*Auto-Issue Consignment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Depend_On_Item__c.field-meta.xml
<CustomField>
    <fullName>Depend_On_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fill up Consignment Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Issue Consignment)</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Remain_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remain_Quantity__c</fullName>
    <formula>IF(ISBLANK( Issue_Quantity__c ),Delivery_Quantity__c,Delivery_Quantity__c - Issue_Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Order Item Delivered Quantity - ZARB Used Quantity</inlineHelpText>
    <label>ZARB Remain Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchNotifyStockAging.cls
/**************************************************************************************************
 * Name: BatchSendEmailToOrder
 * Object: Delivery_Note__c
 * Purpose: ZARB订单需要在每月20号凌晨自动向客户的owner发送邮件通知，通知用户目前的库存为多少
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE            DETAIL             Description
 * 1.0          zach            2025-07-08        Created			    
***************************************************************************************************/
global without sharing class BatchNotifyStockAging implements Database.Batchable<sObject>,Schedulable,Database.Stateful {
    public Set<String> zarbIdSet = new Set<String>();
    public String errorMsg;
    public Datetime startTime;
    public Boolean flag = TRUE;
    
    global BatchNotifyStockAging(){
        
    }
    
    global BatchNotifyStockAging(Set<String> zarbIdSet){
        this.zarbIdSet = zarbIdSet;
    }
    
	global Database.QueryLocator start(Database.BatchableContext bc){
        startTime = System.now();
        Decimal daysNotify5130 = Decimal.valueOf(System.Label.daysNotify5130);
        String sql;
        if(!System.Test.isRunningTest()){
             sql = 'SELECT Id,Order_Item__c,Remain_Quantity__c,Order__c,Order__r.Customer__r.Email__c,Order__r.Customer__r.Name,Order__r.Stock_Aging_Limit__c,Delivery_Post_Date__c,Stock_Aging_Countdown__c,Order__r.Sales_Org__c,Order__r.Customer__r.Owner.Email,' + 
            		'Order_Item__r.Commodity__c,Order_Item__r.Commodity__r.Name,Auto_issue_Consignment__c FROM Delivery_Note__c WHERE Order__r.Order_type__c = \'ZARB\' AND Order__r.Sales_Org__c = \'5130\' ' + 
            		'AND Order__r.RecordType.DeveloperName = \'Model_C\' AND Order__r.Customer__r.Email__c !=NULL AND Days_after_delivery__c >= :daysNotify5130';
        }else{
             sql = 'SELECT Id,Order_Item__c,Remain_Quantity__c,Order__c,Order__r.Customer__r.Email__c,Order__r.Customer__r.Name,Order__r.Stock_Aging_Limit__c,Delivery_Post_Date__c,Stock_Aging_Countdown__c,Order__r.Sales_Org__c,Order__r.Customer__r.Owner.Email,' + 
            		'Order_Item__r.Commodity__c,Order_Item__r.Commodity__r.Name,Auto_issue_Consignment__c FROM Delivery_Note__c WHERE Order__r.Order_type__c = \'ZARB\' AND Order__r.Sales_Org__c = \'5130\' ' + 
            		'AND Order__r.RecordType.DeveloperName = \'Model_C\' AND Order__r.Customer__r.Email__c !=NULL';
        }
        
        system.debug(zarbIdSet);
        if(zarbIdSet != NULL && !zarbIdSet.isEmpty()){
            sql += ' AND Order__c IN:zarbIdSet';
        }
        return Database.getQueryLocator(sql);  
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchNotifyStockAging());
    }
    
    global void execute(Database.BatchableContext BC,List<Delivery_Note__c> itemList){
        system.debug('itemList===='+itemList);
        try{
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            Map<Id,Delivery_Note__c> noteMap = new Map<Id,Delivery_Note__c>(itemList);
            
            //product name
            Set<String> proIdSet = new Set<String>();
            for(Delivery_Note__c item : itemList){
                if(item.Remain_Quantity__c > 0){
                    proIdSet.add(item.Order_Item__r.Commodity__c);
                }
            }
            
            //获取产品名称
            Map<String,List<String>> proNameMap = BatchSendEmailToOrder.getProductName(proIdSet);
            system.debug('proNameMap===='+proNameMap);
            
            for(Delivery_Note__c item : itemList){
                if(item.Remain_Quantity__c > 0){
                    //新建自定义邮件
                    emails.add(BatchSendEmailToOrder.getOrderEmail(item,proNameMap));
                }
                
            }
            //发送邮件
            system.debug(emails);
            Messaging.sendEmail(emails);
        }catch (Exception e) {
            flag = FALSE;
            errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }
    
    global void finish(Database.BatchableContext bc) {
		Utility.setBatchInfo('BatchNotifyStockAging', flag, startTime, errorMsg);
    }
}