force-app/main/default/objects/Account/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract_Processing_Product__c/Contract_Processing_Product__c.object-meta.xml
<CustomObject>
    <label>Tolling Product List</label>
    <nameField>
        <label>Tolling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tolling Product List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DataImportTemplate__c/DataImportTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DataImportTemplate</label>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/ImportDataFieldConf__c.object-meta.xml
<CustomObject>
    <label>Import Data Field Configuration</label>
    <nameField>
        <label>Import Data Field Configuration Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportDataFieldConf__c/fields/Obj_Name__c.field-meta.xml
<CustomField>
    <fullName>Obj_Name__c</fullName>
    <label>Obj Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/FOB_Price__c.field-meta.xml
<CustomField>
    <fullName>FOB_Price__c</fullName>
    <label>FOB Bulking Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>material code + sales org + distribution channel + factory</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchImportQuoteDetailControllerTest.cls
@isTest
public with sharing class BatchImportQuoteDetailControllerTest {
    static testMethod void testMethod1() {
        ContentVersion contentVersion = new ContentVersion(
                    Title = 'Penguins',
                    PathOnClient = 'Penguins.jpg',
                    VersionData = Blob.valueOf('Test Content'),
                    IsMajorVersion = true
            );
        insert contentVersion;
        ContentVersion c = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];
        ContentDistribution cdl = new ContentDistribution();
        cdl.ContentVersionId = contentVersion.Id;
        cdl.Name = 'PublicShare';
        cdl.PreferencesAllowViewInBrowser = true;
        cdl.PreferencesLinkLatestVersion = true;
        cdl.PreferencesNotifyOnVisit = false;
        cdl.PreferencesPasswordRequired = false;
        cdl.PreferencesAllowOriginalDownload = true;
        cdl.PreferencesNotifyRndtnComplete = false;
        insert cdl;

        Quote__c quote1 = new Quote__c();
        quote1.Quotation_Type__c = 'HQ_Purchase';
        insert quote1;


        DataImportTemplate__c dit1 = new DataImportTemplate__c();
        dit1.Name = 'Quote_Detail';
        dit1.FileId__c = c.Id;
        insert dit1;
        
        ImportDataFieldConf__c dataConf=new ImportDataFieldConf__c();
        dataConf.RecordType__c='Tolling;';
        dataConf.Obj_Name__c='Quote_Detail';
        insert dataConf;


        BatchImportQuoteDetailController.getInitData(quote1.Id);
        quote1.Sales_Org__c='3010';
        update quote1;
        BatchImportQuoteDetailController.getInitData(quote1.Id);
    }

    static testMethod void testMethod2() {
        Account acc = new Account();
        acc.Name = 'test';
        acc.Group_Name__c = 'test';
        acc.MDG_Customer_Code__c = '0001006790';
        insert acc;

        Product__c p = new Product__c();
        p.Name = '12341234';
        p.External_Id__c = '12341234';
        insert p;

        Product_Sales_Info__c psi = new Product_Sales_Info__c();
        psi.Product__c = p.Id;
        insert psi;

        Product_Name__c pn = new Product_Name__c();
        pn.Name = 'test';
        pn.Product_Sales_Info__c = psi.Id;
        insert pn;

        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'bisfnewuser@testorg.com';
        u.Alias = 'newUser';
        u.Email='bisfnewuser@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;

        Price_List__c priceList=new Price_List__c();
        priceList.Name='test';
        insert priceList;

        Quote__c quote1 = new Quote__c();
        quote1.Quotation_Type__c = 'HQ_Purchase';
        insert quote1;

        String json ='[{"Order_Qnty__c":"10","CIF_90_Days__c":"100","FOB_Price__c":"20","Unit__c":"L","Price_List__c":"test"}]';
        Map<String,String> strMap = new Map<String,String>();
        strMap.put('Order_Qnty__c','Order Qnty');
        strMap.put('CIF_90_Days__c','Quote Price');
        strMap.put('FOB_Price__c','FOB Bulking Price');
        strMap.put('Unit__c','Unit');
        strMap.put('Price_List__c','Quote English Name');
       
        List<String> mustFillValueFields = new List<String>();
        mustFillValueFields.add('Order_Qnty__c');
        BatchImportQuoteDetailController.saveData(json,strMap,mustFillValueFields,quote1.Id);
    }
    static testMethod void testMethod3() {
        Account acc = new Account();
        acc.Name = 'test';
        acc.Group_Name__c = 'test';
        acc.MDG_Customer_Code__c = '0001006790';
        insert acc;

        Product__c p = new Product__c();
        p.Name = '12341234';
        p.External_Id__c = '12341234';
        insert p;

        Product_Sales_Info__c psi = new Product_Sales_Info__c();
        psi.Product__c = p.Id;
        insert psi;

        Product_Name__c pn = new Product_Name__c();
        pn.Name = 'test';
        pn.Product_Sales_Info__c = psi.Id;
        insert pn;

        Profile prof = [SELECT Id FROM Profile WHERE Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema' LIMIT 1]; 
        User u = new User();
        u.LastName = 'test';
        u.Username = 'bisfnewuser@testorg.com';
        u.Alias = 'newUser';
        u.Email='bisfnewuser@testorg.com';
        u.EmailEncodingKey='UTF-8';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = prof.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        insert u;

        Price_List__c priceList=new Price_List__c();
        priceList.Name='test';
        insert priceList;
        
        Contract_Processing_Product__c cpp=new Contract_Processing_Product__c();
        cpp.Name='test';
        insert cpp;

        Quote__c quote1 = new Quote__c();
        quote1.Sales_Org__c='5070';
        quote1.Deliver_Plant__c = '5070';
        quote1.Quotation_Type__c = 'Tolling';
        insert quote1;

        String json ='[{"Order_Qnty__c":"10","CIF_90_Days__c":"100","FOB_Price__c":"20","Unit__c":"L","Contract_Processing_Product__c":"test"}]';
        Map<String,String> strMap = new Map<String,String>();
        strMap.put('Order_Qnty__c','Order Qnty');
        strMap.put('CIF_90_Days__c','Quote Price');
        strMap.put('FOB_Price__c','FOB Bulking Price');
        strMap.put('Unit__c','Unit');
        strMap.put('Contract_Processing_Product__c','Tolling Product');
       
        List<String> mustFillValueFields = new List<String>();
        mustFillValueFields.add('Order_Qnty__c');
        BatchImportQuoteDetailController.saveData(json,strMap,mustFillValueFields,quote1.Id);
        json ='[{"Order_Qnty__c":"10","CIF_90_Days__c":"100","FOB_Price__c":"20","Unit__c":"L","Contract_Processing_Product__c":""}]';
        BatchImportQuoteDetailController.saveData(json,strMap,mustFillValueFields,quote1.Id);
        json ='[{"Order_Qnty__c":"10","CIF_90_Days__c":"100","FOB_Price__c":20,"Unit__c":"L","Contract_Processing_Product__c":""}]';
        BatchImportQuoteDetailController.saveData(json,strMap,mustFillValueFields,quote1.Id);
       
    }
}