force-app/main/default/objects/Account/fields/HQ_Email__c.field-meta.xml
<CustomField>
    <fullName>HQ_Email__c</fullName>
    <label>HQ Contract Receiver Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/CRM_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Approval_Status__c</fullName>
    <label>CRM Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Final_Customer__c.field-meta.xml
<CustomField>
    <fullName>Final_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts_Final_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>BPM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
                <label>Approving</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/Contracts_Detail__c.object-meta.xml
<CustomObject>
    <label>Contracts Detail</label>
    <nameField>
        <displayFormat>CD-{YYMM}-{000000}</displayFormat>
        <label>Contracts Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts_Detail__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <label>Contracts</label>
    <referenceTo>Contracts__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Code</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubmitContractController.cls
/**************************************************************************************************
 * Name: CloneOrderController
 * Object: 
 * Purpose: 合同提交
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-10-12         Created             
***************************************************************************************************/
public without sharing class SubmitContractController {
    @AuraEnabled
    public static Output submitContract(String conRecordId) {
        try {
            Contracts__c con = [SELECT Final_Customer__r.HQ_Email__c,Id,Name,Sales_Org__c,CRM_Approval_Status__c,Status__c,Final_Customer__c,Final_Customer__r.Name,RecordType.DeveloperName,(SELECT Id,Product__c FROM Contracts_Detail__r) FROM Contracts__c WHERE Id=:conRecordId]; 
            if (con.CRM_Approval_Status__c !='Approved' || con.Status__c!='Draft') {
                Output out = new Output();
                out.isSucess = false;
                //out.errorMsg = 'Can not submit this contract';
                out.errorMsg =System.Label.SubmitContractStatusError;
                return out;
            }
            for(Contracts_Detail__c cd:con.Contracts_Detail__r)
            {
                if(cd.Product__c==null){
                    Output out = new Output();out.isSucess = false; out.errorMsg = System.Label.SupplementaryProductCode;return out;
                }
            }
            DraftContractSyncToBPM.ReturnResult rr = DraftContractSyncToBPM.submitToBPM(conRecordId,true);
            // //同步BPM后发送邮件
            // String body = '<div>'+System.Label.ContractSyncBPMBody+'</div>';
            // Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            // body = body.replaceAll('【合同编号】', con.Name);
            // Integer index = String.valueOf(URL.getOrgDomainUrl()).indexof('=')+1;
            // System.debug('28');
            // String recordURL = String.valueOf(URL.getOrgDomainUrl()).subString(index);
            // System.debug('30');
            // //body = body.replaceAll('【链接】',recordURL.replace(']','')+'/'+con.Id);
            // email.setHtmlBody(body);
            // //email.setSubject(System.Label.Contract_Sync_BPM+con.Name);
            // email.setSubject('New Contract '+con.Final_Customer__r.Name+' '+con.Name);
            // List<String> emailList = new List<String>();
            // if(con.Sales_Org__c=='3010'){ 
            //     for(String userEmail:System.Label.MXContractSyncNoticeEmail.split(';'))
            //         {if(userEmail != null){emailList.add(userEmail);}
            //         }}
            // if(con.Sales_Org__c=='5070'){
            //     if(String.isBlank(con.Final_Customer__r.HQ_Email__c)) {
            //         for(String userEmail:System.Label.ARContractSyncNoticeEmail.split(';')){
            //             if(userEmail != null){emailList.add(userEmail);}
            //         }
            //     }else{
            //          for(String userEmail:con.Final_Customer__r.HQ_Email__c.split(';')){
            //             if(userEmail != null){emailList.add(userEmail);}
            //         }
            //     }
            // }  
            // email.setToAddresses(emailList);
            // OrgWideEmailAddress[] owea = [select Id,DisplayName from OrgWideEmailAddress];
            // if (owea.size() > 0 ) {
            //     email.setOrgWideEmailAddressId(owea.get(0).Id);
            //     // email.setSenderDisplayName(owea.get(0).DisplayName);
            // }
            // email.setUseSignature(false);
            // email.setBccSender(false);
            // if(!Test.isRunningTest())Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
            System.debug('49');
            Output out = new Output();
            out.isSucess = rr.isSuccess;
            out.errorMsg = rr.message;
            return out;
        } catch (Exception e) {
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = e.getMessage()+'Line:'+e.getLineNumber();
            return out;
        }
        
    }

    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}
    }

}