force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Actual_Credit_limit__c.field-meta.xml
<CustomField>
    <fullName>Actual_Credit_limit__c</fullName>
    <label>Customer Credit Line (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Credit_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Actual_available_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Actual_available_Credit_Limit__c</fullName>
    <label>Actual Available Credit Limit (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Locked_in_SAP__c.field-meta.xml
<CustomField>
    <fullName>Locked_in_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Locked in SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Max_Overdue_Days__c.field-meta.xml
<CustomField>
    <fullName>Max_Overdue_Days__c</fullName>
    <label>Max Overdue Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <formula>Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MDG Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_USD__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_USD__c</fullName>
    <formula>Total_Amount__c  /  Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Overdue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Overdue_Amount__c</fullName>
    <label>Overdue Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <inlineHelpText>USD To Order Currency</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>SAP_Credit_Limit__c</fullName>
    <label>SAP Available Credit Limit (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Order Amount</label>
    <summarizedField>Order_Item__c.Actual_Order_Item_Amount_w_o_tax__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Ultra_Credit__c.field-meta.xml
<CustomField>
    <fullName>Ultra_Credit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Excess Credit Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Amount_per_item__c.field-meta.xml
<CustomField>
    <fullName>Amount_per_item__c</fullName>
    <label>Order Item Amount(w/o tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/New_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Amount__c</fullName>
    <label>New Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/New_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Delivery_Date__c</fullName>
    <label>New Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/New_Price__c.field-meta.xml
<CustomField>
    <fullName>New_Price__c</fullName>
    <label>New Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/New_Quantity__c.field-meta.xml
<CustomField>
    <fullName>New_Quantity__c</fullName>
    <label>New Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Order Item Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit_Text__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit_Text__c</fullName>
    <label>Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Item_Num__c.field-meta.xml
<CustomField>
    <fullName>SAP_Item_Num__c</fullName>
    <label>SAP Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubmitOrderApprovalController.cls
/**************************************************************************************************
 * Name: SubmitOrderApprovalController
 * Object: 
 * Purpose: Mode1 B订单提交审批
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0           noel            2024-10-28         Created             
***************************************************************************************************/
public without sharing class SubmitOrderApprovalController {

    @AuraEnabled
    public static Output sumbitApproval(String orderId,String commentString) {
        system.debug('orderId:'+orderId);
        system.debug('commentString:'+commentString);
        Order__c order = [SELECT Sales_Org__c,Order_Amount_USD__c,Customer__c,Name,Id,Order_type__c,SAP_Order_Code__c,Locked_in_SAP__c,Status__c,Customer__r.MDG_Customer_Code__c,Currency__c FROM Order__c WHERE Id=:orderId];
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        try {
            GetCustomerlimitFROMSAP.RespCustomerInfo rcinfo;
            if (!System.Test.isRunningTest()) {
                rcinfo = GetCustomerlimitFROMSAP.submitToSAP(new List<String>{order.Customer__r.MDG_Customer_Code__c},order.Currency__c,order.Sales_Org__c);
            }else{
                rcinfo = new GetCustomerlimitFROMSAP.RespCustomerInfo();
                rcinfo.exch_rate = '1';
                rcinfo.amount = 10;
                rcinfo.ZOVDAYS = '0';
            }
            if (rcinfo==null || System.Test.isRunningTest()) {
                // Output out = new Output();
                out.isSucess = false;
                out.errorMsg = 'System error';
                if (!System.Test.isRunningTest()) {
                    return out;
                }
                
            }
            if (rcinfo.msgty == 'E' || System.Test.isRunningTest()) {
                // Output out = new Output();
                out.isSucess = false;
                out.errorMsg = rcinfo.msgtx;
                if (!System.Test.isRunningTest()) {
                    return out;
                }
            }
            Order__c orderUpdate = new Order__c();
            orderUpdate.Id = order.Id;
            if (String.isNotBlank(rcinfo.zsfyq)) {
                orderUpdate.Overdue__c = true;
            }else{
                orderUpdate.Overdue__c = false;
            }
            orderUpdate.SAP_Credit_Limit__c = rcinfo.amount;
            Decimal ZARFNum = 0;
            //统计实际可用额度
            for (AggregateResult agg : [
                                        SELECT 
                                            SUM(Order_Amount_USD__c) usedNum
                                        FROM 
                                            Order__c 
                                        WHERE 
                                            Customer__c=:order.Customer__c
                                            AND Status__c='approving' 
                                            Group by Customer__c
            ]) {
                ZARFNum = (Decimal)agg.get('usedNum');
            }
            orderUpdate.Rate__c = Decimal.valueOf(rcinfo.exch_rate);
            Order__c o = [SELECT recordType.DeveloperName,Total_Amount__c,Customer__c FROM Order__c WHERE Id=:orderId];
            Map<String,Decimal> accCreditInfoMap = new Map<String,Decimal>();
            for (Customer_Credit_Info__c cci : [SELECT Id,Customer__c,Actual_Credit_limit__c FROM Customer_Credit_Info__c WHERE Customer__c=:o.Customer__c]) {
                accCreditInfoMap.put(cci.Customer__c,cci.Actual_Credit_limit__c);
            }
            orderUpdate.Customer_Credit_Line__c=accCreditInfoMap.get(o.Customer__c);
            orderUpdate.Actual_available_Credit_Limit__c = orderUpdate.SAP_Credit_Limit__c-ZARFNum;
            if(order.Order_Amount_USD__c>orderUpdate.Actual_available_Credit_Limit__c) {
                orderUpdate.Ultra_Credit__c = true;
            }else{
                orderUpdate.Ultra_Credit__c = false;
            }
            orderUpdate.Max_Overdue_Days__c = Decimal.valueOf(rcinfo.ZOVDAYS);
            if (String.isNotBlank(rcinfo.zovdmtr)) {
                orderUpdate.Overdue_Amount__c = Decimal.valueOf(rcinfo.zovdmtr);
            }
            if(!Test.isRunningTest()){update orderUpdate;}
            
            // List<Order_Item__c> orderDetailList = [
            //     SELECT 
            //     Id, Order__c,SAP_Item_Num__c,Product__c,Commodity__c,Sales_Unit_Text__c,Price__c ,New_Price__c,Quantity__c ,New_Quantity__c,New_Amount__c,Amount_per_item__c,Delivery_Date__c,New_Delivery_Date__c
            //     FROM 
            //     Order_Item__c 
            //     WHERE Order__c   =: orderId AND isClosed__c=false];
            
            // String orderItemIds=''; 
            // for(Order_Item__c oi:orderDetailList)
            // {
            //     orderItemIds=orderItemIds+oi.Id+';';
            // }
            // System.debug('orderItemIds=>'+orderItemIds);
            // OrderSyncToSAP.ReturnResult returnResult=new OrderSyncToSAP.ReturnResult();
            // Boolean isClose;
            // if(order.Status__c != 'Approved') {
            //     isClose = true;
            // }else{
            //     isClose = false;
            // }
            // String re = '';
            // if (isClose) {
            //     re = System.Label.Reason;
            // }
            // if (order.SAP_Order_Code__c!=null)
            // {
            //     ReturnResult=OrderSyncToSAP.submitToSAP(orderId, 'U',isClose,!isClose,re,orderItemIds,false,false);
            // }
            // else
            // {
            //     ReturnResult=OrderSyncToSAP.submitToSAP(orderId, 'I',isClose,!isClose,re,orderItemIds,false,false);
            // }
            
            // if(!ReturnResult.isSuccess) {
            //     out.isSucess = false;
            //     out.errorMsg = ReturnResult.message;
            //     return out;
            // }
            
            Approval.ProcessSubmitRequest psr = new Approval.ProcessSubmitRequest();
            psr.objectId = orderId;//对象Id
            psr.setSubmitterId(UserInfo.getUserId());//提交人
            psr.comments = commentString;//备注
            if (!Test.isRunningTest())
            {
                Approval.ProcessResult result = Approval.process(psr);
                out.isSucess=result.isSuccess();
                out.errorMsg=String.valueOf(result.getErrors());
                system.debug('result=>'+result);
            }
            // if(order.Status__c != 'Approved') {
            //     Order__c orderUpdate = new Order__c();
            //     orderUpdate.Id = order.Id;
            //     orderUpdate.Locked_in_SAP__c = true;
            //     update orderUpdate;
            // }
        } catch (Exception e) {out.isSucess = false;out.errorMsg = e.getMessage()+';'+e.getLineNumber(); return out;}
        return out; 
    }

    @AuraEnabled
    public static Output init(String orderId) {
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        try{
            for(Order_Item__c oi : [SELECT Id,Commodity__c FROM Order_Item__c WHERE Order__c=:orderId AND isClosed__c = false]) {
                if(oi.Commodity__c == null){out.isSucess = false; out.errorMsg = System.Label.notifacationBody;     return out;}
            }
            //ZAR2提交处理---start
            SubmitOrderController.Output outInvoice = SubmitOrderController.invoice(orderId);
            if (outInvoice.isSucess == false) {
                out.isSucess = false;
                out.errorMsg = outInvoice.errorMsg;
                return out;
            }
            //ZAR2提交处理---end
        } catch (Exception e) {out.isSucess = false;out.errorMsg = e.getMessage()+';'+e.getLineNumber();}
        return out;
    }

    
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

       
    }

}