force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Can_Submit__c.field-meta.xml
<CustomField>
    <fullName>Can_Submit__c</fullName>
    <formula>CustomerTaxCategoryNumber__c = ActivityCustomerTaxCategoryNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Can Submit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/isSync__c.field-meta.xml
<CustomField>
    <fullName>isSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CloneShipToAccountCustomer.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 12-25-2025
 * @last modified by  : Gerry 
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   12-25-2025   Gerry   Initial Version
**/
public without sharing class CloneShipToAccountCustomer {
    @AuraEnabled
    public static Output confirmClone(String recordId){
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        Savepoint sp = Database.setSavepoint();
        try {
            ObjectClone.ResponseParam rp = ObjectClone.cloneObjectSingle(recordId, true, null,'Customer_Sales_Info__c',System.Label.CloneSaleInfoRemoveField);
            if (rp.code) {
                Map<Id, Id> oldToNewIdMap = rp.oldIdToNewId;
                System.debug(oldToNewIdMap);
                if (oldToNewIdMap != null && oldToNewIdMap.get(recordId) != null) {
                    out.returnUrl = new PageReference('/' + oldToNewIdMap.get(recordId)).getUrl();
                }
            } else {
                Database.rollback(sp); out.isSucess = false; out.errorMsg = rp.message;
            }

        } catch (Exception e) {
            Database.rollback(sp); out.isSucess = false; out.errorMsg = e.getMessage();
        }

        return out;
    }
    @AuraEnabled
    public static Output init(String recordId){
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        
        try {
            List<Customer_Sales_Info__c> csiList=[SELECT Id,Can_Submit__c,Customer__c,Customer__r.MDG_Customer_Code__c,isSync__c FROM Customer_Sales_Info__c WHERE Customer__c =:recordId AND (Sales_Org__c='5130' OR Sales_Org__c='5070')];
            for(Customer_Sales_Info__c csi:csiList){
                if(!csi.Can_Submit__c){
                    out.isSucess = false; out.errorMsg = System.Label.CopyCustomerVertifySumbit;return out;
                }
            }
        } catch (Exception e) {
             out.isSucess = false; out.errorMsg = e.getMessage();
        }

        return out;
    }
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public String returnUrl {get;set;}

       
    }
}