force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Credit_Info__c/Customer_Credit_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Info</label>
    <nameField>
        <displayFormat>CCI-{000000}</displayFormat>
        <label>Customer Credit Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Credit_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/isSync__c.field-meta.xml
<CustomField>
    <fullName>isSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsynchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization Failure</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <formula>Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MDG Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not synchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization error</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReSyncDataController.cls
/**************************************************************************************************
 * Name: ReSyncDataController
 * Object: 
 * Purpose: 重新推送数据
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-11         Created             
***************************************************************************************************/
public without sharing class ReSyncDataController {
    @AuraEnabled
    public static Output reSyncDataMe(String recordId) {
        Id recordId1 = Id.valueOf(recordId);
        String type = recordId1.getSObjectType().getDescribe().getName();
        if (type == 'Account') {
            Account acc = [SELECT Id,MDG_Customer_Code__c,Sync_Status__c FROM Account WHERE Id=:recordId];
            if (acc.Sync_Status__c != 'Synchronization Failure') {
                return new Output(false,'can not resync data');
            }
            CustomerInfoSyncToSAP.ReturnResult rr;
            if (acc.MDG_Customer_Code__c == null) {
                rr = CustomerInfoSyncToSAP.submitToSAP(recordId, 'I');
            }else{
                rr = CustomerInfoSyncToSAP.submitToSAP(recordId, 'U');
            }
            if (rr.isSuccess) {
                return new Output(true,'Success');
            }else{
                return new Output(false,rr.message);
            }
        }

        if (type == 'Customer_Sales_Info__c') {
            Customer_Sales_Info__c acc = [SELECT Id,isSync__c FROM Customer_Sales_Info__c WHERE Id=:recordId];
            CustomerSalesInfoSyncToSAP.ReturnResult rr;
            if (!acc.isSync__c) {
                rr = CustomerSalesInfoSyncToSAP.submitToSAP(recordId, 'I');
            }else{
                rr = CustomerSalesInfoSyncToSAP.submitToSAP(recordId, 'U');
            }
            if (rr.isSuccess) {
                return new Output(true,'Success');
            }else{
                return new Output(false,rr.message);
            }
        }

        if (type == 'Customer_Credit_Info__c') {
            CustomerlimitSyncToSAP.ReturnResult rr = CustomerlimitSyncToSAP.submitToSAP(recordId);
            if (rr.isSuccess) {
                return new Output(true,'Success');
            }else{
                return new Output(false,rr.message);
            }
        }

        if (type == 'Order__c') {
            List<Order_Item__c> oiList = [SELECT Id FROM Order_Item__c WHERE Order__c=:recordId AND isClosed__c=false];
            String orderItemId;
            for(Order_Item__c oi : oiList) {
                if(String.isNotBlank(orderItemId)) {
                    orderItemId += ';'+oi.Id;
                }else{
                    orderItemId = oi.Id;
                }
            }
            OrderSyncToSAP.ReturnResult rr = OrderSyncToSAP.submitToSAP(recordId, 'I',false,false,'',orderItemId,false,false);
            if (rr.isSuccess) {
                return new Output(true,'Success');
            }else{
                return new Output(false,rr.message);
            }
        }

        return null;
    }

    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        Output(Boolean isSucess, String errorMsg) {
            
            this.isSucess = isSucess;
            this.errorMsg = errorMsg;
        }
    } 
}