force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Shipping_Address__c/Customer_Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Shipping Address</label>
    <nameField>
        <displayFormat>CSA-{000000}</displayFormat>
        <label>Customer Shipping Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Shipping_Address__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Shipping Addresses</relationshipLabel>
    <relationshipName>Customer_Shipping_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Shipping_Address__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <description>详细地址</description>
    <label>Detailed Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Approve_Date__c.field-meta.xml
<CustomField>
    <fullName>Approve_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CreatedDate_Text__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate_Text__c</fullName>
    <formula>TEXT(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Cust_Reference__c.field-meta.xml
<CustomField>
    <fullName>Cust_Reference__c</fullName>
    <label>Customer&apos;s PO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>Customer_Shipping_Address__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Customer_Shipping_Address__c.Status__c</field>
            <operation>equals</operation>
            <value>Enable</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Shipping_Address__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deliver_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Incoterms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <formula>Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MDG Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shipping_Address_Text__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Text__c</fullName>
    <formula>IF(OR(ISNULL(Customer_Shipping_Address__c),ISBLANK(Customer_Shipping_Address__c)),Ship_To__r.Shipping_Address__c,Customer_Shipping_Address__r.Direction__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Address Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Order Amount</label>
    <summarizedField>Order_Item__c.Actual_Order_Item_Amount_w_o_tax__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Tax__c</fullName>
    <formula>Total_Tax__c + Total_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax__c</fullName>
    <label>Total Tax</label>
    <summarizedField>Order_Item__c.SAP_Total_Tax__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Amount_per_item__c.field-meta.xml
<CustomField>
    <fullName>Amount_per_item__c</fullName>
    <label>Order Item Amount(w/o tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Date_Text__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Text__c</fullName>
    <formula>TEXT(Delivery_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Date Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit_Text__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit_Text__c</fullName>
    <label>Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>SAP_Total_Tax__c</fullName>
    <label>SAP Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDF__c/PDF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PDF</label>
</CustomObject>

force-app/main/default/objects/PDF__c/fields/Adress__c.field-meta.xml
<CustomField>
    <fullName>Adress__c</fullName>
    <label>Adress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDF__c/fields/logo__c.field-meta.xml
<CustomField>
    <fullName>logo__c</fullName>
    <label>logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PDF__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>PBI-{000000}</displayFormat>
        <label>Price Book Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Item__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Product_Name__r.Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP Carriage and insurance paid to</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAF</fullName>
        <label>DAF Delivered at frontier</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP Delivered at place</label>
    </customValue>
    <customValue>
        <fullName>DAT</fullName>
        <label>DAT Delivered at terminal</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DDU</fullName>
        <label>DDU Delivered Duty Unpaid</label>
    </customValue>
    <customValue>
        <fullName>DEQ</fullName>
        <label>DEQ Delivered ex quay (duty paid)</label>
    </customValue>
    <customValue>
        <fullName>DES</fullName>
        <label>DES Delivered ex ship</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS Free Alongside Ship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FH</fullName>
        <label>FH Free house</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB Free on board</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UN Not Free</label>
    </customValue>
    <description>国际贸易条款</description>
    <masterLabel>Incoterms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendEmailOrder.cls
/**************************************************************************************************
 * Name: SendEmailOrder
 * Object: 
 * Purpose: 发送订单邮件功能类
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-08-14         Created             
***************************************************************************************************/
public without sharing class SendEmailOrder {
    public final Order__c order {get;set;} 
    public final List<Order_Item__c> orderItem {get;set;}
    public final String imageUrl {get;set;} 
    public final String companyName {get;set;} 
    public final String companyAddress {get;set;} 
    public final String INCOTERM {get;set;} 
    public final List<String> specialClause {get;set;} 
    public final String tax {get;set;} 
    public final String PDFRight {get;set;} 
    public final String PDFLeft {get;set;} 
    public SendEmailOrder() {
        
        specialClause = System.Label.Special_Clause.split(';');
        if (System.Test.isRunningTest()) {
            order = [
                    SELECT 
                        CreatedDate_Text__c,Remark__c,Total_Tax__c,Total_Amount_Tax__c,
                        Sales_Org__c,
                        Total_Amount__c,
                        Customer__r.Name,
                        Name,
                        Approve_Date__c,
                        Customer__r.MDG_Customer_Code__c,
                        Customer__r.Tax_Number__c,
                        Customer_Shipping_Address__r.Direction__c,Deliver_Plant__c,
                        Inco_Location1__c,Incoterms__c,Cust_Reference__c,Currency__c,Terms_Of_Payment__c,CreatedDate 
                    FROM 
                        Order__c
                ];
        }else{
            order = [
                    SELECT 
                        CreatedDate_Text__c,Remark__c,Total_Tax__c,Total_Amount_Tax__c,
                        Sales_Org__c,
                        Total_Amount__c,
                        Customer__r.Name,
                        Name,
                        Approve_Date__c,
                        Customer__r.MDG_Customer_Code__c,
                        Customer__r.Tax_Number__c,
                        Customer_Shipping_Address__r.Direction__c,Deliver_Plant__c,
                        Shipping_Address_Text__c,Inco_Location1__c,Incoterms__c,Cust_Reference__c,Currency__c,Terms_Of_Payment__c,CreatedDate 
                    FROM 
                        Order__c
                    WHERE Id = :ApexPages.currentPage().getParameters().get('id')
                ];
        }
        
        order.Remark__c = spliteStringToList(order.Remark__c);
        PDF__c pdf;
        Boolean flag = false;
        if (order.Sales_Org__c == '3010' && order.Deliver_Plant__c == '3011') {
            pdf = PDF__c.getValues('3010');
            flag = true;
        }
        if (order.Sales_Org__c == '3020' && order.Deliver_Plant__c == '3020') {
            pdf = PDF__c.getValues('3020');
            flag = true;
        }
        if (order.Sales_Org__c == '5130' && order.Deliver_Plant__c == '5130') {
            pdf = PDF__c.getValues('5130');
            flag = true;
        }

        String first = order.Incoterms__c==null?'':order.Incoterms__c;
        INCOTERM = first+','+order.Inco_Location1__c==null?'':order.Inco_Location1__c;
        if(flag) {
            companyName = pdf.Company_Name__c;
            imageUrl = pdf.logo__c;
            companyAddress = pdf.Adress__c;
            tax = pdf.Tax__c;
        }
        
        PDFRight = System.Label.PDFRight;
        PDFLeft = System.Label.PDFLeft;
        orderItem = [SELECT Name,Id,Amount_per_item__c,SAP_Total_Tax__c,Sales_Unit_Text__c,Delivery_Date_Text__c,
                            Commodity__c,
                            Delivery_Date__c,
                            Material_Number__c,
                            Price__c,
                            Quantity__c,
                            Sales_Unit__c,
                            Commodity__r.Product__r.Name,
                            Order__r.Currency__c,
                            SAP_Item_Num__c,
                            Basic_Number__c,
                            Material_Description__c,
                            Price_Book_Item__c,
                            Crop__c,
                            Product_Usage__c,
                            Depend_On_Item__c,
                            Guide_Price__c,
                            Price_Rate_User__c FROM Order_Item__c
                   WHERE Order__c = :ApexPages.currentPage().getParameters().get('id')];
        for (Order_Item__c oi : orderItem) {
            oi.Material_Number__c = oi.Material_Number__c.subString(6);
        }
    }

    @Future(callout=true)
    public static void sendem(String orderId) {
        Order__c order = [SELECT Id,Name,User_Country__c,Email__c,Owner.Email,Sales_Org__c,Deliver_Plant__c  FROM Order__c WHERE Id=:orderId];
        //Model B订单直接返回 不发送PDF start
        if (order.Sales_Org__c == '5070' && order.Deliver_Plant__c == '5070') {
            return;
        }
        if (order.Sales_Org__c == '3010' && order.Deliver_Plant__c == '3010') {
            return;
        }
        //Model B订单直接返回 不发送PDF end
        
        // if (order.Email__c == null) {
        //     return;
        // }
        // List<String> emailList = new List<String>();
        // emailList.addall(order.Email__c.split(';'));
        List<String> emailCCList = new List<String>{order.Owner.Email};
        
        // Define the email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 

        // Reference the attachment page and pass in the account ID
        PageReference pdf;
        pdf =  Page.attachmentPDFMX;
        
        
        pdf.getParameters().put('id',orderId); 
        pdf.setRedirect(true);

        // Take the PDF content
        Blob b;
        if (!System.Test.isRunningTest()) {
             b = pdf.getContent();
        }
       

        // Create the email attachment
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(order.Name+'Order.pdf');
        if (!System.Test.isRunningTest()) {
            efa.setBody(b);
        }

        email.setPlainTextBody(System.Label.EmailBody);
        email.setSubject(order.Name+System.Label.EmailSubject);
        // email.setToAddresses(emailList);
        email.setToAddresses(emailCCList);
        // email.setCcAddresses(emailCCList);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        // OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'rb@crm.com'];
        // Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        // if ( owea.size() > 0 ) {
        //     email.setOrgWideEmailAddressId(owea.get(0).Id);
        // }
        // Sends the email
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress];
        if (owea.size() > 0 ) {
            email.setOrgWideEmailAddressId(owea.get(0).Id);
        }
        if (!System.Test.isRunningTest()) {
            Messaging.SendEmailResult [] r = 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
        }
        
		System.debug('已经发送邮件');
        // return null;
    }

    /*自动换行控制*/
    public String spliteStringToList(String s){
        // s = s.trim();
        // 
        String res = '';
        if (s == null) {
            
            return '';
        }

        // s = s.replaceAll(' ', '');
        for(Integer i=0;i<s.length();i++){
            if (String.isBlank(res)) {
                res+= s.Substring(i,i+1);
            }else{
                res+= '<wbr/>'+s.Substring(i,i+1);
            }
        }
        return res;
    }
}