force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <externalId>true</externalId>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/Account_Receivable__c.object-meta.xml
<CustomObject>
    <label>Account Receivable</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Receivable Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Receivable__c/fields/Amount_in_Local_Crcy__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_Local_Crcy__c</fullName>
    <label>Amount (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Amount_in_Trans_Crcy__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_Trans_Crcy__c</fullName>
    <label>Amount (Transaction Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Baseline_Date__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Date__c</fullName>
    <label>Baseline Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Receivable</relationshipLabel>
    <relationshipName>Account_Receivable1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Account Receivable</relationshipLabel>
    <relationshipName>Account_Receivable1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Debit_Credit__c.field-meta.xml
<CustomField>
    <fullName>Debit_Credit__c</fullName>
    <label>Debit/Credit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Debit_Credit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Document_Currency__c.field-meta.xml
<CustomField>
    <fullName>Document_Currency__c</fullName>
    <label>Document Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Due_On__c.field-meta.xml
<CustomField>
    <fullName>Due_On__c</fullName>
    <label>Due On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Account Receivable</relationshipLabel>
    <relationshipName>Account_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Overdue_Days__c.field-meta.xml
<CustomField>
    <fullName>Overdue_Days__c</fullName>
    <label>(Deprecated) Overdue Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <label>Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profit_Center</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Sales_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type__c</fullName>
    <label>Sales Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Receivable__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Debit_Credit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>H</fullName>
        <label>H：Credit</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>S：Debit</label>
    </customValue>
    <masterLabel>Debit Credit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Profit_Center.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3010010101</fullName>
        <label>3010010101 MODEL B</label>
    </customValue>
    <customValue>
        <fullName>3010020101</fullName>
        <label>3010020101 MODEL C+</label>
    </customValue>
    <customValue>
        <fullName>DUMMY</fullName>
    </customValue>
    <masterLabel>Profit Center</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPReceivableWebService.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 03-31-2026
 * @last modified by  : Gerry 
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   03-31-2026   Gerry   Initial Version
**/
@RestResource(urlMapping='/SAPReceivableWebService')
global without sharing class SAPReceivableWebService {
    public class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqOrderInfo> resultinfo;
    }
    public class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
    }
    public class ReqOrderInfo{
        public String KUNNR; //客户编码
        public String BUKRS; //公司代码
        public String GJAHR; //会计年度
        public String BELNR; //会计凭证
        public String BUZEI; //凭证行号
        public String H_BLART; //凭证类型
        public String H_WAERS; //凭证货币
        public String RFCCUR; //本位币
        public String KURSF; //汇率
        public String H_BUDAT; //过账日期
        public String SHKZG; //借贷方
        public String WRBTR; //凭证货币金额
        public String DMBTR; //本位币金额
        public String ZFBDT; //付款基准日期
        public String ZTERM; //付款条件
        public String NETDT; //到期日期
        public String ZYQTS; //逾期天数
        public String ZUONR; //发票号
        public String PRCTR; //利润中心
        public String HKONT; //会计科目
        public String VBELV; //销售订单
        public String AUART; //销售订单类型
        public String VKORG; //销售组织
    }
    global class ResponseBody {
        public RespESInfo esbinfo;
        public RespCustomerInfo resultinfo;
    }
    
    global class RespCustomerInfo{
        public String msgty;//处理状态
        public String msgtx;//错误信息
        public List<ReturnData> returnDataList;
    }
    
    global class ReturnData {
        public String bukrs;//公司代码
        public String gjahr;//会计年度
        public String belnr;//会计凭证
        public String buzei;//凭证行号
        public String msgty;//消息类型
        public String msgtx;//消息文本
    }
    
    global class RespESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
        public String responsetime;//返回时间
        public String returnstatus;//接口状态
        public String returncode;//接口状态码
        public String returnmsg;//接口消息
        public String attr1;//预留字段
        public String attr2;//预留字段
        public String attr3;//预留字段
    }
    public class Output {
        public String error;
        public Boolean isSuccess;
        public Boolean isPartSuccess;
        public List<ReturnData> ReturnDataList;
    }
    /**
     * SAP 应收账款同步接口
     * @param bodyStrJson bodyStrJson
     *
     * @return ResponseBody
     */
    @HttpPost
    global static ResponseBody doPost() {
        String respTime = String.valueOf(Datetime.now());
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String bodyStrJson = req.requestBody.toString();
        List<String> dataIdList = new List<String>();
        Boolean isSuccess = true;
        Boolean isPartSuccess = false;
        Savepoint sp = Database.setSavepoint();
        String errorMsg;
        List<ReturnData> returnDataList = new List<ReturnData>();
        try {
            System.debug('bodyStrJson1==' + bodyStrJson);
            RequestBody reqBody = (RequestBody) JSON.deserialize(bodyStrJson, RequestBody.class);
            Output out = feedbackOrderInfo(reqBody.resultinfo);
            isSuccess = out.isSuccess;
            isPartSuccess = out.isPartSuccess;
            errorMsg = out.error;
            returnDataList = out.ReturnDataList;
        } catch (Exception e) {
            Database.rollback(sp);
            errorMsg = InterfaceUtility.getProperErrorMessage(e.getMessage()) + '[' + e.getLineNumber() + ']';
            isSuccess = false;
            isPartSuccess = false;
        }
        ResponseBody response = returnData(respTime, isSuccess, errorMsg, returnDataList);
        InterfaceUtility.insertInterfaceLog('SAPReceivableWebService', 'SAP', 'CRM',
        '/services/apexrest/receiveD ataFromExternal/  requestCode:SAP001', bodyStrJson, isSuccess, isPartSuccess,
        JSON.serialize(response), errorMsg, 'POST', dataIdList, 'Upsert', 'SAP同步应收账款至CRM'
            );
        return response;
    }
    public static Output feedbackOrderInfo(List<ReqOrderInfo> resultinfo) { //返回
        List<Account_Receivable__C> AccountReceivableList = new List<Account_Receivable__C>();
        Map<Integer,Account_Receivable__C> AccountReceivableMap = new Map<Integer,Account_Receivable__C>();
        Output out = new Output();
        out.ReturnDataList = new List<ReturnData>();
        ReturnData returnDataMsgTmp;
        Boolean isPartSuccess = false;
        Integer accountReceivableIndex = 0;
        Set<String> customerIdSet = new Set<String>();
        Map<String,String> customeMap = new Map<String,String>();
        Set<String> salesOrgSet = new Set<String>();
        Account_Receivable__C accountReceivableMapResult;
        ReturnData returnDataMsg;
        for (ReqOrderInfo reqOrder : resultinfo) {
            customerIdSet.add(reqOrder.KUNNR);
            salesOrgSet.add(reqOrder.BUKRS);
        }
        List<Account> accList = [
            SELECT          
                ID,MDG_Customer_Code__c
                FROM Account
            WHERE  MDG_Customer_Code__c IN: customerIdSet];
        if (accList.size()>0) {
            for(Account acc : accList){
                customeMap.put(acc.MDG_Customer_Code__c,acc.Id);
            }
        }
        Map<String,String> salesInfoMap = new Map<String,String>();
        Map<String,Customer_Sales_Info__c> csiMap = new Map<String,Customer_Sales_Info__c>();
        for (Customer_Sales_Info__c csi : [
                                            SELECT 
                                                Id ,
                                                Customer__r.MDG_Customer_Code__c,
                                                Sales_Org__c,
                                                OwnerId,Owner.IsActive
                                            FROM 
                                                Customer_Sales_Info__c 
                                            WHERE 
                                                Customer__r.MDG_Customer_Code__c IN:customerIdSet AND
                                                Sales_Org__c IN:salesOrgSet
        ]) {
            salesInfoMap.put(csi.Customer__r.MDG_Customer_Code__c+'-'+csi.Sales_Org__c, csi.Id);
            csiMap.put(csi.Customer__r.MDG_Customer_Code__c+'-'+csi.Sales_Org__c,csi);
        }
        
        Set<String> invoiceSet = new Set<String>();
        for (ReqOrderInfo reqOrder : resultinfo) {
            
            If(String.isNotBlank(reqOrder.ZUONR)) {
                invoiceSet.add(reqOrder.ZUONR);
            }
        }
        
        Map<String,String> invoiceMap = new Map<String,String>();
        for(Invoice__c invoice : [SELECT Id,OwnerId,External_Id__c FROM Invoice__c WHERE External_Id__c IN:invoiceSet AND Owner.IsActive =true]) {
            invoiceMap.put(invoice.External_Id__c,invoice.OwnerId);
        }
        
        for (ReqOrderInfo reqOrder : resultinfo) {
            Account_Receivable__C AccountReceivable = new Account_Receivable__C();
            if (customeMap.size()>0 && customeMap.containsKey(reqOrder.KUNNR)) {
                AccountReceivable.Customer__c = customeMap.get(reqOrder.KUNNR);
            }
            AccountReceivable.Company_Code__C = reqOrder.BUKRS;  //公司代码
            AccountReceivable.Fiscal_Year__C = reqOrder.GJAHR; //会计年度
            AccountReceivable.Document_Number__C = reqOrder.BELNR; //会计凭证
            AccountReceivable.Posting_Item__C = reqOrder.BUZEI; //凭证行号
            AccountReceivable.Document_Type__C = reqOrder.H_BLART; //凭证类型
            AccountReceivable.Document_Currency__C = reqOrder.H_WAERS; //凭证货币
            AccountReceivable.Local_Currency__C = reqOrder.RFCCUR; //本位币
            if (reqOrder.kursf!=null) {
                AccountReceivable.Exchange_Rate__C = String.isBlank(reqOrder.KURSF) ? 0 : Decimal.valueOf(reqOrder.KURSF); //汇率
            }else{
                AccountReceivable.Exchange_Rate__C = null; //汇率
            }
            AccountReceivable.Posting_Date__C = Date.valueOf(reqOrder.H_BUDAT); //过账日期
            AccountReceivable.Debit_Credit__C = reqOrder.SHKZG; //借贷方
            AccountReceivable.Amount_in_Trans_Crcy__C = String.isBlank(reqOrder.WRBTR) ? 0 : Decimal.valueOf(reqOrder.WRBTR); //凭证货币金额
            AccountReceivable.Amount_in_Local_Crcy__C =  String.isBlank(reqOrder.DMBTR) ? 0 : Decimal.valueOf(reqOrder.DMBTR); //本位币金额 这里必须要，得把原有单子修改成0
            if(String.isBlank(reqOrder.ZFBDT)) {
                returnDataMsgTmp = new ReturnData();
                returnDataMsgTmp.bukrs = reqOrder.bukrs;//公司代码
                returnDataMsgTmp.gjahr = reqOrder.gjahr;//会计年度
                returnDataMsgTmp.belnr = reqOrder.belnr;//会计凭证
                returnDataMsgTmp.buzei = reqOrder.buzei;//凭证行号
                returnDataMsgTmp.msgty = 'E';
                returnDataMsgTmp.msgtx = '凭证号：'+reqOrder.BELNR+'付款基准日期没有传！';
                out.ReturnDataList.add(returnDataMsgTmp);
                isPartSuccess = true;
                continue;
            }
            AccountReceivable.Baseline_Date__C = Date.valueOf(reqOrder.ZFBDT); //付款基准日期
            AccountReceivable.Payment_Terms__c = reqOrder.ZTERM; //付款条件
            AccountReceivable.Due_On__C = Date.valueOf(reqOrder.NETDT); //到期日期
            AccountReceivable.Overdue_Days__C = String.isBlank(reqOrder.ZYQTS) ? 0 : Decimal.valueOf(reqOrder.ZYQTS.trim()); //逾期天数
            AccountReceivable.Invoice_Number__C = reqOrder.ZUONR; //发票号
            If(String.isNotBlank(reqOrder.ZUONR)) {
                Invoice__c inv = new Invoice__c();
                inv.External_Id__c = reqOrder.ZUONR;
                AccountReceivable.Invoice__r = inv;
                if(invoiceMap.get(reqOrder.ZUONR)!=null) {
                    AccountReceivable.OwnerId = invoiceMap.get(reqOrder.ZUONR);
                }
                
            }
            if(AccountReceivable.OwnerId==null) {
                Customer_Sales_Info__c csi = csiMap.get(reqOrder.KUNNR+'-'+reqOrder.BUKRS);
                if(csi!=null && csi.Owner.IsActive) {
                    AccountReceivable.OwnerId = csi.OwnerId;
                }
            }
            AccountReceivable.Profit_Center__C = reqOrder.PRCTR; //利润中心
            AccountReceivable.Account_Number__C = reqOrder.HKONT; //会计科目
            AccountReceivable.Sales_Order_Number__C = reqOrder.VBELV; //销售订单
            AccountReceivable.Sales_Order_Type__C = reqOrder.AUART; //销售订单类型
            AccountReceivable.Sales_Org__c = reqOrder.VKORG; //销售组织
            AccountReceivable.ExternalId__c = reqOrder.KUNNR + reqOrder.BUKRS + reqOrder.GJAHR + reqOrder.BELNR + reqOrder.BUZEI;
            
            // if(salesInfoMap.containskey(reqOrder.KUNNR+'-'+reqOrder.BUKRS)){
                AccountReceivable.Customer_Sales_Info__c = salesInfoMap.get(reqOrder.KUNNR+'-'+reqOrder.BUKRS);
            // }else{
                //     throw new CustomException(reqOrder.KUNNR+'-'+reqOrder.BUKRS+'不存在！');
            // }
            
            // AccountReceivableList.add(AccountReceivable);
            AccountReceivableMap.put(accountReceivableIndex,AccountReceivable);
            accountReceivableIndex++;
        }
        String errorStr = '';
        Integer resultIndex = 0;
        if (AccountReceivableMap.size() > 0) {
            List<Database.UpsertResult> resultList = Database.upsert(AccountReceivableMap.values(),Account_Receivable__C.fields.ExternalId__c, false);
            // Database.upsert(AccountReceivableList,Account_Receivable__C.fields.ExternalId__c, true);
            for(Integer i=0;i<resultList.size();i++) {
                Database.UpsertResult result = resultList[resultIndex];
                returnDataMsg = new ReturnData();
                errorStr = '';
                accountReceivableMapResult = new Account_Receivable__C();
                accountReceivableMapResult = AccountReceivableMap.get(resultIndex);
                if(!result.isSuccess()) {
                    for(Database.Error errorStrItem : result.getErrors()) {
                        errorStr = errorStr + errorStrItem.getMessage();
                    }
                    returnDataMsg.bukrs = accountReceivableMapResult.Company_Code__C;//公司代码
                    returnDataMsg.gjahr = accountReceivableMapResult.Fiscal_Year__C;//会计年度
                    returnDataMsg.belnr = accountReceivableMapResult.Document_Number__C;//会计凭证
                    returnDataMsg.buzei = accountReceivableMapResult.Posting_Item__C;//凭证行号
                    returnDataMsg.msgty = 'E';
                    returnDataMsg.msgtx = errorStr;
                    out.ReturnDataList.add(returnDataMsg);
                    isPartSuccess = true;
                } else {
                    returnDataMsg.bukrs = accountReceivableMapResult.Company_Code__C;//公司代码
                    returnDataMsg.gjahr = accountReceivableMapResult.Fiscal_Year__C;//会计年度
                    returnDataMsg.belnr = accountReceivableMapResult.Document_Number__C;//会计凭证
                    returnDataMsg.buzei = accountReceivableMapResult.Posting_Item__C;//凭证行号
                    returnDataMsg.msgty = 'S';
                    returnDataMsg.msgtx = 'The data is successfully written!';
                    out.ReturnDataList.add(returnDataMsg);
                }
                resultIndex++;
            }
        }
        out.isSuccess = true;
        out.isPartSuccess = isPartSuccess;
        return out;
    }
    global static ResponseBody returnData(String requestTime,Boolean status,String errorMsg,List<ReturnData> ReturnDataList) {
        ResponseBody re = new ResponseBody();
        re.esbinfo = new RespESInfo();
        re.esbinfo.requesttime = requestTime;//请求时间
        re.esbinfo.responsetime = String.valueOf(Datetime.now());//返回时间
        if (!status) {
            re.esbinfo.returnstatus = 'E';//接口状态
            re.esbinfo.returncode = 'E001';//接口状态码
            re.esbinfo.returnmsg = errorMsg;//接口消息
        }else{
            re.esbinfo.returnstatus = 'S';//接口状态
            re.esbinfo.returncode = 'S001';//接口状态码
        }
        re.resultinfo = new RespCustomerInfo();
        RespCustomerInfo rci = new RespCustomerInfo();
        if (status) {
            rci.msgty = 'S';
            rci.msgtx = '处理成功';
        }else{
            rci.msgty = 'E';
            rci.msgtx = errorMsg;
        }
        rci.returnDataList = ReturnDataList;
        re.resultinfo = rci;
        return re;
    }
}