force-app/main/default/objects/Account/fields/Virtual_customer__c.field-meta.xml
<CustomField>
    <fullName>Virtual_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Virtual customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/Sales_Forcast__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast Detail</label>
    <nameField>
        <displayFormat>SFD-{000000}</displayFormat>
        <label>Sales Forcast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forcast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Forcast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Actual_Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Actual_Local_Currency__c</fullName>
    <label>Monthly Actual (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Actual_USD__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Actual_USD__c</fullName>
    <label>Monthly Actual (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Sales_Forecast_Summary__c.field-meta.xml
<CustomField>
    <fullName>Sales_Forecast_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Forecast Summary</label>
    <referenceTo>Sales_Forecast_Summary__c</referenceTo>
    <relationshipLabel>Sales Forecast Detail</relationshipLabel>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/Sales_Forecast_Summary__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Sales Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
            <value>
                <fullName>2052</fullName>
            </value>
            <value>
                <fullName>2053</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteSalesVirtualForecastDataBatch.cls
/*
* Name: SalesVirtualForecastDataBatch
* Date: 2024-08-23
* Creator: gerry
* Description: 删除记录虚拟客户销量
* History: 
*------------------------------------------------
* Version    Last Modified By     Desription
* v1         Gerry              Create
*------------------------------------------------*/
global without sharing class DeleteSalesVirtualForecastDataBatch implements Database.Batchable<sObject>,Database.Stateful {
    
    String month = '';
    String year = '';
    public String query;
    global Boolean flag;
    global String errorMsg;
    global Datetime startTime;
    global Boolean runCu;
    global DeleteSalesVirtualForecastDataBatch(String year, String month, Boolean runCu) {
        this.month = month;
        this.year = year;
        this.runCu = runCu;
        this.flag = true;
    }

    global DeleteSalesVirtualForecastDataBatch() {
        this.runCu = false;
        this.startTime = System.now();
        this.flag = true;
        Date day = System.today();
        if (day.Day() == 1 || Test.isRunningTest()) {
            if (day.Month() == 1) {
                Integer yeraInt = day.Year() - 1;
                this.year = yeraInt + '';
                this.month = '12';
            }else{
                Integer monthInt = day.Month() - 1;
                this.month = monthInt + '';
                this.year = day.Year() + '';
            }
        }else{
            this.month = day.Month() + '';
            this.year = day.Year() + '';
        }
        if (Test.isRunningTest()) {
            this.month = '1';
            this.year = '2024';
        }
        //this.query = 'SELECT Id,Year__c,Month__c,Product_Name__c,Customer__c,External_Id__c,OwnerId FROM Sales_Forcast__c WHERE Month__c =:month AND Year__c =:year AND Sales_Forecast_Summary__r.Status__c=\'Approved\'';
        System.debug('this.month==>'+this.month);
        System.debug('this.year==>'+this.year);
        System.debug('this.query==>'+this.query);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        this.query = 'SELECT Sales_Forecast_Summary__r.Sales_Org__c,Id,Year__c,Month__c,Product_Name__c,Customer__c,External_Id__c,OwnerId FROM Sales_Forcast__c WHERE Month__c =:month AND Year__c =:year AND Sales_Forecast_Summary__r.Status__c=\'Approved\' AND Customer__r.Virtual_customer__c=true';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sales_Forcast__c> salesForList) {
        try {
            
            for (Sales_Forcast__c sf : salesForList) {
                sf.Monthly_Actual_USD__c = 0;
                sf.Monthly_Actual_Local_Currency__c = 0;
            }
            Update salesForList;
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('DeleteSalesVirtualForecastDataBatch', this.flag, this.startTime, this.errorMsg);
        if(this.runCu) {
            SalesVirtualForecastDataBatch svo = new SalesVirtualForecastDataBatch( this.year, this.month);

            // 每次执行多少条数据，最大200
            String jobId = Database.executeBatch(svo, 100);
        }else{
            SalesVirtualForecastDataBatch svo = new SalesVirtualForecastDataBatch();

            // 每次执行多少条数据，最大200
            String jobId = Database.executeBatch(svo, 100);
        }
        
    }
}