force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShareBillBatch.cls
global without sharing class ShareBillBatch implements Database.Batchable<sObject>,Database.Stateful{
    public String query;
    public List<String> orderIdList;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;
    public ShareBillBatch(List<String> orderIdList) {
        this.startTime = System.now();
        this.flag = true;
        this.orderIdList = orderIdList;
        this.query = 'SELECT Id,Order__r.Customer__c,OwnerId FROM Invoice__c WHERE Id IN:orderIdList';
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Invoice__c> orderList) {
        try {
            for (Invoice__c order : orderList) {
                ShareDataToAccountTeam.shareData('Invoice__c', order.Id, order.Order__r.Customer__c, 'Invoice__c',order.OwnerId);
            }
        }catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('ShareBillBatch', this.flag, this.startTime, this.errorMsg);
    }
}