force-app/main/default/objects/Sales_Forcast__c/Sales_Forcast__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast Detail</label>
    <nameField>
        <displayFormat>SFD-{000000}</displayFormat>
        <label>Sales Forcast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Forecast_USD__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Forecast_USD__c</fullName>
    <label>Monthly Forecast (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Sales_Forecast_Summary__c.field-meta.xml
<CustomField>
    <fullName>Sales_Forecast_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Forecast Summary</label>
    <referenceTo>Sales_Forecast_Summary__c</referenceTo>
    <relationshipLabel>Sales Forecast Detail</relationshipLabel>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/Sales_Forecast_Summary__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Sales Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Total_Forecast_Amount_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Forecast_Amount_USD__c</fullName>
    <label>Total Forecast Amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SalesForecastSummaryTriggerHandler.cls
public without sharing class SalesForecastSummaryTriggerHandler implements Triggers.Handler {
    public void handle() {
        if (Trigger.isbefore && (Trigger.isUpdate)) {
            String sfsId = '';
            Map<Id,Sales_Forecast_Summary__c> oldMap = (Map<Id,Sales_Forecast_Summary__c>)Trigger.oldMap;
            for (Sales_Forecast_Summary__c sfs : (List<Sales_Forecast_Summary__c>)Trigger.new) {
                if (sfs.Status__c == 'Approved' && oldMap.get(sfs.Id).Status__c!=sfs.Status__c) {
                    sfsId = sfs.Id;
                }
                
            }
            Decimal totalForecastAmount = 0;
            if (String.isNotBlank(sfsId)) {
                List<Sales_Forcast__c> sfList = [SELECT Id,Monthly_Forecast_USD__c FROM Sales_Forcast__c WHERE Sales_Forecast_Summary__c =: sfsId];
                for (Sales_Forcast__c sf : sfList) {
                    if (sf.Monthly_Forecast_USD__c!=null) {
                        totalForecastAmount += sf.Monthly_Forecast_USD__c;
                    }
                    
                }
            }
            if (totalForecastAmount > 0) {
                for (Sales_Forecast_Summary__c sfs : (List<Sales_Forecast_Summary__c>)Trigger.new) {
                    sfs.Total_Forecast_Amount_USD__c = totalForecastAmount;
                }
            }
            
            
            
        }
    }
}