force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Customer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeQuoteStatusController.cls
public without sharing class ChangeQuoteStatusController {
    @AuraEnabled
    public static Output changeStatus(String quoteId, Boolean currentStatus) {
        System.debug('currentStatus=>'+currentStatus);
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        try {
            Quote__c quote=new Quote__c();
            quote.Id=quoteId;
            quote.Is_Customer_Confirmed__c=currentStatus;
            update quote;
        } catch (Exception e) {
        	
            out.isSucess = false;
            out.errorMsg = e.getMessage()+';'+e.getLineNumber();
            return out;
        }
        return out;
        
    }

    @AuraEnabled
    public static Output init(String quoteId) {
        Output out = new Output();
        out.isSucess = true;
        out.errorMsg = 'Successful';
        try{
        Quote__c quote = [SELECT Id,Sales_Org__c,Quotation_Type__c,Approval_Status__c,Is_Customer_Confirmed__c FROM Quote__c WHERE Id=:quoteId];
        
        out.currentStatus=quote.Is_Customer_Confirmed__c;
        } catch (Exception e) {
            out.isSucess = false;
            out.errorMsg = e.getMessage()+';'+e.getLineNumber();
           
        }
        return out;
    }

    
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public Boolean currentStatus {get;set;}
        
        
    }
}