force-app/main/default/objects/Campaign_Budget__c/Campaign_Budget__c.object-meta.xml
<CustomObject>
    <label>Campaign Budget</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Budget</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Budget__c/fields/ExteralId__c.field-meta.xml
<CustomField>
    <fullName>ExteralId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>销售组织+年份</inlineHelpText>
    <label>ExteralId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignBudgetTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-19-2025   Gerry   Initial Version
**/
public without sharing class CampaignBudgetTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isbefore && (Trigger.isinsert || Trigger.isupdate))
        {
            // Set<String> duplicateExterl=new Set<String>();
            // for(Campaign_Budget__c cb:[SELECT Id,ExteralId__c,Sales_Org__c,Year__c FROM Campaign_Budget__c WHERE ExteralId__c != null])
            // { duplicateExterl.add(cb.ExteralId__c);}
            for(Campaign_Budget__c campaignBudget :(List<Campaign_Budget__c>)Trigger.new)
            {
                campaignBudget.ExteralId__c=campaignBudget.Sales_Org__c+'_'+campaignBudget.Plant__c+'_'+campaignBudget.Year__c;
                // if(duplicateExterl != null && duplicateExterl.contains(campaignBudget.ExteralId__c)){
                //     //campaignBudget.addError('Current Company Select Year Exist Same Budget');
                //     campaignBudget.addError(System.Label.SameSameYearBudget);}
            }
        }
}
}