force-app/main/default/objects/Contracts_Detail__c/Contracts_Detail__c.object-meta.xml
<CustomObject>
    <label>Contracts Detail</label>
    <nameField>
        <displayFormat>CD-{YYMM}-{000000}</displayFormat>
        <label>Contracts Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Code</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contracts Detail</relationshipLabel>
    <relationshipName>Contracts_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts_Detail__c/fields/Product_Code_Vertify__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Vertify__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Code Vertify</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ContractDetailTriggerHandler.cls
public without sharing class ContractDetailTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isbefore &&  (Trigger.isinsert || Trigger.isupdate))
        {
            for (Contracts_Detail__c conDetail : (List<Contracts_Detail__c>)Trigger.new) 
            {
                if(conDetail.Product__c==null){
                    conDetail.Product_Code_Vertify__c=true;
                }else{
                    conDetail.Product_Code_Vertify__c=false;
                }
            }
        }
    }}