force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions__c</fullName>
    <label>Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Terms_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_Of_Payment__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/Customer_Sales_Info_Change_Application__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info Change Application</label>
    <nameField>
        <displayFormat>CSCA-{00000}</displayFormat>
        <label>Change Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sales Info Change Application</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Approve_Status__c.field-meta.xml
<CustomField>
    <fullName>Approve_Status__c</fullName>
    <label>Approve Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Change_Item__c.field-meta.xml
<CustomField>
    <fullName>Change_Item__c</fullName>
    <label>Change Item</label>
    <summaryFilterItems>
        <field>Customer_Tax_Category_Application__c.New_Tax_Category__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Customer_Tax_Category_Application__c.Customer_Sales_Info_Change_Application__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Sales Info Change Application</relationshipLabel>
    <relationshipName>Customer_Sales_Info_Change_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Is_Change__c.field-meta.xml
<CustomField>
    <fullName>Is_Change__c</fullName>
    <formula>NOT(
	AND(
        OR(
            ISNULL(TEXT(New_Shipping_Conditions__c)),
            ISBLANK(TEXT(New_Shipping_Conditions__c))
        ),
        OR(
            ISNULL(TEXT(New_Payment_term__c)),
            ISBLANK(TEXT(New_Payment_term__c))
        ),
        OR(
            ISNULL(TEXT(New_Customer_Group__c)),
            ISBLANK(TEXT(New_Customer_Group__c))
        ),
        OR(
            ISNULL(TEXT(New_Currency__c)),
            ISBLANK(TEXT(New_Currency__c))
        ),
					   OR(
            ISNULL(TEXT(New_Account_Assessment__c)),
            ISBLANK(TEXT(New_Account_Assessment__c))
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Account_Assessment__c.field-meta.xml
<CustomField>
    <fullName>New_Account_Assessment__c</fullName>
    <label>New Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Currency__c.field-meta.xml
<CustomField>
    <fullName>New_Currency__c</fullName>
    <label>New Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Group__c</fullName>
    <label>New Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Payment_term__c.field-meta.xml
<CustomField>
    <fullName>New_Payment_term__c</fullName>
    <label>New Payment term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivery_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>New_Shipping_Conditions__c</fullName>
    <label>New Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/Customer_Tax_Category_Application__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category Application</label>
    <nameField>
        <displayFormat>CTCA-{000000}</displayFormat>
        <label>Customer Tax Category Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Tax Category Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Customer_Sales_Info_Change_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info_Change_Application__c</fullName>
    <label>Customer Sales Info Change Application</label>
    <referenceTo>Customer_Sales_Info_Change_Application__c</referenceTo>
    <relationshipLabel>Customer Tax Category Application</relationshipLabel>
    <relationshipName>Customer_Tax_Category_Application</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Customer_Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Tax Category</label>
    <referenceTo>Customer_Tax_Category__c</referenceTo>
    <relationshipLabel>Customer Tax Category Application</relationshipLabel>
    <relationshipName>Customer_Tax_Category_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/New_Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>New_Tax_Category__c</fullName>
    <label>New Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Shipping_Conditions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>01 Standard</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Pick up</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03 RB Gualeguaychu</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04 RB Buenos Aires</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05 SLA en Alsina</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06 SLA en Zárate</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>07 Agroterrum Gualeguay</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>08 Daser en Victoria</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>09 Deylar en San Franci</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Tokbritz en Chaco</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11 Agrosym en Salta</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 AGSOF S.A.</label>
    </customValue>
    <masterLabel>Shipping Conditions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomeSalesInfoApplicationHandler.cls
/**
 * @description       : 客户销售信息handler
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 07-04-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   06-17-2025   Gerry   Initial Version
**/
public without sharing class CustomeSalesInfoApplicationHandler implements Triggers.Handler {
    public void handle() {
        if (Trigger.isAfter && Trigger.isupdate) {
            Map<Id,Customer_Sales_Info_Change_Application__c> oldMap = (Map<Id,Customer_Sales_Info_Change_Application__c>)Trigger.oldMap;
            List<Customer_Sales_Info__c> csiList = new List<Customer_Sales_Info__c>();
            List<Customer_Tax_Category__c> ctcList = new List<Customer_Tax_Category__c>();
            List<String> csicaIdList = new List<String>();
            for (Customer_Sales_Info_Change_Application__c csca : (List<Customer_Sales_Info_Change_Application__c>)Trigger.new) {
                if (csca.Approve_Status__c == 'Approved' && csca.Approve_Status__c != oldMap.get(csca.Id).Approve_Status__c) {
                    Boolean flag = false;
                    Customer_Sales_Info__c csi = new Customer_Sales_Info__c();

                    if (csca.New_Payment_term__c!=null) {
                        csi.Terms_Of_Payment__c = csca.New_Payment_term__c;
                        flag = true;
                    }

                    if (csca.New_Customer_Group__c!=null) {
                        csi.Payment_method__c = csca.New_Customer_Group__c;
                        flag = true;
                    }

                    if (csca.New_Shipping_Conditions__c!=null) {
                        csi.Shipping_Conditions__c = csca.New_Shipping_Conditions__c;
                        flag = true;
                    }

                    if (csca.New_Currency__c!=null) {
                        csi.Currency__c = csca.New_Currency__c;
                        flag = true;
                    }
                    if (csca.New_Account_Assessment__c!=null) {
                        csi.Acct_Assmt_Grp_Cust__c = csca.New_Account_Assessment__c;
                        flag = true;
                    }
                    
                    csi.Id = csca.Customer_Sales_Info__c;

                    if (flag) {
                        csiList.add(csi);
                    }
                    if (csca.Sales_Org__c!='5130' && csca.Sales_Org__c!='5070') {
                        csicaIdList.add(csca.Id);
                    }
                }
            }
            

            if (csicaIdList.size()>0) {
                for (Customer_Tax_Category_Application__c ctca : [SELECT Customer_Tax_Category__c,ID,New_Tax_Category__c FROM Customer_Tax_Category_Application__c WHERE Customer_Sales_Info_Change_Application__c IN:csicaIdList]) {
                    if (ctca.New_Tax_Category__c!=null) {
                        Customer_Tax_Category__c ctc = new Customer_Tax_Category__c();
                        ctc.Id = ctca.Customer_Tax_Category__c;
                        ctc.Tax_Category__c = ctca.New_Tax_Category__c;
                        ctcList.add(ctc);
                    }
                    
                }
                if (ctcList.size()>0) {
                    Update ctcList;
                }
            }

            if (csiList.size()>0) {
                Update csiList;
            }
        }

        if (Trigger.isBefore && Trigger.isupdate) {
            Map<Id,Customer_Sales_Info_Change_Application__c> oldMap = (Map<Id,Customer_Sales_Info_Change_Application__c>)Trigger.oldMap;
           
            for (Customer_Sales_Info_Change_Application__c csca : (List<Customer_Sales_Info_Change_Application__c>)Trigger.new) {
                if (csca.Approve_Status__c == 'Approving' && csca.Approve_Status__c != oldMap.get(csca.Id).Approve_Status__c) {
                    if (csca.Sales_Org__c!='5130' && csca.Sales_Org__c!='5070') {
                        if (!csca.Is_Change__c && csca.Change_Item__c==0) {
                            csca.adderror(System.Label.NoChanged);
                        
                        }
                    }else{
                        if (!csca.Is_Change__c ) {
                            csca.adderror(System.Label.NoChanged);
                        
                        }
                    } 
                }
            }
        }
    }
}