force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Acct_Assmt_Grp_Cust__c.field-meta.xml
<CustomField>
    <fullName>Acct_Assmt_Grp_Cust__c</fullName>
    <label>Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions__c</fullName>
    <label>Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Terms_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_Of_Payment__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivering_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/Customer_Sales_Info_Change_Application__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info Change Application</label>
    <nameField>
        <displayFormat>CSCA-{00000}</displayFormat>
        <label>Change Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sales Info Change Application</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Sales Info Change Application</relationshipLabel>
    <relationshipName>Customer_Sales_Info_Change_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/New_Account_Assessment__c.field-meta.xml
<CustomField>
    <fullName>New_Account_Assessment__c</fullName>
    <label>New Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Old_Account_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Old_Account_Assessment__c</fullName>
    <label>Old Account Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Assessment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Old_Currency__c.field-meta.xml
<CustomField>
    <fullName>Old_Currency__c</fullName>
    <label>Old Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Old_Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Old_Customer_Group__c</fullName>
    <label>Old Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Old_Payment_term__c.field-meta.xml
<CustomField>
    <fullName>Old_Payment_term__c</fullName>
    <label>Old Payment term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info_Change_Application__c/fields/Old_Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Old_Shipping_Conditions__c</fullName>
    <label>Old Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Conditions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Category Master Data</label>
    <referenceTo>Tax_Category_Master_Data__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Type__c</fullName>
    <label>Tax Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/Customer_Tax_Category_Application__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category Application</label>
    <nameField>
        <displayFormat>CTCA-{000000}</displayFormat>
        <label>Customer Tax Category Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Tax Category Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Customer_Sales_Info_Change_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info_Change_Application__c</fullName>
    <label>Customer Sales Info Change Application</label>
    <referenceTo>Customer_Sales_Info_Change_Application__c</referenceTo>
    <relationshipLabel>Customer Tax Category Application</relationshipLabel>
    <relationshipName>Customer_Tax_Category_Application</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Customer_Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Tax Category</label>
    <referenceTo>Customer_Tax_Category__c</referenceTo>
    <relationshipLabel>Customer Tax Category Application</relationshipLabel>
    <relationshipName>Customer_Tax_Category_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Old_Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Old_Tax_Category__c</fullName>
    <label>Old Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category_Application__c/fields/Tax_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category_Type__c</fullName>
    <label>Tax Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Category_Master_Data__c/Tax_Category_Master_Data__c.object-meta.xml
<CustomObject>
    <label>Tax Category Master Data</label>
    <nameField>
        <label>Tax Category Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Account_Assessment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Related</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <default>true</default>
        <label>02 Non Related</label>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <masterLabel>Account Assessment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YPF</fullName>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1 Special VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <isActive>false</isActive>
        <label>Z2 General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <isActive>false</isActive>
        <label>Z3  Electronic General VAT Invoice</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <isActive>false</isActive>
        <label>Z4 Electronic Special VAT Invoice</label>
    </customValue>
    <masterLabel>Customer Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Shipping_Conditions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>01 Standard</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Pick up</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03 RB Gualeguaychu</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04 RB Buenos Aires</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05 SLA en Alsina</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06 SLA en Zárate</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>07 Agroterrum Gualeguay</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>08 Daser en Victoria</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>09 Deylar en San Franci</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Tokbritz en Chaco</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11 Agrosym en Salta</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 AGSOF S.A.</label>
    </customValue>
    <masterLabel>Shipping Conditions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tax_Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>J1AU</fullName>
        <label>J1AU IVA Ventas</label>
    </customValue>
    <customValue>
        <fullName>J1A1</fullName>
        <label>J1A1 Perc. IIBB CABA</label>
    </customValue>
    <customValue>
        <fullName>J1A2</fullName>
        <label>J1A2 Perc. IIBB ARBA</label>
    </customValue>
    <customValue>
        <fullName>J1A3</fullName>
        <label>J1A3 Perc. IIBB EntreRios</label>
    </customValue>
    <customValue>
        <fullName>J1A4</fullName>
        <label>J1A4 Perc. IIBB Santa Fe</label>
    </customValue>
    <customValue>
        <fullName>J1A5</fullName>
        <label>J1A5 Perc. IIBB Córdoba</label>
    </customValue>
    <customValue>
        <fullName>J1A6</fullName>
        <label>J1A6 Perc. IIBB Salta</label>
    </customValue>
    <customValue>
        <fullName>J1A7</fullName>
        <label>J1A7 Perc. IIBB Tucumán</label>
    </customValue>
    <customValue>
        <fullName>J1A8</fullName>
        <label>J1A8 Perc. IIBB Otras</label>
    </customValue>
    <customValue>
        <fullName>MWST</fullName>
        <label>MWST IVA repercutido</label>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
        <label>MX01 I.E.P.S. (MEXICO)</label>
    </customValue>
    <masterLabel>Tax Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeCustomerSalesInfoLWCController.cls
/**
 * @description       : 修改客户销售视图控制类
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 07-04-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   07-01-2025   Gerry   Initial Version
**/
public without sharing class ChangeCustomerSalesInfoLWCController {
    @AuraEnabled
    public static Output changeData(String customerSalesInfoId) {
        System.savepoint sp = Database.setSavepoint();
        try {
            Customer_Sales_Info__c csi = [SELECT Acct_Assmt_Grp_Cust__c,Sales_Org__c,Delivering_Plant__c,Id,Currency__c,Shipping_Conditions__c,Terms_Of_Payment__c,Payment_method__c FROM Customer_Sales_Info__c WHERE Id=:customerSalesInfoId];
            Customer_Sales_Info_Change_Application__c scica = new Customer_Sales_Info_Change_Application__c();
            scica.Customer_Sales_Info__c = customerSalesInfoId;
            scica.Delivery_Plant__c = csi.Delivering_Plant__c;
            scica.Sales_Org__c = csi.Sales_Org__c;
            scica.Old_Currency__c = csi.Currency__c;
            scica.Old_Customer_Group__c = csi.Payment_method__c;
            scica.Old_Payment_term__c = csi.Terms_Of_Payment__c;
            scica.Old_Shipping_Conditions__c = csi.Shipping_Conditions__c;
            scica.Old_Account_Assessment__c = csi.Acct_Assmt_Grp_Cust__c;
            scica.New_Account_Assessment__c = null;
            Database.insert(scica);
            if (csi.Sales_Org__c!='5130' && csi.Sales_Org__c!='5070') {
                List<Customer_Tax_Category_Application__c> ctcaList = new List<Customer_Tax_Category_Application__c>();
                for(Customer_Tax_Category__c ctc : [
                    SELECT 
                        Id,
                        Tax_Category__c,
                        Tax_Category_Master_Data__c,
                        Tax_Category_Type__c 
                    FROM Customer_Tax_Category__c WHERE Sales_View__c=:customerSalesInfoId]
                ){
                    Customer_Tax_Category_Application__c ctca = new Customer_Tax_Category_Application__c();
                    ctca.Customer_Tax_Category__c = ctc.Id;
                    ctca.Customer_Sales_Info_Change_Application__c = scica.Id;
                    ctca.Old_Tax_Category__c = ctc.Tax_Category__c;
                    ctca.Tax_Category_Type__c = ctc.Tax_Category_Type__c;
                    ctcaList.add(ctca);
                }
                Database.insert(ctcaList);
            }
            Output out = new Output();
            out.isSucess = true;
            out.errorMsg = 'Successful';
            out.newRecordId = scica.Id;
            return out;
        } catch (Exception e) {
            Database.rollback(sp);
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = e.getMessage()+'Line:'+e.getLineNumber();
            return out;
        }
        
    }

    
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}
        
        @AuraEnabled
        public String newRecordId {get;set;}

        @AuraEnabled
        public List<Option> optionList {get;set;}

        @AuraEnabled
        public Boolean showOption {get;set;}
    }

    public class Option {
        @AuraEnabled
        public String label {get;set;}

        @AuraEnabled
        public String value {get;set;}
    }
}