force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer_MDG_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_MDG_Code__c</fullName>
    <formula>Customer__r.MDG_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer MDG Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Is_Freeze__c.field-meta.xml
<CustomField>
    <fullName>Is_Freeze__c</fullName>
    <label>Is Freeze</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Rate__c/Payment_Rate__c.object-meta.xml
<CustomObject>
    <label>Payment Rate</label>
    <nameField>
        <label>Payment Term Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Rate</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Rate__c/fields/Payment_Term_Cost_Rate__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Cost_Rate__c</fullName>
    <label>Payment Term Cost Rate(Customer)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quote_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Approval__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval__c</fullName>
    <label>Negative Gross Margin Item Count</label>
    <summaryFilterItems>
        <field>Quote_Detail__c.BU_Profit_Rate__c</field>
        <operation>lessThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Quote_Detail__c.Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deliver_Plant__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Client Confirming</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 05-27-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-27-2025   Gerry   Initial Version
**/
public without sharing class QuoteTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isBefore && (Trigger.isupdate || Trigger.isinsert)) {
            //List<Profile> adminPro = [SELECT Id FROM Profile WHERE Id=:UserInfo.getProfileId() AND  (Name='Interface Profile' OR Name='系统管理员' OR Name='System Administrator' or Name = 'Administrador del sistema') limit 1];
            Set<String> paymentTermSet = new Set<String>();
            List<Quote__c> quoteList = (List<Quote__c>)Trigger.new;
            for (Quote__c quote : quoteList) 
            {
                if(quote.Payment_Term__c != null)
                {
                    paymentTermSet.add(quote.Payment_Term__c);
                }
            }
            Map<String,Payment_Rate__c> paymentRateMap = new Map<String,Payment_Rate__c>();
            for(Payment_Rate__c payRate:[SELECT Id,Name,Payment_Term_Cost_Rate__c FROM Payment_Rate__c WHERE Name IN:paymentTermSet])
            {
                paymentRateMap.put(payRate.Name,payRate);
            }
            for (Quote__c quote : (List<Quote__c>)Trigger.new) 
            {
                if(quote.Approval_Status__c=='Draft')
                {       
                    if (paymentRateMap.get(quote.Payment_Term__c) == null) 
                    {
                        //quote.addError('Quote Payment_Term Not Map Payment_Rate__c Data');
                        quote.Payment_Term_Cost_Rate__c =1;
                    }
                    else
                    {
                        quote.Payment_Term_Cost_Rate__c = paymentRateMap.get(quote.Payment_Term__c).Payment_Term_Cost_Rate__c;
                    }
                }
            }
            
        }
        
        if (Trigger.isBefore && Trigger.isupdate) {
            Map<Id,Quote__c> oldMap = (Map<Id,Quote__c>)Trigger.oldMap;
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                if (oldMap.get(quote.Id).Status__c == 'Confirmed' && quote.Status__c != 'Canceled' && oldMap.get(quote.Id).Status__c!=quote.Status__c) {
                    //quote.addError('Status__c Is Comfirmed,Not Change Status__c');
                    quote.addError(System.Label.QuoteChangeStatusError);
                }
            }
        }
        if (Trigger.isBefore && Trigger.isinsert) {
            Set<String> accSet = new Set<String>();
            Set<String> salesOrgSet = new Set<String>();
            Set<String> accSalesOrgSet = new Set<String>();
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                accSet.add(quote.Customer__c);
                salesOrgSet.add(quote.Sales_Org__c);
            }
            for(Customer_Sales_Info__c csi :[SELECT Id,Customer__c,Sales_Org__c FROM Customer_Sales_Info__c WHERE Customer__c IN:accSet AND Sales_Org__c IN:salesOrgSet AND Is_Freeze__c='01'])
            {
                accSalesOrgSet.add(csi.Customer__c+'_'+csi.Sales_Org__c);
            }
            System.debug('accSalesOrgSet=>'+accSalesOrgSet);
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                if (accSalesOrgSet != null && accSalesOrgSet.contains(quote.Customer__c+'_'+quote.Sales_Org__c)) {
                    quote.addError(System.Label.AccFreezeError);
                }
            }
        }
        if (Trigger.isAfter && Trigger.isInsert) 
        {
            // 共享数据到客户小组
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                ShareDataToAccountTeam.shareData('Quote__c', quote.Id, quote.Customer__c, 'Quote__c',quote.OwnerId);
            }
        }
        if (Trigger.isAfter && Trigger.isupdate)
        {
            Map<Id,Quote__c> oldMap = (Map<Id,Quote__c>)Trigger.oldMap;
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                Set<String> uSet = new Set<String>();
                uSet.add(quote.OwnerId);
                if (quote.Quotation_Type__c=='HQ_Purchase' && quote.Is_Approval__c>0 && quote.Approval_Status__c=='Approved' && oldMap.get(quote.Id).Approval_Status__c != quote.Approval_Status__c) 
                {
                    String body = '<div>'+System.Label.QuoteApprovalBody+'<br/><br/><br/>'+System.Label.QuoteApprovalBodyLocal+'</div>';
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    body = body.replaceAll('【报价单号】', quote.Name);
                    Integer index = String.valueOf(URL.getOrgDomainUrl()).indexof('=')+1;
                    String recordURL = String.valueOf(URL.getOrgDomainUrl()).subString(index);
                    body = body.replaceAll('【链接】',recordURL.replace(']','')+'/'+quote.Id);
                    email.setHtmlBody(body);
                    email.setSubject(System.Label.Quote_Approval_Title+quote.Name);
                    List<String> emailList = new List<String>();
                    for(String userEmail:System.Label.QuoteApprovalNoticeEmail.split(';'))
                    {
                        if(userEmail != null)
                        {
                            emailList.add(userEmail);
                        }
                    }
                    OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress];
                    if (owea.size() > 0 ) {
                           email.setOrgWideEmailAddressId(owea.get(0).Id);
                    }
                    email.setToAddresses(emailList);
                    //if(!Test.isRunningTest())Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
                }
                //审批结果通知
                if(quote.Approval_Status__c == 'Approved' && quote.Approval_Status__c!=oldMap.get(quote.Id).Approval_Status__c) {
                    Utility.notificationUserTitle(uSet,quote.Id,System.Label.Quote_Approved_Title,System.Label.Quote_Approved_Title+quote.Name);
                }
                
                if(quote.Approval_Status__c == 'Rejected' && quote.Approval_Status__c!=oldMap.get(quote.Id).Approval_Status__c) {
                    Utility.notificationUserTitle(uSet,quote.Id,System.Label.Quote_Rejected_Title,System.Label.Quote_Rejected_Title+quote.Name);
                }

                //报价为3020时并且没有负毛利时知会lary
                if(
                    quote.Approval_Status__c == 'Approved' && 
                    quote.Approval_Status__c!=oldMap.get(quote.Id).Approval_Status__c && 
                    (quote.Customer_MDG_Code__c == '0000003020' || quote.Customer_MDG_Code__c == '0000003011') &&
                    quote.Is_Approval__c == 0
                ) {
                    Set<String> lary = new Set<String>();
                    User u = [SELECT Id FROM User WHERE Username='laryfan@rainbowagro.com.rbdev' OR Username='laryfan@rainbowagro.com' limit 1];
                    lary.add(u.Id);
                    Utility.notificationUserTitle(lary,quote.Id,System.Label.BTOCTitle,System.Label.BTOCBody+quote.Name);
                }
            }
            for (Quote__c quote : (List<Quote__c>)Trigger.new) {
                if(oldMap.get(quote.Id).Deliver_Plant__c !=quote.Deliver_Plant__c) {
                    system.debug('变更工厂');
                Database.executeBatch(new ChangeShareDataToAccountTeamBatch('Quote__c', quote.Id, quote.Customer__c, 'Quote__c',quote.OwnerId,oldMap.get(quote.Id).Deliver_Plant__c,'Quote__share'));
                }}
        }

    }
}