force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/FOB_Price__c.field-meta.xml
<CustomField>
    <fullName>FOB_Price__c</fullName>
    <label>FOB Bulking Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Approval_Time__c.field-meta.xml
<CustomField>
    <fullName>Approval_Time__c</fullName>
    <label>Approval Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_Customer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Old_Quotation__c.field-meta.xml
<CustomField>
    <fullName>Old_Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Quotation</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/Quote_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Detail</label>
    <nameField>
        <displayFormat>QD-{000000}</displayFormat>
        <label>Quote Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Detail__c/fields/CIF_90_Days__c.field-meta.xml
<CustomField>
    <fullName>CIF_90_Days__c</fullName>
    <label>Quote Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Clearance_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Cost_Percentage__c</fullName>
    <label>Customs Clearance %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission Per Unit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/FOB_Price__c.field-meta.xml
<CustomField>
    <fullName>FOB_Price__c</fullName>
    <label>FOB Bulking Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Order_Qnty__c.field-meta.xml
<CustomField>
    <fullName>Order_Qnty__c</fullName>
    <label>Order Qnty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Packing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Packing_Cost__c</fullName>
    <label>Packing Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Pallet__c.field-meta.xml
<CustomField>
    <fullName>Pallet__c</fullName>
    <label>Pallet Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Term Cost Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product English Name</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Price_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Process_Cost__c.field-meta.xml
<CustomField>
    <fullName>Process_Cost__c</fullName>
    <label>Tolling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Child</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneQuotationController.cls
/**
 * @description       : 报价复制控制类
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 07-16-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   07-14-2025   Gerry   Initial Version
**/
public without sharing class CloneQuotationController {
    @AuraEnabled
    public static Output cloneQoute(String quoteRecordId) {
        System.savepoint sp = Database.setSavepoint();
        try {
            
            ObjectClone.ResponseParam rp = ObjectClone.cloneObjectSingle(quoteRecordId, true, null,'Quote_Detail__c',System.Label.CloneQuoteDetailRemoveField);
            if (rp.code) {
                Output out = new Output();
                Map<Id, Id> oldToNewIdMap = rp.oldIdToNewId;
                System.debug(oldToNewIdMap);
                Quote__c quo = new Quote__c();
                quo.Id = oldToNewIdMap.get(quoteRecordId);
                quo.Old_Quotation__c = quoteRecordId;//关联原有报价
                quo.Approval_Status__c = 'Draft';
                quo.Is_Customer_Confirmed__c = false;
                quo.Approval_Time__c = null;
                quo.OwnerId = System.UserInfo.getUserId();
                update quo;

                //成本重新计算
                List<Quote_Detail__c> qdList = new List<Quote_Detail__c>();
                for (Quote_Detail__c qd : [SELECT Process_Cost__c,Cost__c,Order_Qnty__c,CIF_90_Days__c,Inland_Cost_Including_Insurance__c,Clearance_Cost_Percentage__c,Quote_Detail__c.Commission__c,Quote_Detail__c.Freight_Cost__c,Quote_Detail__c.Pallet__c,Quote_Detail__c.Packing_Cost__c,Quote__r.Quotation_Type__c,Payment_Terms__c,FOB_Price__c,Price_List__c,Id,Quote__r.Payment_Term_Cost_Rate__c,Price_List__r.Unit__c,Price_List__r.FOB_Price__c FROM Quote_Detail__c WHERE Quote__c=:quo.Id]) {
                    System.debug('进入逻辑');
                    if (qd.Price_List__c!=null) {//fob重新赋值
                        qd.FOB_Price__c = qd.Price_List__r.FOB_Price__c;
                        qd.Unit__c = qd.Price_List__r.Unit__c;
                    }
                    qd.Payment_Terms__c = qd.Quote__r.Payment_Term_Cost_Rate__c;
                    BatchImportQuoteDetailController.setData(qd,qd.Quote__r.Quotation_Type__c);
                    qdList.add(qd);
                }
                if (qdList.size()>0) {
                    Database.update(qdList);
                }
                
                out.isSucess = true;
                out.errorMsg = 'Clone Successful';
                out.newRecordId = oldToNewIdMap.get(quoteRecordId);
                return out;
            } else {
                Database.rollback(sp);
                Output out = new Output();
                out.isSucess = false;
                out.errorMsg = rp.message;
                return out;
            }
        } catch (Exception e) {
            Database.rollback(sp);
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = e.getMessage()+'Line:'+e.getLineNumber();
            return out;
        }
        
    }
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}
        
        @AuraEnabled
        public String newRecordId {get;set;}
    }
}