force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Quotation_Type__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Type__c</fullName>
    <label>Quotation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HQ_Purchase</fullName>
                <label>Price List</label>
            </value>
            <value>
                <fullName>Tolling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/Quote_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Detail</label>
    <nameField>
        <displayFormat>QD-{000000}</displayFormat>
        <label>Quote Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Detail__c/fields/BU_Profit_Rate__c.field-meta.xml
<CustomField>
    <fullName>BU_Profit_Rate__c</fullName>
    <label>BU Margin Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product English Name</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Price_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Detail__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Detail</relationshipLabel>
    <relationshipName>Quote_Detail_Child</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FillInPriceListControllerTest.cls
@isTest
private class FillInPriceListControllerTest {
	 static testMethod void testMethod1() {
	 	Quote__c quote1 = new Quote__c();
        //quote1.Name = '报价测试';
        quote1.Quotation_Type__c = 'HQ_Purchase';
        insert quote1;

        Quote_Detail__c quoteDetail=new Quote_Detail__c();
        quoteDetail.Quote__c = quote1.Id;
        quoteDetail.BU_Profit_Rate__c=-10;
        Insert quoteDetail;

        Price_List__c priceList=new Price_List__c();
        priceList.Name=quote1.Name;
        insert priceList;

        FillInPriceListController.setValue(quoteDetail.Id,priceList.Id);
	 }
    
}