force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/Is_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PriceListDataBatchTest.cls
@isTest
private class PriceListDataBatchTest {
	static testMethod void testMethod1() {

        Price_List__c priceList=new Price_List__c();
        priceList.Is_Delete__c=false;
        insert priceList;
        

        PriceListDataBatch svo = new PriceListDataBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
        System.schedule('Test','0 35 6 * * ? *',New PriceListDataBatch());
	 }
    
}