force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery__c</fullName>
    <label>Delivery Note Creator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Date__c</fullName>
    <label>Delivery Note Created Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Time__c</fullName>
    <label>Delivery Note Created Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Amount__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Amount__c</fullName>
    <label>Delivery Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Cost__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Cost__c</fullName>
    <label>Delivery Cost(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Note_Item_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Item_Num__c</fullName>
    <label>SAP Delivery Note Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Note_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Num__c</fullName>
    <label>SAP Delivery Note Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Number</label>
    <referenceTo>DeliveryNumber__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Delivery Quantity(Order Unit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Quantity_Delivery_Unit__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity_Delivery_Unit__c</fullName>
    <label>Delivery Quantity(Delivery Unit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Unit__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Unit__c</fullName>
    <label>Delivery Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/POD_Status__c.field-meta.xml
<CustomField>
    <fullName>POD_Status__c</fullName>
    <label>POD Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Reference_Order__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order__c</fullName>
    <label>Reference Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Reference_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order_Item__c</fullName>
    <label>Reference Order Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/SAP_Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Quantity__c</fullName>
    <label>SAP Delivery Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/SAP_Delivery_Quantity_Delivery_Unit__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Quantity_Delivery_Unit__c</fullName>
    <label>SAP Delivery Quantity Delivery Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Storage_Location__c.field-meta.xml
<CustomField>
    <fullName>Storage_Location__c</fullName>
    <label>Storage Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Storage_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/DeliveryNumber__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery__c</fullName>
    <label>Creator Delivery</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Date__c</fullName>
    <label>Creator Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Time__c</fullName>
    <label>Creator Delivery Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category__c</fullName>
    <label>Delivery Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Note_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Num__c</fullName>
    <label>Delivery Note Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Date__c</fullName>
    <label>Delivery Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Delivery Number</relationshipLabel>
    <relationshipName>Delivery_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Delivery_Amount__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Amount__c</fullName>
    <label>Delivered Amount</label>
    <summarizedField>Delivery_Note__c.Delivery_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Delivery_Note__c.Delivery_Post_Status__c</field>
        <operation>equals</operation>
        <value>B 	Partially processed, C 	Completely processed</value>
    </summaryFilterItems>
    <summaryForeignKey>Delivery_Note__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Reference_Order__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Reference Order</relationshipLabel>
    <relationshipName>Related_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code2__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code2__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number 2</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Order Item Delivered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/External_Id2__c.field-meta.xml
<CustomField>
    <fullName>External_Id2__c</fullName>
    <label>External Id2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Reference_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Reference Order Item)</relationshipLabel>
    <relationshipName>Reference_Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZMX1</fullName>
        <label>ZMX1	Outbound Delivery MX</label>
    </customValue>
    <customValue>
        <fullName>ZMX2</fullName>
        <label>ZMX2	Returns Delivery MX</label>
    </customValue>
    <customValue>
        <fullName>ZAR1</fullName>
        <label>ZAR1	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZAR2</fullName>
        <label>ZAR2	Returns Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZAR6</fullName>
        <label>ZAR6	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZAR7</fullName>
        <label>ZAR7	Delivery w/o Ref.</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>ZARA	Returns Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARB</fullName>
        <label>ZARB	Outbound Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARE</fullName>
        <label>ZARE	Outbound Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARF</fullName>
        <label>ZARF	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZLF1</fullName>
        <label>ZLF1_出库交货1</label>
    </customValue>
    <customValue>
        <fullName>ZLF2</fullName>
        <label>ZLF2_出库交货2</label>
    </customValue>
    <customValue>
        <fullName>ZLF3</fullName>
        <label>ZLF3_出库交货3</label>
    </customValue>
    <customValue>
        <fullName>ZLF4</fullName>
        <label>ZLF4_出库交货4</label>
    </customValue>
    <customValue>
        <fullName>ZLF5</fullName>
        <label>ZLF5_出库交货5</label>
    </customValue>
    <customValue>
        <fullName>ZLFI</fullName>
    </customValue>
    <customValue>
        <fullName>ZLO</fullName>
        <label>ZLO_短驳交货</label>
    </customValue>
    <customValue>
        <fullName>ZLO1</fullName>
        <label>ZLO1_短驳交货-领料</label>
    </customValue>
    <customValue>
        <fullName>ZLO2</fullName>
        <label>ZLO2_短驳交货-移库</label>
    </customValue>
    <customValue>
        <fullName>ZLO3</fullName>
        <label>ZLO3_其它调拨</label>
    </customValue>
    <customValue>
        <fullName>ZLRI</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR8</fullName>
    </customValue>
    <customValue>
        <fullName>LR</fullName>
    </customValue>
    <masterLabel>Delivery Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Storage_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GEN</fullName>
        <label>GEN General</label>
    </customValue>
    <customValue>
        <fullName>PROD</fullName>
        <label>PROD Productos</label>
    </customValue>
    <customValue>
        <fullName>AR05</fullName>
        <label>AR05 SLA en Alsina</label>
    </customValue>
    <customValue>
        <fullName>AR06</fullName>
        <label>AR06 SLA en Zárate</label>
    </customValue>
    <customValue>
        <fullName>AR07</fullName>
        <label>AR07 Greencrops Guale</label>
    </customValue>
    <customValue>
        <fullName>AR08</fullName>
        <label>AR08 Daser en Victori</label>
    </customValue>
    <customValue>
        <fullName>AR09</fullName>
        <label>AR09 Deylar en San Fr</label>
    </customValue>
    <customValue>
        <fullName>AR10</fullName>
        <label>AR10 Tokbritz en Chac</label>
    </customValue>
    <customValue>
        <fullName>AR11</fullName>
        <label>AR11 Agrosyn America</label>
    </customValue>
    <customValue>
        <fullName>AR12</fullName>
        <label>AR12 AGSOF S.A.</label>
    </customValue>
    <customValue>
        <fullName>AR13</fullName>
        <label>AR13 TUCAGRO</label>
    </customValue>
    <customValue>
        <fullName>AR14</fullName>
        <label>AR14 PROAGRO</label>
    </customValue>
    <customValue>
        <fullName>AR15</fullName>
        <label>AR15 PAMPA GRANDE</label>
    </customValue>
    <customValue>
        <fullName>AR16</fullName>
        <label>AR16 TORUNO</label>
    </customValue>
    <customValue>
        <fullName>AR17</fullName>
        <label>AR17 LUIS BLANCO</label>
    </customValue>
    <customValue>
        <fullName>MAFO</fullName>
        <label>MAFOAGRI</label>
    </customValue>
    <customValue>
        <fullName>TRAE</fullName>
    </customValue>
    <customValue>
        <fullName>SAMP</fullName>
        <label>SAMPLES</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0088</fullName>
    </customValue>
    <customValue>
        <fullName>0100</fullName>
    </customValue>
    <customValue>
        <fullName>0200</fullName>
    </customValue>
    <customValue>
        <fullName>BY01</fullName>
    </customValue>
    <customValue>
        <fullName>BY02</fullName>
    </customValue>
    <customValue>
        <fullName>BY03</fullName>
    </customValue>
    <customValue>
        <fullName>BY04</fullName>
    </customValue>
    <customValue>
        <fullName>BY05</fullName>
    </customValue>
    <customValue>
        <fullName>BY06</fullName>
    </customValue>
    <customValue>
        <fullName>BY07</fullName>
    </customValue>
    <customValue>
        <fullName>BY08</fullName>
    </customValue>
    <masterLabel>Storage Location</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPDeliveryNoteWebService.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 04-07-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   11-20-2025   Gerry   Initial Version
**/
@RestResource(urlMapping='/SAPDeliveryNoteWebService')
global without sharing class SAPDeliveryNoteWebService {
    global class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqDeliveryNoteInfo> resultinfo;
    }
    
    global class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
    }
    
    global class ReqDeliveryNoteInfo{
        public String VBELN;//交货单号
        public String LFART;//交货类型
        public String ERNAM;//交货单创建人
        public String ERDAT;//交货单创建日期
        public String ERZET;//交货单创建时间
        public Date wadat_ist;//发货过账日期
        public String WBSTK;//发货过账状态
        public String PDSTK;//POD状态
        public List<DeliveryNoteRow> ITEMS;
    }
    
    
    global class DeliveryNoteRow{
        public String VRKME1;//交货单位
        public Decimal ZQCOV;//交货数量(订单单位)
        public String POSNR;//交货单行号
        public Decimal LFIMG;//交货数量(交货单单位)
        public String WERKS;//工厂
        public String LGORT;//库存地点
        public String CHARG;//批次
        public String VGBEL;//参考订单号
        public String VGPOS;//参考订单行号
        public String MATNR;//物料编码
        public String ARKTX; //物料描述
        public String ZDELIVERY_COST;//发货成本
    }
    
    /**
     * SAP发货单同步接口
     * @param bodyStrJson bodyStrJson
     *
     * @return ResponseBody
     */
    @HttpPost
    global static SAPOrderWebService.ResponseBody doPost() {
        String respTime = String.valueOf(Datetime.now());
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String bodyStrJson = req.requestBody.toString();
        
        List<String> dataIdList = new List<String>();
        List<SAPOrderWebService.ReturnData> returnDataList = new List<SAPOrderWebService.ReturnData>();
        
        Boolean isSuccess = true;
        Boolean isPartSuccess = false;
        Savepoint sp = Database.setSavepoint();
        
        String errorMsg;
        try {
            System.debug('bodyStrJson1==' + bodyStrJson);
            RequestBody reqBody = (RequestBody) JSON.deserialize(bodyStrJson, RequestBody.class);
            SAPOrderWebService.Output out = feedbackOrderInfo(reqBody.resultinfo);
            isSuccess = out.isSuccess;
            isPartSuccess = out.isPartSuccess;
            errorMsg = out.error;
            returnDataList = out.ReturnDataList;
        } catch (Exception e) {
            Database.rollback(sp);
            errorMsg = InterfaceUtility.getProperErrorMessage(e.getMessage()) + '[' + e.getLineNumber() + ']';
            // System.debug('出现错误：' + respBody.message);
            isSuccess = false;
        }
        SAPOrderWebService.ResponseBody response = SAPOrderWebService.returnData(respTime, isSuccess, errorMsg, returnDataList);
        InterfaceUtility.insertInterfaceLog('SAPDeliveryNoteWebService', 'SAP', 'CRM',
        '/services/apexrest/receiveDataFromExternal/  requestCode:SAP003', bodyStrJson, isSuccess, isPartSuccess,
        JSON.serialize(response), errorMsg, 'POST', dataIdList, 'Upsert', 'SAP同步发货单至CRM'
            );
        
        return response;
    }
    
    public static SAPOrderWebService.Output feedbackOrderInfo(List<ReqDeliveryNoteInfo> resultinfo) {
        Boolean isPartSuccess = false;
        List<Delivery_Note__c> deliveryNoteList = new List<Delivery_Note__c>();
        Map<Integer,Delivery_Note__c> deliveryNoteMap = new Map<Integer,Delivery_Note__c>();
        SAPOrderWebService.Output out = new SAPOrderWebService.Output();
        out.ReturnDataList = new List<SAPOrderWebService.ReturnData>();
        SAPOrderWebService.ReturnData returnDataMsgTmp;
        Integer deliveryNoteIndex = 0;
        Set<String> orderItemSet = new Set<String>();
        set<String> orderSet = new Set<String>();
        for(ReqDeliveryNoteInfo rdni : resultinfo){
            for (DeliveryNoteRow dnr : rdni.ITEMS) {
                orderItemSet.add(dnr.VGBEL+'_'+dnr.VGPOS);
                orderSet.add(dnr.VGBEL);
            }
        }
        List<Order_Item__c> oiList = [SELECT Id,External_Id__c,Order__c,External_Id2__c,Price__c 
                                        FROM Order_Item__c 
                                        WHERE External_Id__c IN: orderItemSet OR External_Id2__c IN: orderItemSet];
        Map<String,Order_Item__c> oiMap = new Map<String,Order_Item__c>();
        if (oiList.size()>0) {
            for(Order_Item__c o : oiList){
                oiMap.put(o.External_Id__c,o);
                if (o.External_Id2__c!=null) {
                    oiMap.put(o.External_Id2__c,o);
                }
            }
        }
        
        Map<String,Order__c> orMap = new Map<String,Order__c>();
        for (Order__c order : [SELECT Id,SAP_Order_Code__c,SAP_Order_Code2__c FROM Order__c WHERE SAP_Order_Code__c IN:orderSet OR SAP_Order_Code2__c IN:orderSet]) {
            orMap.put(order.SAP_Order_Code__c, order);
            if (order.SAP_Order_Code2__c!=null) {
                orMap.put(order.SAP_Order_Code2__c,order);
            }
        }
        List<DeliveryNumber__c> dnPaInserList = new List<DeliveryNumber__c>();
        for(ReqDeliveryNoteInfo rdni : resultinfo){
            String orderCode = '';
            Boolean flag = false;
            for (DeliveryNoteRow dnr : rdni.ITEMS) {
                orderCode = dnr.VGBEL;
                Delivery_Note__c dn = new Delivery_Note__c();
                DeliveryNumber__c dnRe = new DeliveryNumber__c();
                dnRe.External_Id__c = rdni.VBELN;
                dn.Delivery_Number__r = dnre;
                //头部分
                dn.Delivery_Note_Num__c = rdni.VBELN;
                dn.Delivery_Category__c = rdni.LFART;
                dn.Creator_Delivery__c = rdni.ERNAM;
                dn.Creator_Delivery_Date__c = rdni.ERDAT;
                dn.Creator_Delivery_Time__c = rdni.ERZET;
                dn.Delivery_Post_Date__c = Date.valueOf(rdni.wadat_ist);
                dn.Delivery_Post_Status__c = rdni.WBSTK;
                dn.POD_Status__c = rdni.PDSTK;
                dn.External_Id__c = rdni.VBELN+'_'+dnr.POSNR;

                
                
                //ITEMS部分
                dn.Delivery_Note_Item_Num__c = dnr.POSNR;
                if (dn.Delivery_Post_Status__c == 'A') {
                    dn.Delivery_Quantity__c = 0;
                    dn.Delivery_Quantity_Delivery_Unit__c = 0;
                }else{
                    dn.Delivery_Quantity__c = dnr.ZQCOV;
                    dn.Delivery_Quantity_Delivery_Unit__c = dnr.LFIMG;
                }
                dn.SAP_Delivery_Quantity__c = dnr.ZQCOV;
                dn.SAP_Delivery_Quantity_Delivery_Unit__c = dnr.LFIMG;
                dn.Delivery_Unit__c = dnr.VRKME1;
                dn.Plant__c = dnr.WERKS;
                
                // dn.Storage_Location__c = dnr.WERKS+'-'+dnr.LGORT;
                dn.Storage_Location__c = dnr.LGORT;
                dn.Batch__c = dnr.CHARG;
                dn.Reference_Order__c = dnr.VGBEL;
                dn.Reference_Order_Item__c = dnr.VGPOS;
                if (oiMap.containsKey(dnr.VGBEL+'_'+dnr.VGPOS)) {
                    dn.Order_Item__c = oiMap.get(dnr.VGBEL+'_'+dnr.VGPOS).Id;
                }else{
                    returnDataMsgTmp = new SAPOrderWebService.ReturnData();
                    returnDataMsgTmp.vbeln = rdni.VBELN;
                    returnDataMsgTmp.posnr = dnr.POSNR;
                    returnDataMsgTmp.msgty = 'E';
                    returnDataMsgTmp.msgtx = dnr.VGBEL+'_'+dnr.VGPOS+'不存在！';
                    out.ReturnDataList.add(returnDataMsgTmp);
                    isPartSuccess = true;
                    
                    continue;
                }
                
                if (orMap.containsKey(dnr.VGBEL)) {
                    dn.Order__c = orMap.get(dnr.VGBEL).Id;
                }else{
                    returnDataMsgTmp = new SAPOrderWebService.ReturnData();
                    returnDataMsgTmp.vbeln = rdni.VBELN;
                    returnDataMsgTmp.posnr = dnr.POSNR;
                    returnDataMsgTmp.msgty = 'E';
                    returnDataMsgTmp.msgtx = dnr.VGBEL+'不存在！';
                    out.ReturnDataList.add(returnDataMsgTmp);
                    isPartSuccess = true;
                    
                    continue;
                }
                if(dn.Delivery_Quantity__c==null) {
                    returnDataMsgTmp = new SAPOrderWebService.ReturnData();
                    returnDataMsgTmp.vbeln = rdni.VBELN;
                    returnDataMsgTmp.posnr = dnr.POSNR;
                    returnDataMsgTmp.msgty = 'E';
                    returnDataMsgTmp.msgtx = rdni.VBELN+'_'+dnr.POSNR+'没有传数量';
                    out.ReturnDataList.add(returnDataMsgTmp);
                    isPartSuccess = true;
                    
                    continue;
                }
                
                if (oiMap.containsKey(dnr.VGBEL+'_'+dnr.VGPOS) && oiMap.get(dnr.VGBEL+'_'+dnr.VGPOS).Price__c != null) {
                    dn.Delivery_Amount__c = dn.Delivery_Quantity__c*oiMap.get(dnr.VGBEL+'_'+dnr.VGPOS).Price__c;
                }
                deliveryNoteList.add(dn);
                dn.Material_Code__c = dnr.MATNR;//物料编码
                dn.Description__c = dnr.ARKTX; //物料描述
                deliveryNoteMap.put(deliveryNoteIndex,dn);
                deliveryNoteIndex++;
                if (String.isNotBlank(dnr.ZDELIVERY_COST)) {
                    dn.Delivery_Cost__c = Decimal.valueOf(dnr.ZDELIVERY_COST);//发货成本
                }
                
                flag = true;
            }
            if (flag) {
                DeliveryNumber__c dnPa = new DeliveryNumber__c();
                dnPa.Delivery_Note_Num__c = rdni.VBELN;
                dnPa.Delivery_Category__c = rdni.LFART;
                dnPa.Creator_Delivery__c = rdni.ERNAM;
                dnPa.Creator_Delivery_Date__c = Date.valueOf(rdni.ERDAT);
                dnPa.Creator_Delivery_Time__c = rdni.ERZET;
                dnPa.Delivery_Post_Date__c = Date.valueOf(rdni.wadat_ist);
                dnPa.Delivery_Post_Status__c = rdni.WBSTK;
                dnPa.POD_Status__c = rdni.PDSTK;
                dnPa.External_Id__c = rdni.VBELN;
                dnPa.Order__c = orMap.get(orderCode).Id;
                dnPaInserList.add(dnPa);
            }
            
        }
        
        // if (deliveryNoteList.size() > 0) {
            // Database.upsert(deliveryNoteList,Delivery_Note__c.fields.External_Id__c, true);
        // }
        SAPOrderWebService.ReturnData returnDataMsg;
        String errorStr = '';
        String code = '';
        Integer index = 0;
        Integer resultIndex = 0;
        if (dnPaInserList.size() > 0) {
            Database.upsert(dnPaInserList,DeliveryNumber__c.fields.External_Id__c);
        }
        if (deliveryNoteMap.size() > 0) {
            resultIndex = 0;
            List<Database.UpsertResult> resultList = Database.upsert(deliveryNoteMap.values(),Delivery_Note__c.fields.External_Id__c, false);
            for(Integer i=0;i<resultList.size();i++) {
                Database.UpsertResult result = resultList[resultIndex];
                returnDataMsg = new SAPOrderWebService.ReturnData();
                errorStr = '';
                code = '';
                index = 0;
                if(!result.isSuccess()) {
                    for(Database.Error errorStrItem : result.getErrors()) {
                        errorStr = errorStr + errorStrItem.getMessage();
                    }
                    code = deliveryNoteMap.get(resultIndex).External_Id__c;
                    index = code.indexOf('_');
                    returnDataMsg.vbeln = code.substring(0,index);
                    returnDataMsg.posnr = code.substring(index + 1);
                    returnDataMsg.msgty = 'E';
                    returnDataMsg.msgtx = errorStr;
                    out.ReturnDataList.add(returnDataMsg);
                    isPartSuccess = true;
                } else {
                    code = deliveryNoteMap.get(resultIndex).External_Id__c;
                    index = code.indexOf('_');
                    returnDataMsg.vbeln = code.substring(0,index);
                    returnDataMsg.posnr = code.substring(index + 1);
                    returnDataMsg.msgty = 'S';
                    returnDataMsg.msgtx = 'The data is successfully written!';
                    out.ReturnDataList.add(returnDataMsg);
                }
                resultIndex++;
            }
        }
        out.isSuccess = true;
        out.isPartSuccess = isPartSuccess;
        return out;
    }
}