force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery__c</fullName>
    <label>Delivery Note Creator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Date__c</fullName>
    <label>Delivery Note Created Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Creator_Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Time__c</fullName>
    <label>Delivery Note Created Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Note_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Num__c</fullName>
    <label>SAP Delivery Note Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/POD_Status__c.field-meta.xml
<CustomField>
    <fullName>POD_Status__c</fullName>
    <label>POD Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/DeliveryNumber__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery__c</fullName>
    <label>Creator Delivery</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Date__c</fullName>
    <label>Creator Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Creator_Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Creator_Delivery_Time__c</fullName>
    <label>Creator Delivery Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category__c</fullName>
    <label>Delivery Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Note_Num__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Num__c</fullName>
    <label>Delivery Note Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Date__c</fullName>
    <label>Delivery Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Delivery Number</relationshipLabel>
    <relationshipName>Delivery_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Delivery_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZMX1</fullName>
        <label>ZMX1	Outbound Delivery MX</label>
    </customValue>
    <customValue>
        <fullName>ZMX2</fullName>
        <label>ZMX2	Returns Delivery MX</label>
    </customValue>
    <customValue>
        <fullName>ZAR1</fullName>
        <label>ZAR1	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZAR2</fullName>
        <label>ZAR2	Returns Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZAR6</fullName>
        <label>ZAR6	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZAR7</fullName>
        <label>ZAR7	Delivery w/o Ref.</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>ZARA	Returns Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARB</fullName>
        <label>ZARB	Outbound Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARE</fullName>
        <label>ZARE	Outbound Delivery</label>
    </customValue>
    <customValue>
        <fullName>ZARF</fullName>
        <label>ZARF	Overseas delivery 1</label>
    </customValue>
    <customValue>
        <fullName>ZLF1</fullName>
        <label>ZLF1_出库交货1</label>
    </customValue>
    <customValue>
        <fullName>ZLF2</fullName>
        <label>ZLF2_出库交货2</label>
    </customValue>
    <customValue>
        <fullName>ZLF3</fullName>
        <label>ZLF3_出库交货3</label>
    </customValue>
    <customValue>
        <fullName>ZLF4</fullName>
        <label>ZLF4_出库交货4</label>
    </customValue>
    <customValue>
        <fullName>ZLF5</fullName>
        <label>ZLF5_出库交货5</label>
    </customValue>
    <customValue>
        <fullName>ZLFI</fullName>
    </customValue>
    <customValue>
        <fullName>ZLO</fullName>
        <label>ZLO_短驳交货</label>
    </customValue>
    <customValue>
        <fullName>ZLO1</fullName>
        <label>ZLO1_短驳交货-领料</label>
    </customValue>
    <customValue>
        <fullName>ZLO2</fullName>
        <label>ZLO2_短驳交货-移库</label>
    </customValue>
    <customValue>
        <fullName>ZLO3</fullName>
        <label>ZLO3_其它调拨</label>
    </customValue>
    <customValue>
        <fullName>ZLRI</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR8</fullName>
    </customValue>
    <customValue>
        <fullName>LR</fullName>
    </customValue>
    <masterLabel>Delivery Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateDeliveryNoteBatch.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 01-23-2026
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   01-23-2026   Gerry   Initial Version
**/
global without sharing class GenerateDeliveryNoteBatch  implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful{
    public String query;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;
    global GenerateDeliveryNoteBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT Order__c,Delivery_Note_Num__c,Delivery_Category__c,Creator_Delivery__c,Creator_Delivery_Date__c,Creator_Delivery_Time__c,Delivery_Post_Date__c,Delivery_Post_Status__c,POD_Status__c FROM Delivery_Note__c';
    }
 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Delivery_Note__c> dnList) {
        try {
            Map<String,DeliveryNumber__c> dnPaInserList = new Map<String,DeliveryNumber__c>();
            for (Delivery_Note__c dn : dnList) {
                DeliveryNumber__c dnPa = new DeliveryNumber__c();
                dnPa.Delivery_Note_Num__c = dn.Delivery_Note_Num__c;
                dnPa.Delivery_Category__c = dn.Delivery_Category__c;
                dnPa.Creator_Delivery__c = dn.Creator_Delivery__c;
                if (dn.Creator_Delivery_Date__c != null) {
                    dnPa.Creator_Delivery_Date__c = Date.valueOf(dn.Creator_Delivery_Date__c);
                }
                
                dnPa.Creator_Delivery_Time__c = dn.Creator_Delivery_Time__c;
                dnPa.Delivery_Post_Date__c = dn.Delivery_Post_Date__c;
                dnPa.Delivery_Post_Status__c = dn.Delivery_Post_Status__c;
                dnPa.POD_Status__c = dn.POD_Status__c;
                dnPa.External_Id__c = dn.Delivery_Note_Num__c;
                dnPa.Order__c = dn.Order__c;
                dnPaInserList.put(dnPa.External_Id__c,dnPa);
            }
            if (dnPaInserList.size()>0) {
                Database.upsert(dnPaInserList.values(),DeliveryNumber__c.External_Id__c);
            }
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('GenerateDeliveryNoteBatch', this.flag, this.startTime, this.errorMsg);
        DeliveryNoteItemToDeliveryNote svo = new DeliveryNoteItemToDeliveryNote();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
    }
}