force-app/main/default/objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Item</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Delivery_Note1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item Number</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT( Order__r.Order_type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note__c/fields/Reference_Order__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order__c</fullName>
    <label>Reference Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Reference_Order__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Reference Order</relationshipLabel>
    <relationshipName>Related_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Closure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closure_Reason__c</fullName>
    <label>Closure Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Closure_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZARB Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Closure_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01	Assigned by the System (Internal)</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02	Delivery date too late</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03	Poor quality</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04	Too expensive</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05	Competitor better</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06	Guarantee</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10	Unreasonable request</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11	Cust.to receive replacement</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12	suspend order</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50	Transaction is being checked</label>
    </customValue>
    <customValue>
        <fullName>CR</fullName>
        <label>CR	Copied and Rejected</label>
    </customValue>
    <customValue>
        <fullName>G1</fullName>
        <label>G1	SMP-Notification</label>
    </customValue>
    <customValue>
        <fullName>G2</fullName>
        <label>G2	SMP-Suspended</label>
    </customValue>
    <customValue>
        <fullName>G3</fullName>
        <label>G3	SMP-Declined</label>
    </customValue>
    <customValue>
        <fullName>G4</fullName>
        <label>G4	SMP-Flagged (Deleted during Release)</label>
    </customValue>
    <customValue>
        <fullName>J1</fullName>
        <label>J1	DRM Claim Canellation/Rejection</label>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
        <label>LV	Bill of services completed</label>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <label>NR	Copy Failure: New SA Rejected</label>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <label>Z1	Cancel by Customer</label>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 Cancalled sales order</label>
    </customValue>
    <masterLabel>Closure Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloseOrderController.cls
/**************************************************************************************************
 * Name: NotificationService
 * Object: 
 * Purpose: 订单关闭
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-20         Created             
***************************************************************************************************/
public without sharing class CloseOrderController {
    @AuraEnabled
    public static Output closeOrder(String orderRecordId,String reasonText) {
        SavePoint sp;
        try {
            Order_Item__c oi = [SELECT Id,Order__c,Order__r.Reference_Order__c,(SELECT Id FROM Delivery_Note__r),Order__r.Order_type__c,Delivery_Note__c FROM Order_Item__c WHERE ID =:orderRecordId];
            // if (oi.Delivery_Note__r!=null && oi.Delivery_Note__r.size()>0) {
            //     Output out = new Output();            out.isSucess = false;            out.errorMsg = 'Can not close the order item';            return out;
            // }
            
            if (
                (oi.Order__r.Order_type__c == 'ZARE' || oi.Order__r.Order_type__c == 'ZARA' || oi.Order__r.Order_type__c == 'ZARF') &&
                oi.Delivery_Note__c==null
            ) {
                Output out = new Output();            
                out.isSucess = false;            
                out.errorMsg = 'Please contact the administrator to delete this order.';            
                return out;
            }
            
            OrderSyncToSAP.ReturnResult rr = OrderSyncToSAP.submitToSAP(oi.Order__c, 'U',true,false,reasonText,orderRecordId,true,false);
            sp = Database.setSavePoint();
            if (rr.isSuccess || System.Test.isRunningTest()) {
                Output out = new Output();
                out.isSucess = true;
                Order_Item__c ord = new Order_Item__c();
                ord.Id = orderRecordId;
                ord.isClosed__c = true;
                ord.Closure_Reason__c = reasonText;
                update ord;
                if ((oi.Order__r.Order_type__c == 'ZMX3' || oi.Order__r.Order_type__c == 'ZMX4' || oi.Order__r.Order_type__c == 'ZMX2') && oi.Order__r.Reference_Order__c!=null) {//墨西哥相关逆向订单
                    SubmitOrderController.calculateZMX1Rate(oi.Order__c, false);
                }
                return out;
            }else{
                Database.rollback(sp);
                Output out = new Output();            out.isSucess = false;            out.errorMsg = rr.message;     return out;
            }
        } catch (Exception e) {
            if (sp!=null) {
                Database.rollback(sp);
            }
            
            Output out = new Output();            
            out.isSucess = false;        
            System.debug('e.getMessage()====>'+e.getMessage());    
            out.errorMsg = Utility.getCustomMessage(e.getMessage(), False);            
            return out;
        }
        
    }

    @AuraEnabled
    public static Output init(String orderRecordId) {
        SavePoint sp = Database.setSavepoint();
        try {
            Output out = new Output();
            out.isSucess = true;
            out.optionList = new List<Option>();
            List<Utility.PicklistItem> valueMap = Utility.getPicklistValueList('Order_Item__c', 'Closure_Reason__c');
            Order_Item__c ord = new Order_Item__c();
            ord.Id = orderRecordId;
            ord.isClosed__c = true;
            update ord;
            for (Utility.PicklistItem pi : valueMap) {
                Option op = new Option();
                op.Label = pi.label;
                op.Value = pi.value;
                out.optionList.add(op);
            }
            System.debug('out.optionList=====>'+out.optionList);
            Database.rollback(sp);
            return out;
        } catch (Exception e) {
            Database.rollback(sp);
            Output out = new Output();
            out.isSucess = false;
            out.errorMsg = Utility.getCustomMessage(e.getMessage(), false); 
            return out;
        }
    }

    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}

        @AuraEnabled
        public List<Option> optionList {get;set;}
    }

    public class Option {
        @AuraEnabled
        public String label {get;set;}

        @AuraEnabled
        public String value {get;set;}
    }
}