force-app/main/default/objects/Customer_Tax_Category__c/Customer_Tax_Category__c.object-meta.xml
<CustomObject>
    <label>Customer Tax Category</label>
    <nameField>
        <displayFormat>CTC-{000000}</displayFormat>
        <label>Customer Tax Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Is_Sync__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync__c</fullName>
    <formula>Sales_View__r.isSync__c</formula>
    <label>Synced to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Sales_View__c.field-meta.xml
<CustomField>
    <fullName>Sales_View__c</fullName>
    <label>Sales View</label>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Customer Tax Category</relationshipLabel>
    <relationshipName>Customer_Tax_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Tax_Category__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tax_Category_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tax_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tax_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-Responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>2-Responsable no IVA</fullName>
    </customValue>
    <customValue>
        <fullName>3-No responsable IVA</fullName>
    </customValue>
    <customValue>
        <fullName>4-Sujeto exención IVA</fullName>
    </customValue>
    <customValue>
        <fullName>5-IVA Consumidor Final</fullName>
    </customValue>
    <customValue>
        <fullName>6-Respons. Monotributo</fullName>
    </customValue>
    <customValue>
        <fullName>7-Monotributo Resp.Imp</fullName>
    </customValue>
    <customValue>
        <fullName>8-Suj. no categorizado</fullName>
    </customValue>
    <customValue>
        <fullName>9-Cliente del exterior</fullName>
    </customValue>
    <customValue>
        <fullName>0-CABA Sin Padrón</fullName>
    </customValue>
    <customValue>
        <fullName>A-CABA A.Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>B-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>C-CABA Dif.0,50%</fullName>
    </customValue>
    <customValue>
        <fullName>D-CABA Dif.0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>E-CABA RG Grupo 01</fullName>
    </customValue>
    <customValue>
        <fullName>F-CABA RG Grupo 02</fullName>
    </customValue>
    <customValue>
        <fullName>G-CABA RG Grupo 03</fullName>
    </customValue>
    <customValue>
        <fullName>H-CABA RG Grupo 04</fullName>
    </customValue>
    <customValue>
        <fullName>I-CABA RG Grupo 05</fullName>
    </customValue>
    <customValue>
        <fullName>J-CABA RG Grupo 06</fullName>
    </customValue>
    <customValue>
        <fullName>K-CABA RG Grupo 07</fullName>
    </customValue>
    <customValue>
        <fullName>L-CABA RG Grupo 08</fullName>
    </customValue>
    <customValue>
        <fullName>M-CABA RG Grupo 09</fullName>
    </customValue>
    <customValue>
        <fullName>N-CABA RG Grupo 10</fullName>
    </customValue>
    <customValue>
        <fullName>O-CABA RG Grupo 11</fullName>
    </customValue>
    <customValue>
        <fullName>P-CABA RG Grupo 12</fullName>
    </customValue>
    <customValue>
        <fullName>Q-CABA RG Grupo 13</fullName>
    </customValue>
    <customValue>
        <fullName>R-CABA RG Grupo 14</fullName>
    </customValue>
    <customValue>
        <fullName>S-CABA RG Grupo 15</fullName>
    </customValue>
    <customValue>
        <fullName>T-CABA RG Grupo 16</fullName>
    </customValue>
    <masterLabel>Tax Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerTaxCategoryTriggerHandler.cls
public without sharing class CustomerTaxCategoryTriggerHandler implements Triggers.Handler{
    public void handle() {
        if (Trigger.isAfter && Trigger.isUpdate) {
            for (Customer_Tax_Category__c ctc : (List<Customer_Tax_Category__c>)Trigger.new) {
                if(
                    ctc.Is_Sync__c &&

                    ((Customer_Tax_Category__c)Trigger.oldMap.get(ctc.Id)).Tax_Category__c != ctc.Tax_Category__c 
                    && !System.isBatch() && !System.isFuture()
                ) {
                    CustomerSalesInfoSyncToSAP.submitToSAPFutrue(ctc.Sales_View__c,'U');
                }
            }
        }
    }
}