force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <label>Customer Sales Info/Account Receivable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep_Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Delivery_Plant__c</fullName>
    <formula>TEXT(Sales_Rep__r.Delivery_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HQ Contracts (Customer)</relationshipLabel>
    <relationshipName>HQ_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quote_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Share.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Share</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeShareDataToAccountTeamBatch.cls
global without sharing class ChangeShareDataToAccountTeamBatch implements Database.Batchable<sObject>,Database.Stateful{
    global String query;
    global String obejctTyp;
    global String recordId;
    global String accId;
    global String fieldType;
    global String ownerData; 
    global String beforeDeliveryPlant;
    global String shareObject;  
    global ChangeShareDataToAccountTeamBatch(String obejctTyp,String recordId,String accId,String fieldType,String ownerData,String beforeDeliveryPlant,String shareObject) {
        this.obejctTyp = obejctTyp;
        this.recordId = recordId;
        this.accId = accId;
        this.fieldType = fieldType;
        this.ownerData = ownerData;
        this.beforeDeliveryPlant = beforeDeliveryPlant;
        this.shareObject = shareObject;
        this.query = 'SELECT Id,UserOrGroupId FROM '+shareObject+' WHERE  ' ;
        if(obejctTyp=='Customer_Sales_Info__c'){
                this.query=this.query+'ParentId=:recordId';
            }
        if(obejctTyp=='Order__c' || obejctTyp=='Quote__c'){
                this.query=this.query+'ParentId=:recordId';
            }
        if(obejctTyp=='Contracts__c'){
                this.query=this.query+'ParentId=:recordId';
            }
        if(obejctTyp=='Invoice__c'){
                this.query=this.query+'Parent.Order__c=:recordId';
            }

        system.debug('this.query=>'+this.query);

    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> shareDeleteList) {
        System.savepoint sp = Database.setSavepoint();
        try {
            Set<String>  userSet= new Set<String>();
            for(Account_Team__c accTeam:[SELECT Id,Sales_Rep_Delivery_Plant__c,Sales_Rep__c FROM Account_Team__c WHERE Customer__c=:this.accId AND Sales_Rep_Delivery_Plant__c=:this.beforeDeliveryPlant])
            {
                userSet.add(accTeam.Sales_Rep__c);
            }
            System.debug('userSet=>'+userSet);
            List<SObject> needDelShareList = new List<SObject>();
            for(SObject sb:shareDeleteList)
            {
                String userId=String.valueOf(sb.get('UserOrGroupId'));
                if (userSet != null && userSet.contains(userId)  && userId != this.ownerData) {
                    needDelShareList.add(sb);
                }
            }
            System.debug('needDelShareList=>'+needDelShareList);
            if (needDelShareList.size() > 0) {
                delete needDelShareList;
            }
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(e.getMessage()+e.getLineNumber());
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        ShareDataToAccountTeam.shareData(this.obejctTyp, this.recordId, this.accId,this.fieldType,this.ownerData);

    }
}