force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <label>Customer Sales Info/Account Receivable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Is_Ruuning__c.field-meta.xml
<CustomField>
    <fullName>Is_Ruuning__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Ruuning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep_Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Delivery_Plant__c</fullName>
    <formula>TEXT(Sales_Rep__r.Delivery_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <formula>TEXT(Order__r.Deliver_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShareDataQuery__c/ShareDataQuery__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ShareDataQuery</label>
</CustomObject>

force-app/main/default/objects/ShareDataQuery__c/fields/Sql__c.field-meta.xml
<CustomField>
    <fullName>Sql__c</fullName>
    <label>Sql</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Share.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Share</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShareAccountDataBatch.cls
/**************************************************************************************************
 * Name: ShareAccountDataBatch
 * Object: 
 * Purpose: 共享客户相关数据
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-08-20         Created             
***************************************************************************************************/
global without sharing class ShareAccountDataBatch implements Database.Batchable<sObject>,Database.Stateful{
    global String query;
    global String atRecordId;
    global Map<String, Schema.SObjectType> globalDescribe;
    global String obejctTyp;
    global String field;
    global Integer index;
    global String recordId;//客户Id
    global String errorMsg;
    global Boolean flag;
    global Datetime startTime;
    global ShareAccountDataBatch(String atRecordId,String recordId,Integer index) {
        this.index = index;
        this.startTime = System.now();
        this.flag = true;
        this.atRecordId = atRecordId;
        this.globalDescribe = Schema.getGlobalDescribe();
        this.recordId = recordId;
        ShareDataQuery__c sdq = [SELECT Id,Object__c,Sql__c,Field__c FROM ShareDataQuery__c WHERE Index__c=:index];
        this.query = sdq.Sql__c;
        this.obejctTyp = sdq.Object__c;
        this.field = sdq.Field__c;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> orderList) {
        System.savepoint sp = Database.setSavepoint();
        try {
            List<SObject> shareList = new List<SObject>();
            String objectName;
            if (this.obejctTyp.contains('_')) {
                objectName = this.obejctTyp.replace('__c', '__share');
            }else{
                objectName = this.obejctTyp+'Share';
            }
            List<Schema.FieldSetMember> fieldSetMembers = SObjectType.Account_Team__c.FieldSets.All_Filed.getFields();
            // 拼接需要复制得字段
            String orderQuery = 'SELECT ';
            String field = '';
            for (Schema.FieldSetMember f : fieldSetMembers) {
                if (String.isNotBlank(field)) {
                    field += ','+f.getFieldPath();
                }else{
                    field += f.getFieldPath();
                }
            }
            String atId = this.atRecordId;
            orderQuery = orderQuery+field+',Sales_Rep_Delivery_Plant__c FROM Account_Team__c WHERE Id=:atId AND Sales_Rep__r.IsActive=true';
            Account_Team__c at = Database.Query(orderQuery);
            for (SObject sb : orderList) {
                if (sb.get('OwnerId') == at.Sales_Rep__c) {
                    continue;
                }
                if (String.valueOf(at.get(this.field))=='Private') {
                    continue;
                }
                if (this.obejctTyp=='Customer_Sales_Info__c' && sb.get('Delivering_Plant__c') != null && sb.get('Delivering_Plant__c') != at.Sales_Rep_Delivery_Plant__c) {
                    continue;
                }
                if (this.obejctTyp=='Contracts__c' && sb.get('Delivery_Plant__c') != null && sb.get('Delivery_Plant__c') != at.Sales_Rep_Delivery_Plant__c) {
                    continue;
                }
                if ((this.obejctTyp=='Order__c' || this.obejctTyp=='Quote__c') && sb.get('Deliver_Plant__c') != null && sb.get('Deliver_Plant__c') != at.Sales_Rep_Delivery_Plant__c) {
                    continue;
                }
                if (this.obejctTyp=='Invoice__c'  && sb.get('Delivery_Plant__c') != null && sb.get('Delivery_Plant__c') != at.Sales_Rep_Delivery_Plant__c) {
                    continue;
                }
                SObject sharingObject = globalDescribe.get(objectName).newSObject();
                if (this.obejctTyp == 'Account') {
                    sharingObject.put('AccountId', sb.get('Id'));
                    sharingObject.put('AccountAccessLevel', String.valueOf(at.get(this.field)));
                    sharingObject.put('OpportunityAccessLevel', 'None');
                }else if(this.obejctTyp == 'Contact') {
                    sharingObject.put('ContactId', sb.get('Id'));
                    sharingObject.put('ContactAccessLevel', String.valueOf(at.get(this.field)));
                }else{
                    sharingObject.put('AccessLevel', String.valueOf(at.get(this.field)));
                    sharingObject.put('ParentId',sb.get('Id'));
                }
                
                
                sharingObject.put('RowCause','Manual');
                
                sharingObject.put('UserOrGroupId',at.Sales_Rep__c);
                shareList.add(sharingObject);
            }
            System.debug(shareList);
            Database.upsert(shareList);
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(e.getMessage()+e.getLineNumber());
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        Integer indexNext = this.index+1;
        List<ShareDataQuery__c> sdq = [SELECT Id,Object__c,Sql__c,Field__c FROM ShareDataQuery__c WHERE Index__c=:indexNext];
        Utility.setBatchInfo('ShareAccountDataBatch:'+this.atRecordId+':'+this.obejctTyp, this.flag, this.startTime, this.errorMsg);
        if (sdq.size()>0) {
            Database.executeBatch(new ShareAccountDataBatch(this.atRecordId,this.recordId,indexNext), 100);
        }else{
            Account_Team__c at = new Account_Team__c();
            at.Is_Ruuning__c = false;
            at.Id = this.atRecordId;
            Update at;
        }

    }
}