force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Invoice_Date_Month__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date_Month__c</fullName>
    <formula>TEXT(MONTH(Invoice_Date__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Date_Year__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date_Year__c</fullName>
    <formula>TEXT(YEAR(Invoice_Date__c  ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>IF(YEAR(Approve_Date__c)=YEAR(TODAY()), MONTH(Approve_Date__c),null )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/Sales_Forcast__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast Detail</label>
    <nameField>
        <displayFormat>SFD-{000000}</displayFormat>
        <label>Sales Forcast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forcast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Forcast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Sales_Forecast_Summary__c.field-meta.xml
<CustomField>
    <fullName>Sales_Forecast_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Forecast Summary</label>
    <referenceTo>Sales_Forecast_Summary__c</referenceTo>
    <relationshipLabel>Sales Forecast Detail</relationshipLabel>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/Sales_Forecast_Summary__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Sales Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forecast_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
            <value>
                <fullName>2052</fullName>
            </value>
            <value>
                <fullName>2053</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesForecastDataBatch.cls
/*
* Name: SalesForecastDataBatch
* Date: 2024-05-23
* Creator: Bob
* Description: 更新销售预测达成
* History: 
*------------------------------------------------
* Version    Last Modified By     Desription
* v1         Bob              Create
*------------------------------------------------*/
global without sharing class SalesForecastDataBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    
    String month = '';
    String year = '';
    public String query;
    global Boolean flag;
    global String errorMsg;
    global Datetime startTime;
    global Boolean runV;
    
    //2024.06.29 Chervin新增：历史数据计算
    global SalesForecastDataBatch(String year, String month, Boolean runV) {
        this.flag = true;
        this.year = year;
        this.month = month;   
        this.runV = runV;
        //this.query = 'SELECT Id,Year__c,Month__c,Product_Name__c,Customer__c,External_Id__c,OwnerId FROM Sales_Forcast__c WHERE Month__c =:month AND Year__c =:year AND Sales_Forecast_Summary__r.Status__c=\'Approved\'';
    }

    global SalesForecastDataBatch() {
        this.runV = true;
        this.startTime = System.now();
        this.flag = true;
        Date day = System.today();
        if (day.Day() == 1) {
            if (day.Month() == 1) {
                Integer yeraInt = day.Year() - 1;
                this.year = yeraInt + '';
                this.month = '12';
            }else{
                Integer monthInt = day.Month() - 1;
                this.month = monthInt + '';
                this.year = day.Year() + '';
            }
        }else{
            this.month = day.Month() + '';
            this.year = day.Year() + '';
        }
        if (Test.isRunningTest()) {
            this.month = '1';
            this.year = '2024';
        }
        //this.query = 'SELECT Id,Year__c,Month__c,Product_Name__c,Customer__c,External_Id__c,OwnerId FROM Sales_Forcast__c WHERE Month__c =:month AND Year__c =:year AND Sales_Forecast_Summary__r.Status__c=\'Approved\'';
        System.debug('this.month==>'+this.month);
        System.debug('this.year==>'+this.year);
        System.debug('this.query==>'+this.query);
    }

    global void execute(SchedulableContext sc) {
        SalesForecastDataBatch svo = new SalesForecastDataBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        this.query = 'SELECT Id,Year__c,Month__c,Product_Name__c,Customer__c,External_Id__c,OwnerId FROM Sales_Forcast__c WHERE Month__c =:month AND Year__c =:year AND Sales_Forecast_Summary__r.Status__c=\'Approved\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sales_Forcast__c> salesForList) {
        try {
            System.debug('salesForList==>'+salesForList);
            Set<String> customerSet = new Set<String>();
            Set<String> proNameSet = new Set<String>();
            Set<String> ownerSet = new Set<String>();
            Set<String> salesForExtIdSet = new Set<String>();
            for (Sales_Forcast__c sf : salesForList) {
                customerSet.add(sf.Customer__c);
                proNameSet.add(sf.Product_Name__c);
                ownerSet.add(sf.OwnerId);
                salesForExtIdSet.add(sf.External_Id__c);
            }
            System.debug('salesForExtIdSet==>'+salesForExtIdSet);
            List<Billing__c> billList = [SELECT Id,Invoice_Date_Month__c,Invoice_Date_Year__c,
                                        Order_Item__r.Commodity__c,Order__r.Customer__c,Order__r.CreatedDate,
                                        SAP_Total_Net_Develop__c,SAP_Total_Net_UDS_Develop__c,
                                        Order__r.OwnerId,Currency__c ,Order__r.User_Plant__c 
                                        FROM Billing__c 
                                        WHERE Invoice_Date_Month__c =: this.month 
                                        AND Invoice_Date_Year__c =: this.year 
                                        AND Order_Item__r.Commodity__c IN: proNameSet 
                                        AND Order__r.Customer__c IN: customerSet 
                                        // AND Order__r.OwnerId IN: ownerSet
                                        AND Billing_Status__c = 'C' AND SAP_Total_Net_Develop__c!=null];
            System.debug('billList==>'+billList);
            Map<String,Decimal> total = new Map<String,Decimal>();
            Map<String,Decimal> totalUSD = new Map<String,Decimal>();
            //双算逻辑 start
            Set<String> accIdSet = new Set<String>();
            for(Billing__c bill : billList) {
                accIdSet.add(bill.Order__r.Customer__c);
            }

            Map<String,List<Account_Team__c>> accTeamMap = new Map<String,List<Account_Team__c>>();
            Map<String,Date> accTeamDateMap = new Map<String,Date>();
            for(Account_Team__c at : [SELECT Sales_Rep__r.Delivery_Plant__c,Id,Sales_Rep__c,Customer__c,Add_Operation_Date__c FROM Account_Team__c WHERE Customer__c IN:accIdSet AND Shared_Performance__c=true]) {
                if(accTeamMap.containsKey(at.Customer__c)) {
                    accTeamMap.get(at.Customer__c).add(at);
                }else{
                    accTeamMap.Put(at.Customer__c,new List<Account_Team__c>{at});   
                }
                accTeamDateMap.put(at.Customer__c+'_'+at.Sales_Rep__c,at.Add_Operation_Date__c);
            }
            //双算逻辑 end
            for(Billing__c bill : billList){
                String key = bill.Invoice_Date_Year__c + bill.Invoice_Date_Month__c 
                        + bill.Order_Item__r.Commodity__c + bill.Order__r.Customer__c
                        + bill.Order__r.OwnerId;
                System.debug('key==>'+key);
                // if (salesForExtIdSet.contains(key)) {
                System.debug('bill.SAP_Total_Net_Develop__c==>'+bill.SAP_Total_Net_Develop__c);
                System.debug('bill.SAP_Total_Net_UDS_Develop__c==>'+bill.SAP_Total_Net_UDS_Develop__c);
                setData(total,totalUSD,key,bill);
                if(accTeamMap.get(bill.Order__r.Customer__c)!=null) {
                    for(Account_Team__c at : accTeamMap.get(bill.Order__r.Customer__c)) {
                        if(at.Sales_Rep__c == bill.Order__r.OwnerId) {
                            continue;
                        }
                        if(accTeamDateMap.get(bill.Order__r.Customer__c+'_'+at.Sales_Rep__c)>bill.Order__r.CreatedDate) {
                            continue;
                        }
                        if(bill.Order__r.User_Plant__c!=at.Sales_Rep__r.Delivery_Plant__c){
                            continue;
                        }
                        key = bill.Invoice_Date_Year__c + bill.Invoice_Date_Month__c 
                            + bill.Order_Item__r.Commodity__c + bill.Order__r.Customer__c
                            + at.Sales_Rep__c;
                        setData(total,totalUSD,key,bill);
                    }
                }
                
            }
            System.debug('total=====>'+total);
            for (Sales_Forcast__c sf : salesForList) {
                System.debug('sf.External_Id__c==>'+sf.External_Id__c);
                if (total.containsKey(sf.External_Id__c) && totalUSD.containsKey(sf.External_Id__c)) {
                    sf.Monthly_Actual_USD__c = totalUSD.get(sf.External_Id__c);
                    sf.Monthly_Actual_Local_Currency__c = total.get(sf.External_Id__c);
                }
            }

            update salesForList;
            
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void setData(Map<String,Decimal> total,Map<String,Decimal> totalUSD,String key,Billing__c bill) {
        if(total.containsKey(key) && totalUSD.containsKey(key)){
            if (bill.Currency__c == 'USD') {
                total.put(key,total.get(key) + bill.SAP_Total_Net_UDS_Develop__c);
                totalUSD.put(key,totalUSD.get(key) + bill.SAP_Total_Net_Develop__c);
            }else{
                total.put(key,total.get(key) + bill.SAP_Total_Net_Develop__c);
                totalUSD.put(key,totalUSD.get(key) + bill.SAP_Total_Net_UDS_Develop__c);
            }
            
        }else{
            if (bill.Currency__c == 'USD') {
                total.put(key,bill.SAP_Total_Net_UDS_Develop__c);
                totalUSD.put(key,bill.SAP_Total_Net_Develop__c);
            }else{
                total.put(key,bill.SAP_Total_Net_Develop__c);
                totalUSD.put(key,bill.SAP_Total_Net_UDS_Develop__c);
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('SalesForecastDataBatch', this.flag, this.startTime, this.errorMsg);
        if(this.runV) {
            DeleteSalesVirtualForecastDataBatch svo = new DeleteSalesVirtualForecastDataBatch();

            // 每次执行多少条数据，最大200
            String jobId = Database.executeBatch(svo, 100);
        }else{
            DeleteSalesVirtualForecastDataBatch svo = new DeleteSalesVirtualForecastDataBatch(this.year,this.month,true);

            // 每次执行多少条数据，最大200
            String jobId = Database.executeBatch(svo, 100);
        }
        
        
    }
}