force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Customer Team</label>
    <nameField>
        <displayFormat>AT-{yyyymm}{00000}</displayFormat>
        <label>Customer Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <label>Customer Sales Info/Account Receivable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/fields/Sales_Rep_Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Delivery_Plant__c</fullName>
    <formula>TEXT(Sales_Rep__r.Delivery_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>HQ Contracts</label>
    <nameField>
        <displayFormat>CON-{YYMM}-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HQ Contracts (Customer)</relationshipLabel>
    <relationshipName>HQ_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contracts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/Customer_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Info</label>
    <nameField>
        <displayFormat>ASI-{000000}</displayFormat>
        <label>Account Sales Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <formula>TEXT(Order__r.Deliver_Plant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2 AND 3 AND 6) OR 7 OR 8) AND 4) OR 5</booleanFilter>
        <errorMessage>Value does not &apos;Approved&apos; or &apos;Synchronized&apos; or NO Credit</errorMessage>
        <filterItems>
            <field>Account.Customer_Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Account.CreditNumber__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Interface Profile, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SAP_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sales_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Info</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Customer Sales Info is not synchronized</errorMessage>
        <filterItems>
            <field>Customer_Sales_Info__c.Sync_Status__c</field>
            <operation>equals</operation>
            <value>Synchronized</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Sales_Info__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Invoice__c.Order__r.RecordTypeId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quote_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Share.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Share</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShareDataToAccountTeam.cls
/**************************************************************************************************
 * Name: ShareDataToAccountTeam
 * Object: 
 * Purpose: 共享数据到客户小组
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-08-20         Created             
***************************************************************************************************/
public without sharing class ShareDataToAccountTeam {
    public static void shareData(String obejctTyp,String recordId,String accId,String fieldType,String ownerData) {
        List<Schema.FieldSetMember> fieldSetMembers = SObjectType.Account_Team__c.FieldSets.All_Filed.getFields();
        // 拼接需要复制得字段
        String orderQuery = 'SELECT ';
        String field = '';
        for (Schema.FieldSetMember f : fieldSetMembers) {
            if (String.isNotBlank(field)) {
                field += ','+f.getFieldPath();
            }else{
                field += f.getFieldPath();
            }
        }
        orderQuery = orderQuery+field+',Sales_Rep_Delivery_Plant__c FROM Account_Team__c WHERE Customer__c=:accId AND Sales_Rep__r.IsActive=true';
        List<Account_Team__c> atList = Database.Query(orderQuery);
        Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
        List<SObject> shareList = new List<SObject>();
        String objectName;
        String deliveryPlant;
        String queryDeliveryPlant='SELECT Id,OwnerId,';
        if(obejctTyp=='Customer_Sales_Info__c' || obejctTyp=='Order__c' || obejctTyp=='Contracts__c'  || obejctTyp=='Invoice__c' || obejctTyp=='Quote__c')
        {
            if(obejctTyp=='Customer_Sales_Info__c'){
                queryDeliveryPlant=queryDeliveryPlant+'Delivering_Plant__c FROM '+obejctTyp+' WHERE Id =: recordId';
            }
            if(obejctTyp=='Order__c' || obejctTyp=='Quote__c'){
                queryDeliveryPlant=queryDeliveryPlant+'Deliver_Plant__c FROM '+obejctTyp+' WHERE Id =: recordId';
            }
            if(obejctTyp=='Contracts__c'){
                queryDeliveryPlant=queryDeliveryPlant+'Delivery_Plant__c FROM '+obejctTyp+' WHERE Id =: recordId';
            }
            if(obejctTyp=='Invoice__c'){
                queryDeliveryPlant=queryDeliveryPlant+'Delivery_Plant__c FROM '+obejctTyp+' WHERE Order__c =: recordId';
            }
            //queryDeliveryPlant=queryDeliveryPlant+' AND Id=:recordId';
            System.debug('queryDeliveryPlant=>'+queryDeliveryPlant);
            List<SObject> deliveryPlantList=Database.Query(queryDeliveryPlant);
            for (SObject sb : deliveryPlantList) {
                if(obejctTyp=='Customer_Sales_Info__c'){
                    deliveryPlant=String.valueOf(sb.get('Delivering_Plant__c'));
                }
                if(obejctTyp=='Order__c' || obejctTyp=='Quote__c'){
                    deliveryPlant=String.valueOf(sb.get('Deliver_Plant__c'));
                }
                if(obejctTyp=='Contracts__c'){
                    deliveryPlant=String.valueOf(sb.get('Delivery_Plant__c'));
                }
                if(obejctTyp=='Invoice__c'){
                    deliveryPlant=String.valueOf(sb.get('Delivery_Plant__c'));
                }
                ownerData=String.valueOf(sb.get('OwnerId'));
                System.debug('deliveryPlant:'+deliveryPlant);
                System.debug('ownerData:'+ownerData);

        if (obejctTyp.contains('_')) {
            objectName = obejctTyp.replace('__c', '__share');
        }else{
            objectName = obejctTyp+'Share';
        }
        for (Account_Team__c at : atList) {
            //system.debug('ownerData:'+ownerData);
            system.debug('at.Sales_Rep__c:'+at.Sales_Rep__c);
            if (ownerData == at.Sales_Rep__c) {
                continue;
            }
            if (String.valueOf(at.get(fieldType))=='Private') {
                    continue;
            }
            if (deliveryPlant != null && deliveryPlant != at.Sales_Rep_Delivery_Plant__c) {
                continue;
            }
            SObject sharingObject = globalDescribe.get(objectName).newSObject();
            if (obejctTyp == 'Account') {
                sharingObject.put('AccountId', recordId);
                sharingObject.put('AccountAccessLevel', String.valueOf(at.get(fieldType)));
                sharingObject.put('OpportunityAccessLevel', 'None');
            }else if(obejctTyp == 'Contact') {
                sharingObject.put('ContactId', recordId);
                sharingObject.put('ContactAccessLevel', String.valueOf(at.get(fieldType)));
            }else{
                sharingObject.put('AccessLevel', String.valueOf(at.get(fieldType)));
                sharingObject.put('ParentId',sb.get('Id'));
            }
            
            
            sharingObject.put('RowCause','Manual');
            sharingObject.put('UserOrGroupId',at.Sales_Rep__c);
            shareList.add(sharingObject);
            System.debug('shareList=>'+shareList);
        }}}
        if (shareList.size()>0) {
            Database.upsert(shareList);
        }
        
    }
}