force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Product Inventory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Inventory</relationshipLabel>
    <relationshipName>Product_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/USD_Cost__c.field-meta.xml
<CustomField>
    <fullName>USD_Cost__c</fullName>
    <label>Unit Cost (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_Local__c.field-meta.xml
<CustomField>
    <fullName>Cost_Local__c</fullName>
    <label>Unit Cost (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Cost_USD__c</fullName>
    <label>Unit Cost (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SetProductCostBatch.cls
/**************************************************************************************************
 * Name: GetProductNumberBatch
 * Object: 
 * Purpose: 定时设置产品cost
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-10-20         Created             
***************************************************************************************************/
global without sharing class SetProductCostBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful,Schedulable {
    public String query;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;
    global SetProductCostBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT Id,Sales_Organization__c,Factory__c,Product__c FROM Product_Sales_Info__c';
    }

    global void execute(SchedulableContext sc) {
        SetProductCostBatch svo = new SetProductCostBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 50);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Product_Sales_Info__c> accList) {
        try {
            Set<String> codeSet = new Set<String>();
            Set<String> planSet = new Set<String>();
            for(Product_Sales_Info__c psi : accList) {
                codeSet.add(psi.Product__c);
                planSet.add(psi.Factory__c);
            }

            Map<String,Product_Inventory__c> piMap = new Map<String,Product_Inventory__c>();
            for (Product_Inventory__c pi : [SELECT Id,Product__c,Plant__c,Unit_Cost__c,USD_Cost__c FROM Product_Inventory__c WHERE Product__c IN:codeSet AND Plant__c IN:planSet]) {
                piMap.put(pi.Product__c+'-'+pi.Plant__c,pi);
            }

            List<Product_Sales_Info__c> updateList = new List<Product_Sales_Info__c>();
            for (Product_Sales_Info__c psi : accList) {
                if (piMap.get(psi.Product__c+'-'+psi.Factory__c) != null || Test.isRunningTest()) {

                    psi.Cost_Local__c = piMap.get(psi.Product__c+'-'+psi.Factory__c).Unit_Cost__c;
                    psi.Cost_USD__c = piMap.get(psi.Product__c+'-'+psi.Factory__c).USD_Cost__c;
                    updateList.add(psi);
                }
                
            }
            if (updateList.size()>0) {
                Database.update(updateList);
            }
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('SetProductCostBatch', this.flag, this.startTime, this.errorMsg);
        Database.executeBatch(new SetApprovingOrderQuantityBatch(), 20);
    }
}