force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Basic_Metering_Unit__c.field-meta.xml
<CustomField>
    <fullName>Basic_Metering_Unit__c</fullName>
    <label>Basic Metering Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Business_Volume__c.field-meta.xml
<CustomField>
    <fullName>Business_Volume__c</fullName>
    <label>Volume</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Chinese_Description__c.field-meta.xml
<CustomField>
    <fullName>Chinese_Description__c</fullName>
    <label>Chinese Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Cross_Factory_Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Cross_Factory_Material_Status__c</fullName>
    <label>Cross Factory Material Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Effective_Start__c.field-meta.xml
<CustomField>
    <fullName>Effective_Start__c</fullName>
    <label>Effective Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/English_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Description__c</fullName>
    <label>English Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>External_Material_Group__c</fullName>
    <label>External Material Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Laboratory_Office__c.field-meta.xml
<CustomField>
    <fullName>Laboratory_Office__c</fullName>
    <label>Laboratory/Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>001 A.I.</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002 Formulation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material_Group__c.field-meta.xml
<CustomField>
    <fullName>Material_Group__c</fullName>
    <label>Material Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material_Type__c.field-meta.xml
<CustomField>
    <fullName>Material_Type__c</fullName>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portuguese_Description__c.field-meta.xml
<CustomField>
    <fullName>Portuguese_Description__c</fullName>
    <label>Portuguese Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Spanish_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Description__c</fullName>
    <label>Spanish Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Volumetric_Unit__c.field-meta.xml
<CustomField>
    <fullName>Volumetric_Unit__c</fullName>
    <label>Volumetric Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_Unit__c</fullName>
    <label>Weight Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Default_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Unit__c</fullName>
    <label>Default Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Material_Subject_Assign_Group__c.field-meta.xml
<CustomField>
    <fullName>Material_Subject_Assign_Group__c</fullName>
    <label>Material Subject Assign Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Subject_Assign_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Unit</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Project_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Project_Category_Group__c</fullName>
    <label>Project Category Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Category_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Basic_Unit__c.field-meta.xml
<CustomField>
    <fullName>Basic_Unit__c</fullName>
    <label>Basic Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Denominator__c.field-meta.xml
<CustomField>
    <fullName>Denominator__c</fullName>
    <label>Denominator</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Molecule__c.field-meta.xml
<CustomField>
    <fullName>Molecule__c</fullName>
    <label>Molecule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Unit</relationshipLabel>
    <relationshipName>Product_Unit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 General Division</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <description>产品组</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_Subject_Assign_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Trading Goods</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Performances</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
    </customValue>
    <customValue>
        <fullName>04</fullName>
    </customValue>
    <customValue>
        <fullName>M0</fullName>
        <label>M0 POR LOGISTICA</label>
    </customValue>
    <customValue>
        <fullName>M1</fullName>
        <label>M1 ADICION DE MARCA</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>M2 POR INTERESES</label>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
        <label>M3 DEV Y DESC 0%</label>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
        <label>M4 DEV Y DESC 16%</label>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
        <label>M5 Downpayment</label>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <label>Z1 Productos Producidos</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <label>Z2 Dif. Realiz. Gananc.</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <label>Z3 Correo y Mensajería</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <label>Z4 Bs de Uso - Rodados</label>
    </customValue>
    <customValue>
        <fullName>Z5</fullName>
        <label>Z5 Comisiones Bancarias</label>
    </customValue>
    <customValue>
        <fullName>Z6</fullName>
        <label>Z6 Venta (No Productos)</label>
    </customValue>
    <customValue>
        <fullName>Z7</fullName>
        <label>Z7 Dctos y Bonif.</label>
    </customValue>
    <customValue>
        <fullName>Z8</fullName>
        <label>Z8 Intereses</label>
    </customValue>
    <customValue>
        <fullName>Z9</fullName>
        <label>Z9 Anticipo de Clientes</label>
    </customValue>
    <customValue>
        <fullName>ZA</fullName>
        <label>ZA Cheque Rechazado</label>
    </customValue>
    <customValue>
        <fullName>ZB</fullName>
        <label>ZB Dif. Realiz. Perdida</label>
    </customValue>
    <customValue>
        <fullName>ZD</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <isActive>false</isActive>
        <label>11</label>
    </customValue>
    <masterLabel>Material Subject Assign Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z002</fullName>
        <label>Z002 Product</label>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
        <label>Z001 Raw/Semi-Finished Product</label>
    </customValue>
    <customValue>
        <fullName>Z003</fullName>
        <label>Z003 Package</label>
    </customValue>
    <customValue>
        <fullName>DIEN</fullName>
        <label>DIEN Service</label>
    </customValue>
    <customValue>
        <fullName>Z005</fullName>
    </customValue>
    <masterLabel>Material Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Project_Category_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NORM</fullName>
    </customValue>
    <customValue>
        <fullName>DIEN</fullName>
    </customValue>
    <customValue>
        <fullName>LEIS</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <isActive>false</isActive>
        <label>11</label>
    </customValue>
    <masterLabel>Project Category Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductSyncToSAP.cls
public without sharing class ProductSyncToSAP {
    public static final String END_POINT = '';

    @AuraEnabled
    public static ReturnResult submitToSAP(String Id){
        ReturnResult returnResult = new ReturnResult();
        returnResult.isSuccess = true;

        Boolean isSuccess = true;
        String requestBody = '';
        String responseBodyStr = '';
        String errorMessage = '';
        
        try{
            RequestBody request = new RequestBody();
            request.esbinfo = new ReqESInfo();
            List<ReqProductInfo> resultinfoList = new List<ReqProductInfo>();
            //获取产品信息
            List<Product__c> proList=[SELECT Id,Name,Material_Type__c,Chinese_Description__c,
                                        English_Description__c,Spanish_Description__c,Portuguese_Description__c,
                                        Basic_Metering_Unit__c,Material_Group__c,Division__c,
                                        Cross_Factory_Material_Status__c,Effective_Start__c,Gross_Weight__c,
                                        Weight_Unit__c,Net_Weight__c,Business_Volume__c,Volumetric_Unit__c,
                                        Laboratory_Office__c,External_Material_Group__c,Industry_Standard_Description__c      
                                        FROM Product__c 
                                        WHERE Id =:Id];
            //获取产品销售视图类别
            List<Product_Sales_Info__c> proSalesInfoList=[SELECT Id,Sales_Organization__c,
                                        Distr_Channel__c,Default_Sales_Unit__c,Delivering_Plant__c,
                                        Material_Subject_Assign_Group__c,Project_Category_Group__c  
                                        FROM Product_Sales_Info__c 
                                        WHERE Product__c =: Id];

            //获取产品单位
            List<Product_Unit__c> proUnitList=[SELECT Id,Name,Basic_Unit__c,Molecule__c,Denominator__c     
                                        FROM Product_Unit__c 
                                        WHERE Product__c =: Id];
            
            
            ReqProductInfo rpi = new ReqProductInfo();
            rpi.matnr = proList[0].Name;
            rpi.mtart = proList[0].Material_Type__c;
            rpi.ltext_zh = proList[0].Chinese_Description__c;
            rpi.ltext_en = proList[0].English_Description__c;
            rpi.ltext_es = proList[0].Spanish_Description__c;
            rpi.ltext_pt = proList[0].Portuguese_Description__c;
            rpi.meins = proList[0].Basic_Metering_Unit__c;
            rpi.matkl = proList[0].Material_Group__c;
            rpi.spart = proList[0].Division__c;
            rpi.mstae = proList[0].Cross_Factory_Material_Status__c;
            rpi.mstde = proList[0].Effective_Start__c;
            rpi.brgew = proList[0].Gross_Weight__c;
            rpi.ntgew = proList[0].Weight_Unit__c;
            rpi.gewei = proList[0].Net_Weight__c;
            rpi.volum = proList[0].Business_Volume__c;
            rpi.voleh = proList[0].Volumetric_Unit__c;
            rpi.labor = proList[0].Laboratory_Office__c;
            rpi.extwg = proList[0].External_Material_Group__c;
            rpi.normt = proList[0].Industry_Standard_Description__c;
            

            //产品销售视图赋值
            List<SalesInfoRow> salesInfoList = new List<SalesInfoRow>();
            for(Product_Sales_Info__c psi : proSalesInfoList){
                SalesInfoRow sir = new SalesInfoRow();
                sir.vkorg = psi.Sales_Organization__c;
                sir.vtweg = psi.Distr_Channel__c;
                sir.vrkme = psi.Default_Sales_Unit__c;
                sir.dwerk = psi.Delivering_Plant__c;
                sir.ktgrm = psi.Material_Subject_Assign_Group__c;
                sir.mtpos = psi.Project_Category_Group__c;
                salesInfoList.add(sir);
            }
            rpi.salesInfo = salesInfoList;

            //产品单位赋值
            List<ProductUnitRow> pUnitList = new List<ProductUnitRow>();
            for(Product_Unit__c pu : proUnitList){
                ProductUnitRow pur = new ProductUnitRow();
                pur.meinh = pu.Name;
                pur.meins = pu.Basic_Unit__c;
                pur.umrez = pu.Molecule__c+'';
                pur.umren = pu.Denominator__c+'';
                pUnitList.add(pur);
            }
            rpi.productUnit = pUnitList;


            resultinfoList.add(rpi);
            request.resultinfo = resultinfoList;

            requestBody = JSON.serialize(request);
            System.debug('requestBody++'+requestBody);
            HttpResponse responseBody = InterfaceUtility.send_SAP_POST_Service(requestBody, END_POINT);
            System.debug('responseBody++'+responseBody);
            responseBodyStr = responseBody.getBody();
            System.debug('responseBodyStr===' + responseBodyStr);
            isSuccess = responseBody.getStatusCode() == 200 ? true : false;
            if (isSuccess) {
                ResponseBody syncReturnData = (ResponseBody) JSON.deserialize(responseBodyStr, ResponseBody.class);
                System.debug('responseData===' + syncReturnData);
                if ( syncReturnData.esbinfo != null ) {
                    returnResult.message = syncReturnData.esbinfo.returnmsg;
                    if(syncReturnData.esbinfo.returnstatus == 'E'){
                        returnResult.isSuccess = false;
                    }
                }else{
                    returnResult.isSuccess = false;
                    returnResult.message = responseBodyStr;
                    isSuccess = false;
                    errorMessage = responseBodyStr;
                }
                
            } else {
                returnResult.isSuccess = false;
                returnResult.message = responseBodyStr;
                isSuccess = false;
                errorMessage = responseBodyStr;
            }

        }
        catch (Exception e) {
            System.debug('错误信息'+e.getMessage()+e.getLineNumber());
            returnResult.isSuccess = false;
            returnResult.message = e.getMessage()+e.getLineNumber();
            isSuccess = false;
            errorMessage = e.getMessage()+e.getLineNumber();
        }
        InterfaceUtility.insertInterfaceLog('ProductSyncToSAP', 'CRM',
                    'SAP', END_POINT, requestBody, isSuccess, false,
                    responseBodyStr, errorMessage, 'POST', new List<String>{Id},
                    '产品主数据同步SAP', '产品主数据同步SAP');
        return returnResult;
    }

    public class ReturnResult {
        @InvocableVariable(Label='是否成功' Description='是否成功')
        public Boolean isSuccess;
        @InvocableVariable(Label='返回信息结果' Description='返回信息结果')
        public String message;
    }

    public class ResponseBody {
      public RespESInfo esbinfo;
      public List<RespCustomerInfo> resultinfo;
    }

    public class RespESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
        public String responsetime;//返回时间
        public String returnstatus;//接口状态
        public String returncode;//接口状态码
        public String returnmsg;//接口消息
        public String attr1;//预留字段
        public String attr2;//预留字段
        public String attr3;//预留字段
    }

    public class RespCustomerInfo{
        public String msgty;//处理状态
        public String msgtx;//错误信息
        
    }

    public class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqProductInfo> resultinfo;
    }

    public class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
    }

    public class ReqProductInfo{
        public String matnr;//物料号
        public String mtart;//物料类型
        public String ltext_zh;//中文描述
        public String ltext_en;//英文描述
        public String ltext_es;//西语描述
        public String ltext_pt;//葡语描述
        public String meins;//基本计量单位
        public String matkl;//物料组
        public String spart;//产品组
        public String mstae;//跨工厂的物料状态
        public String mstde;//有效起始期
        public String brgew;//毛重
        public String ntgew;//重量单位
        public String gewei;//净重
        public String volum;//业务量
        public String voleh;//体积单位
        public String labor;//实验室/办公室
        public String extwg;//外部物料组
        public String normt;//行业标准描述
        public List<SalesInfoRow> salesInfo;//销售视图
        public List<ProductUnitRow> productUnit;//产品单位
    }

    public class SalesInfoRow{
        public String vkorg;//销售组织
        public String vtweg;//分销渠道
        public String vrkme;//默认销售单位
        public String dwerk;//交货工厂
        public String ktgrm;//物料科目分配组
        public String mtpos;//项目类别组
    }

    public class ProductUnitRow{
        public String meinh;//可选单位
        public String meins;//基本单位
        public String umrez;//转换分子
        public String umren;//转换分母
    }


}