force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Basic_Metering_Unit__c.field-meta.xml
<CustomField>
    <fullName>Basic_Metering_Unit__c</fullName>
    <label>Basic Metering Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Business_Volume__c.field-meta.xml
<CustomField>
    <fullName>Business_Volume__c</fullName>
    <label>Volume</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Chinese_Description__c.field-meta.xml
<CustomField>
    <fullName>Chinese_Description__c</fullName>
    <label>Chinese Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Cross_Factory_Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Cross_Factory_Material_Status__c</fullName>
    <label>Cross Factory Material Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Effective_Start__c.field-meta.xml
<CustomField>
    <fullName>Effective_Start__c</fullName>
    <label>Effective Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/English_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Description__c</fullName>
    <label>English Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>External_Material_Group__c</fullName>
    <label>External Material Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Laboratory_Office__c.field-meta.xml
<CustomField>
    <fullName>Laboratory_Office__c</fullName>
    <label>Laboratory/Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>001 A.I.</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002 Formulation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material_Group__c.field-meta.xml
<CustomField>
    <fullName>Material_Group__c</fullName>
    <label>Material Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material_Type__c.field-meta.xml
<CustomField>
    <fullName>Material_Type__c</fullName>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portuguese_Description__c.field-meta.xml
<CustomField>
    <fullName>Portuguese_Description__c</fullName>
    <label>Portuguese Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Spanish_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Description__c</fullName>
    <label>Spanish Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Volumetric_Unit__c.field-meta.xml
<CustomField>
    <fullName>Volumetric_Unit__c</fullName>
    <label>Volumetric Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_Unit__c</fullName>
    <label>Weight Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Distr_Channel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribution Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Default_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Unit__c</fullName>
    <label>Default Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Delivering_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivering_Plant__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Distr_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distr_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>material code + sales org + distribution channel + factory</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Material_Subject_Assign_Group__c.field-meta.xml
<CustomField>
    <fullName>Material_Subject_Assign_Group__c</fullName>
    <label>Material Subject Assign Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Subject_Assign_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Unit</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Shelves</fullName>
                <default>true</default>
                <label>On Shelves</label>
            </value>
            <value>
                <fullName>Off Shelves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Basic_Unit__c.field-meta.xml
<CustomField>
    <fullName>Basic_Unit__c</fullName>
    <label>Basic Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Conversion_Coefficient__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Coefficient__c</fullName>
    <inlineHelpText>1 [Product Sales Unit] = [Conversion Coefficient] [Basic Metering Unit]</inlineHelpText>
    <label>Conversion Coefficient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Denominator__c.field-meta.xml
<CustomField>
    <fullName>Denominator__c</fullName>
    <label>Denominator</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Molecule__c.field-meta.xml
<CustomField>
    <fullName>Molecule__c</fullName>
    <label>Molecule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Unit</relationshipLabel>
    <relationshipName>Product_Unit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Unit__c</fullName>
    <label>Product Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Name_Relationship__c/Quote_Name_Relationship__c.object-meta.xml
<CustomObject>
    <label>Quote  Name Relationship</label>
    <nameField>
        <displayFormat>QNR-{000000}</displayFormat>
        <label>Quote  Name Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote  Name Relationship</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Name_Relationship__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>报价名称+产品code</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote_Name_Relationship__c/fields/Lang_Text__c.field-meta.xml
<CustomField>
    <fullName>Lang_Text__c</fullName>
    <label>Language Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Name_Relationship__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Name Relationship</relationshipLabel>
    <relationshipName>Quote_Name_Relationship</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Name_Relationship__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <default>true</default>
        <label>00 General Channel</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Distribution Channel 01</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90_Intercompany</label>
    </customValue>
    <customValue>
        <fullName>A0</fullName>
        <label>A0_Export Sales</label>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
        <label>A1_Model A+</label>
    </customValue>
    <customValue>
        <fullName>B0</fullName>
        <label>B0_Commercial &amp; Service Domestic Sales</label>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
        <label>B1_Model B+</label>
    </customValue>
    <customValue>
        <fullName>C0</fullName>
        <label>C0_Model C</label>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
        <label>C1_Model C+</label>
    </customValue>
    <description>分销渠道</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 General Division</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <description>产品组</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_Subject_Assign_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Trading Goods</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Performances</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
    </customValue>
    <customValue>
        <fullName>04</fullName>
    </customValue>
    <customValue>
        <fullName>M0</fullName>
        <label>M0 POR LOGISTICA</label>
    </customValue>
    <customValue>
        <fullName>M1</fullName>
        <label>M1 ADICION DE MARCA</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>M2 POR INTERESES</label>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
        <label>M3 DEV Y DESC 0%</label>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
        <label>M4 DEV Y DESC 16%</label>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
        <label>M5 Downpayment</label>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <label>Z1 Productos Producidos</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <label>Z2 Dif. Realiz. Gananc.</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <label>Z3 Correo y Mensajería</label>
    </customValue>
    <customValue>
        <fullName>Z4</fullName>
        <label>Z4 Bs de Uso - Rodados</label>
    </customValue>
    <customValue>
        <fullName>Z5</fullName>
        <label>Z5 Comisiones Bancarias</label>
    </customValue>
    <customValue>
        <fullName>Z6</fullName>
        <label>Z6 Venta (No Productos)</label>
    </customValue>
    <customValue>
        <fullName>Z7</fullName>
        <label>Z7 Dctos y Bonif.</label>
    </customValue>
    <customValue>
        <fullName>Z8</fullName>
        <label>Z8 Intereses</label>
    </customValue>
    <customValue>
        <fullName>Z9</fullName>
        <label>Z9 Anticipo de Clientes</label>
    </customValue>
    <customValue>
        <fullName>ZA</fullName>
        <label>ZA Cheque Rechazado</label>
    </customValue>
    <customValue>
        <fullName>ZB</fullName>
        <label>ZB Dif. Realiz. Perdida</label>
    </customValue>
    <customValue>
        <fullName>ZD</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <isActive>false</isActive>
        <label>11</label>
    </customValue>
    <masterLabel>Material Subject Assign Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z002</fullName>
        <label>Z002 Product</label>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
        <label>Z001 Raw/Semi-Finished Product</label>
    </customValue>
    <customValue>
        <fullName>Z003</fullName>
        <label>Z003 Package</label>
    </customValue>
    <customValue>
        <fullName>DIEN</fullName>
        <label>DIEN Service</label>
    </customValue>
    <customValue>
        <fullName>Z005</fullName>
    </customValue>
    <masterLabel>Material Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPProductWebService.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 08-18-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   08-18-2025   Gerry   Initial Version
**/
@RestResource(urlMapping='/SAPProductWebService')
global without sharing class SAPProductWebService {
    global class RequestBody {
        public ReqESInfo esbinfo;
        public List<ReqProductInfo> resultinfo;
    }

    global class ReqESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
    }

    global class ReqProductInfo{
        public String matnr;//物料号
        public String werks;//工厂
        public String mtart;//物料类型
        public String ltext_1;//中文描述
        public String ltext_e;//英文描述
        public String ltext_s;//西语描述
        public String ltext_pt;//葡语描述
        public String meins;//基本计量单位
        public String matkl;//物料组
        public String spart;//产品组
        public String mstae;//跨工厂的物料状态
        public String mstde;//有效起始期
        public String brgew;//毛重
        public String ntgew;//重量单位
        public String gewei;//净重
        public String volum;//业务量
        public String voleh;//体积单位
        public String labor;//实验室/办公室
        public String extwg;//外部物料组
        public String normt;//行业标准描述
        public List<SalesInfoRow> salev;//销售视图
        public List<ProductUnitRow> units;//产品单位
        public List<PriceNameRow> princename;//报价名称产品关系
    }


    global class SalesInfoRow{
        public String werks;
        public String vkorg;//销售组织
        public String vtweg;//分销渠道
        public String vrkme;//默认销售单位
        public String dwerk;//交货工厂
        public String ktgrm;//物料科目分配组
        public String mtpos;//项目类别组
        public String prodh;//产品层级
    }

    global class ProductUnitRow{
        public String meinh;//可选单位
        public String meins;//基本单位
        public String umrez;//转换分子
        public String umren;//转换分母
    }

    global class PriceNameRow{
        public String spras;//语言代码
        public String sprastxt;//语言文本
        public String ltext;//报价表名称
    }

    /**
     * SAP 产品主数据单同步接口
     * @param bodyStrJson bodyStrJson
     *
     * @return ResponseBody
     */
    @HttpPost
    global static ResponseBody doPost() {
        String respTime = String.valueOf(Datetime.now());
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String bodyStrJson = req.requestBody.toString();
        List<String> dataIdList = new List<String>();
        String errorMsg = '';
        Boolean isSuccess = true;
        Savepoint sp = Database.setSavepoint();
        RequestBody reqBody;
        
        try {
            System.debug('bodyStrJson1==' + bodyStrJson);
            reqBody = (RequestBody) JSON.deserialize(bodyStrJson, RequestBody.class);
            feedbackOrderInfo(reqBody.resultinfo);
            // respTime = reqBody.esbinfo.requesttime;
        } catch (Exception e) {
            Database.rollback(sp);
            errorMsg = InterfaceUtility.getProperErrorMessage(e.getMessage()) + '[' + e.getLineNumber() + ']';
            // System.debug('出现错误：' + reqBody.message);
            isSuccess = false;
            // respTime = String.valueOf(Datetime.now());
        }
        ResponseBody response = returnData(respTime, isSuccess, errorMsg);
        InterfaceUtility.insertInterfaceLog('SAPProductWebService', 'SAP', 'CRM',
                '/services/apexrest/receiveDataFromExternal/  requestCode:SAP002', bodyStrJson, isSuccess, false,
                JSON.serialize(response), errorMsg, 'POST', dataIdList, 'Upsert', 'SAP同步产品主数据至CRM'
        );
        return response;
        
    }

    public static void feedbackOrderInfo(List<ReqProductInfo> resultinfo) {
        Map<String,Product__c> proList = new Map<String,Product__c>();
        Map<String,Product_Sales_Info__c> proSalesList = new Map<String,Product_Sales_Info__c>();
        Map<String,Product_Unit__c> proUnitList = new Map<String,Product_Unit__c>();
        Map<String,Quote_Name_Relationship__c> quoteNameRelationList = new Map<String,Quote_Name_Relationship__c>();
        MAP<String,Product_Name__c> proNameList = new MAP<String,Product_Name__c>();
        Set<String> proSAPCodeSet = new Set<String>();
        for(ReqProductInfo rpi : resultinfo){
            proSAPCodeSet.add(rpi.matnr);
        }

        // List<Product__c> productList = [SELECT Id,Name 
        //                                 FROM Product__c 
        //                                 WHERE Name IN: proSAPCodeSet];
        // Map<String,String> proIdNameMap = new Map<String,String>();
        // if (productList.size()>0) {
        //     for(Product__c pr : productList){
        //         proIdNameMap.put(pr.Name,pr.Id);
        //     }
        // }

        for(ReqProductInfo rpi : resultinfo){
            Product__c pr = new Product__c();
            // if (proIdNameMap.size()>0 && proIdNameMap.containsKey(rpi.matnr)) {
            //     pr.Id = proIdNameMap.get(rpi.matnr);
            // }
            pr.Name = rpi.matnr;
            
            pr.Material_Type__c = rpi.mtart;
            pr.Chinese_Description__c = rpi.ltext_1;
            pr.English_Description__c = rpi.ltext_e;
            pr.Spanish_Description__c = rpi.ltext_s;
            pr.Portuguese_Description__c = rpi.ltext_pt;
            pr.Basic_Metering_Unit__c = rpi.meins;
            pr.Material_Group__c = rpi.matkl;
            pr.Division__c = rpi.spart;
            pr.Cross_Factory_Material_Status__c = rpi.mstae;
            pr.Effective_Start__c = rpi.mstde;
            pr.Gross_Weight__c = rpi.brgew;
            pr.Weight_Unit__c = rpi.gewei;
            pr.Net_Weight__c = rpi.ntgew;
            pr.Business_Volume__c = rpi.volum;
            pr.Volumetric_Unit__c = rpi.voleh;
            pr.Laboratory_Office__c = rpi.labor;
            pr.External_Material_Group__c = rpi.extwg;
            pr.Industry_Standard_Description__c = rpi.normt;
            pr.External_Id__c = rpi.matnr;
            if(rpi.units!=null) {
                for (ProductUnitRow pur : rpi.units) {
                    Product_Unit__c pu = new Product_Unit__c();
                    pu.External_Id__c = rpi.matnr+'_'+pur.meinh;
                    pu.Product_Sales_Unit__c = pur.meinh;
                    pu.Basic_Unit__c = pur.meins;
                    pu.Molecule__c = String.isBlank(pur.umrez) ? 0 : Decimal.valueOf(pur.umrez);
                    pu.Denominator__c = String.isBlank(pur.umren) ? 0 : Decimal.valueOf(pur.umren);
                    Product__c prPa = new Product__c();
                    prPa.External_Id__c = rpi.matnr;
                    pu.Product__r = prPa;
                    pu.Conversion_Coefficient__c = pu.Molecule__c/pu.Denominator__c;
                    proUnitList.put(pu.External_Id__c,pu);
                }
            }
            
            if(rpi.princename!=null) {
                for (PriceNameRow pnr : rpi.princename) {
                    Quote_Name_Relationship__c quoteNameRelation= new Quote_Name_Relationship__c();
                    quoteNameRelation.Quote_Name__c =pnr.ltext;
                    quoteNameRelation.Lang_Text__c  =pnr.sprastxt;
                    Product__c prPa = new Product__c();
                    prPa.External_Id__c = rpi.matnr;
                    quoteNameRelation.Products__r = prPa;
                    quoteNameRelation.External_Id__c=rpi.matnr+pnr.spras;
                    quoteNameRelationList.put(quoteNameRelation.External_Id__c,quoteNameRelation);
                }
            }
            if(rpi.salev!=null) {
                for (SalesInfoRow sir : rpi.salev) {
                    Product_Sales_Info__c psi = new Product_Sales_Info__c();
                    if(String.isNotBlank(rpi.mstae) && rpi.mstae=='Z1') {
                        psi.Status__c = 'Off Shelves';
                    }else{
                        psi.Status__c = 'On Shelves';
                    }
                    Product__c prPa = new Product__c();
                    prPa.External_Id__c = rpi.matnr;
                    psi.Factory__c = rpi.werks;
                    psi.External_Id__c = rpi.matnr+'_'+sir.vkorg+'_'+sir.vtweg+'_'+rpi.werks;
                    psi.Sales_Organization__c = sir.vkorg;
                    psi.Distr_Channel__c = sir.vtweg;
                    if (String.isNotBlank(sir.vrkme)) {
                        psi.Default_Sales_Unit__c = sir.vrkme;
                    }else{
                        psi.Default_Sales_Unit__c = pr.Basic_Metering_Unit__c;
                    }
                    
                    Product_Unit__c pu = new Product_Unit__c();
                    if (String.isNotBlank(sir.vrkme)) {
                        pu.External_Id__c = rpi.matnr+'_'+sir.vrkme;
                    }else{
                        pu.External_Id__c = rpi.matnr+'_'+pr.Basic_Metering_Unit__c;
                    }
                    psi.Product_Unit__r = pu;
                    if(String.isNotBlank(sir.dwerk)) {
                        psi.Delivering_Plant__c = sir.dwerk;
                    }else{
                        psi.Delivering_Plant__c = rpi.werks;
                    }
                    
                    psi.Material_Subject_Assign_Group__c = sir.ktgrm;
                    psi.Project_Category_Group__c = sir.mtpos;
                    psi.Product__r = prPa;
                    psi.Product_Group__c = sir.prodh;
                    proSalesList.put(psi.External_Id__c,psi);

                    // Model B产品自动生成商品名
                    if ( psi.Sales_Organization__c == '5070' && psi.Factory__c == '5070' && pr.English_Description__c!=null)                     
                    {
                        Product_Name__c pn = new Product_Name__c();
                        Product_Sales_Info__c proRe = new Product_Sales_Info__c();
                        proRe.External_Id__c = psi.External_Id__c;
                        pn.Product_Sales_Info__r = proRe;
                        pn.Name = pr.English_Description__c;
                        // pn.Material_Code__c+'_'+pn.Sales_Org__c+'_'+pn.Distr_Channel__c+'_'+pn.Plan__c+'_'+pn.Name+'_';
                        pn.External_Id__c = psi.External_Id__c+'_'+pr.English_Description__c+'_';
                        proNameList.put(pn.External_Id__c,pn);
                    }
                }
            }
            

            
            proList.put(pr.External_Id__c,pr);
        }


        if (proList.size() > 0) {
            Database.upsert(proList.values(),Product__c.fields.External_Id__c);
        }
        if (proUnitList.size() > 0) {
            Database.upsert(proUnitList.values(),Product_Unit__c.fields.External_Id__c);
        }
        if (quoteNameRelationList.size() > 0) {
            Database.upsert(quoteNameRelationList.values(),Quote_Name_Relationship__c.fields.External_Id__c);
        }
        if (proSalesList.size() > 0) {
            Database.upsert(proSalesList.values(),Product_Sales_Info__c.fields.External_Id__c);
        }

        if (proNameList.size()>0) {
            Utility.IgnoreAction(true,false,'SAPProductWebService'); 
            Database.upsert(proNameList.values(),Product_Name__c.fields.External_Id__c);
            Utility.IgnoreAction(false,false,'SAPProductWebService'); 
        }
    }

    
    global static ResponseBody returnData(String requestTime,Boolean status,String errorMsg) {
        ResponseBody re = new ResponseBody();
        re.esbinfo = new RespESInfo();
        re.esbinfo.requesttime = requestTime;//请求时间
        re.esbinfo.responsetime = String.valueOf(Datetime.now());//返回时间
        if (!status) {
            re.esbinfo.returnstatus = 'E';//接口状态
            re.esbinfo.returncode = 'E001';//接口状态码
            re.esbinfo.returnmsg = errorMsg;//接口消息
        }else{
            re.esbinfo.returnstatus = 'S';//接口状态
            re.esbinfo.returncode = 'S001';//接口状态码
        }
        re.resultinfo = new RespCustomerInfo();
        RespCustomerInfo rci = new RespCustomerInfo();
        if (status) {
            rci.msgty = 'S';
            rci.msgtx = '处理成功';
        }else{
            rci.msgty = 'E';
            rci.msgtx = errorMsg;
        }
        re.resultinfo = rci;
        return re;
    }
    global class ResponseBody {
        public RespESInfo esbinfo;
        public RespCustomerInfo resultinfo;
    }

    global class RespCustomerInfo{
        public String msgty;//处理状态
        public String msgtx;//错误信息
        // public List<ErrorData> errorDataList;
    }

    // global class ErrorData {
    //     public String code;//唯一值
    //     public String error;//错误信息
    // }

    global class RespESInfo{
        public String instid;//接口编号
        public String requesttime;//请求时间
        public String responsetime;//返回时间
        public String returnstatus;//接口状态
        public String returncode;//接口状态码
        public String returnmsg;//接口消息
        public String attr1;//预留字段
        public String attr2;//预留字段
        public String attr3;//预留字段
    }
}