force-app/main/default/objects/Company_Dynamics__c/Company_Dynamics__c.object-meta.xml
<CustomObject>
    <label>Company Dynamics</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Company Dynamics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Dynamics__c/fields/Company_Dynamics__c.field-meta.xml
<CustomField>
    <fullName>Company_Dynamics__c</fullName>
    <label>Company Dynamics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Company_Dynamics__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Company Dynamics</relationshipLabel>
    <relationshipName>Company_Dynamics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CompanyDynamicsTriggerHandler.cls
public without sharing class CompanyDynamicsTriggerHandler  implements Triggers.Handler{
    public void handle() {
        // 共享数据到客户小组
        if (Trigger.isAfter && (Trigger.isinsert || Trigger.isupdate)) {
            for (Company_Dynamics__c order : (List<Company_Dynamics__c>)Trigger.new) {
                ShareDataToAccountTeam.shareData('Company_Dynamics__c', order.Id, order.Customer__c, 'Company_Dynamics__c',order.OwnerId);
            }
        }
    }
}