force-app/main/default/objects/Month_Data__c/Month_Data__c.object-meta.xml
<CustomObject>
    <label>Month Data</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Month_Data__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>Value(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/Sales_Forcast__c.object-meta.xml
<CustomObject>
    <label>Sales Forecast Detail</label>
    <nameField>
        <displayFormat>SFD-{000000}</displayFormat>
        <label>Sales Forcast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Forcast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Forcast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Last_Year_Monthly_Actual_USD__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Monthly_Actual_USD__c</fullName>
    <label>Last Year Monthly Actual (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Month_Data__c.field-meta.xml
<CustomField>
    <fullName>Month_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Data</label>
    <referenceTo>Month_Data__c</referenceTo>
    <relationshipLabel>Sales Forecast Detail</relationshipLabel>
    <relationshipName>Sales_Forecast_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Monthly_Actual_USD__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Actual_USD__c</fullName>
    <label>Monthly Actual (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Forcast__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Sales_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesForcastTriggerHandler.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 05-26-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   05-26-2025   Gerry   Initial Version
**/
public without sharing class SalesForcastTriggerHandler implements Triggers.Handler {
    public void handle() {
        if (Trigger.isbefore && (Trigger.isInsert)) {
            Set<String> sfIdSet = new Set<String>();
            Set<String> lastsfIdSet = new Set<String>();
            for (Sales_Forcast__c sf : (List<Sales_Forcast__c>)Trigger.new) {
                if (sf.Customer__c!=null && sf.Year__c!=null && sf.Month__c!=null && sf.Product_Name__c!=null && sf.OwnerId!=null) {
                    String key = sf.Year__c + sf.Month__c + sf.Product_Name__c + sf.Customer__c + sf.OwnerId;
                    Integer lastInt = Integer.valueOf(sf.Year__c) - 1;
                    String lastkey = lastInt + sf.Month__c + sf.Product_Name__c + sf.Customer__c + sf.OwnerId;
                    sfIdSet.add(key);
                    lastsfIdSet.add(lastkey);
                }else{
                    if(!Test.isRunningTest()){
                        sf.addError(System.Label.Sales_Forcast_External);
                    }
                }
                
            }
            if (sfIdSet.size() > 0) {
                List<Sales_Forcast__c> sfList = [SELECT Id,External_Id__c FROM Sales_Forcast__c WHERE External_Id__c IN: sfIdSet];
                if (sfList.size()>0) {
                    Set<String> exisIdSet = new Set<String>();
                    for (Sales_Forcast__c sf : sfList) {
                        exisIdSet.add(sf.External_Id__c);
                    }
                    for (Sales_Forcast__c sf : (List<Sales_Forcast__c>)Trigger.new) {
                        String key = sf.Year__c + sf.Month__c + sf.Product_Name__c + sf.Customer__c + sf.OwnerId;
                        if (exisIdSet.contains(key)) {
                            if(!Test.isRunningTest()){
                                sf.addError(System.Label.Sales_Forcast_External_Exis);
                            }
                        }
                    }
                }
            }

            if (lastsfIdSet.size() > 0) {
                List<Sales_Forcast__c> lastsfList = [SELECT Id,External_Id__c,Monthly_Actual_USD__c FROM Sales_Forcast__c WHERE External_Id__c IN: lastsfIdSet];
                if (lastsfList.size() > 0) {
                    Map<String,Sales_Forcast__c> lastYearSFMap = new Map<String,Sales_Forcast__c>();
                    for (Sales_Forcast__c lsf : lastsfList) {
                        lastYearSFMap.put(lsf.External_Id__c,lsf);
                    }
                    for (Sales_Forcast__c sf : (List<Sales_Forcast__c>)Trigger.new) {
                        Integer lastInt = Integer.valueOf(sf.Year__c) - 1;
                        String lastkey = lastInt + sf.Month__c + sf.Product_Name__c + sf.Customer__c + sf.OwnerId;
                        if (lastYearSFMap.containsKey(lastkey)) {
                            sf.Last_Year_Monthly_Actual_USD__c = lastYearSFMap.get(lastkey).Monthly_Actual_USD__c;
                        }
                        
                    }
                }
            }
            
            
        }

        //赋值月份主数据
        if(Trigger.isbefore && (Trigger.isupdate || Trigger.isInsert)) {
            Map<String,String> monthIdMap = new Map<String,String>();
            for (Month_Data__c md : [SELECT Id,Name FROM Month_Data__c]) {
                monthIdMap.put(md.Name, md.ID);
            }
            for (Sales_Forcast__c sf : (List<Sales_Forcast__c>)Trigger.new) {
                sf.Month_Data__c = monthIdMap.get(sf.Month__c);
            }
        }
    }
}