force-app/main/default/objects/DeliveryNumber__c/DeliveryNumber__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryNumber__c/fields/Delivery_Post_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Post_Status__c</fullName>
    <label>Delivery Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Post_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Is_Invoice_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Invoice_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is POD Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Delivery Number</relationshipLabel>
    <relationshipName>Delivery_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryNumber__c/fields/Over_20days__c.field-meta.xml
<CustomField>
    <fullName>Over_20days__c</fullName>
    <description>The calculation to determine whether the invoice has been uploaded within 20 days.</description>
    <formula>(TODAY()-Delivery_Post_Date__c) &gt; 20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Over 20days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Post_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A 	Not yet processed</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B 	Partially processed</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C 	Completely processed</label>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>Delivery Post Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryNumberOverdueBatch.cls
/**
 * @description       : The function is used to send notice to the Delivery Number owner who haven't upload invoice over 20 days
 * @author            : Niko
 * @group             : 
 * @last modified on  : 01-27-2026
 * @last modified by  : Gerry
**/

global without sharing class DeliveryNumberOverdueBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    public String query;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;

    public DeliveryNumberOverdueBatch() {
        this.query = 'SELECT Id, Name, Is_Invoice_Uploaded__c, Over_20days__c,Order__r.Deliver_Plant__c FROM DeliveryNumber__c WHERE Delivery_Post_Status__c=\'C\' AND Is_Invoice_Uploaded__c = false AND Over_20days__c = true AND (Order__r.Deliver_Plant__c=\'3010\' OR Order__r.Deliver_Plant__c=\'3020\' OR Order__r.Deliver_Plant__c=\'3011\')';
        this.startTime = System.now();
        this.flag = true;
    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new DeliveryNumberOverdueBatch(), 20);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<DeliveryNumber__c> dnList) {
        try {
            CustomNotificationType notificationType = [SELECT Id,DeveloperName FROM CustomNotificationType WHERE DeveloperName ='Notification'];
            Map<String,Set<String>> ownerMap = new Map<String,Set<String>>();
            ownerMap.put('3010', new Set<String>());
            ownerMap.put('3020', new Set<String>());
            for (GroupMember gm : [SELECT Id,UserOrGroupId,Group.DeveloperName FROm GroupMember WHERE Group.DeveloperName ='MX_Logistics3010' OR Group.DeveloperName ='MX_Logistics3020']) {
                if (gm.Group.DeveloperName == 'MX_Logistics3010') {
                    ownerMap.get('3010').add(gm.UserOrGroupId);
                } 
                if (gm.Group.DeveloperName == 'MX_Logistics3020'){
                    ownerMap.get('3020').add(gm.UserOrGroupId);
                }
            }
            for (DeliveryNumber__c dn : dnList) {
                String NOTICE_SUBJECT = System.label.DeliveryAttachment+' ' + dn.Name;
                String noticeBody = System.Label.DeliveryAttachmentBody.replace('[xx]',dn.Name);
                Set<String> notificationSet = new Set<String>();
                if (dn.Order__r.Deliver_Plant__c == '3010' || dn.Order__r.Deliver_Plant__c == '3011') {
                    notificationSet.addAll(ownerMap.get('3010'));
                }
                if (dn.Order__r.Deliver_Plant__c == '3020') {
                    notificationSet.addAll(ownerMap.get('3020'));
                }
                CustomNotificationFromApex.notifyUsers(
                    notificationType,
                    notificationSet,
                    dn.Id,
                    NOTICE_SUBJECT,
                    noticeBody
                );
            }
        }catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('DeliveryNumberOverdueBatch', this.flag, this.startTime, this.errorMsg);
    }
}