force-app/main/default/objects/Account_Receivable__c/Account_Receivable__c.object-meta.xml
<CustomObject>
    <label>Account Receivable</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Receivable Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Receivable__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Account Receivable</relationshipLabel>
    <relationshipName>Account_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Billing_Num__c.field-meta.xml
<CustomField>
    <fullName>Billing_Num__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Item</relationshipLabel>
    <relationshipName>Invoice_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A Billing document blocked for forwarding to FI</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B Journal entry not created (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>C Journal entry has been created</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D Billing document is not relevant for accounting</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>E Billing document canceled</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>F Journal entry not created (pricing error)</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G Journal entry not created (export data missing)</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>H Posted via invoice list</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>I Posted via invoice list (account determination error)</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>K Journal entry not created (no authorization)</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L Billing doc. blocked for transfer to manager (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M Analyst Approval refused (only IS-OIL)</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>N No Journal entry due to fund management (only IS-PS)</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SetDataBatch.cls
global without sharing class SetDataBatch implements Database.Batchable<sObject>,Database.Stateful{
    public String query;
    public Integer index;
    global SetDataBatch(Integer index) {
        this.index = index;
        if (index==1) {
            this.query = 'SELECT Id,Billing_Num__c,Billing_Status__c FROM Billing__c';
        }else{
            this.query = 'SELECT Id,Invoice_Number__c FROM Account_Receivable__c';
        }
        
    }


    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> orderList) {
        if (this.index==1) {
            List<Billing__c> udpateB = new List<Billing__c>();
            List<Invoice__c> udpateI = new List<Invoice__c>();
            List<Billing__c> bList = (List<Billing__c>)orderList;
            for (Billing__c b : bList) {
                Invoice__c inv = new Invoice__c();
                inv.External_Id__c = b.Billing_Num__c;
                b.Invoice__r = inv;
                udpateB.add(b);

                // if (b.Billing_Status__c=='E') {
                //     Invoice__c ui = new Invoice__c();
                //     ui.External_Id__c = b.Billing_Num__c;
                //     ui.Invoice_Status__c = 'E';
                //     udpateI.add(ui);
                // }
            }

            if (udpateI.size()>0) {
                Database.upsert(udpateI,Invoice__c.fields.External_Id__c, true);
            }

            if (udpateB.size()>0) {
                update udpateB;
            }
        }
        
        if (this.index==2) {
            List<Account_Receivable__c> udpatea = new List<Account_Receivable__c>();
            List<Account_Receivable__c> bList = (List<Account_Receivable__c>)orderList;
            for (Account_Receivable__c b : bList) {
                if (b.Invoice_Number__c == null) {
                    continue;
                }
                Invoice__c inv = new Invoice__c();
                inv.External_Id__c = b.Invoice_Number__c;
                b.Invoice__r = inv;
                udpatea.add(b);
            }
            if (udpatea.size()>0) {
                update udpatea;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        Integer i = this.index+1;
        if (i<=2) {
            Database.executeBatch(new SetDataBatch(i));
        }
    }
}