force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Cash_Price__c.field-meta.xml
<CustomField>
    <fullName>Cash_Price__c</fullName>
    <label>Cash Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Order_Item_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_Combo_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Combo_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Combo Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipLabel>Order Item (Product Combo Name)</relationshipLabel>
    <relationshipName>Order_Item_Combo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Unit Master Data</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Unit_Estimate_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Estimate_Cost__c</fullName>
    <description>阿根廷特有成本</description>
    <label>Unit Estimate Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>PBI-{000000}</displayFormat>
        <label>Price Book Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Item__c/fields/Estimation_Cost_Local__c.field-meta.xml
<CustomField>
    <fullName>Estimation_Cost_Local__c</fullName>
    <label>Estimation Cost Local</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/fields/Estimation_Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Estimation_Cost_USD__c</fullName>
    <label>Estimation Cost USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <formula>IF(TEXT(Product_Name__r.Product_Sales_Info__r.Default_Sales_Unit__c)=&apos;ST&apos;,&apos;PC&apos;,TEXT(Product_Name__r.Product_Sales_Info__r.Default_Sales_Unit__c))</formula>
    <label>Sales Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Conversion_Coefficient__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Coefficient__c</fullName>
    <inlineHelpText>1 [Product Sales Unit] = [Conversion Coefficient] [Basic Metering Unit]</inlineHelpText>
    <label>Conversion Coefficient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SetOrderItemFieldBatch.cls
/**
 * @description       : 
 * @author            : Gerry
 * @group             : 
 * @last modified on  : 08-27-2025
 * @last modified by  : Gerry
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   08-27-2025   Gerry   Initial Version
**/

/**************************************************************************************************
 * Name: SubmitOrderController
 * Object: 
 * Purpose: 销售数据batch
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-20         Created             
***************************************************************************************************/
global without sharing class SetOrderItemFieldBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    public String query;
    global SetOrderItemFieldBatch() {
        
        this.query = 'SELECT Order__r.Interest_Rate__c,Price__c,Product_Combo_Name__c,Order__r.Currency__c,Id,Price_Book_Item__r.Estimation_Cost_Local__c,Price_Book_Item__r.Estimation_Cost_USD__c,Sales_Unit__r.Conversion_Coefficient__c,Unit_Estimate_Cost__c  FROM Order_Item__c';
        
    }

    global void execute(SchedulableContext sc) {
        SetOrderItemFieldBatch svo = new SetOrderItemFieldBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 100);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order_Item__c> oiList) {
        for(Order_item__c oi : oiList) {
            //测算成本赋值 -start
            if (oi.order__r.Currency__c == 'USD') {
                oi.Unit_Estimate_Cost__c = oi.Price_Book_Item__r.Estimation_Cost_USD__c;
            }else{
                oi.Unit_Estimate_Cost__c = oi.Price_Book_Item__r.Estimation_Cost_Local__c;
            }
            if(oi.Unit_Estimate_Cost__c!=null) {
                if(oi.Sales_Unit__r.Conversion_Coefficient__c!=null ) {
                    oi.Unit_Estimate_Cost__c = (oi.Unit_Estimate_Cost__c * oi.Sales_Unit__r.Conversion_Coefficient__c).setScale(2);
                }else if(oi.Unit_Estimate_Cost__c!=null){
                    oi.Unit_Estimate_Cost__c = oi.Unit_Estimate_Cost__c.setScale(2);
                }
            }
            
            //测算成本赋值 -end
            if(oi.Price__c!=null && oi.Order__r.Interest_Rate__c!=null && String.isBlank(oi.Product_Combo_Name__c)) {
                oi.Cash_Price__c = ((oi.Price__c)/oi.Order__r.Interest_Rate__c).setScale(2);
            }
            
        }
        update oiList;
    }

    global void finish(Database.BatchableContext BC) {
        // SalesOrderInvoiceBatch soib = new SalesOrderInvoiceBatch();
        // Database.executeBatch(soib,100);
        // Utility.setBatchInfo('SalesOrderDataBatch', this.flag, this.startTime, this.errorMsg);
    }
}