force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Down Payment Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select down payment order.</errorMessage>
        <filterItems>
            <field>Order__c.Order_type__c</field>
            <operation>equals</operation>
            <value>ZMX6 Down Payment MX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Basic_Number__c.field-meta.xml
<CustomField>
    <fullName>Basic_Number__c</fullName>
    <formula>Quantity__c * Sales_Unit__r.Molecule__c/ Sales_Unit__r.Denominator__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Item Quantity (Basic Unit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivery_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Quantity__c</fullName>
    <label>Order Item Delivered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Depend_On_Item__c.field-meta.xml
<CustomField>
    <fullName>Depend_On_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fill up Consignment Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Issue Consignment)</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Order_Item_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Order Item Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Unit Master Data</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Used_Number__c.field-meta.xml
<CustomField>
    <fullName>Used_Number__c</fullName>
    <description>寄售补货已经使用的数量</description>
    <label>Issue Consignment Quantity (Migration)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/ZARB_Used_Quantity_Test_Only__c.field-meta.xml
<CustomField>
    <fullName>ZARB_Used_Quantity_Test_Only__c</fullName>
    <label>ZARB Used Quantity(Test Only)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>PBI-{000000}</displayFormat>
        <label>Price Book Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Item__c/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <formula>IF(TEXT(Product_Name__r.Product_Sales_Info__r.Default_Sales_Unit__c)=&apos;ST&apos;,&apos;PC&apos;,TEXT(Product_Name__r.Product_Sales_Info__r.Default_Sales_Unit__c))</formula>
    <label>Sales Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Description_User__c.field-meta.xml
<CustomField>
    <fullName>Description_User__c</fullName>
    <formula>IF( OR(TEXT($User.LocaleSidKey) =&apos;es_MX&apos;,TEXT($User.LocaleSidKey) =&apos;es_AR&apos;), Spanish_Description__c ,English_Description__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_Local__c.field-meta.xml
<CustomField>
    <fullName>Cost_Local__c</fullName>
    <label>Unit Cost (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Cost_USD__c</fullName>
    <label>Unit Cost (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Unit</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Shelves</fullName>
                <default>true</default>
                <label>On Shelves</label>
            </value>
            <value>
                <fullName>Off Shelves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Unit</relationshipLabel>
    <relationshipName>Product_Unit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Unit__c</fullName>
    <label>Product Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchUpdateZARBItemUsedQty.cls
//illion 20250826 仅用于期初数据的刷新
global without sharing class BatchUpdateZARBItemUsedQty implements Database.Batchable<sObject>,Schedulable,Database.Stateful {
	public Set<String> zarbIdSet = new Set<String>();
	public String errorMsg;
    public Datetime startTime;
    public Boolean flag = TRUE;

	global BatchUpdateZARBItemUsedQty(){
        
    }

    global BatchUpdateZARBItemUsedQty(Set<String> zarbIdSet){
        this.zarbIdSet = zarbIdSet;
    }

	global Database.QueryLocator start(Database.BatchableContext bc){
        startTime = System.now();
        String sql = 
	                    'SELECT '+
	                        'Id,'+
	                        'Commodity__c,Commodity__r.Product_Sales_Info__r.Cost_Local__c,Commodity__r.Product_Sales_Info__r.Cost_USD__c,'+
	                        'Price__c,Commodity__r.Product__r.Description_User__c,Order__r.Order_type__c,'+
	                        'Sales_Unit__c,Commodity__r.Product__r.Name,'+
	                        'Commodity__r.Name,TOLabel(Sales_Unit__r.Product_Sales_Unit__c),'+
	                        'Quantity__c,Used_Number__c,Basic_Number__c,Order__r.SAP_Order_Code__c,Order__r.CreatedDate,Price_Book_Item__c,Delivery_Quantity__c,isClosed__c '+
	                    'FROM '+
	                        'Order_Item__c  '+
	                    'WHERE '+
	                            'Order__r.Order_type__c=\'ZARB\' AND Order__r.Status__c=\'Approved\'';

	    system.debug(zarbIdSet);
        if(zarbIdSet != NULL && !zarbIdSet.isEmpty()){
            sql += ' AND Order__c IN:zarbIdSet';
        }
        
        return Database.getQueryLocator(sql);  
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchUpdateZARBItemUsedQty());
    }
    
    global void execute(Database.BatchableContext BC,List<Order_Item__c> itemList){
        system.debug('itemList===='+itemList);
        Set<String> oiIdSet = new Set<String>();
        for(Order_Item__c oi : itemList){
        	oiIdSet.add(oi.Id);
        }

        try{
            //Approving/Approved ZARE
            Map<String,Decimal> inventoryZAREMap = new Map<String,Decimal>();
            //Approving/Approved ZARA
            Map<String,Decimal> inventoryZARAMap = new Map<String,Decimal>();
            //Approved ZARF
            Map<String,Decimal> inventoryZARFMap = new Map<String,Decimal>();
            for (AggregateResult agg1 : [
                                        SELECT 
                                            Depend_On_Item__c depend,
                                            SUM(Quantity__c) usedNum
                                        FROM 
                                            Order_Item__c 
                                        WHERE 
                                            Depend_On_Item__c IN:oiIdSet
                                            AND (Order__r.Status__c='Approved' OR Order__r.Status__c='Approving') AND Order__r.Order_type__c='ZARE' AND isClosed__c = false
                                            Group by Depend_On_Item__c
            ]) {
                inventoryZAREMap.put((String)agg1.get('depend'), (Decimal)agg1.get('usedNum'));
            }

            for (AggregateResult agg2 : [
                                        SELECT 
                                            Depend_On_Item__c depend,
                                            SUM(Quantity__c) usedNum
                                        FROM 
                                            Order_Item__c 
                                        WHERE 
                                            Depend_On_Item__c IN:oiIdSet
                                            AND Order__r.Status__c='Approved' AND Order__r.Order_type__c='ZARF' AND isClosed__c = false
                                            Group by Depend_On_Item__c
            ]) {
                inventoryZARFMap.put((String)agg2.get('depend'), (Decimal)agg2.get('usedNum'));
        	}

            for (AggregateResult agg3 : [
                                        SELECT 
                                            Depend_On_Item__c depend,
                                            SUM(Quantity__c) usedNum
                                        FROM 
                                            Order_Item__c 
                                        WHERE 
                                            Depend_On_Item__c IN:oiIdSet
                                            AND (Order__r.Status__c='Approved' OR Order__r.Status__c='Approving') AND Order__r.Order_type__c='ZARA' AND isClosed__c = false
                                            Group by Depend_On_Item__c
            ]) {
                inventoryZARAMap.put((String)agg3.get('depend'), (Decimal)agg3.get('usedNum'));
            }

            for(Order_Item__c oi : itemList){
            	Decimal zara = inventoryZARAMap.get(oi.Id)==null? 0:inventoryZARAMap.get(oi.Id);
            	Decimal zare = inventoryZAREMap.get(oi.Id)==null? 0:inventoryZAREMap.get(oi.Id);
            	Decimal zarf = inventoryZARFMap.get(oi.Id)==null? 0:inventoryZARFMap.get(oi.Id);
            	system.debug('zara===='+zara+'zare===='+zare+'zarf===='+zarf);
            	oi.ZARB_Used_Quantity_Test_Only__c = (zara + zare -zarf);
            }

            update itemList;

        }catch (Exception e) {
            flag = FALSE;
            errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }
    
    global void finish(Database.BatchableContext bc) {
		Utility.setBatchInfo('BatchUpdateZARBItemUsedQty', flag, startTime, errorMsg);
    }
}