force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Locked_in_SAP__c.field-meta.xml
<CustomField>
    <fullName>Locked_in_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Locked in SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Edit_Status__c.field-meta.xml
<CustomField>
    <fullName>Edit_Status__c</fullName>
    <label>Edit Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SAP_Item_Num__c.field-meta.xml
<CustomField>
    <fullName>SAP_Item_Num__c</fullName>
    <label>SAP Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LockOrderLWCController.cls
/**************************************************************************************************
 * Name: NotificationService
 * Object: 
 * Purpose: 订单锁定
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-05-20         Created             
***************************************************************************************************/
public without sharing class LockOrderLWCController {
    @AuraEnabled
    public static Output lockOrder(String orderId) {
        List<Order_Item__c> oiList = [SELECT Id,SAP_Item_Num__c FROM Order_Item__c WHERE isClosed__c=false AND Order__c =:orderId];
        String orderItemIds;
        
        for (Order_Item__c oi : oiList) {
            if (String.isNotBlank(orderItemIds)) {
                orderItemIds += ';'+oi.Id;
            }else{
                orderItemIds = ';'+oi.Id;
            }
             
        }
        OrderSyncToSAP.ReturnResult rr = OrderSyncToSAP.submitToSAP(orderId, 'U',true,false,System.Label.Reason,orderItemIds,false,false);
        if(Test.isRunningTest()){
            rr.isSuccess=true;
            rr.item=new List<OrderSyncToSAP.Item>();
            OrderSyncToSAP.Item item1=new OrderSyncToSAP.Item();
            item1.status='A';
            item1.POSNR='10';    
            rr.item.add(item1);
        }
           
        Output out = new Output();
        out.isSucess = rr.isSuccess;
        out.errorMsg = rr.message;
        if (out.isSucess) {
            Map<String,String> itemNumberMap = new Map<String,String>();
            for (OrderSyncToSAP.item i :  rr.item) {
                itemNumberMap.put(i.POSNR,i.status);
            }
            for (Order_Item__c oi : oiList) {
                oi.Edit_Status__c = itemNumberMap.get(oi.SAP_Item_Num__c);
            }
            Database.update(oiList);
            Order__c order = new Order__c();
            order.Id = orderId;
            order.Locked_in_SAP__c = true;
            update order;
        }
        return out;
    }
    public class Output{

        @AuraEnabled
        public Boolean isSucess {get;set;}

        @AuraEnabled
        public String errorMsg {get;set;}
    }
}