force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Approve_Date__c.field-meta.xml
<CustomField>
    <fullName>Approve_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivery_Amount__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Amount__c</fullName>
    <label>Delivered Amount</label>
    <summarizedField>Delivery_Note__c.Delivery_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Delivery_Note__c.Delivery_Post_Status__c</field>
        <operation>equals</operation>
        <value>B 	Partially processed, C 	Completely processed</value>
    </summaryFilterItems>
    <summaryForeignKey>Delivery_Note__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/NotificationClose__c.field-meta.xml
<CustomField>
    <fullName>NotificationClose__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Already Sent Closure Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP Created Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not synchronized</fullName>
            </value>
            <value>
                <fullName>Synchronization error</fullName>
            </value>
            <value>
                <fullName>Synchronized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseOrderNotificaionBatch.cls
/**************************************************************************************************
 * Name: GetProductNumberBatch
 * Object: 
 * Purpose: 定时通知订单关闭
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE             DETAIL             Description
 * 1.0          Gerry             2024-10-20         Created             
***************************************************************************************************/
global without sharing class CloseOrderNotificaionBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful,Schedulable {
    public String query;
    global String errorMsg;
    global Datetime startTime;
    global Boolean flag;
    global CloseOrderNotificaionBatch() {
        this.startTime = System.now();
        this.flag = true;
        this.query = 'SELECT OwnerId,SAP_Order_Code__c,Id,Status__c,Approve_Date__c,SAP_Order__c,Sales_Org__c,Deliver_Plant__c FROM Order__c WHERE Status__c=\'Approved\' AND Delivery_Amount__c=0 AND Sync_Status__c=\'Synchronized\' AND SAP_Order__c=false';
    }

    global void execute(SchedulableContext sc) {
        CloseOrderNotificaionBatch svo = new CloseOrderNotificaionBatch();

        // 每次执行多少条数据，最大200
        String jobId = Database.executeBatch(svo, 50);
    } 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order__c> orList) {
        try {
            CustomNotificationType notificationType = [SELECT Id,DeveloperName FROM CustomNotificationType WHERE DeveloperName ='Notification'];
            List<Order__c> updateList = new List<Order__c>();
            for (Order__c order : orList) {
                Integer days = Date.today().daysBetween(order.Approve_Date__c);
                Boolean flag = false;
                if (order.Sales_Org__c == '3020' && order.Deliver_Plant__c == '3020') {//mx C
                    Integer dayDefault = Integer.valueOf(System.Label.MXFIDays);
                    if (days>dayDefault) {
                        flag = true;
                    }
                }
                if (order.Sales_Org__c == '3010' && order.Deliver_Plant__c == '3011') {//mx C+
                    Integer dayDefault = Integer.valueOf(System.Label.MXFIRAMXDays);
                    if (days>dayDefault) {
                        flag = true;
                    }
                }

                if (order.Sales_Org__c == '3010' && order.Deliver_Plant__c == '3010') {//mx B
                    Integer dayDefault = Integer.valueOf(System.Label.MXFIRAMXDays);
                    if (days>dayDefault) {
                        flag = true;
                    }
                }

                if (order.Sales_Org__c == '5130' && order.Deliver_Plant__c == '5130') {
                    Integer dayDefault = Integer.valueOf(System.Label.ARFI_BDays);
                    if (days>dayDefault) {
                        flag = true;
                    }
                }
                if (order.Sales_Org__c == '5070' && order.Deliver_Plant__c == '5070') {
                    Integer dayDefault = Integer.valueOf(System.Label.ARFI_BDays);
                    if (days>dayDefault) {
                        flag = true;
                    }
                }
                if (flag) {
                    CustomNotificationFromApex.notifyUsers(
                        notificationType, 
                        new Set<String>{order.OwnerId}, //发送通知给谁
                        order.Id, //通知点击后跳转到什么数据上
                        System.Label.NotficationOrderTitle, //标题
                        '['+order.SAP_Order_Code__c+']'+System.Label.NotficationOrderBody//内容
                    );
                    order.NotificationClose__c = true;
                    updateList.add(order);
                }
            }
            Utility.IgnoreAction(true,false,'CloseOrderNotificaionBatch'); 
            Database.Update(updateList);
            Utility.IgnoreAction(false,false,'CloseOrderNotificaionBatch'); 
        } catch (Exception e) {
            this.flag = false;
            this.errorMsg = e.getMessage()+';行数：'+e.getLineNumber();
        }
    }

    global void finish(Database.BatchableContext BC) {
        Utility.setBatchInfo('CloseOrderNotificaionBatch', this.flag, this.startTime, this.errorMsg);
        
    }
}