force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{YYMM}-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Auto_Issue_Consignment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Issue_Consignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Issue Consignment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Deliver_Plant__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Plant__c</fullName>
    <defaultValue>$User.Deliver_Plant_Text__c</defaultValue>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Plant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T</fullName>
                <label>T Transferencia Bancaria</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>D Condonacion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <defaultValue>$User.Sales_Org_Text__c</defaultValue>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Source_Order__c.field-meta.xml
<CustomField>
    <fullName>Source_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order (Source Order)</relationshipLabel>
    <relationshipName>SourceOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approving</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>To be shipped</fullName>
                <isActive>false</isActive>
                <label>To be shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/ZAR1_Order__c.field-meta.xml
<CustomField>
    <fullName>ZAR1_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZAR1 Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order (ZAR1 Order)</relationshipLabel>
    <relationshipName>ZAR1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Model_C.recordType-meta.xml
<RecordType>
    <fullName>Model_C</fullName>
    <active>true</active>
    <label>Model C</label>
</RecordType>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Auto_Issue_Consignment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Issue_Consignment__c</fullName>
    <formula>Order__r.Auto_Issue_Consignment__c</formula>
    <label>*Auto-Issue Consignment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product_Name__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Depend_On_Item__c.field-meta.xml
<CustomField>
    <fullName>Depend_On_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fill up Consignment Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item (Issue Consignment)</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Guide_Price__c.field-meta.xml
<CustomField>
    <fullName>Guide_Price__c</fullName>
    <label>Guide Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/IsCreate__c.field-meta.xml
<CustomField>
    <fullName>IsCreate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCreate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Order__r.Order_type__c)</formula>
    <label>*Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT(Order__r.Sales_Org__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Unit Master Data</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Order_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Description_User__c.field-meta.xml
<CustomField>
    <fullName>Description_User__c</fullName>
    <formula>IF( OR(TEXT($User.LocaleSidKey) =&apos;es_MX&apos;,TEXT($User.LocaleSidKey) =&apos;es_AR&apos;), Spanish_Description__c ,English_Description__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/Product_Name__c.object-meta.xml
<CustomObject>
    <label>Product Name</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Name__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Commodity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Product_Sales_Info__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Info__c</fullName>
    <label>Product Info</label>
    <referenceTo>Product_Sales_Info__c</referenceTo>
    <relationshipLabel>Product Name</relationshipLabel>
    <relationshipName>Commodity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Name__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>TEXT( Product_Sales_Info__r.Sales_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/Product_Sales_Info__c.object-meta.xml
<CustomObject>
    <label>Product Info</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Product Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_Local__c.field-meta.xml
<CustomField>
    <fullName>Cost_Local__c</fullName>
    <label>Unit Cost (Local Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Cost_USD__c</fullName>
    <label>Unit Cost (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Unit</label>
    <referenceTo>Product_Unit__c</referenceTo>
    <relationshipName>Product_Sales_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Info__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Shelves</fullName>
                <default>true</default>
                <label>On Shelves</label>
            </value>
            <value>
                <fullName>Off Shelves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Unit__c/Product_Unit__c.object-meta.xml
<CustomObject>
    <label>Product Unit</label>
    <nameField>
        <displayFormat>PU-{000000}</displayFormat>
        <label>Product Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Unit__c/fields/Conversion_Coefficient__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Coefficient__c</fullName>
    <inlineHelpText>1 [Product Sales Unit] = [Conversion Coefficient] [Basic Metering Unit]</inlineHelpText>
    <label>Conversion Coefficient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Unit</relationshipLabel>
    <relationshipName>Product_Unit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Unit__c/fields/Product_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Unit__c</fullName>
    <label>Product Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFA</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AON</fullName>
    </customValue>
    <customValue>
        <fullName>AOR</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>ATS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZM</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BEF</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYB</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>币种</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
    </customValue>
    <customValue>
        <fullName>KL</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>16C</fullName>
    </customValue>
    <customValue>
        <fullName>20C</fullName>
    </customValue>
    <customValue>
        <fullName>BOT</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>DRM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>12C</fullName>
    </customValue>
    <customValue>
        <fullName>JRC</fullName>
    </customValue>
    <customValue>
        <fullName>04C</fullName>
    </customValue>
    <customValue>
        <fullName>Z02</fullName>
        <label>SET</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>ZBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUP</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <customValue>
        <fullName>02C</fullName>
    </customValue>
    <customValue>
        <fullName>IBC</fullName>
    </customValue>
    <customValue>
        <fullName>24C</fullName>
    </customValue>
    <customValue>
        <fullName>05B</fullName>
    </customValue>
    <customValue>
        <fullName>H00</fullName>
    </customValue>
    <customValue>
        <fullName>48C</fullName>
    </customValue>
    <customValue>
        <fullName>DR</fullName>
    </customValue>
    <customValue>
        <fullName>10C</fullName>
    </customValue>
    <description>单位</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MassEditOrderController.cls
/**************************************************************************************************
* Name: MassEditOrderController
* Object: Order__c
* Purpose: 批量编辑订单
* ************************************************************************************************
* History
* --------
* VERSION     AUTHOR              DATE            DETAIL             Description
* 1.0         zach	           2025-07-02         Created
***************************************************************************************************/
public without sharing class MassEditOrderController {
	/**
    * 获取 ZARA 订单数据
    * @Author   Zach
    * @DateTime 2025-07-02
    * @param
    * @return  页面数据的Map
    */
	@AuraEnabled
    public static Map<String, Object> initData(){
        Map<String, Object> returnMap = new Map<String, Object>();
        //校验权限
        List<PermissionSetAssignment> psaList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSet.Name = 'ZAR1_Auto_Create_Permission'];
        if(psaList.isEmpty()){
            returnMap.put(System.Label.OrderLabe21, Label.no_access);
            return returnMap;
        }
        
		List<OrderData> dataList = new List<OrderData>();
        //peyment term 和 payment method 的依赖选项列表值
        Map<String,List<Utility.returnValue>> termMap = Utility.getDependentOptionsImpl('Order__c','Deliver_Plant__c','Terms_Of_Payment__c');
        //Map<String,List<Utility.returnValue>> methodMap = Utility.getDependentOptionsImpl('Order__c','Sales_Org__c','Payment_Method__c');
        
        String orderSoql = Utility.getAllFieldSoql('Order__c') + ' WHERE Order_type__c = \'ZARA\' AND Status__c != \'Approved\' AND Auto_Issue_Consignment__c = TRUE ' + 
                            ' AND (Sales_Org__c = \'5070\' OR Sales_Org__c = \'5130\') AND Deliver_Plant__c != NULL AND RecordType.DeveloperName = \'Model_C\' AND OwnerId =\'' + UserInfo.getUserId() + '\'';
        for(Order__c order : (List<Order__c>)Database.query(orderSoql)){
            dataList.add(new OrderData(order,termMap,dataList.size() + 1));
        }        
   
        returnMap.put('dataList', dataList);
        //returnMap.put('translateMap', Utility.getFieldLabelTranslateMap('Order__c'));
       
        return returnMap;
    }

    /**
    * 保存ZARA 并生成ZAR1
    * @Author   Zach
    * @DateTime 2025-07-04
    * @param
    * @return  页面数据的Map
    */
	@AuraEnabled
    public static Map<String, Object> saveData(String selectListStr){
        Savepoint sp = Database.setSavepoint();
        try{
            List<OrderData> dataList = (List<OrderData>)JSON.deserialize(selectListStr, List<OrderData>.class);
            List<Order__c> zaraDataList = new List<Order__c>();
            Map<String,Order__c> zar1DataMap = new Map<String,Order__c>();
            for(OrderData data : dataList){
                Order__c order = data.order;
                if(data.isAutoCreate){
                    system.debug(order);
                    Order__c zar1Order = order.clone(FALSE,TRUE,FALSE,FALSE);
                    zar1Order.Order_type__c = 'ZAR1';
                    zar1Order.Source_Order__c = order.Id;
                    zar1Order.Status__c = 'Draft';
                    order.Status__c = 'Approved';
                    zar1DataMap.put(order.Id,zar1Order);
                }
                zaraDataList.add(order);
            }
            Utility.isBypassValidationRule = TRUE;
            if(!zar1DataMap.isEmpty()){
                insert zar1DataMap.values();
                cloneItem(zar1DataMap);
            }

            for(Order__c order : zaraDataList){
                if(zar1DataMap.containsKey(order.Id)){
                    order.ZAR1_Order__c = zar1DataMap.get(order.Id).Id;
                }
            }
            System.debug('zaraDataList===='+zaraDataList.size());
			update zaraDataList;
            //ZAR1同步SAP
            /*List<BatchOrderSyncToSap.BatchData> batchDataList = new List<BatchOrderSyncToSap.BatchData>();
            Map<Id,Order__c> orderMap = new Map<Id,Order__c>(zar1DataMap.values());
            for(Order__c order : [SELECT Id,(SELECT Id FROM Order_Item__r) FROM Order__c WHERE Id IN:orderMap.keySet()]){
                String itemIdStr = '';
                for(Order_Item__c item : order.Order_Item__r) {
                    itemIdStr += item.Id + ';';
                }
                itemIdStr.removeEnd(';');
                batchDataList.add(new BatchOrderSyncToSap.BatchData(order.Id, 'I',false,false,'',false,itemIdStr));
            }
            if(!batchDataList.isEmpty()){
                Database.executeBatch(new BatchOrderSyncToSap(JSON.serialize(batchDataList)),1);
            }*/
        }catch(Exception e){
            Database.rollback(sp);
            Map<String, Object> returnMap = new Map<String, Object>();
            returnMap.put('error',Utility.getCustomMessage(e.getMessage(),FALSE));
            return returnMap;
        }
        return initData();
    }
    
    /**
    * 克隆order item
    * @Author   Zach
    * @DateTime 2025-07-04
    * @param
    * @return  
    */
    public static void cloneItem(Map<String,Order__c> newOrderMap){
        Set<String> orderIdSet = newOrderMap.keySet();
        String orderItemSoql = Utility.getAllFieldSoql('Order_Item__c') + ' WHERE Order__c IN :orderIdSet';
        List<Order_Item__c> itemList = (List<Order_Item__c>)Database.query(orderItemSoql);

        Set<String> productId = new Set<String>();
        Set<String> unitId = new Set<String>();
        for (Order_Item__c oi : itemList) {
            productId.add(oi.Commodity__c);
            unitId.add(oi.Sales_Unit__c);
        }
        Map<String,Product_Name__c> marCodeMap = new Map<String,Product_Name__c>();
        for (Product_Name__c pn : [SELECT Product_Sales_Info__r.Cost_Local__c,Product_Sales_Info__r.Cost_USD__c,Id,Name,Product__r.Name,Product__r.Description_User__c,Product_Sales_Info__r.Product_Unit__r.Conversion_Coefficient__c FROM Product_Name__c WHERE Id IN:productId]) {
            marCodeMap.put(pn.Id, pn);
        }

        Map<String,Product_Unit__c> unitMap = new Map<String,Product_Unit__c>();
        for (Product_Unit__c pn : [SELECT Product_Sales_Unit__c,Id,Conversion_Coefficient__c FROM Product_Unit__c WHERE Id IN:unitId]) {
            unitMap.put(pn.Id, pn);
        }

        Map<Id,Order__c> orderMap = new Map<Id,Order__c>([SELECT Id,Currency__c,Interest_Rate__c,Sales_Org__c FROM Order__c WHERE Id IN:orderIdSet]);
        
        List<Order_Item__c> zar1ItemList = new List<Order_Item__c>();
        for(Order_Item__c item : itemList){
            Order_Item__c zar1Item = item.clone(FALSE,TRUE,FALSE,FALSE);
            zar1Item.Order__c = newOrderMap.get(item.Order__c)?.Id;
            zar1Item.Depend_On_Item__c = item.Id;
            zar1Item.IsCreate__c = TRUE;
            zar1Item.Price__c = item.Guide_Price__c;
            if (orderMap.get(item.Order__c).Currency__c == 'USD') {
                zar1Item.Original_Product_Cost__c = marCodeMap.get(zar1Item.Commodity__c).Product_Sales_Info__r.Cost_USD__c;
            }else{
                zar1Item.Original_Product_Cost__c = marCodeMap.get(zar1Item.Commodity__c).Product_Sales_Info__r.Cost_Local__c;
            }
            if(zar1Item.Original_Product_Cost__c!=null && unitMap.get(zar1Item.Sales_Unit__c) != null && unitMap.get(zar1Item.Sales_Unit__c).Conversion_Coefficient__c != null) {
                zar1Item.Product_Cost__c = (zar1Item.Original_Product_Cost__c * unitMap.get(zar1Item.Sales_Unit__c).Conversion_Coefficient__c).setScale(2);
            }else if(zar1Item.Product_Cost__c!=null){
                zar1Item.Product_Cost__c=zar1Item.Product_Cost__c.setScale(2);
            }
            if (orderMap.get(item.Order__c).Interest_Rate__c != null && (orderMap.get(item.Order__c).Sales_Org__c == '5130' || orderMap.get(item.Order__c).Sales_Org__c =='5070') && zar1Item.Product_Cost__c <> null) {//AR、ypf Guide Price增加账期成本
                zar1Item.Product_Cost__c *= orderMap.get(item.Order__c).Interest_Rate__c;
            }
            zar1ItemList.add(zar1Item);
        }
        insert zar1ItemList;        
    }
    
    public class OrderData{
        @AuraEnabled public Order__c order;//订单
        @AuraEnabled public String orderUrl;//订单
        @AuraEnabled public Integer index;//序号
        @AuraEnabled public List<Utility.returnValue> termList;//可选的Payment term
        //@AuraEnabled public List<Utility.returnValue> methodList;//可选的Payment method
        @AuraEnabled public Boolean isAutoCreate;//是否自动创建
        @AuraEnabled public Boolean isSelect;
        
        public OrderData(Order__c order,Map<String,List<Utility.returnValue>> termMap,Integer index){
            this.order = order;
            this.orderUrl = Utility.ordUrl + '/lightning/r/Order__c/' + order.Id + '/view';
            this.termList = termMap.get(order.Deliver_Plant__c)??new List<Utility.returnValue>();
            //this.methodList = methodMap.get(order.Sales_Org__c)??new List<Utility.returnValue>();
            this.isAutoCreate = FALSE;
            this.index = index;
            this.isSelect = FALSE;
        }
    }
}